.PHONY: all doc clean veryclean install

.SUFFIXES:
.SUFFIXES: .c .f .o .mpi.o .a


SHELL = /bin/sh
ECHO = echo


CC = gcc-4.4
CLANGFLAGS = --std=gnu99 -Wall
COPTFLAGS = -O2 -march=core2 -ffast-math
CFLAGS = $(CLANGFLAGS) $(COPTFLAGS)

FC = gfortran-4.4
FLANGFLAGS = -Wall
FOPTFLAGS = -O2 -march=core2 -ffast-math
FFLAGS = $(FLANGFLAGS) $(FOPTFLAGS)

LD = gcc-4.4
LDFLAGS = -L. 
SYSLIBS = -lgfortran -lm -lz

LAPACKLIBS = -llapack -lblas

# compare with mpicc -showme:compile, mpicc -showme:link

MPIPATH = /usr/lib/openmpi

MPICC = gcc-4.4
MPICFLAGS = -I$(MPIPATH)/include -I$(MPIPATH)/include/openmpi -pthread $(CFLAGS)

MPILD = gcc-4.4
MPILDFLAGS = -L. -pthread -L$(MPIPATH)/lib
MPILIBS = -lmpi -lopen-rte -lopen-pal -ldl -Wl,--export-dynamic -lnsl -lutil -lm -ldl


AR = ar

INSTALL = install -m 750


# implicit rules

%.mpi.o: %.c
	$(MPICC) -c -DMPI $(CPPFLAGS) $(MPICFLAGS) $< -o $@

# automatic dependencies

%.d: %.c
	$(SHELL) -ec '$(CC) -MM $(CFLAGS) $< \
		| sed '\''s/\($*\)\.o[ :]*/\1.o $@ : /g'\'' > $@; \
		[ -s $@ ] || rm -f $@'


