FMD: fmd/angprojection.c File Reference
fmd/angprojection.c File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "SlaterDet.h"
#include "Projection.h"
#include "Symmetry.h"
#include "numerics/zcw.h"
#include "numerics/gaussquad.h"
Defines
#define SQR(x) ((x)*(x))
Functions
int initAngintegration (angintegrationpara *par, const char *projpar)
void freeAngintegration (angintegrationpara *par)
double _estimateangkappa (const SlaterDet *Q)
void _setangkappacrit (double kappa)
double _getangkappacrit ()
void _initangintegration (const Projection *P, double kappa, Symmetry S, Symmetry Sp, angintegrationpara *par)
void initangintegration (const Projection *P, const SlaterDet *Q, const SlaterDet *Qp, Symmetry S, Symmetry Sp, angintegrationpara *par)
void reinitangintegration (const SlaterDet *Q, const SlaterDet *Qp, Symmetry S, Symmetry Sp, angintegrationpara *par)
void getangintegrationpoint (int i, const angintegrationpara *par, double *alpha, double *beta, double *gamma, double *w)
Detailed Description
Gridpoints used for angular momentum projection
(c) 2004, 2005 Thomas Neff
Definition in file angprojection.c.
Define Documentation
#define SQR (x) ((x)*(x))
Definition at line 25 of file angprojection.c.
Function Documentation
double _estimateangkappa (const SlaterDet * Q)
Definition at line 92 of file angprojection.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), initSlaterDet(), initSlaterDetAux(), log, SlaterDetAux::ovlap, and rotateSlaterDet().
Referenced by calcprojectedMultiMBME(), calcprojectedMultiMBMEmpi(), initangintegration(), and reinitangintegration().
{
  const double cosb0 = 0.5;
  double ovl0;
  complex double ovlcosb0;
  // do we have to (re)initialize workspace first ?
  if (Qpp.A < Q->A) {
    initSlaterDet(Q, &Qpp);
    initSlaterDetAux(Q, &Xpp);
  }
  copySlaterDet(Q, &Qpp);
  calcSlaterDetAuxod(Q, &Qpp, &Xpp);
  ovl0 = Xpp.ovlap;
  rotateSlaterDet(&Qpp, 0.0,acos(cosb0),0.0);
  calcSlaterDetAuxod(Q, &Qpp, &Xpp);
  ovlcosb0 = Xpp.ovlap;
  return (log(cabs(ovlcosb0/ovl0))/log(cosb0));
}
double _getangkappacrit ()
Definition at line 125 of file angprojection.c.
Referenced by calcprojectedMultiMBME(), and calcprojectedMultiMBMEmpi().
{
  return (kappacrit);
}
void _initangintegration (const Projection * P, double kappa, Symmetry S, Symmetry Sp, angintegrationpara * par)
Definition at line 131 of file angprojection.c.
References angprodintegrationpara::alpha, Projection::ang, AngNone, Projection::angprod, AngProd, AngProdA, Projection::angzcw, AngZCW, angprodintegrationpara::beta, angprodintegrationpara::gamma, GaussExponentialPoints(), GaussLegendrePoints(), angzcwpara::idx, angzcwintegrationpara::idx, angintegrationpara::n, angprodintegrationpara::nalpha, nangles3(), angprodpara::nazimuth, angprodintegrationpara::nbeta, angprodpara::nbeta, angprodintegrationpara::ngamma, angintegrationpara::prod, ShiftedPeriodicTrapezoidalPoints(), spherical, angintegrationpara::type, angprodintegrationpara::walpha, angprodintegrationpara::wbeta, angprodintegrationpara::wgamma, and angintegrationpara::zcw.
Referenced by calcprojectedMultiMBME(), calcprojectedMultiMBMEmpi(), and initangintegration().
{
  par->type = P->ang;
  if (P->ang == AngNone) {
    par->n = 1;
  }
  else if (P->ang == AngZCW) {
    par->zcw.idx = P->angzcw.idx;
    par->n = nangles3(P->angzcw.idx);
  }
  else if (P->ang == AngProd || P->ang == AngProdA) {
    int nbeta = P->angprod.nbeta;
    int nazim = P->angprod.nazimuth;
    // use Gauss-Legendre integration for cos(beta)
    // if overlap is very strongly peaked, use Gauss-Exponential
    if (hasSymmetry(S, spherical))
      par->prod.nbeta = 1;
    else
      par->prod.nbeta = nbeta;
    par->prod.beta = malloc(par->prod.nbeta*sizeof(double));
    par->prod.wbeta = malloc(par->prod.nbeta*sizeof(double));
    if (kappa < kappacrit)
      GaussLegendrePoints(par->prod.nbeta, -1.0, 1.0, par->prod.beta, par->prod.wbeta);
    else
      GaussExponentialPoints(par->prod.nbeta, -1.0, 1.0, kappa, par->prod.beta, par->prod.wbeta);
    // azimuthal integration can be skipped if symmetry allows
    // trapezoidal rule with shifted grid points
    // special handling for rotatez2, rotatez3 ?
    double shift = 0.25;
    if (hasAxialSymmetry(S))
      par->prod.nalpha = 1;
    else
      par->prod.nalpha = nazim;
    par->prod.alpha = malloc(par->prod.nalpha*sizeof(double));
    par->prod.walpha = malloc(par->prod.nalpha*sizeof(double));
    ShiftedPeriodicTrapezoidalPoints(par->prod.nalpha, 0, 2*M_PI, shift,
                                     par->prod.alpha, par->prod.walpha);
    if (hasAxialSymmetry(Sp))
      par->prod.ngamma = 1;
    else
      par->prod.ngamma = nazim;
    par->prod.gamma = malloc(par->prod.ngamma*sizeof(double));
    par->prod.wgamma = malloc(par->prod.ngamma*sizeof(double));
    ShiftedPeriodicTrapezoidalPoints(par->prod.ngamma, 0, 2*M_PI, shift,
                                     par->prod.gamma, par->prod.wgamma);
    par->n = par->prod.nbeta* par->prod.nalpha* par->prod.ngamma;
  }
}
void _setangkappacrit (double kappa)
Definition at line 120 of file angprojection.c.
Referenced by main().
{
  kappacrit = kappa;
}
void freeAngintegration (angintegrationpara * par)
Definition at line 77 of file angprojection.c.
References angprodintegrationpara::alpha, AngProd, angprodintegrationpara::beta, angintegrationpara::prod, angintegrationpara::type, angprodintegrationpara::walpha, and angprodintegrationpara::wbeta.
Referenced by calcprojectedMultiMBME(), and calcprojectedMultiMBMEmpi().
{
  if(par->type == AngProd) {
    free(par->prod.beta);
    free(par->prod.wbeta);
    free(par->prod.alpha);
    free(par->prod.walpha);
  }
}
void getangintegrationpoint (int i, const angintegrationpara * par, double * alpha, double * beta, double * gamma, double * w)
Definition at line 250 of file angprojection.c.
References angprodintegrationpara::alpha, AngNone, AngProd, AngProdA, AngZCW, angprodintegrationpara::beta, angprodintegrationpara::gamma, getangles3(), angzcwintegrationpara::idx, angintegrationpara::n, n, angprodintegrationpara::nalpha, angprodintegrationpara::nbeta, angintegrationpara::prod, SQR, angintegrationpara::type, angprodintegrationpara::walpha, angprodintegrationpara::wbeta, angprodintegrationpara::wgamma, and angintegrationpara::zcw.
Referenced by calcgradorthprojectedHamiltonian(), calcgradprojectedHamiltonian(), calcgradprojectedHamiltonianmatrix(), calcorthprojectedHamiltonian(), calcprojectedHamiltonian(), calcprojectedHamiltonianmatrix(), calcprojectedMBME(), calcprojectedMBMEmpi(), calcprojectedMBMEs(), calcprojectedMBMEsmpi(), calcprojectedMultiMBME(), and calcprojectedMultiMBMEmpi().
{
  assert(i < par->n);
  if (par->type == AngNone) {
    *alpha = 0.0; *beta = 0.0; *gamma = 0.0;
    *w = 8*SQR(M_PI);
  }
  else if (par->type == AngZCW) {
    getangles3(par->zcw.idx, i, alpha, beta, gamma);
    *w = 8*SQR(M_PI)/par->n;
  }
  else if (par->type == AngProd || par->type == AngProdA) {
    int ibeta, ialpha, igamma;
    ibeta = i % par->prod.nbeta;
    ialpha = (i/par->prod.nbeta) % par->prod.nalpha;
    igamma = i/(par->prod.nbeta*par->prod.nalpha);
    *beta = acos(par->prod.beta[ibeta]);
    *alpha = par->prod.alpha[ialpha];
    *gamma = par->prod.gamma[igamma];
    *w = par->prod.wbeta[ibeta]*
      par->prod.walpha[ialpha]*par->prod.wgamma[igamma];
  }
  // fprintf(stderr, "ang integration point: (%8.5f, %8.5f, %8.5f) weight %8.5f\n",
  //         *alpha, *beta, *gamma, *w);
}
int initAngintegration (angintegrationpara * par, const char * projpar)
Definition at line 28 of file angprojection.c.
References angprodintegrationpara::alpha, angprodintegrationpara::beta, angprodintegrationpara::gamma, GaussLegendrePoints(), angzcwintegrationpara::idx, angintegrationpara::n, angprodintegrationpara::nalpha, nangles3(), angprodintegrationpara::nbeta, angprodintegrationpara::ngamma, angintegrationpara::prod, ShiftedPeriodicTrapezoidalPoints(), SQR, angintegrationpara::type, angprodintegrationpara::walpha, angprodintegrationpara::wbeta, angprodintegrationpara::wgamma, and angintegrationpara::zcw.
Referenced by main().
{
  char projparcpy[strlen(projpar)];
  strcpy(projparcpy, projpar);
  char* c = projparcpy;
  c = strtok(c, "-");
  if (!strncmp(c, "ang", 3)) {
    c=strtok(NULL, "-");
    if (!strncmp(c, "none", 4)) {
      par->type = AngNone;
      par->n = 1;
    } else if (!strncmp(c, "zcw", 3)) {
      par->type = AngZCW;
      c=strtok(NULL, "-");
      par->zcw.idx = atoi(c);
      par->n = nangles3(par->zcw.idx);
    } else {
      par->type = AngProd;
      int nbeta = atoi(c);
      c=strtok(NULL, "-");
      int nazimuth = atoi(c);
      par->n = nbeta*SQR(nazimuth);
      par->prod.nbeta = nbeta;
      par->prod.beta = malloc(nbeta*sizeof(double));
      par->prod.wbeta = malloc(nbeta*sizeof(double));
      GaussLegendrePoints(nbeta, -1.0, 1.0, par->prod.beta, par->prod.wbeta);
      par->prod.nalpha = nazimuth;
      par->prod.alpha = malloc(nazimuth*sizeof(double));
      par->prod.walpha = malloc(nazimuth*sizeof(double));
      double shift = 0.25;
      ShiftedPeriodicTrapezoidalPoints(nazimuth, 0, 2*M_PI, shift,
                                       par->prod.alpha, par->prod.walpha);
      par->prod.ngamma = nazimuth;
      par->prod.gamma = par->prod.alpha;
      par->prod.wgamma = par->prod.walpha;
    }
  }
  return 0;
}
void initangintegration (const Projection * P, const SlaterDet * Q, const SlaterDet * Qp, Symmetry S, Symmetry Sp, angintegrationpara * par)
Definition at line 210 of file angprojection.c.
References _estimateangkappa(), _initangintegration(), Projection::ang, and AngProdA.
Referenced by calcprojectedMBME(), calcprojectedMBMEmpi(), calcprojectedMBMEs(), calcprojectedMBMEsmpi(), and main().
{
  double kappa = 0.0;
  if (P->ang == AngProdA) {
    kappa = dmin(_estimateangkappa(Q), _estimateangkappa(Qp));
    fprintf(stderr, "kappa: %8.3f\n", kappa);
  }
  _initangintegration(P, kappa,  S, Sp, par);
}
void reinitangintegration (const SlaterDet * Q, const SlaterDet * Qp, Symmetry S, Symmetry Sp, angintegrationpara * par)
Definition at line 225 of file angprojection.c.
References _estimateangkappa(), AngProdA, angprodintegrationpara::beta, GaussExponentialPoints(), GaussLegendrePoints(), angprodintegrationpara::nbeta, angintegrationpara::prod, angintegrationpara::type, and angprodintegrationpara::wbeta.
Referenced by calcgradprojectedHamiltonian(), calcgradprojectedHamiltonianmatrix(), calcprojectedHamiltonian(), and calcprojectedHamiltonianmatrix().
{
  // we only have to modify something for adaptive integration
  // use Gauss-Legendre integration for cos(beta)
  // if overlap is very strongly peaked, use Gauss-Exponential
  double kappa = 0.0;
  if (par->type == AngProdA) {
    kappa = dmin(_estimateangkappa(Q), _estimateangkappa(Qp));
    fprintf(stderr, "estimated kappa: %8.3f\n", kappa);
    if (kappa < kappacrit)
      GaussLegendrePoints(par->prod.nbeta, -1.0, 1.0, par->prod.beta, par->prod.wbeta);
    else
      GaussExponentialPoints(par->prod.nbeta, -1.0, 1.0, kappa, par->prod.beta, par->prod.wbeta);
  }
}