FMD: fmd/AngularMomenta.c File Reference
fmd/AngularMomenta.c File Reference
#include <complex.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "AngularMomenta.h"
#include "numerics/cmath.h"
Functions
void calcAngularMomenta (const SlaterDet *Q, const SlaterDetAux *X, double *l2, double *s2, double *j2)
calculate l2, s2 and j2
void calcAngularMomentaod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *l2, complex double *s2, complex double *j2)
void calcl2HF (const SlaterDet *Q, const SlaterDetAux *X, void *mes)
calc single-particle HF angular momenta
void calcj2HF (const SlaterDet *Q, const SlaterDetAux *X, void *mes)
void calcJ2 (const SlaterDet *Q, const SlaterDetAux *X, double j2[3])
calculate Jx^2, Jy^2, Jz^2
void calcJ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double j2[3])
void calcL (const SlaterDet *Q, const SlaterDetAux *X, double l[3])
calculate Lx, Ly, Lz
void calcS (const SlaterDet *Q, const SlaterDetAux *X, double s[3])
calculate Sx, Sy, Sz
void calcJ (const SlaterDet *Q, const SlaterDetAux *X, double j[3])
calculate Jx, Jy, Jz
void calcLod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double l[3])
void calcSod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double s[3])
void calcJod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double j[3])
Detailed Description
calculate angular momenta
(c) 2003 Thomas Neff
Definition in file AngularMomenta.c.
Function Documentation
void calcAngularMomenta (const SlaterDet * Q, const SlaterDetAux * X, double * l2, double * s2, double * j2)
calculate l2, s2 and j2
Definition at line 129 of file AngularMomenta.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), and dim.
Referenced by calcObservables(), and main().
{
  double angone[3], angtwo[3];
  OneBodyOperator op_ob_angmom = {dim: 3, opt: 1, par: NULL, me: ob_angmom};
  TwoBodyOperator op_tb_angmom = {dim: 3, opt: 1, par: NULL, me: tb_angmom};
  calcSlaterDetOBME(Q, X, &op_ob_angmom, angone);
  calcSlaterDetTBME(Q, X, &op_tb_angmom, angtwo);
  *l2 = angone[0] + angtwo[0];
  *s2 = angone[1] + angtwo[1];
  *j2 = angone[2] + angtwo[2];
}
void calcAngularMomentaod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * l2, complex double * s2, complex double * j2)
Definition at line 146 of file AngularMomenta.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), and dim.
Referenced by calcObservablesod().
{
  complex double angone[3], angtwo[3];
  OneBodyOperator op_ob_angmom = {dim: 3, opt: 1, par: NULL, me: ob_angmom};
  TwoBodyOperator op_tb_angmom = {dim: 3, opt: 1, par: NULL, me: tb_angmom};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_angmom, angone);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_angmom, angtwo);
  *l2 = angone[0] + angtwo[0];
  *s2 = angone[1] + angtwo[1];
  *j2 = angone[2] + angtwo[2];
}
void calcJ (const SlaterDet * Q, const SlaterDetAux * X, double j[3])
calculate Jx, Jy, Jz
Definition at line 248 of file AngularMomenta.c.
References calcSlaterDetOBME(), and dim.
Referenced by calcSpinOrientation(), and main().
{
  OneBodyOperator op_ob_j = {dim: 3, opt: 1, par: NULL, me: ob_j};
  calcSlaterDetOBME(Q, X, &op_ob_j, j);
}
void calcJ2 (const SlaterDet * Q, const SlaterDetAux * X, double j2[3])
calculate Jx^2, Jy^2, Jz^2
Definition at line 199 of file AngularMomenta.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), and dim.
{
  double j2one[3], j2two[3];
  int i;
  OneBodyOperator op_ob_j2 = {dim: 3, opt: 1, par: NULL, me: ob_j2};
  TwoBodyOperator op_tb_j2 = {dim: 3, opt: 1, par: NULL, me: tb_j2};
  calcSlaterDetOBME(Q, X, &op_ob_j2, j2one);
  calcSlaterDetTBME(Q, X, &op_tb_j2, j2two);
  for (i=0; i<3; i++)
    j2[i] = j2one[i] + j2two[i];
}
void calcj2HF (const SlaterDet * Q, const SlaterDetAux * X, void * mes)
Definition at line 182 of file AngularMomenta.c.
References SlaterDet::A, calcSlaterDetOBHFMEs(), dim, k, and m.
Referenced by main().
{
  OneBodyOperator op_ob_angmom = {dim: 3, opt: 1, par: NULL, me: ob_angmom};
  int A=Q->A;
  complex double angmommes[A*A][3];
  complex double *j2mes = mes;
  calcSlaterDetOBHFMEs(Q, X, &op_ob_angmom, angmommes);
  int k,m;
  for (m=0; m<A; m++)
    for (k=0; k<A; k++)
      j2mes[k+m*A] = angmommes[k+m*A][2];
}
void calcJ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double j2[3])
Definition at line 215 of file AngularMomenta.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), and dim.
{
  complex double j2one[3], j2two[3];
  int i;
  OneBodyOperator op_ob_j2 = {dim: 3, opt: 1, par: NULL, me: ob_j2};
  TwoBodyOperator op_tb_j2 = {dim: 3, opt: 1, par: NULL, me: tb_j2};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_j2, j2one);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_j2, j2two);
  for (i=0; i<3; i++)
    j2[i] = j2one[i] + j2two[i];
}
void calcJod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double j[3])
Definition at line 275 of file AngularMomenta.c.
References calcSlaterDetOBMEod(), and dim.
{
  OneBodyOperator op_ob_j = {dim: 3, opt: 1, par: NULL, me: ob_j};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_j, j);
}
void calcL (const SlaterDet * Q, const SlaterDetAux * X, double l[3])
calculate Lx, Ly, Lz
Definition at line 232 of file AngularMomenta.c.
References calcSlaterDetOBME(), and dim.
Referenced by main().
{
  OneBodyOperator op_ob_l = {dim: 3, opt: 1, par: NULL, me: ob_l};
  calcSlaterDetOBME(Q, X, &op_ob_l, l);
}
void calcl2HF (const SlaterDet * Q, const SlaterDetAux * X, void * mes)
calc single-particle HF angular momenta
Definition at line 165 of file AngularMomenta.c.
References SlaterDet::A, calcSlaterDetOBHFMEs(), dim, k, and m.
Referenced by main().
{
  OneBodyOperator op_ob_angmom = {dim: 3, opt: 1, par: NULL, me: ob_angmom};
  int A=Q->A;
  complex double angmommes[A*A][3];
  complex double *l2mes = mes;
  calcSlaterDetOBHFMEs(Q, X, &op_ob_angmom, angmommes);
  int k,m;
  for (m=0; m<A; m++)
    for (k=0; k<A; k++)
      l2mes[k+m*A] = angmommes[k+m*A][0];
}
void calcLod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double l[3])
Definition at line 257 of file AngularMomenta.c.
References calcSlaterDetOBMEod(), and dim.
{
  OneBodyOperator op_ob_l = {dim: 3, opt: 1, par: NULL, me: ob_l};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_l, l);
}
void calcS (const SlaterDet * Q, const SlaterDetAux * X, double s[3])
calculate Sx, Sy, Sz
Definition at line 240 of file AngularMomenta.c.
References calcSlaterDetOBME(), and dim.
Referenced by main().
{
  OneBodyOperator op_ob_s = {dim: 3, opt: 1, par: NULL, me: ob_s};
  calcSlaterDetOBME(Q, X, &op_ob_s, s);
}
void calcSod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double s[3])
Definition at line 266 of file AngularMomenta.c.
References calcSlaterDetOBMEod(), and dim.
{
  OneBodyOperator op_ob_s = {dim: 3, opt: 1, par: NULL, me: ob_s};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_s, s);
}