FMD: calcnorm.c File Reference
calcnorm.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include <complex.h>
#include "fmd/SlaterDet.h"
#include "fmd/CenterofMass.h"
#include "misc/utils.h"
#include "misc/physics.h"
Functions
int main (int argc, char *argv[])
Detailed Description
calculate norm of Slater determinant
(c) 2004 Thomas Neff
Definition in file calcnorm.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 25 of file calcnorm.c.
References SlaterDet::A, calcSlaterDetAuxod(), calcTCM(), createinfo(), fprintinfo(), initSlaterDetAux(), mneutron, mproton, SlaterDet::N, SlaterDetAux::ovlap, Q, readSlaterDetfromFile(), X, and SlaterDet::Z.
{
  createinfo(argc, argv);
  if (argc < 2) {
    fprintf(stderr, "\nusage: %s slaterdetfile\n", argv[0]);
    exit(-1);
  }
  char* slaterdetfile = argv[optind];
  SlaterDet Q;
  readSlaterDetfromFile(&Q, slaterdetfile);
  SlaterDetAux X;
  initSlaterDetAux(&Q, &X);
  calcSlaterDetAuxod(&Q, &Q, &X);
  double norm = sqrt(creal(X.ovlap));
  double tcm;
  calcTCM(&Q, &X, &tcm);
  double a = Q.A*0.75/(tcm*(mproton*Q.Z+mneutron*Q.N));
  fprintinfo(stdout);
  fprintf(stdout, "norm: %15.8e\n", norm);
  fprintf(stdout, "a   : %15.8e\n", a);
  return 0;
}