FMD: fmd/CenterofMass.c File Reference
fmd/CenterofMass.c File Reference
#include <complex.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "CenterofMass.h"
#include "numerics/cmath.h"
#include "misc/physics.h"
Defines
#define SQR(x) ((x)*(x))
Functions
void calcCMPosition (const SlaterDet *Q, const SlaterDetAux *X, double xcm[3])
void calcCMVelocity (const SlaterDet *Q, const SlaterDetAux *X, double vcm[3])
void calcTCM (const SlaterDet *Q, const SlaterDetAux *X, double *tcm)
void calcTCMod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *tcm)
void calcTCMHF (const SlaterDet *Q, const SlaterDetAux *X, void *mes)
Detailed Description
calculate observables related to center of mass motion
(c) 2003 Thomas Neff
Definition in file CenterofMass.c.
Define Documentation
#define SQR (x) ((x)*(x))
Definition at line 22 of file CenterofMass.c.
Function Documentation
void calcCMPosition (const SlaterDet * Q, const SlaterDetAux * X, double xcm[3])
Definition at line 71 of file CenterofMass.c.
References calcSlaterDetOBME(), dim, mneutron, mproton, SlaterDet::N, and SlaterDet::Z.
Referenced by calcConstraintDetQ(), calcConstraintED2(), calcConstraintEO2(), calcConstraintEQ2(), calcConstraintJ2(), calcConstraintJ2(), calcConstraintl2(), calcConstraintls(), calcConstraintLS(), calcConstraintNNOsci(), calcConstraintNO2(), calcConstraintNOsci(), calcConstraintNQ2(), calcConstraintO2(), calcConstraintPNOsci(), calcConstraintQ2(), calcConstraintQ2offdiagonal(), calcgradConstraintDetQ(), calcgradConstraintED2(), calcgradConstraintEO2(), calcgradConstraintEQ2(), calcgradConstraintJ2(), calcgradConstraintJ2(), calcgradConstraintl2(), calcgradConstraintls(), calcgradConstraintLS(), calcgradConstraintNNOsci(), calcgradConstraintNO2(), calcgradConstraintNOsci(), calcgradConstraintNQ2(), calcgradConstraintO2(), calcgradConstraintPNOsci(), calcgradConstraintQ2(), calcgradConstraintQ2offdiagonal(), calcInertiaTensor(), calcOctupoleTensor(), calcShellOccupationsod(), invertcmSlaterDet(), main(), moveboostorientSlaterDet(), and moveboostSlaterDet().
{
  int i;
  double M;
  OneBodyOperator op_ob_mx = {dim: 3, opt: 1, par: NULL, me: ob_mx};
  calcSlaterDetOBME(Q, X, &op_ob_mx, xcm);
  M = Q->Z*mproton+Q->N*mneutron;
  for (i=0; i<3; i++)
    xcm[i] /= M;
}
void calcCMVelocity (const SlaterDet * Q, const SlaterDetAux * X, double vcm[3])
Definition at line 85 of file CenterofMass.c.
References calcSlaterDetOBME(), dim, mneutron, mproton, SlaterDet::N, and SlaterDet::Z.
Referenced by calcConstraintJ2(), calcConstraintJ2(), calcConstraintl2(), calcConstraintls(), calcConstraintLS(), calcConstraintNNOsci(), calcConstraintNOsci(), calcConstraintPNOsci(), calcgradConstraintJ2(), calcgradConstraintJ2(), calcgradConstraintl2(), calcgradConstraintls(), calcgradConstraintLS(), calcgradConstraintNNOsci(), calcgradConstraintNOsci(), calcgradConstraintPNOsci(), calcShellOccupationsod(), invertcmSlaterDet(), main(), moveboostorientSlaterDet(), and moveboostSlaterDet().
{
  int i;
  double M;
  OneBodyOperator op_ob_p = {dim: 3, opt: 1, par: NULL, me: ob_p};
  calcSlaterDetOBME(Q, X, &op_ob_p, vcm);
  M = Q->Z*mproton+Q->N*mneutron;
  for (i=0; i<3; i++)
    vcm[i] /= M;
}
void calcTCM (const SlaterDet * Q, const SlaterDetAux * X, double * tcm)
Definition at line 99 of file CenterofMass.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), and dim.
Referenced by _estimateacm(), calcHamiltonian(), calcHamiltonianmpi(), calcObservables(), calcShellOccupationsod(), and main().
{
  double tcmone, tcmtwo;
  OneBodyOperator op_ob_tcm = {dim: 1, opt: 1, par: Q, me: ob_tcm};
  TwoBodyOperator op_tb_tcm = {dim: 1, opt: 1, par: Q, me: tb_tcm};
  calcSlaterDetOBME(Q, X, &op_ob_tcm, &tcmone);
  calcSlaterDetTBME(Q, X, &op_tb_tcm, &tcmtwo);
  *tcm = tcmone+tcmtwo;
}
void calcTCMHF (const SlaterDet * Q, const SlaterDetAux * X, void * mes)
Definition at line 128 of file CenterofMass.c.
References SlaterDet::A, calcSlaterDetOBHFMEs(), calcSlaterDetTBHFMEs(), dim, k, and l.
Referenced by calcHamiltonianHF().
{
  OneBodyOperator op_ob_tcm = {dim: 1, opt: 1, par: Q, me: ob_tcm};
  TwoBodyOperator op_tb_tcm = {dim: 1, opt: 1, par: Q, me: tb_tcm};
  int A=Q->A;
  complex double tcmone[A*A];
  complex double tcmtwo[A*A];
  calcSlaterDetOBHFMEs(Q, X, &op_ob_tcm, tcmone);
  calcSlaterDetTBHFMEs(Q, X, &op_tb_tcm, tcmtwo);
  complex double *tcm = mes;
  int k,l;
  for (l=0; l<A; l++)
    for (k=0; k<A; k++)
      tcm[k+l*A] = tcmone[k+l*A] + tcmtwo[k+l*A];
}
void calcTCMod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * tcm)
Definition at line 113 of file CenterofMass.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), and dim.
Referenced by calcgradprojectedHamiltonian(), calcHamiltonianod(), calcHamiltonianodmpi(), calcObservablesod(), calcprojectedHamiltonian(), and main().
{
  complex double tcmone, tcmtwo;
  OneBodyOperator op_ob_tcm = {dim: 1, opt: 1, par: Q, me: ob_tcm};
  TwoBodyOperator op_tb_tcm = {dim: 1, opt: 1, par: Q, me: tb_tcm};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_tcm, &tcmone);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_tcm, &tcmtwo);
  *tcm = tcmone+tcmtwo;
}