FMD: numerics/clebsch.c File Reference
numerics/clebsch.c File Reference
#include <math.h>
#include <assert.h>
#include "clebsch.h"
Defines
#define MAX_FACTAB 100
#define c_pi_sqrt 1.77245385090551602729817
Functions
double clebsch (int jj1, int jj2, int jj3, int mm1, int mm2, int mm3)
Variables
double tab_fac [100]
double tab_oddfac [100]
Define Documentation
#define c_pi_sqrt 1.77245385090551602729817
Definition at line 43 of file clebsch.c.
#define MAX_FACTAB 100
Definition at line 42 of file clebsch.c.
Function Documentation
double clebsch (int jj1, int jj2, int jj3, int mm1, int mm2, int mm3)
Definition at line 304 of file clebsch.c.
Referenced by amplitudesHOGaussian(), calcexpectprojectedMBME(), calcexpectprojectedMBMEipj(), calcexpectprojectedMultiMBME(), calcOneNucleonOvlapsod(), calctransitionprojectedMBME(), calctransitionprojectedMBMEipj(), calctransitionprojectedMultiMBME(), calcTwoNucleonOvlapsTod(), calcTwoNucleonOvlapsYod(), and initcg2().
{
    int nnu, lower, upper;
    double x, sign;
    if(mm3 != mm1 + mm2) return 0.;
    x = 0.0;
    lower = jj2-jj3-mm1;
    lower = (jj1-jj3+mm2 > lower? jj1-jj3+mm2 : lower);
    if(lower < 0) lower = 0;
    sign = lower%4? -1. : 1.;
    upper = jj1+jj2-jj3;
    upper = (jj1-mm1 < upper? jj1-mm1 : upper);
    upper = (jj2+mm2 < upper? jj2+mm2 : upper);
    assert(!(lower%2));
    assert(!(upper%2));
    for(nnu = lower; nnu <= upper; nnu += 2) {
        x += sign/(f1h(nnu)*f1h(jj1+jj2-jj3-nnu)*f1h(jj1-mm1-nnu)
                   *f1h(jj2+mm2-nnu)*f1h(jj3-jj2+mm1+nnu)
                   *f1h(jj3-jj1-mm2+nnu));
        sign = -sign;
    }
    x *= sqrt((double)(jj3+1)*f1h(jj1+jj2-jj3)*f1h(jj3+jj1-jj2)
              *f1h(jj3+jj2-jj1)/f1h(jj1+jj2+jj3+2)
              *f1h(jj1+mm1)*f1h(jj1-mm1)*f1h(jj2+mm2)*f1h(jj2-mm2)
              *f1h(jj3+mm3)*f1h(jj3-mm3));
    return x;
}
Variable Documentation
double tab_fac[100]
Definition at line 45 of file clebsch.c.
double tab_oddfac[100]
Definition at line 148 of file clebsch.c.