FMD: numerics/clebsch.h File Reference
numerics/clebsch.h File Reference
Functions
double clebsch (int j1, int j2, int j3, int m1, int m2, int m3)
Detailed Description
calculates Clebsch-Gordan coefficient
(c) 2003 Thomas Neff
Definition in file clebsch.h.
Function Documentation
double clebsch (int j1, int j2, int j3, int m1, int m2, int m3)
Definition at line 304 of file clebsch.c.
Referenced by amplitudesHOGaussian(), calcexpectprojectedMBME(), calcexpectprojectedMBMEipj(), calcexpectprojectedMultiMBME(), calcOneNucleonOvlapsod(), calctransitionprojectedMBME(), calctransitionprojectedMBMEipj(), calctransitionprojectedMultiMBME(), calcTwoNucleonOvlapsTod(), calcTwoNucleonOvlapsYod(), and initcg2().
{
    int nnu, lower, upper;
    double x, sign;
    if(mm3 != mm1 + mm2) return 0.;
    x = 0.0;
    lower = jj2-jj3-mm1;
    lower = (jj1-jj3+mm2 > lower? jj1-jj3+mm2 : lower);
    if(lower < 0) lower = 0;
    sign = lower%4? -1. : 1.;
    upper = jj1+jj2-jj3;
    upper = (jj1-mm1 < upper? jj1-mm1 : upper);
    upper = (jj2+mm2 < upper? jj2+mm2 : upper);
    assert(!(lower%2));
    assert(!(upper%2));
    for(nnu = lower; nnu <= upper; nnu += 2) {
        x += sign/(f1h(nnu)*f1h(jj1+jj2-jj3-nnu)*f1h(jj1-mm1-nnu)
                   *f1h(jj2+mm2-nnu)*f1h(jj3-jj2+mm1+nnu)
                   *f1h(jj3-jj1-mm2+nnu));
        sign = -sign;
    }
    x *= sqrt((double)(jj3+1)*f1h(jj1+jj2-jj3)*f1h(jj3+jj1-jj2)
              *f1h(jj3+jj2-jj1)/f1h(jj1+jj2+jj3+2)
              *f1h(jj1+mm1)*f1h(jj1-mm1)*f1h(jj2+mm2)*f1h(jj2-mm2)
              *f1h(jj3+mm3)*f1h(jj3-mm3));
    return x;
}