FMD: numerics/cmat.c File Reference
numerics/cmat.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <complex.h>
#include <math.h>
#include "cmat.h"
#include "lapack.h"
Defines
#define BUFSIZE 4096
#define BUFSIZE 655536
#define BUFSIZE 655536
#define BUFSIZE 655536
Functions
complex double * initcmat (int n)
initialize complex nxn matrix
void copycmat (int n, const complex double *A, complex double *B)
copy matrix A into B
void mirrorcmat (int n, complex double *A)
mirror upper triangle of hermitian matrix into lower triangle
void hermitizecmat (int n, complex double *A)
make matrix hermitian
void multcmat (const complex double *A, const complex double *B, complex double *C, int n)
multiply complex matrices C = A.B
void freadivec (FILE *fp, int n, int *v)
read integer vector from fp
void fprintcvec (FILE *fp, int n, const complex double *V)
write vector to fp
void fwritecvecbin (FILE *fp, int n, const complex double *V)
write vector to fp in binary format
void freadcvec (FILE *fp, int n, complex double *a)
read vector from fp
void fprintcmat (FILE *fp, int n, const complex double *A)
write matrix to fp
void fwritecmatbin (FILE *fp, int n, const complex double *A)
write matrix to fp in binary format
void freadcmat (FILE *fp, int n, complex double *A)
read matrix from fp
void fprintcmatcols (FILE *fp, int n, int cols, const complex double *A)
write colums of matrix to fp
void freadcmatcols (FILE *fp, int n, int cols, complex double *A)
read colums of matrix from fp
void pseudoinverse (const complex double *A, complex double *B, int n, double thresh)
calculate pseudoinverse B of A using SVD
void eigensystem (complex double *A, complex double *a, complex double *V, int n)
solve eigenvalue problem for complex matrix A
void generalizedeigensystem (complex double *A, complex double *N, int n, double thresh, complex double *v, complex double *V, int *dim)
void sorteigenstates (int n, complex double *v, complex double *V, int dim)
sort first dim eigenstates, starting with smallest eigenvalue
Define Documentation
#define BUFSIZE 4096
Definition at line 188 of file cmat.c.
#define BUFSIZE 655536
Definition at line 188 of file cmat.c.
#define BUFSIZE 655536
Definition at line 188 of file cmat.c.
#define BUFSIZE 655536
Definition at line 188 of file cmat.c.
Function Documentation
void copycmat (int n, const complex double * A, complex double * B)
copy matrix A into B
Definition at line 36 of file cmat.c.
Referenced by calcSlaterDetAux(), calcSlaterDetAuxod(), generalizedeigensystem(), main(), and pseudoinverse().
{
  int i;
  for (i=0; i<n*n; i++)
    B[i] = A[i];
}
void eigensystem (complex double * A, complex double * a, complex double * V, int n)
solve eigenvalue problem for complex matrix A
Definition at line 244 of file cmat.c.
References FORTRAN, and zgeev().
{
  const char jobvl='N', jobvr='V';
  const int lwork=5*n;
  complex double* work = malloc(lwork*sizeof(complex double));
  double* rwork = malloc(2*n*sizeof(double));
  int info;
  FORTRAN(zgeev)(&jobvl, &jobvr, &n, A, &n, a, NULL, &n, V, &n,
                 work, &lwork, rwork, &info);
  if (info) {
    fprintf(stderr, "eigensystem: zgeev returned with error code: %d\n", info);
  }
  free(work); free(rwork);
}
void fprintcmat (FILE * fp, int n, const complex double * A)
write matrix to fp
Definition at line 136 of file cmat.c.
References j.
{
  int i,j;
  for (i=0; i<n; i++) {
    for (j=0; j<n; j++)
      fprintf(fp, "(%15.8e,%15.8e) ", creal(A[i+j*n]), cimag(A[i+j*n]));
    fprintf(fp, "\n");
  }
}
void fprintcmatcols (FILE * fp, int n, int cols, const complex double * A)
write colums of matrix to fp
Definition at line 175 of file cmat.c.
References j.
Referenced by writeEigenstates().
{
  int i,j;
  for (i=0; i<cols; i++) {
    for (j=0; j<n; j++)
      fprintf(fp, "(%15.8e,%15.8e) ", creal(A[j+i*n]), cimag(A[j+i*n]));
    fprintf(fp, "\n");
  }
}
void fprintcvec (FILE * fp, int n, const complex double * V)
write vector to fp
Definition at line 101 of file cmat.c.
{
  int i;
  for (i=0; i<n; i++)
    fprintf(fp, "(%15.8e,%15.8e) ", creal(V[i]), cimag(V[i]));
  fprintf(fp, "\n");
}
void freadcmat (FILE * fp, int n, complex double * A)
read matrix from fp
Definition at line 155 of file cmat.c.
References BUFSIZE, I, k, and l.
{
  int k, l;
  char buf[BUFSIZE];
  char *c;
  double ref, imf;
  for (k=0; k<n; k++) {
    fgets(buf, BUFSIZE, fp);
    c = strtok(buf, " ,()");
    for (l=0; l<n; l++) {
      ref=atof(c); c=strtok(NULL, " ,()");
      imf=atof(c); c=strtok(NULL, " ,()");
      A[k+l*n] = ref + I*imf;
    }
  }
}
void freadcmatcols (FILE * fp, int n, int cols, complex double * A)
read colums of matrix from fp
Definition at line 189 of file cmat.c.
References BUFSIZE, I, k, and l.
Referenced by readEigenstates().
{
  int k, l;
  char buf[BUFSIZE];
  char *c;
  double ref, imf;
  for (k=0; k<cols; k++) {
    fgets(buf, BUFSIZE, fp);
    c = strtok(buf, " ,()");
    for (l=0; l<n; l++) {
      ref=atof(c); c=strtok(NULL, " ,()");
      imf=atof(c); c=strtok(NULL, " ,()");
      A[l+k*n] = ref + I*imf;
    }
  }
}
void freadcvec (FILE * fp, int n, complex double * a)
read vector from fp
Definition at line 118 of file cmat.c.
References BUFSIZE, I, and l.
Referenced by readEigenstates().
{
  int l;
  char buf[BUFSIZE];
  char *c;
  double ref, imf;
  fgets(buf, BUFSIZE, fp);
  c = strtok(buf, " ,()");
  for (l=0; l<n; l++) {
    ref=atof(c); c=strtok(NULL, " ,()");
    imf=atof(c); c=strtok(NULL, " ,()");
    a[l] = ref + I*imf;
  }
}
void freadivec (FILE * fp, int n, int * v)
read integer vector from fp
Definition at line 85 of file cmat.c.
References BUFSIZE, and k.
Referenced by readEigenstates().
{
  int k;
  char buf[BUFSIZE];
  char* c;
  fgets(buf, BUFSIZE, fp);
  c=strtok(buf, " ");
  for (k=0; k<n; k++) {
    v[k]=atoi(c);
    c=strtok(NULL, " ");
  }
}
void fwritecmatbin (FILE * fp, int n, const complex double * A)
write matrix to fp in binary format
Definition at line 148 of file cmat.c.
{
  fwrite(A, sizeof(complex double), n*n, fp);
}
void fwritecvecbin (FILE * fp, int n, const complex double * V)
write vector to fp in binary format
Definition at line 111 of file cmat.c.
{
  fwrite(V, sizeof (complex double), n, fp);
}
void generalizedeigensystem (complex double * A, complex double * N, int n, double thresh, complex double * v, complex double * V, int * dim)
solve generalized eigenvalue problem for complex matrices A and N using SVD
Definition at line 264 of file cmat.c.
References copycmat(), FORTRAN, j, k, l, m, zgeev(), and zgesvd().
Referenced by calcEigenstates(), calcEigenstatesK(), calcenergyeigenvalue(), calcgradprojectedHamiltonian(), calcMultiEigenstates(), calcMultiEigenstatesMulti(), calcprojectedHamiltonian(), initWork(), kmixingstates(), and main().
{
  const char jobu='O', jobvt='A';
  complex double* U = malloc(n*n*sizeof(complex double));
  complex double* Vh = malloc(n*n*sizeof(complex double));
  double* S = malloc(n*sizeof(double));
  const int lwork=5*n;
  complex double* work = malloc(lwork*sizeof(complex double));
  double* rwork = malloc(lwork*sizeof(double));
  int info;
  // perform SVD of overlap matrix
  copycmat(n, N, U);
  FORTRAN(zgesvd)(&jobu, &jobvt, &n, &n, U, &n, S,
                  NULL, &n, Vh, &n, work, &lwork, rwork, &info);
  // for zero matrices
  if (S[0] == 0.0) {
    *dim = 0;
    return;
  }
  // dimension of subspace
  int m=0;
  while (m<n && S[m]/S[0] > thresh)
    m++;
  // if our subspace is empty nothing to do any more
  if (!m) {
    *dim = 0;
    return;
  }
  // project into subspace
  complex double *AV = malloc(m*n*sizeof(complex double));
  complex double *invNA = malloc(m*m*sizeof(complex double));
  int k,l,i,j;
  for (i=0; i<n; i++)
    for (l=0; l<m; l++) {
      AV[i+l*n] = 0.0;
      for (j=0; j<n; j++)
        AV[i+l*n] += A[i+j*n]*conj(Vh[l+j*n]);
    }
  for (l=0; l<m; l++)
    for (k=0; k<m; k++) {
      invNA[k+l*m] = 0.0;
      for (i=0; i<n; i++)
        invNA[k+l*m] += 1/S[k]*conj(U[i+k*n])*AV[i+l*n];
      }
  // solve eigenvalue problem in subspace
  const char jobvl='N', jobvr='V';
  complex double *vb = malloc(m*sizeof(complex double));
  complex double *Vb = malloc(m*m*sizeof(complex double));
  FORTRAN(zgeev)(&jobvl, &jobvr, &m, invNA, &m, vb, NULL, &m, Vb, &m,
                 work, &lwork, rwork, &info);
  // imbed solution in full space
  for (i=0; i<m; i++)
    v[i] = vb[i];
  for (k=0; k<m; k++)
    for (i=0; i<n; i++) {
      V[i+k*n] = 0.0;
      for (l=0; l<m; l++)
        V[i+k*n] += conj(Vh[l+i*n])*Vb[l+k*m];
    }
  // // normalize eigenvectors with respect to overlap matrix N
  //
  // double *norm2 = malloc(m*sizeof(double));
  //
  // for (i=0; i<m; i++) {
  //   norm2[i] = 0.0;
  //
  //   for (k=0; k<n; k++)
  //     for (l=0; l<n; l++)
  //       norm2[i] += conj(V[l+i*n])*N[l+k*n]*V[k+i*n];
  // }
  //
  // for (i=0; i<m; i++)
  //   for (k=0; k<n; k++)
  //     V[k+i*n] /= sqrt(norm2[i]);
  //
  // free(norm2);
  *dim = m;
  free(Vb); free(vb);
  free(AV); free(invNA);
  free(work); free(rwork);
  free(U); free(Vh); free(S);
}
void hermitizecmat (int n, complex double * A)
make matrix hermitian
Definition at line 55 of file cmat.c.
References j.
{
  int i,j;
  complex double alower, aupper;
  for (i=0; i<n; i++)
    for (j=0; j<=i; j++) {
      aupper = A[i+n*j];
      alower = A[j+n*i];
      A[i+n*j] = 0.5*(aupper+conj(alower));
      A[j+n*i] = 0.5*(alower+conj(aupper));
    }
}
complex double* initcmat (int n)
initialize complex nxn matrix
Definition at line 23 of file cmat.c.
Referenced by allocateSlaterDetAux(), calcShellOccupationsod(), and initSlaterDetAux().
{
  int i;
  complex double* A;
  A = (complex double*) malloc(n*n*sizeof(complex double));
  for (i=0; i<n*n; i++)
    A[i] = 0.0;
  return A;
}
void mirrorcmat (int n, complex double * A)
mirror upper triangle of hermitian matrix into lower triangle
Definition at line 45 of file cmat.c.
References j.
Referenced by calcSlaterDetAux().
{
  int i,j;
  for (j=0; j<n; j++)
    for (i=0; i<j; i++)
      A[j+i*n] = conj(A[i+j*n]);
}
void multcmat (const complex double * A, const complex double * B, complex double * C, int n)
multiply complex matrices C = A.B
Definition at line 70 of file cmat.c.
References k, l, and m.
Referenced by calcEigenstates(), calcgradprojectedHamiltonian(), calcprojectedHamiltonian(), calcSlaterDetAuxodsingular(), and kmixingstates().
{
  int k,l,m;
  for (l=0; l<n; l++)
    for (k=0; k<n; k++) {
      C[l*n+k] = 0.0;
      for (m=0; m<n; m++)
        C[l*n+k] += A[m*n+k]*B[l*n+m];
    }
}
void pseudoinverse (const complex double * A, complex double * B, int n, double thresh)
calculate pseudoinverse B of A using SVD
Definition at line 208 of file cmat.c.
References copycmat(), FORTRAN, k, l, m, and zgesvd().
Referenced by calcbasisovlap(), calcsubspaceoverlap(), and main().
{
  const char jobu='O', jobvt='A';
  complex double *U = malloc(n*n*sizeof(complex double));
  complex double *Vh = malloc(n*n*sizeof(complex double));
  double* S = malloc(n*sizeof(double));
  const int lwork=5*n;
  complex double* work = malloc(lwork*sizeof(complex double));
  double* rwork = malloc(lwork*sizeof(double));
  int info;
  copycmat(n, A, U);
  FORTRAN(zgesvd)(&jobu, &jobvt, &n, &n, U, &n, S,
                  NULL, &n, Vh, &n, work, &lwork, rwork, &info);
  int k,l,m;
  for (l=0; l<n; l++)
    for (k=0; k<n; k++) {
      B[k+l*n] = 0.0;
      m=0;
      while (m<n && S[m]/S[0] > thresh) {
        B[k+l*n] += conj(Vh[m+k*n])*1/S[m]*conj(U[l+m*n]);
        m++;
      }
    }
  free(Vh); free(U); free(S);
  free(work); free(rwork);
}
void sorteigenstates (int n, complex double * v, complex double * V, int dim)
sort first dim eigenstates, starting with smallest eigenvalue
Definition at line 381 of file cmat.c.
References k, and val.
Referenced by calcgradprojectedHamiltonian(), calcprojectedHamiltonian(), and initWork().
{
  int i,k;
  struct merit {
    double val;
    int idx;
  } merits[dim];
  for (i=0; i<dim; i++) {
    merits[i].idx = i;
    merits[i].val = -creal(v[i]);
  }
  qsort(merits, dim, sizeof(struct merit), cmpmerit);
  complex double vsorted[dim];
  complex double Vsorted[n*dim];
  for (i=0; i<dim; i++) {
    vsorted[i] = v[merits[i].idx];
    for (k=0; k<n; k++)
      Vsorted[k+i*n] = V[k+merits[i].idx*n];
  }
  // copy into original v and V
  for (i=0; i<dim; i++) {
    v[i] = vsorted[i];
    for (k=0; k<n; k++)
      V[k+i*n] = Vsorted[k+i*n];
  }
}