FMD: fmd/cmprojection.c File Reference
fmd/cmprojection.c File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "SlaterDet.h"
#include "CenterofMass.h"
#include "Projection.h"
#include "misc/physics.h"
#include "numerics/gaussquad.h"
Defines
#define SQR(x) ((x)*(x))
#define CUB(x) ((x)*(x)*(x))
Functions
void initCMintegration (cmintegrationpara *cmpara, const char *projpar)
double _estimateacm (const SlaterDet *Q)
void _initcmintegration (const Projection *P, double alpha, cmintegrationpara *par)
void initcmintegration (const Projection *P, const SlaterDet *Q, const SlaterDet *Qp, cmintegrationpara *par)
void reinitcmintegration (const SlaterDet *Q, const SlaterDet *Qp, cmintegrationpara *par)
void freecmintegration (cmintegrationpara *par)
void getcmintegrationpoint (int i, const cmintegrationpara *par, double x[3], double *w)
Variables
double linear [1][3] = {{ 0., 0., 1.}}
double tetrahedron [4][3]
double octahedron [6][3]
double cube [8][3]
double(*[] polyhedron)[3]
Detailed Description
Gridpoints used for linear momentum projection
(c) 2004-2011 Thomas Neff
Definition in file cmprojection.c.
Define Documentation
#define CUB (x) ((x)*(x)*(x))
Definition at line 31 of file cmprojection.c.
Referenced by _initcmintegration(), and reinitcmintegration().
#define SQR (x) ((x)*(x))
Definition at line 30 of file cmprojection.c.
Function Documentation
double _estimateacm (const SlaterDet * Q)
Definition at line 128 of file cmprojection.c.
References calcSlaterDetAux(), calcTCM(), freeSlaterDetAux(), initSlaterDetAux(), mneutron, mproton, SlaterDet::N, X, and SlaterDet::Z.
Referenced by calcprojectedMultiMBME(), calcprojectedMultiMBMEmpi(), initcmintegration(), and reinitcmintegration().
{
  // do we have to initialize workspace first ?
  // if (X.Gaux == NULL)
  //   initSlaterDetAux(Q, &X);
  SlaterDetAux X;
  initSlaterDetAux(Q, &X);
  double tcm;
  calcSlaterDetAux(Q, &X);
  calcTCM(Q, &X, &tcm);
  freeSlaterDetAux(&X);
  return (0.75/(tcm*(mproton*Q->Z+mneutron*Q->N)));
}
void _initcmintegration (const Projection * P, double alpha, cmintegrationpara * par)
Definition at line 147 of file cmprojection.c.
References Projection::cm, CMNone, Projection::cmpoly, CMPoly, Projection::cmprod, CMProd, CMSimple, CUB, GaussLegendrePoints(), GaussSqrHermitePoints(), j, cmintegrationpara::n, cmprodpara::nphi, cmpolypara::npoly, cmpolypara::nr, cmprodpara::nr, nr, cmprodpara::ntheta, nx, polyhedron, ShiftedPeriodicTrapezoidalPoints(), SQR, cmintegrationpara::w, and cmintegrationpara::x.
Referenced by calcprojectedMultiMBME(), calcprojectedMultiMBMEmpi(), and initcmintegration().
{
  if (P->cm == CMNone) {
    par->n = 1;
    par->x = malloc(3*sizeof(double));
    par->w = malloc(1*sizeof(double));
    par->x[0][0] = 0.0; par->x[0][1] = 0.0; par->x[0][2] = 0.0;
    par->w[0] = 1.0;
  }
  else if (P->cm == CMSimple) {
    par->n = 1;
    par->x = malloc(3*sizeof(double));
    par->w = malloc(1*sizeof(double));
    par->x[0][0] = 0.0; par->x[0][1] = 0.0; par->x[0][2] = 0.0;
    par->w[0] = 0.125*pow(M_PI*alpha,-1.5);
  }
  else if (P->cm == CMProd) {
    int nr=P->cmprod.nr;
    int nx=P->cmprod.ntheta; int nphi=P->cmprod.nphi;
    double pointr[nr], weightr[nr];
    GaussSqrHermitePoints(nr, alpha, pointr, weightr);
    double pointx[nx], weightx[nx];
    GaussLegendrePoints(nx, -1.0, 1.0, pointx, weightx);
    double pointphi[nphi], weightphi[nphi];
    ShiftedPeriodicTrapezoidalPoints(nphi, 0, 2*M_PI, 0.00,
                                     pointphi, weightphi);
    par->n = nr*nx*nphi;
    par->x = malloc(3*par->n*sizeof(double));
    par->w = malloc(par->n*sizeof(double));
    int i=0;
    int ir, ix, iphi;
    for (ir=0; ir<nr; ir++)
      for (ix=0; ix<nx; ix++)
        for (iphi=0; iphi<nphi; iphi++) {
          par->x[i][0] = pointr[ir]*sqrt(1-SQR(pointx[ix]))*cos(pointphi[iphi]);
          par->x[i][1] = pointr[ir]*sqrt(1-SQR(pointx[ix]))*sin(pointphi[iphi]);
          par->x[i][2] = pointr[ir]*pointx[ix];
          par->w[i] = 1/CUB(2*M_PI)*
            weightr[ir]*weightx[ix]*weightphi[iphi];
          i++;
        }
  }
  else if (P->cm == CMPoly) {
    int nr=P->cmpoly.nr;
    int npoly=P->cmpoly.npoly;
    double pointr[nr], weightr[nr];
    GaussSqrHermitePoints(nr, alpha, pointr, weightr);
    par->n = nr*npoly;
    par->x = malloc(3*par->n*sizeof(double));
    par->w = malloc(par->n*sizeof(double));
    int i=0;
    int ir, ipoly, j;
    for (ir=0; ir<nr; ir++)
      for (ipoly=0; ipoly<npoly; ipoly++) {
        for (j=0; j<3; j++)
          par->x[i][j] = pointr[ir]*polyhedron[npoly][ipoly][j];
        par->w[i] = 1/CUB(2*M_PI)*
          weightr[ir]*(4*M_PI/npoly);
        i++;
      }
  }
}
void freecmintegration (cmintegrationpara * par)
Definition at line 298 of file cmprojection.c.
References cmintegrationpara::w, and cmintegrationpara::x.
Referenced by calcprojectedMultiMBME(), and calcprojectedMultiMBMEmpi().
{
  free(par->x);
  free(par->w);
}
void getcmintegrationpoint (int i, const cmintegrationpara * par, double x[3], double * w)
Definition at line 305 of file cmprojection.c.
References j, n, cmintegrationpara::w, and cmintegrationpara::x.
Referenced by calcgradprojectedHamiltonianmatrix(), calcprojectedHamiltonianmatrix(), calcprojectedMBME(), calcprojectedMBMEmpi(), calcprojectedMBMEs(), calcprojectedMBMEsmpi(), calcprojectedMultiMBME(), and calcprojectedMultiMBMEmpi().
{
  assert(i < par->n);
  int j;
  for (j=0; j<3; j++)
    x[j] = par->x[i][j];
  *w = par->w[i];
  // fprintf(stderr, "cm integration point: (%8.5f, %8.5f, %8.5f) weight %8.5f\n",
  //         x[0], x[1], x[2], *w);
}
void initcmintegration (const Projection * P, const SlaterDet * Q, const SlaterDet * Qp, cmintegrationpara * par)
Definition at line 224 of file cmprojection.c.
References _estimateacm(), _initcmintegration(), and alpha.
Referenced by calcprojectedMBME(), calcprojectedMBMEmpi(), calcprojectedMBMEs(), and calcprojectedMBMEsmpi().
{
  alpha = 0.5/(_estimateacm(Q)+_estimateacm(Qp));
  _initcmintegration(P, alpha, par);
}
void initCMintegration (cmintegrationpara * cmpara, const char * projpar)
Definition at line 69 of file cmprojection.c.
References cmintegrationpara::n, cmprodpara::nphi, cmpolypara::npoly, cmprodpara::nr, cmpolypara::nr, nr, cmprodpara::ntheta, cmintegrationpara::poly, cmintegrationpara::prod, cmintegrationpara::type, cmintegrationpara::w, and cmintegrationpara::x.
Referenced by main().
{
  char projparcpy[strlen(projpar)];
  strcpy(projparcpy, projpar);
  char* c = projparcpy;
  // default is CMNone
  cmpara->type = CMNone;
  cmpara->n = 1;
  c = strtok(c, "-");
  while (c && strncmp(c, "cm", 2)) {
    c=strtok(NULL, "-");
  };
  if (c) {
    c=strtok(NULL, "-");
    if (!strncmp(c, "none", 4)) {
      cmpara->type = CMNone;
      cmpara->n = 1;
    } else if (!strncmp(c, "simple", 6)) {
      cmpara->type = CMSimple;
      cmpara->n = 1;
    } else {
      int nr = atoi(c);
      c=strtok(NULL, "-");
      if (!strncmp(c, "tet", 3)) {
        cmpara->type = CMPoly;
        cmpara->poly.nr = nr;
        cmpara->poly.npoly = 4;
        cmpara->n = 4*nr;
      } else if (!strncmp(c, "oct", 3)) {
        cmpara->type = CMPoly;
        cmpara->poly.nr = nr;
        cmpara->poly.npoly = 6;
        cmpara->n = 6*nr;
      } else if (!strncmp(c, "cbe", 3)) {
        cmpara->type = CMPoly;
        cmpara->poly.nr = nr;
        cmpara->poly.npoly = 8;
        cmpara->n = 8*nr;
      } else {
        cmpara->type = CMProd;
        cmpara->prod.nr = nr;
        cmpara->prod.ntheta = atoi(c);
        c = strtok(NULL, "-");
        cmpara->prod.nphi = atoi(c);
        cmpara->n = nr*cmpara->prod.ntheta*cmpara->prod.nphi;
      }
    }
  }
  cmpara->x = malloc(3*cmpara->n*sizeof(double));
  cmpara->w = malloc(cmpara->n*sizeof(double));
  return 0;
}
void reinitcmintegration (const SlaterDet * Q, const SlaterDet * Qp, cmintegrationpara * par)
Definition at line 234 of file cmprojection.c.
References _estimateacm(), alpha, CMNone, CMPoly, CMProd, CMSimple, CUB, GaussLegendrePoints(), GaussSqrHermitePoints(), j, cmprodpara::nphi, cmpolypara::npoly, cmpolypara::nr, cmprodpara::nr, nr, cmprodpara::ntheta, nx, cmintegrationpara::poly, polyhedron, cmintegrationpara::prod, ShiftedPeriodicTrapezoidalPoints(), SQR, cmintegrationpara::type, cmintegrationpara::w, and cmintegrationpara::x.
Referenced by calcgradprojectedHamiltonianmatrix(), and calcprojectedHamiltonianmatrix().
{
  alpha = 0.5/(_estimateacm(Q)+_estimateacm(Qp));
  if (par->type == CMNone) {
    par->w[0] = 1.0;
    par->x[0][0] = 0.0; par->x[0][1] = 0.0; par->x[0][2] = 0.0;
  }
  else if (par->type == CMSimple) {
    par->w[0] = 0.125*pow(M_PI*alpha,-1.5);
    par->x[0][0] = 0.0; par->x[0][1] = 0.0; par->x[0][2] = 0.0;
  }
  else if (par->type == CMProd) {
    int nr=par->prod.nr;
    int nx=par->prod.ntheta; int nphi=par->prod.nphi;
    double pointr[nr], weightr[nr];
    GaussSqrHermitePoints(nr, alpha, pointr, weightr);
    double pointx[nx], weightx[nx];
    GaussLegendrePoints(nx, -1.0, 1.0, pointx, weightx);
    double pointphi[nphi], weightphi[nphi];
    ShiftedPeriodicTrapezoidalPoints(nphi, 0, 2*M_PI, 0.00,
                                     pointphi, weightphi);
    int i=0;
    int ir, ix, iphi;
    for (ir=0; ir<nr; ir++)
      for (ix=0; ix<nx; ix++)
        for (iphi=0; iphi<nphi; iphi++) {
          par->x[i][0] = pointr[ir]*sqrt(1-SQR(pointx[ix]))*cos(pointphi[iphi]);
          par->x[i][1] = pointr[ir]*sqrt(1-SQR(pointx[ix]))*sin(pointphi[iphi]);
          par->x[i][2] = pointr[ir]*pointx[ix];
          par->w[i] = 1/CUB(2*M_PI)*
            weightr[ir]*weightx[ix]*weightphi[iphi];
          i++;
        }
  }
  else if (par->type == CMPoly) {
    int nr=par->poly.nr;
    int npoly=par->poly.npoly;
    double pointr[nr], weightr[nr];
    GaussSqrHermitePoints(nr, alpha, pointr, weightr);
    int i=0;
    int ir, ipoly, j;
    for (ir=0; ir<nr; ir++)
      for (ipoly=0; ipoly<npoly; ipoly++) {
        for (j=0; j<3; j++)
          par->x[i][j] = pointr[ir]*polyhedron[npoly][ipoly][j];
        par->w[i] = 1/CUB(2*M_PI)*
          weightr[ir]*(4*M_PI/npoly);
        i++;
      }
  }
}
Variable Documentation
double cube[8][3]
Initial value:
 {{  0.57735,  0.57735,  0.57735},
                     {  0.57735,  0.57735, -0.57735},
                     {  0.57735, -0.57735,  0.57735},
                     {  0.57735, -0.57735, -0.57735},
                     { -0.57735,  0.57735,  0.57735},
                     { -0.57735,  0.57735, -0.57735},
                     { -0.57735, -0.57735,  0.57735},
                     { -0.57735, -0.57735, -0.57735}}
Definition at line 48 of file cmprojection.c.
double linear[1][3] = {{ 0., 0., 1.}}
Definition at line 34 of file cmprojection.c.
double octahedron[6][3]
Initial value:
 {{0., 0., 1.},
                           {1., 0., 0.},
                           {0., 1., 0.},
                           {0., 0., -1.},
                           {-1., 0., 0.},
                           {0, -1., 0.}}
Definition at line 41 of file cmprojection.c.
double(*[] polyhedron)[3]
Initial value:
 { NULL,
                              linear,
                              NULL,
                              NULL,
                              tetrahedron,
                              NULL,
                              octahedron,
                              NULL,
                              cube }
Definition at line 57 of file cmprojection.c.
Referenced by _initcmintegration(), and reinitcmintegration().
double tetrahedron[4][3]
Initial value:
 {{0., 0., 1.},
                            {0., 0.942809, -0.333333},
                            {-0.816497, -0.471405, -0.333333},
                            {0.816497, -0.471405, -0.333333}}
Definition at line 36 of file cmprojection.c.