FMD: fmdmpi/Communication.c File Reference
fmdmpi/Communication.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mpi.h>
#include "fmd/Interaction.h"
#include "fmd/Gaussian.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "Communication.h"
Defines
#define SQR(x) ((x)*(x))
Functions
void BroadcastA (int *A)
broadcast size of nucleus
void BroadcastTask (int *task)
void BroadcastSlaterDet (SlaterDet *Q)
void BroadcastSlaterDetAux (const SlaterDet *Q, SlaterDetAux *X)
void BroadcastgradSlaterDetAux (const SlaterDet *Q, gradSlaterDetAux *dX)
void BroadcastInteraction (Interaction *Int)
void BroadcastParameters (void *par, int size)
generic broadcast for Parameters
Variables
int mpirank
int mpisize
Detailed Description
Communicate using MPI
(c) 2003 Thomas Neff
Definition in file Communication.c.
Define Documentation
#define SQR (x) ((x)*(x))
Definition at line 26 of file Communication.c.
Function Documentation
void BroadcastA (int * A)
broadcast size of nucleus
Definition at line 32 of file Communication.c.
Referenced by DiagonalDensityHOSlave(), FormfactorSlave(), main(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
{
  MPI_Bcast(A, 1, MPI_INT, 0, MPI_COMM_WORLD);
}
void BroadcastgradSlaterDetAux (const SlaterDet * Q, gradSlaterDetAux * dX)
Definition at line 85 of file Communication.c.
References SlaterDet::A, gradSlaterDetAux::dGaux, gradSlaterDetAux::dno, gradSlaterDetAux::ngauss, and SQR.
{
  MPI_Bcast(&dX->ngauss, 1, MPI_INT, 0, MPI_COMM_WORLD);
  MPI_Bcast(dX->dGaux, SQR(dX->ngauss)*sizeof(gradGaussianAux),
            MPI_BYTE, 0, MPI_COMM_WORLD);
  MPI_Bcast(dX->dno, Q->A*dX->ngauss*sizeof(gradGaussian),
            MPI_BYTE, 0, MPI_COMM_WORLD);
}
void BroadcastInteraction (Interaction * Int)
slaves allocate space for Interaction labels are not broadcastet
Definition at line 97 of file Communication.c.
References Interaction::c, mpirank, and Interaction::ncomponents.
Referenced by main(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), and ProjectionSlave().
{
  if (mpirank == 0) {
    // send
    MPI_Bcast(Int, sizeof(Interaction), MPI_BYTE, 0, MPI_COMM_WORLD);
    MPI_Bcast(Int->c, Int->ncomponents*sizeof(InteractionComponent),
              MPI_BYTE, 0, MPI_COMM_WORLD);
  } else {
    // receive
    MPI_Bcast(Int, sizeof(Interaction), MPI_BYTE, 0, MPI_COMM_WORLD);
    Int->c = malloc(Int->ncomponents*sizeof(InteractionComponent));
    MPI_Bcast(Int->c, Int->ncomponents*sizeof(InteractionComponent),
              MPI_BYTE, 0, MPI_COMM_WORLD);
  }
}
void BroadcastParameters (void * par, int size)
generic broadcast for Parameters
generic broadcast for Parameters will only broadcast scalar components
Definition at line 117 of file Communication.c.
References mpirank.
Referenced by DiagonalDensityHOSlave(), FormfactorSlave(), and main().
{
  if (mpirank == 0) {
    // send
    MPI_Bcast(par, size, MPI_BYTE, 0, MPI_COMM_WORLD);
  } else {
    // receive
    MPI_Bcast(par, size, MPI_BYTE, 0, MPI_COMM_WORLD);
  }
}
void BroadcastSlaterDet (SlaterDet * Q)
Definition at line 45 of file Communication.c.
References SlaterDet::A, G, SlaterDet::G, SlaterDet::idx, mpirank, ng, SlaterDet::ng, and SlaterDet::ngauss.
Referenced by calcgradPotentialmpi(), calcgradPotentialodmpi(), calcPotentialmpi(), calcPotentialodmpi(), calcprojectedMBMEmpi(), calcprojectedMBMEsmpi(), calcprojectedMultiMBMEmpi(), DiagonalDensityHOSlave(), FormfactorSlave(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
{
  if (mpirank == 0) {
    // send
    MPI_Bcast(Q, sizeof(SlaterDet), MPI_BYTE, 0, MPI_COMM_WORLD);
    MPI_Bcast(Q->idx, Q->A, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(Q->ng, Q->A, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(Q->G, Q->ngauss*sizeof(Gaussian),
              MPI_BYTE, 0, MPI_COMM_WORLD);
  } else {
    int* idx = Q->idx;
    int* ng = Q->ng;
    Gaussian* G = Q->G;
    MPI_Bcast(Q, sizeof(SlaterDet), MPI_BYTE, 0, MPI_COMM_WORLD);
    Q->idx = idx;
    Q->ng = ng;
    Q->G = G;
    MPI_Bcast(Q->idx, Q->A, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(Q->ng, Q->A, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(Q->G, Q->ngauss*sizeof(Gaussian),
              MPI_BYTE, 0, MPI_COMM_WORLD);
  }
}
void BroadcastSlaterDetAux (const SlaterDet * Q, SlaterDetAux * X)
Definition at line 72 of file Communication.c.
References SlaterDet::A, SlaterDetAux::Gaux, SlaterDetAux::n, SlaterDet::ngauss, SlaterDetAux::o, SlaterDetAux::ovlap, and SQR.
{
    MPI_Bcast(X->Gaux, SQR(Q->ngauss)*sizeof(GaussianAux),
              MPI_BYTE, 0, MPI_COMM_WORLD);
    MPI_Bcast(X->n, SQR(Q->A)*sizeof(complex double),
              MPI_BYTE, 0, MPI_COMM_WORLD);
    MPI_Bcast(X->o, SQR(Q->A)*sizeof(complex double),
              MPI_BYTE, 0, MPI_COMM_WORLD);
    MPI_Bcast(&X->ovlap, 1,
              MPI_DOUBLE_COMPLEX, 0, MPI_COMM_WORLD);
}
void BroadcastTask (int * task)
Definition at line 38 of file Communication.c.
Referenced by calcgradPotentialmpi(), calcgradPotentialodmpi(), calcPotentialmpi(), calcPotentialodmpi(), calcprojectedMBMEmpi(), calcprojectedMBMEsmpi(), calcprojectedMultiMBMEmpi(), cleanup(), DiagonalDensityHOSlave(), FormfactorSlave(), main(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
{
  MPI_Bcast(task, 1, MPI_INT, 0, MPI_COMM_WORLD);
}
Variable Documentation
int mpirank
Definition at line 28 of file Communication.c.
Referenced by BroadcastInteraction(), BroadcastParameters(), BroadcastSlaterDet(), and main().
int mpisize
Definition at line 29 of file Communication.c.
Referenced by calcgradPotentialmpi(), calcgradPotentialodmpi(), calcPotentialmpi(), calcPotentialodmpi(), calcprojectedMBMEmpi(), calcprojectedMBMEsmpi(), calcprojectedMultiMBMEmpi(), and main().