FMD: fmdmpi/Communication.h File Reference
fmdmpi/Communication.h File Reference
#include "../fmd/Interaction.h"
#include "../fmd/SlaterDet.h"
#include "../fmd/gradSlaterDet.h"
Defines
#define TASKFIN -1
#define TASKSTART 1
#define TASKSTARTCM 2
#define TASKPOTENTIAL 10
#define TASKGRADPOTENTIAL 11
#define TASKPOTENTIALOD 12
#define TASKGRADPOTENTIALOD 13
#define TASKHAMILTONIANOD 14
#define TASKGRADHAMILTONIANOD 15
#define TASKPROJECTOVLAPOD 100
#define TASKPROJECTOBSERVABLESOD 101
#define TASKPROJECTMONOPOLEFORMFACTOROD 110
#define TASKPROJECTEDDIAGONALDENSITYMATRIXHOOD 120
#define TASKPROJECTONENUCLEONOVLAPSOD 130
#define TASKPROJECTTWONUCLEONOVLAPSTOD 140
#define TASKPROJECTTWONUCLEONOVLAPSYOD 141
#define TAGROW 0
#define TAGROWCOL 1
#define TAGANGLES3 2
#define TAGPROJECT3 3
#define TAGPROJECT6 4
#define TAGPOTENTIAL 11
#define TAGGRADPOTENTIALVAL 12
#define TAGGRADPOTENTIALGRAD 13
#define TAGPOTENTIALOD 21
#define TAGGRADPOTENTIALODVAL 22
#define TAGGRADPOTENTIALODGRAD 23
#define TAGOVLAPOD 31
#define TAGGRADOVLAPODVAL 32
#define TAGGRADOVLAPODGRAD 33
#define TAGHAMILTONIANOD 41
#define TAGGRADHAMILTONIANODVAL 42
#define TAGGRADHAMILTONIANODGRAD 43
#define TAGANGULARMOMENTUMOD 51
#define TAGMEOD 1001
Functions
void BroadcastInteraction (Interaction *Int)
void BroadcastParameters (void *par, int size)
generic broadcast for Parameters
void BroadcastA (int *A)
broadcast size of nucleus
void BroadcastTask (int *task)
void BroadcastSlaterDet (SlaterDet *Q)
void BroadcastSlaterDetAux (const SlaterDet *Q, SlaterDetAux *X)
void BroadcastgradSlaterDetAux (const SlaterDet *Q, gradSlaterDetAux *dX)
Variables
int mpirank
int mpisize
Detailed Description
Communicate using MPI
(c) 2003 Thomas Neff
Definition in file Communication.h.
Define Documentation
#define TAGANGLES3 2
Definition at line 38 of file Communication.h.
#define TAGANGULARMOMENTUMOD 51
Definition at line 53 of file Communication.h.
Referenced by MinimizerprojSlave().
#define TAGGRADHAMILTONIANODGRAD 43
Definition at line 52 of file Communication.h.
Referenced by MinimizerprojSlave().
#define TAGGRADHAMILTONIANODVAL 42
Definition at line 51 of file Communication.h.
Referenced by MinimizerprojSlave().
#define TAGGRADOVLAPODGRAD 33
Definition at line 49 of file Communication.h.
Referenced by MinimizerprojSlave().
#define TAGGRADOVLAPODVAL 32
Definition at line 48 of file Communication.h.
Referenced by MinimizerprojSlave().
#define TAGGRADPOTENTIALGRAD 13
Definition at line 43 of file Communication.h.
Referenced by calcgradPotentialmpi(), and MinimizerSlave().
#define TAGGRADPOTENTIALODGRAD 23
Definition at line 46 of file Communication.h.
Referenced by calcgradPotentialodmpi(), and MinimizerSlaveod().
#define TAGGRADPOTENTIALODVAL 22
Definition at line 45 of file Communication.h.
Referenced by calcgradPotentialodmpi(), and MinimizerSlaveod().
#define TAGGRADPOTENTIALVAL 12
Definition at line 42 of file Communication.h.
Referenced by calcgradPotentialmpi(), and MinimizerSlave().
#define TAGHAMILTONIANOD 41
Definition at line 50 of file Communication.h.
Referenced by MinimizerprojSlave().
#define TAGMEOD 1001
Definition at line 55 of file Communication.h.
Referenced by calcprojectedMBMEmpi(), calcprojectedMBMEsmpi(), calcprojectedMultiMBMEmpi(), DiagonalDensityHOSlave(), FormfactorSlave(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
#define TAGOVLAPOD 31
Definition at line 47 of file Communication.h.
Referenced by MinimizerprojSlave().
#define TAGPOTENTIAL 11
Definition at line 41 of file Communication.h.
Referenced by calcPotentialmpi(), and MinimizerSlave().
#define TAGPOTENTIALOD 21
Definition at line 44 of file Communication.h.
Referenced by calcPotentialodmpi(), and MinimizerSlaveod().
#define TAGPROJECT3 3
Definition at line 39 of file Communication.h.
Referenced by MinimizerprojSlave().
#define TAGPROJECT6 4
Definition at line 40 of file Communication.h.
Referenced by calcprojectedMBMEmpi(), calcprojectedMBMEsmpi(), calcprojectedMultiMBMEmpi(), DiagonalDensityHOSlave(), FormfactorSlave(), MinimizerprojSlave(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
#define TAGROW 0
Definition at line 36 of file Communication.h.
#define TAGROWCOL 1
Definition at line 37 of file Communication.h.
Referenced by calcgradPotentialmpi(), calcgradPotentialodmpi(), calcPotentialmpi(), calcPotentialodmpi(), MinimizerSlave(), and MinimizerSlaveod().
#define TASKFIN -1
Definition at line 17 of file Communication.h.
Referenced by MinimizerSlave(), and MinimizerSlaveod().
#define TASKGRADHAMILTONIANOD 15
Definition at line 25 of file Communication.h.
Referenced by MinimizerprojSlave().
#define TASKGRADPOTENTIAL 11
Definition at line 21 of file Communication.h.
Referenced by MinimizerSlave().
#define TASKGRADPOTENTIALOD 13
Definition at line 23 of file Communication.h.
Referenced by MinimizerSlaveod().
#define TASKHAMILTONIANOD 14
Definition at line 24 of file Communication.h.
Referenced by MinimizerprojSlave().
#define TASKPOTENTIAL 10
Definition at line 20 of file Communication.h.
Referenced by MinimizerSlave().
#define TASKPOTENTIALOD 12
Definition at line 22 of file Communication.h.
Referenced by MinimizerSlaveod().
#define TASKPROJECTEDDIAGONALDENSITYMATRIXHOOD 120
Definition at line 30 of file Communication.h.
Referenced by DiagonalDensityHOSlave().
#define TASKPROJECTMONOPOLEFORMFACTOROD 110
Definition at line 29 of file Communication.h.
Referenced by FormfactorSlave().
#define TASKPROJECTOBSERVABLESOD 101
Definition at line 28 of file Communication.h.
Referenced by ProjectionSlave().
#define TASKPROJECTONENUCLEONOVLAPSOD 130
Definition at line 31 of file Communication.h.
Referenced by OneNucleonOvlapsSlave().
#define TASKPROJECTOVLAPOD 100
Definition at line 27 of file Communication.h.
Referenced by ProjectionSlave().
#define TASKPROJECTTWONUCLEONOVLAPSTOD 140
Definition at line 32 of file Communication.h.
Referenced by TwoNucleonOvlapsSlave().
#define TASKPROJECTTWONUCLEONOVLAPSYOD 141
Definition at line 33 of file Communication.h.
Referenced by TwoNucleonOvlapsSlave().
#define TASKSTART 1
Definition at line 18 of file Communication.h.
Referenced by DiagonalDensityHOSlave(), FormfactorSlave(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
#define TASKSTARTCM 2
Definition at line 19 of file Communication.h.
Referenced by MinimizerprojSlave().
Function Documentation
void BroadcastA (int * A)
broadcast size of nucleus
Definition at line 32 of file Communication.c.
Referenced by DiagonalDensityHOSlave(), FormfactorSlave(), main(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
{
  MPI_Bcast(A, 1, MPI_INT, 0, MPI_COMM_WORLD);
}
void BroadcastgradSlaterDetAux (const SlaterDet * Q, gradSlaterDetAux * dX)
Definition at line 85 of file Communication.c.
References SlaterDet::A, gradSlaterDetAux::dGaux, gradSlaterDetAux::dno, gradSlaterDetAux::ngauss, and SQR.
{
  MPI_Bcast(&dX->ngauss, 1, MPI_INT, 0, MPI_COMM_WORLD);
  MPI_Bcast(dX->dGaux, SQR(dX->ngauss)*sizeof(gradGaussianAux),
            MPI_BYTE, 0, MPI_COMM_WORLD);
  MPI_Bcast(dX->dno, Q->A*dX->ngauss*sizeof(gradGaussian),
            MPI_BYTE, 0, MPI_COMM_WORLD);
}
void BroadcastInteraction (Interaction * Int)
use MPI Broadcast to distribute Interaction parameters slaves allocate space for Interaction labels are not broadcastet
slaves allocate space for Interaction labels are not broadcastet
Definition at line 97 of file Communication.c.
References Interaction::c, mpirank, and Interaction::ncomponents.
Referenced by main(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), and ProjectionSlave().
{
  if (mpirank == 0) {
    // send
    MPI_Bcast(Int, sizeof(Interaction), MPI_BYTE, 0, MPI_COMM_WORLD);
    MPI_Bcast(Int->c, Int->ncomponents*sizeof(InteractionComponent),
              MPI_BYTE, 0, MPI_COMM_WORLD);
  } else {
    // receive
    MPI_Bcast(Int, sizeof(Interaction), MPI_BYTE, 0, MPI_COMM_WORLD);
    Int->c = malloc(Int->ncomponents*sizeof(InteractionComponent));
    MPI_Bcast(Int->c, Int->ncomponents*sizeof(InteractionComponent),
              MPI_BYTE, 0, MPI_COMM_WORLD);
  }
}
void BroadcastParameters (void * par, int size)
generic broadcast for Parameters
generic broadcast for Parameters will only broadcast scalar components
Definition at line 117 of file Communication.c.
References mpirank.
Referenced by DiagonalDensityHOSlave(), FormfactorSlave(), and main().
{
  if (mpirank == 0) {
    // send
    MPI_Bcast(par, size, MPI_BYTE, 0, MPI_COMM_WORLD);
  } else {
    // receive
    MPI_Bcast(par, size, MPI_BYTE, 0, MPI_COMM_WORLD);
  }
}
void BroadcastSlaterDet (SlaterDet * Q)
Definition at line 45 of file Communication.c.
References SlaterDet::A, G, SlaterDet::G, SlaterDet::idx, mpirank, ng, SlaterDet::ng, and SlaterDet::ngauss.
Referenced by calcgradPotentialmpi(), calcgradPotentialodmpi(), calcPotentialmpi(), calcPotentialodmpi(), calcprojectedMBMEmpi(), calcprojectedMBMEsmpi(), calcprojectedMultiMBMEmpi(), DiagonalDensityHOSlave(), FormfactorSlave(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
{
  if (mpirank == 0) {
    // send
    MPI_Bcast(Q, sizeof(SlaterDet), MPI_BYTE, 0, MPI_COMM_WORLD);
    MPI_Bcast(Q->idx, Q->A, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(Q->ng, Q->A, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(Q->G, Q->ngauss*sizeof(Gaussian),
              MPI_BYTE, 0, MPI_COMM_WORLD);
  } else {
    int* idx = Q->idx;
    int* ng = Q->ng;
    Gaussian* G = Q->G;
    MPI_Bcast(Q, sizeof(SlaterDet), MPI_BYTE, 0, MPI_COMM_WORLD);
    Q->idx = idx;
    Q->ng = ng;
    Q->G = G;
    MPI_Bcast(Q->idx, Q->A, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(Q->ng, Q->A, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(Q->G, Q->ngauss*sizeof(Gaussian),
              MPI_BYTE, 0, MPI_COMM_WORLD);
  }
}
void BroadcastSlaterDetAux (const SlaterDet * Q, SlaterDetAux * X)
Definition at line 72 of file Communication.c.
References SlaterDet::A, SlaterDetAux::Gaux, SlaterDetAux::n, SlaterDet::ngauss, SlaterDetAux::o, SlaterDetAux::ovlap, and SQR.
{
    MPI_Bcast(X->Gaux, SQR(Q->ngauss)*sizeof(GaussianAux),
              MPI_BYTE, 0, MPI_COMM_WORLD);
    MPI_Bcast(X->n, SQR(Q->A)*sizeof(complex double),
              MPI_BYTE, 0, MPI_COMM_WORLD);
    MPI_Bcast(X->o, SQR(Q->A)*sizeof(complex double),
              MPI_BYTE, 0, MPI_COMM_WORLD);
    MPI_Bcast(&X->ovlap, 1,
              MPI_DOUBLE_COMPLEX, 0, MPI_COMM_WORLD);
}
void BroadcastTask (int * task)
Definition at line 38 of file Communication.c.
Referenced by calcgradPotentialmpi(), calcgradPotentialodmpi(), calcPotentialmpi(), calcPotentialodmpi(), calcprojectedMBMEmpi(), calcprojectedMBMEsmpi(), calcprojectedMultiMBMEmpi(), cleanup(), DiagonalDensityHOSlave(), FormfactorSlave(), main(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
{
  MPI_Bcast(task, 1, MPI_INT, 0, MPI_COMM_WORLD);
}
Variable Documentation
int mpirank
Definition at line 28 of file Communication.c.
Referenced by BroadcastInteraction(), BroadcastParameters(), BroadcastSlaterDet(), and main().
int mpisize
Definition at line 29 of file Communication.c.
Referenced by calcgradPotentialmpi(), calcgradPotentialodmpi(), calcPotentialmpi(), calcPotentialodmpi(), calcprojectedMBMEmpi(), calcprojectedMBMEsmpi(), calcprojectedMultiMBMEmpi(), and main().