FMD: fmd/ConstraintNOsci.h File Reference
fmd/ConstraintNOsci.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Constraint.h"
Functions
void calcConstraintNOsci (const SlaterDet *Q, const SlaterDetAux *X, double *nosci)
void calcConstraintPNOsci (const SlaterDet *Q, const SlaterDetAux *X, double *nosci)
void calcConstraintNNOsci (const SlaterDet *Q, const SlaterDetAux *X, double *nosci)
void calcgradConstraintNOsci (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dnosci)
void calcgradConstraintPNOsci (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dnosci)
void calcgradConstraintNNOsci (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dnosci)
double outputConstraintNOsci (double val)
Variables
Constraint ConstraintNOsci
Constraint ConstraintPNOsci
Constraint ConstraintNNOsci
Detailed Description
Constrain number of oscillator quanta for an isotropic oscillator
(c) 2006 Thomas Neff
Definition in file ConstraintNOsci.h.
Function Documentation
void calcConstraintNNOsci (const SlaterDet * Q, const SlaterDetAux * X, double * nosci)
Definition at line 443 of file ConstraintNOsci.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), dim, and par.
Referenced by main().
{
  double Xcm[3], Vcm[3];
  double x2, k2;
  // use neutron cm instead ?
  calcCMPosition(Q, X, Xcm);
  calcCMVelocity(Q, X, Vcm);
  OneBodyOperator op_ob_nx2 = {dim: 1, opt: 1, par: Xcm, me: ob_nx2};
  OneBodyOperator op_ob_nk2 = {dim: 1, opt: 1, par: Vcm, me: ob_nk2};
  calcSlaterDetOBME(Q, X, &op_ob_nx2, &x2);
  calcSlaterDetOBME(Q, X, &op_ob_nk2, &k2);
  *nosci = x2*k2;
}
void calcConstraintNOsci (const SlaterDet * Q, const SlaterDetAux * X, double * nosci)
Definition at line 405 of file ConstraintNOsci.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), dim, and par.
Referenced by main().
{
  double Xcm[3], Vcm[3];
  double x2, k2;
  calcCMPosition(Q, X, Xcm);
  calcCMVelocity(Q, X, Vcm);
  OneBodyOperator op_ob_x2 = {dim: 1, opt: 1, par: Xcm, me: ob_x2};
  OneBodyOperator op_ob_k2 = {dim: 1, opt: 1, par: Vcm, me: ob_k2};
  calcSlaterDetOBME(Q, X, &op_ob_x2, &x2);
  calcSlaterDetOBME(Q, X, &op_ob_k2, &k2);
  *nosci = x2*k2;
}
void calcConstraintPNOsci (const SlaterDet * Q, const SlaterDetAux * X, double * nosci)
Definition at line 423 of file ConstraintNOsci.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), dim, and par.
Referenced by main().
{
  double Xcm[3], Vcm[3];
  double x2, k2;
  // use proton cm instead ?
  calcCMPosition(Q, X, Xcm);
  calcCMVelocity(Q, X, Vcm);
  OneBodyOperator op_ob_px2 = {dim: 1, opt: 1, par: Xcm, me: ob_px2};
  OneBodyOperator op_ob_pk2 = {dim: 1, opt: 1, par: Vcm, me: ob_pk2};
  calcSlaterDetOBME(Q, X, &op_ob_px2, &x2);
  calcSlaterDetOBME(Q, X, &op_ob_pk2, &k2);
  *nosci = x2*k2;
}
void calcgradConstraintNNOsci (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dnosci)
Definition at line 540 of file ConstraintNOsci.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), dim, noscipara::k2, par, noscipara::Vcm, noscipara::x2, and noscipara::Xcm.
{
  double Xcm[3], Vcm[3];
  double x2, k2;
  noscipara opar;
  int i;
  // neutron cm instead ?
  calcCMPosition(Q, X, Xcm);
  calcCMVelocity(Q, X, Vcm);
  OneBodyOperator op_ob_nx2 = {dim: 1, opt: 1, par: Xcm, me: ob_nx2};
  OneBodyOperator op_ob_nk2 = {dim: 1, opt: 1, par: Vcm, me: ob_nk2};
  calcSlaterDetOBME(Q, X, &op_ob_nx2, &x2);
  calcSlaterDetOBME(Q, X, &op_ob_nk2, &k2);
  for (i=0; i<3; i++)
    opar.Xcm[i] = Xcm[i];
  for (i=0; i<3; i++)
    opar.Vcm[i] = Vcm[i];
  opar.x2 = x2;
  opar.k2 = k2;
  gradOneBodyOperator gop_ob_nnosci = { opt: 1, par: &opar, me: gob_nnosci };
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_nnosci, dnosci);
  OneBodyOperator gcmop_ob_nnosci = { dim: 6, opt: 1, par: &opar,
                                      me: gcmob_nnosci };
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_nnosci, dnosci);
  dnosci->val = x2*k2;
}
void calcgradConstraintNOsci (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dnosci)
Definition at line 464 of file ConstraintNOsci.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), dim, noscipara::k2, par, noscipara::Vcm, noscipara::x2, and noscipara::Xcm.
{
  double Xcm[3], Vcm[3];
  double x2, k2;
  noscipara opar;
  int i;
  calcCMPosition(Q, X, Xcm);
  calcCMVelocity(Q, X, Vcm);
  OneBodyOperator op_ob_x2 = {dim: 1, opt: 1, par: Xcm, me: ob_x2};
  OneBodyOperator op_ob_k2 = {dim: 1, opt: 1, par: Vcm, me: ob_k2};
  calcSlaterDetOBME(Q, X, &op_ob_x2, &x2);
  calcSlaterDetOBME(Q, X, &op_ob_k2, &k2);
  for (i=0; i<3; i++)
    opar.Xcm[i] = Xcm[i];
  for (i=0; i<3; i++)
    opar.Vcm[i] = Vcm[i];
  opar.x2 = x2;
  opar.k2 = k2;
  gradOneBodyOperator gop_ob_nosci = { opt: 1, par: &opar, me: gob_nosci };
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_nosci, dnosci);
  OneBodyOperator gcmop_ob_nosci = { dim: 6, opt: 1, par: &opar,
                                     me: gcmob_nosci };
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_nosci, dnosci);
  dnosci->val = x2*k2;
}
void calcgradConstraintPNOsci (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dnosci)
Definition at line 501 of file ConstraintNOsci.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), dim, noscipara::k2, par, noscipara::Vcm, noscipara::x2, and noscipara::Xcm.
{
  double Xcm[3], Vcm[3];
  double x2, k2;
  noscipara opar;
  int i;
  // proton cm instead ?
  calcCMPosition(Q, X, Xcm);
  calcCMVelocity(Q, X, Vcm);
  OneBodyOperator op_ob_px2 = {dim: 1, opt: 1, par: Xcm, me: ob_px2};
  OneBodyOperator op_ob_pk2 = {dim: 1, opt: 1, par: Vcm, me: ob_pk2};
  calcSlaterDetOBME(Q, X, &op_ob_px2, &x2);
  calcSlaterDetOBME(Q, X, &op_ob_pk2, &k2);
  for (i=0; i<3; i++)
    opar.Xcm[i] = Xcm[i];
  for (i=0; i<3; i++)
    opar.Vcm[i] = Vcm[i];
  opar.x2 = x2;
  opar.k2 = k2;
  gradOneBodyOperator gop_ob_pnosci = { opt: 1, par: &opar, me: gob_pnosci };
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_pnosci, dnosci);
  OneBodyOperator gcmop_ob_pnosci = { dim: 6, opt: 1, par: &opar,
                                      me: gcmob_pnosci };
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_pnosci, dnosci);
  dnosci->val = x2*k2;
}
double outputConstraintNOsci (double val)
Definition at line 580 of file ConstraintNOsci.c.
{
  return sqrt(val);
}
Variable Documentation
Constraint ConstraintNNOsci
Definition at line 46 of file ConstraintNOsci.c.
Referenced by main().
Constraint ConstraintNOsci
Definition at line 30 of file ConstraintNOsci.c.
Referenced by main().
Constraint ConstraintPNOsci
Definition at line 38 of file ConstraintNOsci.c.
Referenced by main().