FMD: fmd/ConstraintSymmetries.h File Reference
fmd/ConstraintSymmetries.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Constraint.h"
Functions
void calcConstraintParP (const SlaterDet *Q, const SlaterDetAux *X, double *parpconstraint)
void calcgradConstraintParP (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dparpconstraint)
void calcConstraintParN (const SlaterDet *Q, const SlaterDetAux *X, double *parnconstraint)
void calcgradConstraintParN (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dparnconstraint)
void calcConstraintParCh (const SlaterDet *Q, const SlaterDetAux *X, double *parchconstraint)
void calcgradConstraintParCh (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dparchconstraint)
void calcConstraintD3H (const SlaterDet *Q, const SlaterDetAux *X, double *d3hconstraint)
void calcgradConstraintD3H (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dd3hconstraint)
void calcConstraintSxz (const SlaterDet *Q, const SlaterDetAux *X, double *sxzconstraint)
void calcgradConstraintSxz (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dsxzconstraint)
void calcConstraintSyz (const SlaterDet *Q, const SlaterDetAux *X, double *syzconstraint)
void calcgradConstraintSyz (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dsyzconstraint)
double outputConstraintZero (double val)
Variables
Constraint ConstraintParityP
Constraint ConstraintParityN
Constraint ConstraintParityCharge
Constraint ConstraintD3H
Constraint ConstraintSxz
Constraint ConstraintSyz
Detailed Description
constrain intrinsic state regarding discrete symmetries
(c) 2009 Thomas Neff
Definition in file ConstraintSymmetries.h.
Function Documentation
void calcConstraintD3H (const SlaterDet * Q, const SlaterDetAux * X, double * d3hconstraint)
Definition at line 301 of file ConstraintSymmetries.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), N, SlaterDetAux::ovlap, and rotateSlaterDet().
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // rotation by 120deg
  rotateSlaterDet(&SQ, 0.0, 0.0, 2.0/3.0*M_PI);
  copySlaterDet(Q, &SdagQ);
  // rotation by -120deg
  rotateSlaterDet(&SdagQ, 0.0, 0.0, -2.0/3.0*M_PI);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcSlaterDetAuxod(Q, &SQ, X);
  complex double S = X->ovlap;
  calcSlaterDetAuxod(Q, &SdagQ, X);
  complex double Sdag = X->ovlap;
  // do not ignore phase
  // *pard3hconstraint = (Sdag/N - 1.0)*(S/N - 1.0);
  // ignore phase
  *pard3hconstraint = Sdag*S/(N*N) - 1.0;
}
void calcConstraintParCh (const SlaterDet * Q, const SlaterDetAux * X, double * parchconstraint)
Definition at line 232 of file ConstraintSymmetries.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), invertSlaterDet(), N, and SlaterDetAux::ovlap.
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // parity and charge
  invertSlaterDet(&SQ);
  RisoppiSlaterDet(&SQ);
  copySlaterDet(Q, &SdagQ);
  // parity and charge
  invertSlaterDet(&SdagQ);
  RisompiSlaterDet(&SdagQ);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcSlaterDetAuxod(Q, &SQ, X);
  complex double S = X->ovlap;
  calcSlaterDetAuxod(Q, &SdagQ, X);
  complex double Sdag = X->ovlap;
  *parchconstraint = (Sdag*S)/(N*N) - 1.0;
}
void calcConstraintParN (const SlaterDet * Q, const SlaterDetAux * X, double * parnconstraint)
Definition at line 149 of file ConstraintSymmetries.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), invertSlaterDet(), N, and SlaterDetAux::ovlap.
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // parity operation
  invertSlaterDet(&SQ);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcSlaterDetAuxod(Q, &SQ, X);
  double S = X->ovlap;
  *parnconstraint = S/N + 1.0;
}
void calcConstraintParP (const SlaterDet * Q, const SlaterDetAux * X, double * parpconstraint)
Definition at line 101 of file ConstraintSymmetries.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), invertSlaterDet(), N, and SlaterDetAux::ovlap.
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // parity operation
  invertSlaterDet(&SQ);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcSlaterDetAuxod(Q, &SQ, X);
  double S = X->ovlap;
  *parpconstraint = S/N-1.0;
}
void calcConstraintSxz (const SlaterDet * Q, const SlaterDetAux * X, double * sxzconstraint)
Definition at line 370 of file ConstraintSymmetries.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), invertSlaterDet(), N, SlaterDetAux::ovlap, and rotateSlaterDet().
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // invert and rotate by 180deg around y-axis
  invertSlaterDet(&SQ);
  rotateSlaterDet(&SQ, 0.0, M_PI, 0.0);
  copySlaterDet(Q, &SdagQ);
  // invert and rotate by -180deg around y-axis
  rotateSlaterDet(&SdagQ, 0.0, -M_PI, 0.0);
  invertSlaterDet(&SdagQ);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcSlaterDetAuxod(Q, &SQ, X);
  complex double S = X->ovlap;
  calcSlaterDetAuxod(Q, &SdagQ, X);
  complex double Sdag = X->ovlap;
  *sxzconstraint = (Sdag*S)/(N*N) - 1.0;
}
void calcConstraintSyz (const SlaterDet * Q, const SlaterDetAux * X, double * syzconstraint)
Definition at line 439 of file ConstraintSymmetries.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), invertSlaterDet(), N, SlaterDetAux::ovlap, and rotateSlaterDet().
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // invert and rotate by 180deg around x-axis
  invertSlaterDet(&SQ);
  rotateSlaterDet(&SQ, 0.5*M_PI, M_PI, -0.5*M_PI);
  copySlaterDet(Q, &SdagQ);
  // invert and rotate by -180deg around x-axis
  rotateSlaterDet(&SdagQ, 0.5*M_PI, -M_PI, -0.5*M_PI);
  invertSlaterDet(&SdagQ);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcSlaterDetAuxod(Q, &SQ, X);
  complex double S = X->ovlap;
  calcSlaterDetAuxod(Q, &SdagQ, X);
  complex double Sdag = X->ovlap;
  *syzconstraint = (Sdag*S)/(N*N) - 1.0;
}
void calcgradConstraintD3H (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dd3hconstraint)
Definition at line 331 of file ConstraintSymmetries.c.
References SlaterDet::A, addmulttogradSlaterDet(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcSlaterDetAuxod(), copySlaterDet(), N, SlaterDetAux::ovlap, rotateSlaterDet(), and gradSlaterDet::val.
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // rotation by 120deg
  rotateSlaterDet(&SQ, 0.0, 0.0, 2.0/3.0*M_PI);
  copySlaterDet(Q, &SdagQ);
  // rotation by -120deg
  rotateSlaterDet(&SdagQ, 0.0, 0.0, -2.0/3.0*M_PI);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcgradSlaterDetAuxod(Q, Q, X, dX);
  calcgradOvlapod(Q, Q, X, dX, &dN);
  calcSlaterDetAuxod(Q, &SQ, X);
  double S = X->ovlap;
  calcgradSlaterDetAuxod(Q, &SQ, X, dX);
  calcgradOvlapod(Q, &SQ, X, dX, &dS);
  calcSlaterDetAuxod(Q, &SdagQ, X);
  double Sdag = X->ovlap;
  calcgradSlaterDetAuxod(Q, &SdagQ, X, dX);
  calcgradOvlapod(Q, &SdagQ, X, dX, &dSdag);
  // ignore phase
  addmulttogradSlaterDet(dd3hconstraint, &dSdag, S/(N*N));
  addmulttogradSlaterDet(dd3hconstraint, &dS, Sdag/(N*N));
  addmulttogradSlaterDet(dd3hconstraint, &dN, -2*Sdag*S/(N*N*N));
  dd3hconstraint->val = Sdag*S/(N*N) - 1.0;
}
void calcgradConstraintParCh (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dparchconstraint)
Definition at line 261 of file ConstraintSymmetries.c.
References SlaterDet::A, addmulttogradSlaterDet(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcSlaterDetAuxod(), copySlaterDet(), invertSlaterDet(), N, SlaterDetAux::ovlap, and gradSlaterDet::val.
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // parity and charge
  invertSlaterDet(&SQ);
  RisoppiSlaterDet(&SQ);
  copySlaterDet(Q, &SdagQ);
  // parity and charge
  invertSlaterDet(&SdagQ);
  RisompiSlaterDet(&SdagQ);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcgradSlaterDetAuxod(Q, Q, X, dX);
  calcgradOvlapod(Q, Q, X, dX, &dN);
  calcSlaterDetAuxod(Q, &SQ, X);
  complex double S = X->ovlap;
  calcgradSlaterDetAuxod(Q, &SQ, X, dX);
  calcgradOvlapod(Q, &SQ, X, dX, &dS);
  calcSlaterDetAuxod(Q, &SdagQ, X);
  complex double Sdag = X->ovlap;
  calcgradSlaterDetAuxod(Q, &SdagQ, X, dX);
  calcgradOvlapod(Q, &SdagQ, X, dX, &dSdag);
  addmulttogradSlaterDet(dparchconstraint, &dSdag, S/(N*N));
  addmulttogradSlaterDet(dparchconstraint, &dS, Sdag/(N*N));
  addmulttogradSlaterDet(dparchconstraint, &dN, -2*Sdag*S/(N*N*N));
  dparchconstraint->val = Sdag*S/(N*N) - 1.0;
}
void calcgradConstraintParN (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dparnconstraint)
Definition at line 168 of file ConstraintSymmetries.c.
References SlaterDet::A, addmulttogradSlaterDet(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcSlaterDetAuxod(), copySlaterDet(), invertSlaterDet(), N, SlaterDetAux::ovlap, and gradSlaterDet::val.
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // parity operation
  invertSlaterDet(&SQ);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcgradSlaterDetAuxod(Q, Q, X, dX);
  calcgradOvlapod(Q, Q, X, dX, &dN);
  calcSlaterDetAuxod(Q, &SQ, X);
  double S = X->ovlap;
  calcgradSlaterDetAuxod(Q, &SQ, X, dX);
  calcgradOvlapod(Q, &SQ, X, dX, &dS);
  addmulttogradSlaterDet(dparnconstraint, &dS, 1.0/N);
  addmulttogradSlaterDet(dparnconstraint, &dN, -S/(N*N));
  dparnconstraint->val = S/N + 1.0;
}
void calcgradConstraintParP (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dparpconstraint)
Definition at line 120 of file ConstraintSymmetries.c.
References SlaterDet::A, addmulttogradSlaterDet(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcSlaterDetAuxod(), copySlaterDet(), invertSlaterDet(), N, SlaterDetAux::ovlap, and gradSlaterDet::val.
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // parity operation
  invertSlaterDet(&SQ);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcgradSlaterDetAuxod(Q, Q, X, dX);
  calcgradOvlapod(Q, Q, X, dX, &dN);
  calcSlaterDetAuxod(Q, &SQ, X);
  double S = X->ovlap;
  calcgradSlaterDetAuxod(Q, &SQ, X, dX);
  calcgradOvlapod(Q, &SQ, X, dX, &dS);
  addmulttogradSlaterDet(dparpconstraint, &dS, 1.0/N);
  addmulttogradSlaterDet(dparpconstraint, &dN, -S/(N*N));
  dparpconstraint->val = S/N - 1.0;
}
void calcgradConstraintSxz (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dsxzconstraint)
Definition at line 398 of file ConstraintSymmetries.c.
References SlaterDet::A, addmulttogradSlaterDet(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcSlaterDetAuxod(), copySlaterDet(), invertSlaterDet(), N, SlaterDetAux::ovlap, rotateSlaterDet(), and gradSlaterDet::val.
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // invert and rotate by 180deg around y-axis
  invertSlaterDet(&SQ);
  rotateSlaterDet(&SQ, 0.0, M_PI, 0.0);
  copySlaterDet(Q, &SdagQ);
  // invert and rotate by -180deg around y-axis
  rotateSlaterDet(&SdagQ, 0.0, -M_PI, 0.0);
  invertSlaterDet(&SdagQ);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcgradSlaterDetAuxod(Q, Q, X, dX);
  calcgradOvlapod(Q, Q, X, dX, &dN);
  calcSlaterDetAuxod(Q, &SQ, X);
  complex double S = X->ovlap;
  calcgradSlaterDetAuxod(Q, &SQ, X, dX);
  calcgradOvlapod(Q, &SQ, X, dX, &dS);
  calcSlaterDetAuxod(Q, &SdagQ, X);
  complex double Sdag = X->ovlap;
  calcgradSlaterDetAuxod(Q, &SdagQ, X, dX);
  calcgradOvlapod(Q, &SdagQ, X, dX, &dSdag);
  addmulttogradSlaterDet(dsxzconstraint, &dSdag, S/(N*N));
  addmulttogradSlaterDet(dsxzconstraint, &dS, Sdag/(N*N));
  addmulttogradSlaterDet(dsxzconstraint, &dN, -(2*Sdag*S)/(N*N*N));
  dsxzconstraint->val = (Sdag*S)/(N*N) - 1.0;
}
void calcgradConstraintSyz (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dsyzconstraint)
Definition at line 467 of file ConstraintSymmetries.c.
References SlaterDet::A, addmulttogradSlaterDet(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcSlaterDetAuxod(), copySlaterDet(), invertSlaterDet(), N, SlaterDetAux::ovlap, rotateSlaterDet(), and gradSlaterDet::val.
{
  if (SQ.A == 0)
    initworkspace(Q);
  copySlaterDet(Q, &SQ);
  // invert and rotate by 180deg around x-axis
  invertSlaterDet(&SQ);
  rotateSlaterDet(&SQ, 0.5*M_PI, M_PI, -0.5*M_PI);
  copySlaterDet(Q, &SdagQ);
  // invert and rotate by -180deg around x-axis
  rotateSlaterDet(&SdagQ, 0.5*M_PI, -M_PI, -0.5*M_PI);
  invertSlaterDet(&SdagQ);
  calcSlaterDetAuxod(Q, Q, X);
  double N = X->ovlap;
  calcgradSlaterDetAuxod(Q, Q, X, dX);
  calcgradOvlapod(Q, Q, X, dX, &dN);
  calcSlaterDetAuxod(Q, &SQ, X);
  complex double S = X->ovlap;
  calcgradSlaterDetAuxod(Q, &SQ, X, dX);
  calcgradOvlapod(Q, &SQ, X, dX, &dS);
  calcSlaterDetAuxod(Q, &SdagQ, X);
  complex double Sdag = X->ovlap;
  calcgradSlaterDetAuxod(Q, &SdagQ, X, dX);
  calcgradOvlapod(Q, &SdagQ, X, dX, &dSdag);
  addmulttogradSlaterDet(dsyzconstraint, &dSdag, S/(N*N));
  addmulttogradSlaterDet(dsyzconstraint, &dS, Sdag/(N*N));
  addmulttogradSlaterDet(dsyzconstraint, &dN, -(2*Sdag*S)/(N*N*N));
  dsyzconstraint->val = (Sdag*S)/(N*N) - 1.0;
}
double outputConstraintZero (double val)
Definition at line 508 of file ConstraintSymmetries.c.
{
  return (val);
}
Variable Documentation
Constraint ConstraintD3H
Definition at line 53 of file ConstraintSymmetries.c.
Referenced by main().
Constraint ConstraintParityCharge
Definition at line 43 of file ConstraintSymmetries.c.
Referenced by main().
Constraint ConstraintParityN
Definition at line 35 of file ConstraintSymmetries.c.
Referenced by main().
Constraint ConstraintParityP
Definition at line 26 of file ConstraintSymmetries.c.
Referenced by main().
Constraint ConstraintSxz
Definition at line 62 of file ConstraintSymmetries.c.
Referenced by main().
Constraint ConstraintSyz
Definition at line 71 of file ConstraintSymmetries.c.
Referenced by main().