FMD: fmd/ConstraintCM.c File Reference
fmd/ConstraintCM.c File Reference
#include <complex.h>
#include <math.h>
#include "Gaussian.h"
#include "gradGaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "ConstraintCM.h"
#include "numerics/cmath.h"
#include "misc/physics.h"
Data Structures
struct cmconpara
Defines
#define SQR(x) (x)*(x)
Functions
void calcConstraintCM (const SlaterDet *Q, const SlaterDetAux *X, double *cmconstraint)
void calcgradConstraintCM (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dcmconstraint)
double outputConstraintCM (double val)
Variables
Constraint ConstraintCM
Detailed Description
constrain CM position in coordinate and momentum space
(c) 2003 Thomas Neff
Definition in file ConstraintCM.c.
Define Documentation
#define SQR (x) (x)*(x)
Definition at line 95 of file ConstraintCM.c.
Function Documentation
void calcConstraintCM (const SlaterDet * Q, const SlaterDetAux * X, double * cmconstraint)
Definition at line 97 of file ConstraintCM.c.
References calcSlaterDetOBME(), dim, and SQR.
{
  double xcm[3], pcm[3];
  OneBodyOperator op_ob_mx = {dim: 3, opt: 1, par: NULL, me: ob_mx};
  OneBodyOperator op_ob_p = {dim: 3, opt: 1, par: NULL, me: ob_p};
  calcSlaterDetOBME(Q, X, &op_ob_mx, xcm);
  calcSlaterDetOBME(Q, X, &op_ob_p, pcm);
  *cmconstraint = SQR(xcm[0])+SQR(xcm[1])+SQR(xcm[2])+
                  SQR(pcm[0])+SQR(pcm[1])+SQR(pcm[2]);
  // the donlp2 routine tries to sample unphysical states
  // from time to time, punish that try
  if (isnan(*cmconstraint))
    *cmconstraint = 100000;
}
void calcgradConstraintCM (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dcmconstraint)
Definition at line 120 of file ConstraintCM.c.
References calcgradSlaterDetOBME(), calcSlaterDetOBME(), dim, cmconpara::pcm, and cmconpara::xcm.
{
  cmconpara p;
  OneBodyOperator op_ob_mx = {dim: 3, opt: 1, par: NULL, me: ob_mx};
  OneBodyOperator op_ob_p = {dim: 3, opt: 1, par: NULL, me: ob_p};
  gradOneBodyOperator gop_ob_cmcon = {opt: 1, par: &p, me: gob_cmcon};
  calcSlaterDetOBME(Q, X, &op_ob_mx, p.xcm);
  calcSlaterDetOBME(Q, X, &op_ob_p, p.pcm);
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_cmcon, dcmconstraint);
}
double outputConstraintCM (double val)
Definition at line 135 of file ConstraintCM.c.
{
  return (val);
}
Variable Documentation
Constraint ConstraintCM
Initial value:
 {
  val : 0.0,
  label : "CM",
  me : calcConstraintCM,
  gradme : calcgradConstraintCM,
  output : outputConstraintCM
}
Definition at line 26 of file ConstraintCM.c.
Referenced by egradh(), eh(), and main().