FMD: fmd/ConstraintJ2.h File Reference
fmd/ConstraintJ2.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Constraint.h"
Functions
void calcConstraintJ2 (const SlaterDet *Q, const SlaterDetAux *X, double *j2)
void calcgradConstraintJ2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dj2)
void calcConstraintJ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *j2)
void calcgradConstraintJ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *dummy, gradSlaterDet *dj2)
double outputConstraintJ2 (double val)
Variables
Constraint ConstraintJ2
Constraintod ConstraintJ2od
Function Documentation
void calcConstraintJ2 (const SlaterDet * Q, const SlaterDetAux * X, double * j2)
Definition at line 396 of file ConstraintJ2.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), calcSlaterDetTBME(), dim, CMpara::Vcm, and CMpara::Xcm.
{
  CMpara para;
  double j2one, j2two;
  calcCMPosition(Q, X, para.Xcm);
  calcCMVelocity(Q, X, para.Vcm);
  OneBodyOperator op_ob_j2 = {dim: 1, opt: 1, par: &para, me: ob_j2};
  TwoBodyOperator op_tb_j2 = {dim: 1, opt: 1, par: &para, me: tb_j2};
  calcSlaterDetOBME(Q, X, &op_ob_j2, &j2one);
  calcSlaterDetTBME(Q, X, &op_tb_j2, &j2two);
  *j2 = j2one + j2two;
}
void calcConstraintJ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * j2)
Definition at line 446 of file ConstraintJ2.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), and dim.
Referenced by calcorthprojectedHamiltonian(), calcprojectedHamiltonian(), calcprojectedHamiltonianmatrix(), and MinimizerprojSlave().
{
  CMpara para = { { 0.0, 0.0, 0.0}, {0.0, 0.0, 0.0} };
  complex double j2one, j2two;
  OneBodyOperator op_ob_j2 = {dim: 1, opt: 1, par: &para, me: ob_j2};
  TwoBodyOperator op_tb_j2 = {dim: 1, opt: 1, par: &para, me: tb_j2};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_j2, &j2one);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_j2, &j2two);
  *j2 = j2one + j2two;
}
void calcgradConstraintJ2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dj2)
Definition at line 416 of file ConstraintJ2.c.
References calcCMPosition(), calcCMVelocity(), calcgradCMSlaterDetOBME(), calcgradCMSlaterDetTBME(), calcgradSlaterDetOBME(), calcgradSlaterDetTBME(), dim, gcmob_j2(), gcmtb_j2(), gradSlaterDet::val, CMpara::Vcm, and CMpara::Xcm.
{
  CMpara para;
  double j2;
  calcCMPosition(Q, X, para.Xcm);
  calcCMVelocity(Q, X, para.Vcm);
  gradOneBodyOperator gop_ob_j2 = {opt: 1, par: &para, me: gob_j2};
  gradTwoBodyOperator gop_tb_j2 = {opt: 1, par: &para, me: gtb_j2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_j2, dj2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_j2, dj2);
  j2 = dj2->val;
  OneBodyOperator gcmop_ob_j2 = {dim: 6, opt: 1, par: &para, me: gcmob_j2};
  TwoBodyOperator gcmop_tb_j2 = {dim: 6, opt: 1, par: &para, me: gcmtb_j2};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_j2, dj2);
  calcgradCMSlaterDetTBME(Q, X, dX, &gcmop_tb_j2, dj2);
  dj2->val = j2;
}
void calcgradConstraintJ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * dummy, gradSlaterDet * dj2)
Definition at line 463 of file ConstraintJ2.c.
References calcgradSlaterDetOBMEod(), and calcgradSlaterDetTBMEod().
{
  CMpara para = { {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0} };
  gradOneBodyOperator gop_ob_j2 = {opt: 1, par: &para, me: gob_j2};
  gradTwoBodyOperator gop_tb_j2 = {opt: 1, par: &para, me: gtb_j2};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_j2, dj2);
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_j2, dj2);
}
double outputConstraintJ2 (double val)
Definition at line 479 of file ConstraintJ2.c.
{
  return (val);
}
Variable Documentation
Constraint ConstraintJ2
Definition at line 29 of file ConstraintJ2.c.
Referenced by main().
Constraintod ConstraintJ2od
Definition at line 38 of file ConstraintJ2.c.
Referenced by main().