FMD: fmd/ConstraintMainAxes.c File Reference
fmd/ConstraintMainAxes.c File Reference
#include <complex.h>
#include "Gaussian.h"
#include "gradGaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "ConstraintMainAxes.h"
#include "numerics/cmath.h"
Data Structures
struct quadrupolepara
Defines
#define SQR(x) (x)*(x)
Functions
void calcConstraintMainAxes (const SlaterDet *Q, const SlaterDetAux *X, double *q2)
void calcgradConstraintMainAxes (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dq2)
void calcConstraintQbeta2 (const SlaterDet *Q, const SlaterDetAux *X, double *beta2)
void calcgradConstraintQbeta2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dbeta2)
Detailed Description
Constrain Main Axes of Quadrupole tensor
(c) 2003 Thomas Neff
Definition in file ConstraintMainAxes.c.
Define Documentation
#define SQR (x) (x)*(x)
Definition at line 216 of file ConstraintMainAxes.c.
Function Documentation
void calcConstraintMainAxes (const SlaterDet * Q, const SlaterDetAux * X, double * q2)
Definition at line 218 of file ConstraintMainAxes.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), dim, par, and SQR.
{
  double qijone[3], qijtwo[3], qsq = 0.0;
  int i;
  OneBodyOperator op_ob_qij = {dim: 3, opt: 1, par: Q, me: ob_qoffdiag};
  TwoBodyOperator op_tb_qij = {dim: 3, opt: 1, par: Q, me: tb_qoffdiag};
  calcSlaterDetOBME(Q, X, &op_ob_qij, qijone);
  calcSlaterDetTBME(Q, X, &op_tb_qij, qijtwo);
  for (i=0; i<3; i++)
    qsq += SQR(qijone[i]+qijtwo[i]);
  *q2 = qsq;
}
void calcConstraintQbeta2 (const SlaterDet * Q, const SlaterDetAux * X, double * beta2)
Definition at line 265 of file ConstraintMainAxes.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), dim, par, and SQR.
{
  double qone[3], qtwo[3], qsq = 0.0;
  int i;
  OneBodyOperator op_ob_q = {dim: 3, opt: 1, par: Q, me: ob_qdiag};
  TwoBodyOperator op_tb_q = {dim: 3, opt: 1, par: Q, me: tb_qdiag};
  calcSlaterDetOBME(Q, X, &op_ob_q, qone);
  calcSlaterDetTBME(Q, X, &op_tb_q, qtwo);
  for (i=0; i<3; i++)
    qsq += SQR(qone[i]+qtwo[i]);
  *beta = qsq;
}
void calcgradConstraintMainAxes (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dq2)
Definition at line 237 of file ConstraintMainAxes.c.
References SlaterDet::A, calcSlaterDetOBME(), calcSlaterDetTBME(), dim, and par.
{
  double qijone[3], qijtwo[3];
  int i;
  quadrupolepara qpar;
  OneBodyOperator op_ob_qij = {dim: 3, opt: 1, par: Q, me: ob_offdiag};
  TwoBodyOperator op_tb_qij = {dim: 3, opt: 1, par: Q, me: tb_offdiag};
  calcSlaterDetOBME(Q, X, &op_ob_qij, qijone);
  calcSlaterDetTBME(Q, X, &op_tb_qij, qijtwo);
  q2par.A = Q->A;
  for (i=0; i<3; i++)
    q2par.q[i] = qijone[i]+qijtwo[i];
  gradOneBodyOperator gop_ob_q2 = {opt: 1, par: &q2par, me: gob_mainaxes};
  gradTwoBodyOperator gop_tb_q2 = {opt: 1, par: &q2par, me: gtb_mainaxes};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_q2, dq2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_q2, dq2);
}
void calcgradConstraintQbeta2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dbeta2)
Definition at line 284 of file ConstraintMainAxes.c.
References SlaterDet::A, quadrupolepara::A, calcSlaterDetOBME(), calcSlaterDetTBME(), dim, par, and quadrupolepara::q.
{
  double qone[3], qtwo[3];
  int i;
  quadrupolepara qpara;
  OneBodyOperator op_ob_q = {dim: 3, opt: 1, par: Q, me: ob_offdiag};
  TwoBodyOperator op_tb_q = {dim: 3, opt: 1, par: Q, me: tb_offdiag};
  calcSlaterDetOBME(Q, X, &op_ob_q, qone);
  calcSlaterDetTBME(Q, X, &op_tb_q, qtwo);
  qpara.A = Q->A;
  for (i=0; i<3; i++)
    qpara.q[i] = qone[i]+qtwo[i];
  gradOneBodyOperator gop_ob_qbeta2 = {opt: 1, par: &qpara, me: gob_qbeta2};
  gradTwoBodyOperator gop_tb_qbeta2 = {opt: 1, par: &qpara, me: gtb_qbeta2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_qbeta2, dbeta2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_qbeta2, dbeta2);
}