FMD: fmd/ConstraintLS.c File Reference
fmd/ConstraintLS.c File Reference
#include <math.h>
#include <complex.h>
#include "Gaussian.h"
#include "gradGaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "CenterofMass.h"
#include "gradCMSlaterDet.h"
#include "Constraint.h"
#include "ConstraintLS.h"
#include "numerics/cmath.h"
#include "misc/physics.h"
Data Structures
struct CMpara
Functions
void gcmob_ls (const CMpara *par, const Gaussian *G1, const Gaussian *G2, const GaussianAux *X, gradCM *dCMls)
void gcmtb_ls (const CMpara *par, const Gaussian *G1, const Gaussian *G2, const Gaussian *G3, const Gaussian *G4, const GaussianAux *X13, const GaussianAux *X24, gradCM *dCMls)
void calcConstraintLS (const SlaterDet *Q, const SlaterDetAux *X, double *ls)
void calcgradConstraintLS (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dls)
void calcConstraintLSod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *ls)
void calcgradConstraintLSod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *dummy, gradSlaterDet *dls)
double outputConstraintLS (double val)
Variables
Constraint ConstraintLS
Constraintod ConstraintLSod
Detailed Description
Constrain expectation value of LS
(c) 2005 Thomas Neff
Definition in file ConstraintLS.c.
Function Documentation
void calcConstraintLS (const SlaterDet * Q, const SlaterDetAux * X, double * ls)
Definition at line 279 of file ConstraintLS.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), calcSlaterDetTBME(), dim, CMpara::Vcm, and CMpara::Xcm.
{
  CMpara para;
  double lsone, lstwo;
  calcCMPosition(Q, X, para.Xcm);
  calcCMVelocity(Q, X, para.Vcm);
  OneBodyOperator op_ob_ls = {dim: 1, opt: 1, par: &para, me: ob_ls};
  TwoBodyOperator op_tb_ls = {dim: 1, opt: 1, par: &para, me: tb_ls};
  calcSlaterDetOBME(Q, X, &op_ob_ls, &lsone);
  calcSlaterDetTBME(Q, X, &op_tb_ls, &lstwo);
  *ls = lsone + lstwo;
}
void calcConstraintLSod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * ls)
Definition at line 327 of file ConstraintLS.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), and dim.
{
  CMpara para = { { 0.0, 0.0, 0.0}, {0.0, 0.0, 0.0} };
  complex double lsone, lstwo;
  OneBodyOperator op_ob_ls = {dim: 1, opt: 1, par: &para, me: ob_ls};
  TwoBodyOperator op_tb_ls = {dim: 1, opt: 1, par: &para, me: tb_ls};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_ls, &lsone);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_ls, &lstwo);
  *ls = lsone + lstwo;
}
void calcgradConstraintLS (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dls)
Definition at line 299 of file ConstraintLS.c.
References calcCMPosition(), calcCMVelocity(), calcgradCMSlaterDetOBME(), calcgradCMSlaterDetTBME(), calcgradSlaterDetOBME(), calcgradSlaterDetTBME(), dim, gcmob_ls(), gcmtb_ls(), gradSlaterDet::val, CMpara::Vcm, and CMpara::Xcm.
{
  CMpara para;
  double ls;
  calcCMPosition(Q, X, para.Xcm);
  calcCMVelocity(Q, X, para.Vcm);
  gradOneBodyOperator gop_ob_ls = {opt: 1, par: &para, me: gob_ls};
  gradTwoBodyOperator gop_tb_ls = {opt: 1, par: &para, me: gtb_ls};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_ls, dls);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_ls, dls);
  ls = dls->val;
  OneBodyOperator gcmop_ob_ls = {dim: 6, opt: 1, par: &para, me: gcmob_ls};
  TwoBodyOperator gcmop_tb_ls = {dim: 6, opt: 1, par: &para, me: gcmtb_ls};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_ls, dls);
  calcgradCMSlaterDetTBME(Q, X, dX, &gcmop_tb_ls, dls);
  dls->val = ls;
}
void calcgradConstraintLSod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * dummy, gradSlaterDet * dls)
Definition at line 344 of file ConstraintLS.c.
References calcgradSlaterDetOBMEod(), and calcgradSlaterDetTBMEod().
{
  CMpara para = { {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0} };
  gradOneBodyOperator gop_ob_ls = {opt: 1, par: &para, me: gob_ls};
  gradTwoBodyOperator gop_tb_ls = {opt: 1, par: &para, me: gtb_ls};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_ls, dls);
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_ls, dls);
}
void gcmob_ls (const CMpara * par, const Gaussian * G1, const Gaussian * G2, const GaussianAux * X, gradCM * dCMls)
Definition at line 201 of file ConstraintLS.c.
References GaussianAux::pi, GaussianAux::R, GaussianAux::rho, GaussianAux::sig, GaussianAux::T, gradCM::V, CMpara::Vcm, gradCM::X, CMpara::Xcm, and Gaussian::xi.
Referenced by calcgradConstraintls(), and calcgradConstraintLS().
{
  double* Xcm = par->Xcm;
  double* Vcm = par->Vcm;
  complex double rhocm[3], picm[3];
  complex double rhoxpicm[3];
  gradCM dlsm;
  int i;
  for (i=0; i<3; i++)
    rhocm[i] = X->rho[i]-Xcm[i];
  for (i=0; i<3; i++)
    picm[i] = X->pi[i]-mass(G1->xi)*Vcm[i];
  cvec3cross(rhocm, picm, rhoxpicm);
  for (i=0; i<3; i++)
    dlsm.X[i] = -0.5*(picm[(i+1)%3]*X->sig[(i+2)%3] -
                      picm[(i+2)%3]*X->sig[(i+1)%3]);
  for (i=0; i<3; i++)
    dlsm.V[i] = 0.5*mass(G1->xi)*(rhocm[(i+1)%3]*X->sig[(i+2)%3] -
                                  rhocm[(i+2)%3]*X->sig[(i+1)%3]);
  for (i=0; i<3; i++)
    dCMls->X[i] += X->T* 2*dlsm.X[i]* X->R;
  for (i=0; i<3; i++)
    dCMls->V[i] += X->T* 2*dlsm.V[i]* X->R;
}
void gcmtb_ls (const CMpara * par, const Gaussian * G1, const Gaussian * G2, const Gaussian * G3, const Gaussian * G4, const GaussianAux * X13, const GaussianAux * X24, gradCM * dCMls)
Definition at line 235 of file ConstraintLS.c.
References GaussianAux::pi, GaussianAux::R, GaussianAux::rho, GaussianAux::S, GaussianAux::sig, GaussianAux::T, gradCM::V, CMpara::Vcm, gradCM::X, CMpara::Xcm, and Gaussian::xi.
Referenced by calcgradConstraintLS().
{
  double* Xcm = par->Xcm;
  double* Vcm = par->Vcm;
  complex double rho13cm[3], rho24cm[3], pi13cm[3], pi24cm[3];
  gradCM dlsm;
  int i;
  for (i=0; i<3; i++)
    rho13cm[i] = X13->rho[i]-Xcm[i];
  for (i=0; i<3; i++)
    pi13cm[i] = X13->pi[i]-mass(G1->xi)*Vcm[i];
  for (i=0; i<3; i++)
    rho24cm[i] = X24->rho[i]-Xcm[i];
  for (i=0; i<3; i++)
    pi24cm[i] = X24->pi[i]-mass(G2->xi)*Vcm[i];
  for (i=0; i<3; i++)
    dlsm.X[i] =
      -0.25*(pi13cm[(i+1)%3]*X13->S*X24->sig[(i+2)%3] -
             pi13cm[(i+2)%3]*X13->S*X24->sig[(i+1)%3])
      -0.25*(X13->sig[(i+2)%3]*pi24cm[(i+1)%3]*X24->S -
             X13->sig[(i+1)%3]*pi24cm[(i+2)%3]*X24->S);
  for (i=0; i<3; i++)
    dlsm.V[i] =
      0.25*mass(G1->xi)*(rho13cm[(i+1)%3]*X13->S*X24->sig[(i+2)%3] -
                         rho13cm[(i+2)%3]*X13->S*X24->sig[(i+1)%3]) +
      0.25*mass(G2->xi)*(X13->sig[(i+2)%3]*rho24cm[(i+1)%3]*X24->S -
                         X13->sig[(i+1)%3]*rho24cm[(i+2)%3]*X24->S);
  for (i=0; i<3; i++)
    dCMls->X[i] += 2*X13->T*X24->T*
      2*dlsm.X[i]* X13->R* X24->R;
  for (i=0; i<3; i++)
    dCMls->V[i] += 2*X13->T*X24->T*
      2*dlsm.V[i]* X13->R* X24->R;
}
double outputConstraintLS (double val)
Definition at line 360 of file ConstraintLS.c.
{
  return (val);
}
Variable Documentation
Constraint ConstraintLS
Initial value:
 {
  val : 0.0,
  label : "LS",
  me : calcConstraintLS,
  gradme : calcgradConstraintLS,
  output : outputConstraintLS
}
Definition at line 29 of file ConstraintLS.c.
Referenced by main().
Constraintod ConstraintLSod
Initial value:
 {
  val : 0.0,
  label : "LS",
  dim : 1,
  gradneedsme : 0,
  me : calcConstraintLSod,
  gradme : calcgradConstraintLSod,
  output : outputConstraintLS
}
Definition at line 38 of file ConstraintLS.c.
Referenced by main().