FMD: fmd/ConstraintR2.c File Reference
fmd/ConstraintR2.c File Reference
#include <complex.h>
#include <math.h>
#include "Gaussian.h"
#include "gradGaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Constraint.h"
#include "ConstraintR2.h"
#include "numerics/cmath.h"
Functions
void calcConstraintR2 (const SlaterDet *Q, const SlaterDetAux *X, double *r2)
void calcgradConstraintR2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dr2)
void calcConstraintR2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *r2)
void calcgradConstraintR2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *dummy, gradSlaterDet *dr2)
double outputConstraintR2 (double val)
void calcConstraintER2 (const SlaterDet *Q, const SlaterDetAux *X, double *r2)
void calcgradConstraintER2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dr2)
void calcConstraintER2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *r2)
void calcgradConstraintER2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *dummy, gradSlaterDet *dr2)
double outputConstraintER2 (double val)
void calcConstraintNR2 (const SlaterDet *Q, const SlaterDetAux *X, double *r2)
void calcgradConstraintNR2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dr2)
void calcConstraintNR2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *r2)
void calcgradConstraintNR2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *dummy, gradSlaterDet *dr2)
double outputConstraintNR2 (double val)
Variables
Constraint ConstraintR2
Constraintod ConstraintR2od
Constraint ConstraintER2
Constraintod ConstraintER2od
Constraint ConstraintNR2
Constraintod ConstraintNR2od
Detailed Description
Constrain Mass/Charge Radius
(c) 2003 Thomas Neff
Definition in file ConstraintR2.c.
Function Documentation
void calcConstraintER2 (const SlaterDet * Q, const SlaterDetAux * X, double * r2)
Definition at line 404 of file ConstraintR2.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), dim, and par.
Referenced by main().
{
  double r2one, r2two;
  OneBodyOperator op_ob_r2 = {dim: 1, opt: 1, par: Q, me: ob_er2};
  TwoBodyOperator op_tb_r2 = {dim: 1, opt: 1, par: Q, me: tb_er2};
  calcSlaterDetOBME(Q, X, &op_ob_r2, &r2one);
  calcSlaterDetTBME(Q, X, &op_tb_r2, &r2two);
  *r2 = r2one + r2two;
}
void calcConstraintER2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * r2)
Definition at line 432 of file ConstraintR2.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), dim, and par.
{
  complex double r2one, r2two;
  OneBodyOperator op_ob_r2 = {dim: 1, opt: 1, par: Q, me: ob_er2};
  TwoBodyOperator op_tb_r2 = {dim: 1, opt: 1, par: Q, me: tb_er2};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_r2, &r2one);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_r2, &r2two);
  *r2 = r2one + r2two;
}
void calcConstraintNR2 (const SlaterDet * Q, const SlaterDetAux * X, double * r2)
Definition at line 472 of file ConstraintR2.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), dim, and par.
Referenced by main().
{
  double r2one, r2two;
  OneBodyOperator op_ob_r2 = {dim: 1, opt: 1, par: Q, me: ob_nr2};
  TwoBodyOperator op_tb_r2 = {dim: 1, opt: 1, par: Q, me: tb_nr2};
  calcSlaterDetOBME(Q, X, &op_ob_r2, &r2one);
  calcSlaterDetTBME(Q, X, &op_tb_r2, &r2two);
  *r2 = r2one + r2two;
}
void calcConstraintNR2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * r2)
Definition at line 500 of file ConstraintR2.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), dim, and par.
{
  complex double r2one, r2two;
  OneBodyOperator op_ob_r2 = {dim: 1, opt: 1, par: Q, me: ob_nr2};
  TwoBodyOperator op_tb_r2 = {dim: 1, opt: 1, par: Q, me: tb_nr2};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_r2, &r2one);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_r2, &r2two);
  *r2 = r2one + r2two;
}
void calcConstraintR2 (const SlaterDet * Q, const SlaterDetAux * X, double * r2)
Definition at line 339 of file ConstraintR2.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), dim, and par.
Referenced by main().
{
  double r2one, r2two;
  OneBodyOperator op_ob_r2 = {dim: 1, opt: 1, par: Q, me: ob_r2};
  TwoBodyOperator op_tb_r2 = {dim: 1, opt: 1, par: Q, me: tb_r2};
  calcSlaterDetOBME(Q, X, &op_ob_r2, &r2one);
  calcSlaterDetTBME(Q, X, &op_tb_r2, &r2two);
  *r2 = r2one + r2two;
}
void calcConstraintR2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * r2)
Definition at line 367 of file ConstraintR2.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), dim, and par.
{
  complex double r2one, r2two;
  OneBodyOperator op_ob_r2 = {dim: 1, opt: 1, par: Q, me: ob_r2};
  TwoBodyOperator op_tb_r2 = {dim: 1, opt: 1, par: Q, me: tb_r2};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_r2, &r2one);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_r2, &r2two);
  *r2 = r2one + r2two;
}
void calcgradConstraintER2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dr2)
Definition at line 419 of file ConstraintR2.c.
References calcgradSlaterDetOBME(), calcgradSlaterDetTBME(), and par.
{
  gradOneBodyOperator gop_ob_r2 = {opt: 1, par: Q, me: gob_er2};
  gradTwoBodyOperator gop_tb_r2 = {opt: 1, par: Q, me: gtb_er2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_r2, dr2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_r2, dr2);
}
void calcgradConstraintER2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * dummy, gradSlaterDet * dr2)
Definition at line 448 of file ConstraintR2.c.
References calcgradSlaterDetOBMEod(), calcgradSlaterDetTBMEod(), and par.
{
  gradOneBodyOperator gop_ob_r2 = {opt: 1, par: Q, me: gob_er2};
  gradTwoBodyOperator gop_tb_r2 = {opt: 1, par: Q, me: gtb_er2};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_r2, dr2);
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_r2, dr2);
}
void calcgradConstraintNR2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dr2)
Definition at line 487 of file ConstraintR2.c.
References calcgradSlaterDetOBME(), calcgradSlaterDetTBME(), and par.
{
  gradOneBodyOperator gop_ob_r2 = {opt: 1, par: Q, me: gob_nr2};
  gradTwoBodyOperator gop_tb_r2 = {opt: 1, par: Q, me: gtb_nr2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_r2, dr2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_r2, dr2);
}
void calcgradConstraintNR2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * dummy, gradSlaterDet * dr2)
Definition at line 516 of file ConstraintR2.c.
References calcgradSlaterDetOBMEod(), calcgradSlaterDetTBMEod(), and par.
{
  gradOneBodyOperator gop_ob_r2 = {opt: 1, par: Q, me: gob_nr2};
  gradTwoBodyOperator gop_tb_r2 = {opt: 1, par: Q, me: gtb_nr2};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_r2, dr2);
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_r2, dr2);
}
void calcgradConstraintR2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dr2)
Definition at line 354 of file ConstraintR2.c.
References calcgradSlaterDetOBME(), calcgradSlaterDetTBME(), and par.
{
  gradOneBodyOperator gop_ob_r2 = {opt: 1, par: Q, me: gob_r2};
  gradTwoBodyOperator gop_tb_r2 = {opt: 1, par: Q, me: gtb_r2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_r2, dr2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_r2, dr2);
}
void calcgradConstraintR2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * dummy, gradSlaterDet * dr2)
Definition at line 383 of file ConstraintR2.c.
References calcgradSlaterDetOBMEod(), calcgradSlaterDetTBMEod(), and par.
{
  gradOneBodyOperator gop_ob_r2 = {opt: 1, par: Q, me: gob_r2};
  gradTwoBodyOperator gop_tb_r2 = {opt: 1, par: Q, me: gtb_r2};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_r2, dr2);
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_r2, dr2);
}
double outputConstraintER2 (double val)
Definition at line 463 of file ConstraintR2.c.
{
  if (val > 0.0)
    return(sqrt(val));
  else
    return(-sqrt(-val));
}
double outputConstraintNR2 (double val)
Definition at line 531 of file ConstraintR2.c.
{
  if (val > 0.0)
    return(sqrt(val));
  else
    return(-sqrt(-val));
}
double outputConstraintR2 (double val)
Definition at line 398 of file ConstraintR2.c.
{
  return(sqrt(val));
}
Variable Documentation
Constraint ConstraintER2
Initial value:
 {
  val : 0.0,
  label : "ER",
  me : calcConstraintER2,
  gradme : calcgradConstraintER2,
  output : outputConstraintER2
}
Definition at line 44 of file ConstraintR2.c.
Referenced by main().
Constraintod ConstraintER2od
Initial value:
 {
  val : 0.0,
  label : "ER",
  dim : 1,
  gradneedsme : 0,
  me : calcConstraintER2od,
  gradme : calcgradConstraintER2od,
  output : outputConstraintR2
}
Definition at line 52 of file ConstraintR2.c.
Referenced by main().
Constraint ConstraintNR2
Initial value:
 {
  val : 0.0,
  label : "NR",
  me : calcConstraintNR2,
  gradme : calcgradConstraintNR2,
  output : outputConstraintNR2
}
Definition at line 62 of file ConstraintR2.c.
Referenced by main().
Constraintod ConstraintNR2od
Initial value:
 {
  val : 0.0,
  label : "NR",
  dim : 1,
  gradneedsme : 0,
  me : calcConstraintNR2od,
  gradme : calcgradConstraintNR2od,
  output : outputConstraintR2
}
Definition at line 70 of file ConstraintR2.c.
Constraint ConstraintR2
Initial value:
 {
  val : 0.0,
  label : "R",
  me : calcConstraintR2,
  gradme : calcgradConstraintR2,
  output : outputConstraintR2
}
Definition at line 26 of file ConstraintR2.c.
Referenced by main().
Constraintod ConstraintR2od
Initial value:
 {
  val : 0.0,
  label : "R",
  dim : 1,
  gradneedsme : 0,
  me : calcConstraintR2od,
  gradme : calcgradConstraintR2od,
  output : outputConstraintR2
}
Definition at line 34 of file ConstraintR2.c.
Referenced by main().