FMD: fmd/ConstraintT2.c File Reference
fmd/ConstraintT2.c File Reference
#include <math.h>
#include <complex.h>
#include "Gaussian.h"
#include "gradGaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Constraint.h"
#include "ConstraintT2.h"
#include "numerics/cmath.h"
Functions
void calcConstraintT2 (const SlaterDet *Q, const SlaterDetAux *X, double *t2)
void calcConstraintPT2 (const SlaterDet *Q, const SlaterDetAux *X, double *t2)
void calcConstraintNT2 (const SlaterDet *Q, const SlaterDetAux *X, double *t2)
void calcgradConstraintT2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dt2)
void calcgradConstraintPT2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dt2)
void calcgradConstraintNT2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dt2)
void calcConstraintT2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *t2)
void calcgradConstraintT2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *dummy, gradSlaterDet *dt2)
double outputConstraintT2 (double val)
Variables
Constraint ConstraintT2
Constraint ConstraintPT2
Constraint ConstraintNT2
Constraintod ConstraintT2od
Detailed Description
Constrain expectation value of T2
(c) 2004 Thomas Neff
Definition in file ConstraintT2.c.
Function Documentation
void calcConstraintNT2 (const SlaterDet * Q, const SlaterDetAux * X, double * t2)
Definition at line 295 of file ConstraintT2.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), and dim.
Referenced by main().
{
  double t2one, t2two;
  OneBodyOperator op_ob_t2 = {dim: 1, opt: 1, par: NULL, me: ob_nt2};
  TwoBodyOperator op_tb_t2 = {dim: 1, opt: 0, par: NULL, me: tb_nt2};
  calcSlaterDetOBME(Q, X, &op_ob_t2, &t2one);
  calcSlaterDetTBME(Q, X, &op_tb_t2, &t2two);
  *t2 = t2one + t2two;
}
void calcConstraintPT2 (const SlaterDet * Q, const SlaterDetAux * X, double * t2)
Definition at line 281 of file ConstraintT2.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), and dim.
Referenced by main().
{
  double t2one, t2two;
  OneBodyOperator op_ob_t2 = {dim: 1, opt: 1, par: NULL, me: ob_pt2};
  TwoBodyOperator op_tb_t2 = {dim: 1, opt: 0, par: NULL, me: tb_pt2};
  calcSlaterDetOBME(Q, X, &op_ob_t2, &t2one);
  calcSlaterDetTBME(Q, X, &op_tb_t2, &t2two);
  *t2 = t2one + t2two;
}
void calcConstraintT2 (const SlaterDet * Q, const SlaterDetAux * X, double * t2)
Definition at line 267 of file ConstraintT2.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), and dim.
Referenced by main().
{
  double t2one, t2two;
  OneBodyOperator op_ob_t2 = {dim: 1, opt: 1, par: NULL, me: ob_t2};
  TwoBodyOperator op_tb_t2 = {dim: 1, opt: 0, par: NULL, me: tb_t2};
  calcSlaterDetOBME(Q, X, &op_ob_t2, &t2one);
  calcSlaterDetTBME(Q, X, &op_tb_t2, &t2two);
  *t2 = t2one + t2two;
}
void calcConstraintT2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * t2)
Definition at line 348 of file ConstraintT2.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), and dim.
{
  complex double t2one, t2two;
  OneBodyOperator op_ob_t2 = {dim: 1, opt: 1, par: NULL, me: ob_t2};
  TwoBodyOperator op_tb_t2 = {dim: 1, opt: 0, par: NULL, me: tb_t2};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_t2, &t2one);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_t2, &t2two);
  *t2 = t2one + t2two;
}
void calcgradConstraintNT2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dt2)
Definition at line 335 of file ConstraintT2.c.
References calcgradSlaterDetOBME(), and calcgradSlaterDetTBME().
{
  gradOneBodyOperator gop_ob_t2 = {opt: 1, par: NULL, me: gob_nt2};
  gradTwoBodyOperator gop_tb_t2 = {opt: 0, par: NULL, me: gtb_nt2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_t2, dt2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_t2, dt2);
}
void calcgradConstraintPT2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dt2)
Definition at line 323 of file ConstraintT2.c.
References calcgradSlaterDetOBME(), and calcgradSlaterDetTBME().
{
  gradOneBodyOperator gop_ob_t2 = {opt: 1, par: NULL, me: gob_pt2};
  gradTwoBodyOperator gop_tb_t2 = {opt: 0, par: NULL, me: gtb_pt2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_t2, dt2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_t2, dt2);
}
void calcgradConstraintT2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dt2)
Definition at line 311 of file ConstraintT2.c.
References calcgradSlaterDetOBME(), and calcgradSlaterDetTBME().
{
  gradOneBodyOperator gop_ob_t2 = {opt: 1, par: NULL, me: gob_t2};
  gradTwoBodyOperator gop_tb_t2 = {opt: 0, par: NULL, me: gtb_t2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_t2, dt2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_t2, dt2);
}
void calcgradConstraintT2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * dummy, gradSlaterDet * dt2)
Definition at line 365 of file ConstraintT2.c.
References calcgradSlaterDetOBMEod(), and calcgradSlaterDetTBMEod().
{
  gradOneBodyOperator gop_ob_t2 = {opt: 1, par: NULL, me: gob_t2};
  gradTwoBodyOperator gop_tb_t2 = {opt: 0, par: NULL, me: gtb_t2};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_t2, dt2);
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_t2, dt2);
}
double outputConstraintT2 (double val)
Definition at line 380 of file ConstraintT2.c.
{
  return (val);
}
Variable Documentation
Constraint ConstraintNT2
Initial value:
 {
  val : 0.0,
  label : "NT2",
  me : calcConstraintNT2,
  gradme : calcgradConstraintNT2,
  output : outputConstraintT2
}
Definition at line 42 of file ConstraintT2.c.
Constraint ConstraintPT2
Initial value:
 {
  val : 0.0,
  label : "PT2",
  me : calcConstraintPT2,
  gradme : calcgradConstraintPT2,
  output : outputConstraintT2
}
Definition at line 34 of file ConstraintT2.c.
Constraint ConstraintT2
Initial value:
 {
  val : 0.0,
  label : "T2",
  me : calcConstraintT2,
  gradme : calcgradConstraintT2,
  output : outputConstraintT2
}
Definition at line 26 of file ConstraintT2.c.
Referenced by main().
Constraintod ConstraintT2od
Initial value:
 {
  val : 0.0,
  label : "T2",
  dim : 1,
  gradneedsme : 0,
  me : calcConstraintT2od,
  gradme : calcgradConstraintT2od,
  output : outputConstraintT2
}
Definition at line 51 of file ConstraintT2.c.
Referenced by main().