FMD: fmd/ConstraintMainAxes.h File Reference
fmd/ConstraintMainAxes.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
Functions
void calcConstraintMainAxes (const SlaterDet *Q, const SlaterDetAux *X, double *q2)
void calcgradConstraintMainAxes (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dq2)
Detailed Description
Constrain to main axes of quadrupole tensor
(c) 2003 Thomas Neff
Definition in file ConstraintMainAxes.h.
Function Documentation
void calcConstraintMainAxes (const SlaterDet * Q, const SlaterDetAux * X, double * q2)
Definition at line 218 of file ConstraintMainAxes.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), dim, par, and SQR.
{
  double qijone[3], qijtwo[3], qsq = 0.0;
  int i;
  OneBodyOperator op_ob_qij = {dim: 3, opt: 1, par: Q, me: ob_qoffdiag};
  TwoBodyOperator op_tb_qij = {dim: 3, opt: 1, par: Q, me: tb_qoffdiag};
  calcSlaterDetOBME(Q, X, &op_ob_qij, qijone);
  calcSlaterDetTBME(Q, X, &op_tb_qij, qijtwo);
  for (i=0; i<3; i++)
    qsq += SQR(qijone[i]+qijtwo[i]);
  *q2 = qsq;
}
void calcgradConstraintMainAxes (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dq2)
Definition at line 237 of file ConstraintMainAxes.c.
References SlaterDet::A, calcSlaterDetOBME(), calcSlaterDetTBME(), dim, and par.
{
  double qijone[3], qijtwo[3];
  int i;
  quadrupolepara qpar;
  OneBodyOperator op_ob_qij = {dim: 3, opt: 1, par: Q, me: ob_offdiag};
  TwoBodyOperator op_tb_qij = {dim: 3, opt: 1, par: Q, me: tb_offdiag};
  calcSlaterDetOBME(Q, X, &op_ob_qij, qijone);
  calcSlaterDetTBME(Q, X, &op_tb_qij, qijtwo);
  q2par.A = Q->A;
  for (i=0; i<3; i++)
    q2par.q[i] = qijone[i]+qijtwo[i];
  gradOneBodyOperator gop_ob_q2 = {opt: 1, par: &q2par, me: gob_mainaxes};
  gradTwoBodyOperator gop_tb_q2 = {opt: 1, par: &q2par, me: gtb_mainaxes};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_q2, dq2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_q2, dq2);
}