FMD: fmd/ConstraintJ2.c File Reference
fmd/ConstraintJ2.c File Reference
#include <math.h>
#include <complex.h>
#include "Gaussian.h"
#include "gradGaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "CenterofMass.h"
#include "gradCMSlaterDet.h"
#include "Constraint.h"
#include "ConstraintJ2.h"
#include "numerics/cmath.h"
#include "misc/physics.h"
Data Structures
struct CMpara
Functions
void gcmob_j2 (const CMpara *par, const Gaussian *G1, const Gaussian *G2, const GaussianAux *X, gradCM *dCMj2)
void gcmtb_j2 (const CMpara *par, const Gaussian *G1, const Gaussian *G2, const Gaussian *G3, const Gaussian *G4, const GaussianAux *X13, const GaussianAux *X24, gradCM *dCMj2)
void calcConstraintJ2 (const SlaterDet *Q, const SlaterDetAux *X, double *j2)
void calcgradConstraintJ2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dj2)
void calcConstraintJ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *j2)
void calcgradConstraintJ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *dummy, gradSlaterDet *dj2)
double outputConstraintJ2 (double val)
Variables
Constraint ConstraintJ2
Constraintod ConstraintJ2od
Detailed Description
Constrain expectation value of J2
(c) 2003 Thomas Neff
Definition in file ConstraintJ2.c.
Function Documentation
void calcConstraintJ2 (const SlaterDet * Q, const SlaterDetAux * X, double * j2)
Definition at line 396 of file ConstraintJ2.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), calcSlaterDetTBME(), dim, CMpara::Vcm, and CMpara::Xcm.
{
  CMpara para;
  double j2one, j2two;
  calcCMPosition(Q, X, para.Xcm);
  calcCMVelocity(Q, X, para.Vcm);
  OneBodyOperator op_ob_j2 = {dim: 1, opt: 1, par: &para, me: ob_j2};
  TwoBodyOperator op_tb_j2 = {dim: 1, opt: 1, par: &para, me: tb_j2};
  calcSlaterDetOBME(Q, X, &op_ob_j2, &j2one);
  calcSlaterDetTBME(Q, X, &op_tb_j2, &j2two);
  *j2 = j2one + j2two;
}
void calcConstraintJ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * j2)
Definition at line 446 of file ConstraintJ2.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), and dim.
Referenced by calcorthprojectedHamiltonian(), calcprojectedHamiltonian(), calcprojectedHamiltonianmatrix(), and MinimizerprojSlave().
{
  CMpara para = { { 0.0, 0.0, 0.0}, {0.0, 0.0, 0.0} };
  complex double j2one, j2two;
  OneBodyOperator op_ob_j2 = {dim: 1, opt: 1, par: &para, me: ob_j2};
  TwoBodyOperator op_tb_j2 = {dim: 1, opt: 1, par: &para, me: tb_j2};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_j2, &j2one);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_j2, &j2two);
  *j2 = j2one + j2two;
}
void calcgradConstraintJ2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dj2)
Definition at line 416 of file ConstraintJ2.c.
References calcCMPosition(), calcCMVelocity(), calcgradCMSlaterDetOBME(), calcgradCMSlaterDetTBME(), calcgradSlaterDetOBME(), calcgradSlaterDetTBME(), dim, gcmob_j2(), gcmtb_j2(), gradSlaterDet::val, CMpara::Vcm, and CMpara::Xcm.
{
  CMpara para;
  double j2;
  calcCMPosition(Q, X, para.Xcm);
  calcCMVelocity(Q, X, para.Vcm);
  gradOneBodyOperator gop_ob_j2 = {opt: 1, par: &para, me: gob_j2};
  gradTwoBodyOperator gop_tb_j2 = {opt: 1, par: &para, me: gtb_j2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_j2, dj2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_j2, dj2);
  j2 = dj2->val;
  OneBodyOperator gcmop_ob_j2 = {dim: 6, opt: 1, par: &para, me: gcmob_j2};
  TwoBodyOperator gcmop_tb_j2 = {dim: 6, opt: 1, par: &para, me: gcmtb_j2};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_j2, dj2);
  calcgradCMSlaterDetTBME(Q, X, dX, &gcmop_tb_j2, dj2);
  dj2->val = j2;
}
void calcgradConstraintJ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * dummy, gradSlaterDet * dj2)
Definition at line 463 of file ConstraintJ2.c.
References calcgradSlaterDetOBMEod(), and calcgradSlaterDetTBMEod().
{
  CMpara para = { {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0} };
  gradOneBodyOperator gop_ob_j2 = {opt: 1, par: &para, me: gob_j2};
  gradTwoBodyOperator gop_tb_j2 = {opt: 1, par: &para, me: gtb_j2};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_j2, dj2);
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_j2, dj2);
}
void gcmob_j2 (const CMpara * par, const Gaussian * G1, const Gaussian * G2, const GaussianAux * X, gradCM * dCMj2)
Definition at line 286 of file ConstraintJ2.c.
References Gaussian::a, GaussianAux::alpha, I, GaussianAux::lambda, GaussianAux::pi, GaussianAux::R, GaussianAux::rho, GaussianAux::S, GaussianAux::sig, GaussianAux::T, gradCM::V, CMpara::Vcm, gradCM::X, CMpara::Xcm, and Gaussian::xi.
Referenced by calcgradConstraintJ2(), and calcgradConstraintJ2().
{
  double* Xcm = par->Xcm;
  double* Vcm = par->Vcm;
  complex double beta;
  complex double rhocm[3], picm[3];
  complex double rhocm2, picm2, rhopicm;
  complex double rhoxpicm[3];
  gradCM dl2m, drhocm2, dpicm2, drhopicm;
  gradCM dlsm;
  int i;
  beta = I*X->lambda*(conj(G1->a)-G2->a);
  for (i=0; i<3; i++)
    rhocm[i] = X->rho[i]-Xcm[i];
  rhocm2 = cvec3mult(rhocm, rhocm);
  for (i=0; i<3; i++)
    picm[i] = X->pi[i]-mass(G1->xi)*Vcm[i];
  picm2 = cvec3mult(picm, picm);
  rhopicm = cvec3mult(rhocm, picm);
  cvec3cross(rhocm, picm, rhoxpicm);
  for (i=0; i<3; i++)
    drhocm2.X[i] = -2*rhocm[i];
  for (i=0; i<3; i++)
    dpicm2.V[i] = -2*mass(G1->xi)*picm[i];
  for (i=0; i<3; i++)
    drhopicm.X[i] = -picm[i];
  for (i=0; i<3; i++)
    drhopicm.V[i] = -mass(G1->xi)*rhocm[i];
  for (i=0; i<3; i++)
    dl2m.X[i] = 2*X->lambda*drhocm2.X[i] - 2*beta*drhopicm.X[i] +
      drhocm2.X[i]*picm2 - 2*rhopicm*drhopicm.X[i];
  for (i=0; i<3; i++)
    dl2m.V[i] = 2*X->alpha*dpicm2.V[i] - 2*beta*drhopicm.V[i] +
      rhocm2*dpicm2.V[i] - 2*rhopicm*drhopicm.V[i];
  for (i=0; i<3; i++)
    dlsm.X[i] = -0.5*(picm[(i+1)%3]*X->sig[(i+2)%3] -
                      picm[(i+2)%3]*X->sig[(i+1)%3]);
  for (i=0; i<3; i++)
    dlsm.V[i] = 0.5*mass(G1->xi)*(rhocm[(i+1)%3]*X->sig[(i+2)%3] -
                                  rhocm[(i+2)%3]*X->sig[(i+1)%3]);
  for (i=0; i<3; i++)
    dCMj2->X[i] += X->T* (dl2m.X[i]* X->S*X->R + 2*dlsm.X[i]* X->R);
  for (i=0; i<3; i++)
    dCMj2->V[i] += X->T* (dl2m.V[i]* X->S*X->R + 2*dlsm.V[i]* X->R);
}
void gcmtb_j2 (const CMpara * par, const Gaussian * G1, const Gaussian * G2, const Gaussian * G3, const Gaussian * G4, const GaussianAux * X13, const GaussianAux * X24, gradCM * dCMj2)
Definition at line 342 of file ConstraintJ2.c.
References GaussianAux::pi, GaussianAux::R, GaussianAux::rho, GaussianAux::S, GaussianAux::sig, GaussianAux::T, gradCM::V, CMpara::Vcm, gradCM::X, CMpara::Xcm, and Gaussian::xi.
Referenced by calcgradConstraintJ2().
{
  double* Xcm = par->Xcm;
  double* Vcm = par->Vcm;
  complex double rho13cm[3], rho24cm[3], pi13cm[3], pi24cm[3];
  gradCM dl2m, dlsm;
  int i;
  for (i=0; i<3; i++)
    rho13cm[i] = X13->rho[i]-Xcm[i];
  for (i=0; i<3; i++)
    pi13cm[i] = X13->pi[i]-mass(G1->xi)*Vcm[i];
  for (i=0; i<3; i++)
    rho24cm[i] = X24->rho[i]-Xcm[i];
  for (i=0; i<3; i++)
    pi24cm[i] = X24->pi[i]-mass(G2->xi)*Vcm[i];
  for (i=0; i<3; i++)
    dl2m.X[i] = - (rho24cm[i]+rho13cm[i])*cvec3mult(pi13cm, pi24cm) +
      pi24cm[i]*cvec3mult(pi13cm, rho24cm) +
      cvec3mult(rho13cm, pi24cm)*pi13cm[i];
  for (i=0; i<3; i++)
    dl2m.V[i] = - cvec3mult(rho13cm, rho24cm)*
      (mass(G1->xi)*pi24cm[i]+mass(G2->xi)*pi13cm[i]) +
      mass(G2->xi)*rho13cm[i]*cvec3mult(pi13cm, rho24cm) +
      cvec3mult(rho13cm, pi24cm)*mass(G1->xi)*rho24cm[i];
  for (i=0; i<3; i++)
    dlsm.X[i] =
      -0.25*(pi13cm[(i+1)%3]*X13->S*X24->sig[(i+2)%3] -
             pi13cm[(i+2)%3]*X13->S*X24->sig[(i+1)%3])
      -0.25*(X13->sig[(i+2)%3]*pi24cm[(i+1)%3]*X24->S -
             X13->sig[(i+1)%3]*pi24cm[(i+2)%3]*X24->S);
  for (i=0; i<3; i++)
    dlsm.V[i] =
      0.25*mass(G1->xi)*(rho13cm[(i+1)%3]*X13->S*X24->sig[(i+2)%3] -
                         rho13cm[(i+2)%3]*X13->S*X24->sig[(i+1)%3]) +
      0.25*mass(G2->xi)*(X13->sig[(i+2)%3]*rho24cm[(i+1)%3]*X24->S -
                         X13->sig[(i+1)%3]*rho24cm[(i+2)%3]*X24->S);
  for (i=0; i<3; i++)
    dCMj2->X[i] += 2*X13->T*X24->T*
      (dl2m.X[i]* X13->S*X24->S + 2*dlsm.X[i])* X13->R* X24->R;
  for (i=0; i<3; i++)
    dCMj2->V[i] += 2*X13->T*X24->T*
      (dl2m.V[i]* X13->S*X24->S + 2*dlsm.V[i])* X13->R* X24->R;
}
double outputConstraintJ2 (double val)
Definition at line 479 of file ConstraintJ2.c.
{
  return (val);
}
Variable Documentation
Constraint ConstraintJ2
Initial value:
 {
  val : 0.0,
  label : "J2",
  me : calcConstraintJ2,
  gradme : calcgradConstraintJ2,
  output : outputConstraintJ2
}
Definition at line 29 of file ConstraintJ2.c.
Referenced by main().
Constraintod ConstraintJ2od
Initial value:
 {
  val : 0.0,
  label : "J2",
  dim : 1,
  gradneedsme : 0,
  me : calcConstraintJ2od,
  gradme : calcgradConstraintJ2od,
  output : outputConstraintJ2
}
Definition at line 38 of file ConstraintJ2.c.
Referenced by main().