FMD: fmd/ConstraintS2.h File Reference
fmd/ConstraintS2.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Constraint.h"
Functions
void calcConstraintS2 (const SlaterDet *Q, const SlaterDetAux *X, double *s2)
void calcConstraintPS2 (const SlaterDet *Q, const SlaterDetAux *X, double *s2)
void calcConstraintNS2 (const SlaterDet *Q, const SlaterDetAux *X, double *s2)
void calcgradConstraintS2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *ds2)
void calcgradConstraintPS2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *ds2)
void calcgradConstraintNS2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *ds2)
void calcConstraintS2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *s2)
void calcgradConstraintS2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *dummy, gradSlaterDet *ds2)
double outputConstraintS2 (double val)
Variables
Constraint ConstraintS2
Constraint ConstraintPS2
Constraint ConstraintNS2
Constraintod ConstraintS2od
Detailed Description
Constrain expectation value of S2
(c) 2004 Thomas Neff
Definition in file ConstraintS2.h.
Function Documentation
void calcConstraintNS2 (const SlaterDet * Q, const SlaterDetAux * X, double * s2)
Definition at line 293 of file ConstraintS2.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), and dim.
Referenced by main().
{
  double s2one, s2two;
  OneBodyOperator op_ob_s2 = {dim: 1, opt: 1, par: NULL, me: ob_ns2};
  TwoBodyOperator op_tb_s2 = {dim: 1, opt: 1, par: NULL, me: tb_ns2};
  calcSlaterDetOBME(Q, X, &op_ob_s2, &s2one);
  calcSlaterDetTBME(Q, X, &op_tb_s2, &s2two);
  *s2 = s2one + s2two;
}
void calcConstraintPS2 (const SlaterDet * Q, const SlaterDetAux * X, double * s2)
Definition at line 279 of file ConstraintS2.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), and dim.
Referenced by main().
{
  double s2one, s2two;
  OneBodyOperator op_ob_s2 = {dim: 1, opt: 1, par: NULL, me: ob_ps2};
  TwoBodyOperator op_tb_s2 = {dim: 1, opt: 1, par: NULL, me: tb_ps2};
  calcSlaterDetOBME(Q, X, &op_ob_s2, &s2one);
  calcSlaterDetTBME(Q, X, &op_tb_s2, &s2two);
  *s2 = s2one + s2two;
}
void calcConstraintS2 (const SlaterDet * Q, const SlaterDetAux * X, double * s2)
Definition at line 265 of file ConstraintS2.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), and dim.
Referenced by main().
{
  double s2one, s2two;
  OneBodyOperator op_ob_s2 = {dim: 1, opt: 1, par: NULL, me: ob_s2};
  TwoBodyOperator op_tb_s2 = {dim: 1, opt: 1, par: NULL, me: tb_s2};
  calcSlaterDetOBME(Q, X, &op_ob_s2, &s2one);
  calcSlaterDetTBME(Q, X, &op_tb_s2, &s2two);
  *s2 = s2one + s2two;
}
void calcConstraintS2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * s2)
Definition at line 345 of file ConstraintS2.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), and dim.
{
  complex double s2one, s2two;
  OneBodyOperator op_ob_s2 = {dim: 1, opt: 1, par: NULL, me: ob_s2};
  TwoBodyOperator op_tb_s2 = {dim: 1, opt: 1, par: NULL, me: tb_s2};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_s2, &s2one);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_s2, &s2two);
  *s2 = s2one + s2two;
}
void calcgradConstraintNS2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * ds2)
Definition at line 332 of file ConstraintS2.c.
References calcgradSlaterDetOBME(), and calcgradSlaterDetTBME().
{
  gradOneBodyOperator gop_ob_s2 = {opt: 1, par: NULL, me: gob_ns2};
  gradTwoBodyOperator gop_tb_s2 = {opt: 1, par: NULL, me: gtb_ns2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_s2, ds2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_s2, ds2);
}
void calcgradConstraintPS2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * ds2)
Definition at line 320 of file ConstraintS2.c.
References calcgradSlaterDetOBME(), and calcgradSlaterDetTBME().
{
  gradOneBodyOperator gop_ob_s2 = {opt: 1, par: NULL, me: gob_ps2};
  gradTwoBodyOperator gop_tb_s2 = {opt: 1, par: NULL, me: gtb_ps2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_s2, ds2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_s2, ds2);
}
void calcgradConstraintS2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * ds2)
Definition at line 308 of file ConstraintS2.c.
References calcgradSlaterDetOBME(), and calcgradSlaterDetTBME().
{
  gradOneBodyOperator gop_ob_s2 = {opt: 1, par: NULL, me: gob_s2};
  gradTwoBodyOperator gop_tb_s2 = {opt: 1, par: NULL, me: gtb_s2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_s2, ds2);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_s2, ds2);
}
void calcgradConstraintS2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * dummy, gradSlaterDet * ds2)
Definition at line 361 of file ConstraintS2.c.
References calcgradSlaterDetOBMEod(), and calcgradSlaterDetTBMEod().
{
  gradOneBodyOperator gop_ob_s2 = {opt: 1, par: NULL, me: gob_s2};
  gradTwoBodyOperator gop_tb_s2 = {opt: 1, par: NULL, me: gtb_s2};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_s2, ds2);
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_s2, ds2);
}
double outputConstraintS2 (double val)
Definition at line 376 of file ConstraintS2.c.
{
  return (val);
}
Variable Documentation
Constraint ConstraintNS2
Definition at line 42 of file ConstraintS2.c.
Referenced by main().
Constraint ConstraintPS2
Definition at line 34 of file ConstraintS2.c.
Referenced by main().
Constraint ConstraintS2
Definition at line 26 of file ConstraintS2.c.
Referenced by main().
Constraintod ConstraintS2od
Definition at line 51 of file ConstraintS2.c.
Referenced by main().