FMD: fmd/ConstraintCMXP.c File Reference
fmd/ConstraintCMXP.c File Reference
#include <complex.h>
#include "Gaussian.h"
#include "gradGaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "ConstraintCMXP.h"
#include "numerics/cmath.h"
#include "misc/physics.h"
Defines
#define SQR(x) (x)*(x)
Functions
void calcConstraintX (const SlaterDet *Q, const SlaterDetAux *X, double *mxcon)
void calcConstraintY (const SlaterDet *Q, const SlaterDetAux *X, double *mxcon)
void calcConstraintZ (const SlaterDet *Q, const SlaterDetAux *X, double *mxcon)
void calcConstraintPX (const SlaterDet *Q, const SlaterDetAux *X, double *mxcon)
void calcConstraintPY (const SlaterDet *Q, const SlaterDetAux *X, double *mxcon)
void calcConstraintPZ (const SlaterDet *Q, const SlaterDetAux *X, double *mxcon)
void calcgradConstraintX (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dmxcon)
void calcgradConstraintY (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dmxcon)
void calcgradConstraintZ (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dmxcon)
void calcgradConstraintPX (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dmxcon)
void calcgradConstraintPY (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dmxcon)
void calcgradConstraintPZ (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dmxcon)
double outputConstraintCM (double val)
Variables
Constraint ConstraintX
Constraint ConstraintY
Constraint ConstraintZ
Constraint ConstraintPX
Constraint ConstraintPY
Constraint ConstraintPZ
Define Documentation
#define SQR (x) (x)*(x)
Definition at line 244 of file ConstraintCMXP.c.
Function Documentation
void calcConstraintPX (const SlaterDet * Q, const SlaterDetAux * X, double * mxcon)
Definition at line 270 of file ConstraintCMXP.c.
References calcSlaterDetOBME(), dim, and par.
{
  OneBodyOperator op_ob_mx = {dim: 1, opt: 1, par: NULL, me: ob_px};
  calcSlaterDetOBME(Q, X, &op_ob_mx, mxcon);
}
void calcConstraintPY (const SlaterDet * Q, const SlaterDetAux * X, double * mxcon)
Definition at line 278 of file ConstraintCMXP.c.
References calcSlaterDetOBME(), dim, and par.
{
  OneBodyOperator op_ob_mx = {dim: 1, opt: 1, par: NULL, me: ob_py};
  calcSlaterDetOBME(Q, X, &op_ob_mx, mxcon);
}
void calcConstraintPZ (const SlaterDet * Q, const SlaterDetAux * X, double * mxcon)
Definition at line 286 of file ConstraintCMXP.c.
References calcSlaterDetOBME(), dim, and par.
{
  OneBodyOperator op_ob_mx = {dim: 1, opt: 1, par: NULL, me: ob_pz};
  calcSlaterDetOBME(Q, X, &op_ob_mx, mxcon);
}
void calcConstraintX (const SlaterDet * Q, const SlaterDetAux * X, double * mxcon)
Definition at line 246 of file ConstraintCMXP.c.
References calcSlaterDetOBME(), dim, and par.
{
  OneBodyOperator op_ob_mx = {dim: 1, opt: 1, par: NULL, me: ob_mx};
  calcSlaterDetOBME(Q, X, &op_ob_mx, mxcon);
}
void calcConstraintY (const SlaterDet * Q, const SlaterDetAux * X, double * mxcon)
Definition at line 254 of file ConstraintCMXP.c.
References calcSlaterDetOBME(), dim, and par.
{
  OneBodyOperator op_ob_mx = {dim: 1, opt: 1, par: NULL, me: ob_my};
  calcSlaterDetOBME(Q, X, &op_ob_mx, mxcon);
}
void calcConstraintZ (const SlaterDet * Q, const SlaterDetAux * X, double * mxcon)
Definition at line 262 of file ConstraintCMXP.c.
References calcSlaterDetOBME(), dim, and par.
{
  OneBodyOperator op_ob_mx = {dim: 1, opt: 1, par: NULL, me: ob_mz};
  calcSlaterDetOBME(Q, X, &op_ob_mx, mxcon);
}
void calcgradConstraintPX (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dmxcon)
Definition at line 322 of file ConstraintCMXP.c.
References calcgradSlaterDetOBME(), and par.
{
  gradOneBodyOperator gop_ob_mx = {opt: 1, par: NULL, me: gob_px};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_mx, dmxcon);
}
void calcgradConstraintPY (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dmxcon)
Definition at line 331 of file ConstraintCMXP.c.
References calcgradSlaterDetOBME(), and par.
{
  gradOneBodyOperator gop_ob_mx = {opt: 1, par: NULL, me: gob_py};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_mx, dmxcon);
}
void calcgradConstraintPZ (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dmxcon)
Definition at line 340 of file ConstraintCMXP.c.
References calcgradSlaterDetOBME(), and par.
{
  gradOneBodyOperator gop_ob_mx = {opt: 1, par: NULL, me: gob_pz};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_mx, dmxcon);
}
void calcgradConstraintX (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dmxcon)
Definition at line 295 of file ConstraintCMXP.c.
References calcgradSlaterDetOBME(), and par.
{
  gradOneBodyOperator gop_ob_mx = {opt: 1, par: NULL, me: gob_mx};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_mx, dmxcon);
}
void calcgradConstraintY (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dmxcon)
Definition at line 304 of file ConstraintCMXP.c.
References calcgradSlaterDetOBME(), and par.
{
  gradOneBodyOperator gop_ob_mx = {opt: 1, par: NULL, me: gob_my};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_mx, dmxcon);
}
void calcgradConstraintZ (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dmxcon)
Definition at line 313 of file ConstraintCMXP.c.
References calcgradSlaterDetOBME(), and par.
{
  gradOneBodyOperator gop_ob_mx = {opt: 1, par: NULL, me: gob_mz};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_mx, dmxcon);
}
double outputConstraintCM (double val)
Definition at line 350 of file ConstraintCMXP.c.
{
  return (val);
}
Variable Documentation
Constraint ConstraintPX
Initial value:
 {
  val : 0.0,
  label : "PX",
  me : calcConstraintPX,
  gradme : calcgradConstraintPX,
  output : outputConstraintCM
}
Definition at line 49 of file ConstraintCMXP.c.
Constraint ConstraintPY
Initial value:
 {
  val : 0.0,
  label : "PY",
  me : calcConstraintPY,
  gradme : calcgradConstraintPY,
  output : outputConstraintCM
}
Definition at line 57 of file ConstraintCMXP.c.
Constraint ConstraintPZ
Initial value:
 {
  val : 0.0,
  label : "PZ",
  me : calcConstraintPZ,
  gradme : calcgradConstraintPZ,
  output : outputConstraintCM
}
Definition at line 65 of file ConstraintCMXP.c.
Constraint ConstraintX
Initial value:
 {
  val : 0.0,
  label : "X",
  me : calcConstraintX,
  gradme : calcgradConstraintX,
  output : outputConstraintCM
}
Definition at line 25 of file ConstraintCMXP.c.
Constraint ConstraintY
Initial value:
 {
  val : 0.0,
  label : "Y",
  me : calcConstraintY,
  gradme : calcgradConstraintY,
  output : outputConstraintCM
}
Definition at line 33 of file ConstraintCMXP.c.
Constraint ConstraintZ
Initial value:
 {
  val : 0.0,
  label : "Z",
  me : calcConstraintZ,
  gradme : calcgradConstraintZ,
  output : outputConstraintCM
}
Definition at line 41 of file ConstraintCMXP.c.