FMD: fmd/ConstraintQuadrupole.h File Reference
fmd/ConstraintQuadrupole.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Constraint.h"
Functions
void calcConstraintQ2 (const SlaterDet *Q, const SlaterDetAux *X, double *q2)
void calcgradConstraintQ2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dq2)
void calcConstraintQ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *q2)
void calcgradConstraintQ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *q, gradSlaterDet *dq2)
double outputConstraintQ2 (double val)
void calcConstraintEQ2 (const SlaterDet *Q, const SlaterDetAux *X, double *q2)
void calcgradConstraintEQ2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dq2)
void calcConstraintEQ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *q2)
void calcgradConstraintEQ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *q, gradSlaterDet *dq2)
double outputConstraintEQ2 (double val)
void calcConstraintNQ2 (const SlaterDet *Q, const SlaterDetAux *X, double *q2)
void calcgradConstraintNQ2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dq2)
void calcConstraintNQ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *q2)
void calcgradConstraintNQ2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *q, gradSlaterDet *dq2)
double outputConstraintNQ2 (double val)
void calcConstraintDetQ (const SlaterDet *Q, const SlaterDetAux *X, double *detq)
void calcgradConstraintDetQ (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *ddetq)
double outputConstraintDetQ (double val)
void calcConstraintQ2offdiagonal (const SlaterDet *Q, const SlaterDetAux *X, double *dq2)
void calcgradConstraintQ2offdiagonal (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dq2)
double outputConstraintQ2offdiagonal (double val)
Variables
Constraint ConstraintQ2
Constraintod ConstraintQ2od
Constraint ConstraintEQ2
Constraintod ConstraintEQ2od
Constraint ConstraintNQ2
Constraintod ConstraintNQ2od
Constraint ConstraintDetQ
Constraint ConstraintQ2offdiagonal
Detailed Description
Constrain mass quadrupole moment
(c) 2003 Thomas Neff
Definition in file ConstraintQuadrupole.h.
Function Documentation
void calcConstraintDetQ (const SlaterDet * Q, const SlaterDetAux * X, double * detq)
Definition at line 719 of file ConstraintQuadrupole.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, and par.
{
  double Xcm[3];
  double q[9];
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_quadrupole};
  calcSlaterDetOBME(Q, X, &op_ob_q, q);
  *detq = cbrt(det(q));
}
void calcConstraintEQ2 (const SlaterDet * Q, const SlaterDetAux * X, double * q2)
Definition at line 469 of file ConstraintQuadrupole.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, par, and SQR.
Referenced by main().
{
  double Xcm[3];
  double q[9], qsq = 0.0;
  int i;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_equadrupole};
  calcSlaterDetOBME(Q, X, &op_ob_q, q);
  for (i=0; i<9; i++)
    qsq += SQR(q[i]);
  *q2 = sqrt(qsq);
}
void calcConstraintEQ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * q2)
Definition at line 489 of file ConstraintQuadrupole.c.
References calcSlaterDetOBMEod(), dim, and par.
{
  double Xcm[3] = { 0.0, 0.0, 0.0 };
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_equadrupole};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_q, q);
}
void calcConstraintNQ2 (const SlaterDet * Q, const SlaterDetAux * X, double * q2)
Definition at line 501 of file ConstraintQuadrupole.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, par, and SQR.
Referenced by main().
{
  double Xcm[3];
  double q[9], qsq = 0.0;
  int i;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_nquadrupole};
  calcSlaterDetOBME(Q, X, &op_ob_q, q);
  for (i=0; i<9; i++)
    qsq += SQR(q[i]);
  *q2 = sqrt(qsq);
}
void calcConstraintNQ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * q2)
Definition at line 521 of file ConstraintQuadrupole.c.
References calcSlaterDetOBMEod(), dim, and par.
{
  double Xcm[3] = { 0.0, 0.0, 0.0 };
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_nquadrupole};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_q, q);
}
void calcConstraintQ2 (const SlaterDet * Q, const SlaterDetAux * X, double * q2)
Definition at line 437 of file ConstraintQuadrupole.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, par, and SQR.
Referenced by main().
{
  double Xcm[3];
  double q[9], qsq = 0.0;
  int i;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_quadrupole};
  calcSlaterDetOBME(Q, X, &op_ob_q, q);
  for (i=0; i<9; i++)
    qsq += SQR(q[i]);
  *q2 = sqrt(qsq);
}
void calcConstraintQ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * q2)
Definition at line 457 of file ConstraintQuadrupole.c.
References calcSlaterDetOBMEod(), dim, and par.
{
  double Xcm[3] = { 0.0, 0.0, 0.0 };
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_quadrupole};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_q, q);
}
void calcConstraintQ2offdiagonal (const SlaterDet * Q, const SlaterDetAux * X, double * dq2)
Definition at line 786 of file ConstraintQuadrupole.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, par, and SQR.
{
  double Xcm[3];
  double q[9], qsq = 0.0;
  int i;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_quadrupoleoffd};
  calcSlaterDetOBME(Q, X, &op_ob_q, q);
  for (i=0; i<9; i++)
    qsq += SQR(q[i]);
  *q2 = sqrt(qsq);
}
void calcgradConstraintDetQ (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * ddetq)
Definition at line 747 of file ConstraintQuadrupole.c.
References calcCMPosition(), calcgradSlaterDetOBME(), calcSlaterDetOBME(), dim, par, quadrupolepara::q, SQR, gradSlaterDet::val, and quadrupolepara::Xcm.
{
  double Xcm[3];
  double q[9], detq, adjq[9];
  int i;
  quadrupolepara q2par;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_quadrupole};
  calcSlaterDetOBME(Q, X, &op_ob_q, q);
  for (i=0; i<3; i++)
    q2par.Xcm[i] = Xcm[i];
  detq = det(q);
  adjunct(q, adjq);
  for (i=0; i<9; i++)
    q2par.q[i] = 1.0/(3*SQR(cbrt(detq)))*adjq[i];
  gradOneBodyOperator gop_ob_detq = {opt: 1, par: &q2par, me: gob_quadrupole};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_detq, ddetq);
  ddetq->val = cbrt(detq);
}
void calcgradConstraintEQ2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dq2)
Definition at line 583 of file ConstraintQuadrupole.c.
References calcCMPosition(), calcgradCMSlaterDetOBME(), calcgradSlaterDetOBME(), calcSlaterDetOBME(), dim, par, quadrupolepara::q, SQR, gradSlaterDet::val, and quadrupolepara::Xcm.
{
  double Xcm[3];
  double q[9], qsq = 0.0;
  int i;
  quadrupolepara q2par;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_equadrupole};
  calcSlaterDetOBME(Q, X, &op_ob_q, q);
  for (i=0; i<9; i++)
    qsq += SQR(q[i]);
  for (i=0; i<3; i++)
    q2par.Xcm[i] = Xcm[i];
  for (i=0; i<9; i++)
    q2par.q[i] = q[i]/sqrt(qsq);
  gradOneBodyOperator gop_ob_q2 = {opt: 1, par: &q2par, me: gob_equadrupole};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_q2, dq2);
  OneBodyOperator gcmop_ob_q2 = {dim: 6, opt: 1, par: &q2par, me: gcmob_equadrupole};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_q2, dq2);
  dq2->val = sqrt(qsq);
}
void calcgradConstraintEQ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * q, gradSlaterDet * dq2)
Definition at line 618 of file ConstraintQuadrupole.c.
References par, and quadrupolepara::q.
{
  double Xcm[3] = { 0.0, 0.0, 0.0 };
  int i;
  quadrupolepara q2par;
  for (i=0; i<9; i++)
    q2par.q[i] = q[i];
  gradOneBodyOperator gop_ob_q2 = {opt: 1, par: &q2par, me: gob_equadrupole};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_q2, dq2);
}
void calcgradConstraintNQ2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dq2)
Definition at line 638 of file ConstraintQuadrupole.c.
References calcCMPosition(), calcgradCMSlaterDetOBME(), calcgradSlaterDetOBME(), calcSlaterDetOBME(), dim, par, quadrupolepara::q, SQR, gradSlaterDet::val, and quadrupolepara::Xcm.
{
  double Xcm[3];
  double q[9], qsq = 0.0;
  int i;
  quadrupolepara q2par;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_nquadrupole};
  calcSlaterDetOBME(Q, X, &op_ob_q, q);
  for (i=0; i<9; i++)
    qsq += SQR(q[i]);
  for (i=0; i<3; i++)
    q2par.Xcm[i] = Xcm[i];
  for (i=0; i<9; i++)
    q2par.q[i] = q[i]/sqrt(qsq);
  gradOneBodyOperator gop_ob_q2 = {opt: 1, par: &q2par, me: gob_nquadrupole};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_q2, dq2);
  OneBodyOperator gcmop_ob_q2 = {dim: 6, opt: 1, par: &q2par, me: gcmob_nquadrupole};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_q2, dq2);
  dq2->val = sqrt(qsq);
}
void calcgradConstraintNQ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * q, gradSlaterDet * dq2)
Definition at line 673 of file ConstraintQuadrupole.c.
References par, and quadrupolepara::q.
{
  double Xcm[3] = { 0.0, 0.0, 0.0 };
  int i;
  quadrupolepara q2par;
  for (i=0; i<9; i++)
    q2par.q[i] = q[i];
  gradOneBodyOperator gop_ob_q2 = {opt: 1, par: &q2par, me: gob_nquadrupole};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_q2, dq2);
}
void calcgradConstraintQ2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dq2)
Definition at line 533 of file ConstraintQuadrupole.c.
References calcCMPosition(), calcgradSlaterDetOBME(), calcSlaterDetOBME(), dim, par, quadrupolepara::q, SQR, and quadrupolepara::Xcm.
{
  double Xcm[3];
  double q[9], qsq = 0.0;
  int i;
  quadrupolepara q2par;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_quadrupole};
  calcSlaterDetOBME(Q, X, &op_ob_q, q);
  for (i=0; i<9; i++)
    qsq += SQR(q[i]);
  for (i=0; i<3; i++)
    q2par.Xcm[i] = Xcm[i];
  for (i=0; i<9; i++)
    q2par.q[i] = q[i]/sqrt(qsq);
  gradOneBodyOperator gop_ob_q2 = {opt: 1, par: &q2par, me: gob_quadrupole};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_q2, dq2);
}
void calcgradConstraintQ2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * q, gradSlaterDet * dq2)
Definition at line 563 of file ConstraintQuadrupole.c.
References par, and quadrupolepara::q.
{
  double Xcm[3] = { 0.0, 0.0, 0.0 };
  int i;
  quadrupolepara q2par;
  for (i=0; i<9; i++)
    q2par.q[i] = q[i];
  gradOneBodyOperator gop_ob_q2 = {opt: 1, par: &q2par, me: gob_quadrupole};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_q2, dq2);
}
void calcgradConstraintQ2offdiagonal (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dq2)
Definition at line 806 of file ConstraintQuadrupole.c.
References calcCMPosition(), calcgradSlaterDetOBME(), calcSlaterDetOBME(), dim, par, quadrupolepara::q, SQR, and quadrupolepara::Xcm.
{
  double Xcm[3];
  double q[9], qsq = 0.0;
  int i;
  quadrupolepara q2par;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_q = {dim: 9, opt: 1, par: Xcm, me: ob_quadrupoleoffd};
  calcSlaterDetOBME(Q, X, &op_ob_q, q);
  for (i=0; i<9; i++)
    qsq += SQR(q[i]);
  for (i=0; i<3; i++)
    q2par.Xcm[i] = Xcm[i];
  for (i=0; i<9; i++)
    q2par.q[i] = q[i]/sqrt(qsq);
  gradOneBodyOperator gop_ob_q2 = {opt: 1, par: &q2par, me: gob_quadrupoleoffd};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_q2, dq2);
}
double outputConstraintDetQ (double val)
Definition at line 779 of file ConstraintQuadrupole.c.
{
  return 3*val;
}
double outputConstraintEQ2 (double val)
Definition at line 699 of file ConstraintQuadrupole.c.
{
  return val;
}
double outputConstraintNQ2 (double val)
Definition at line 705 of file ConstraintQuadrupole.c.
{
  return val;
}
double outputConstraintQ2 (double val)
Definition at line 693 of file ConstraintQuadrupole.c.
{
  return val;
}
double outputConstraintQ2offdiagonal (double val)
Definition at line 836 of file ConstraintQuadrupole.c.
{
  return val;
}
Variable Documentation
Constraint ConstraintDetQ
Definition at line 83 of file ConstraintQuadrupole.c.
Referenced by main().
Constraint ConstraintEQ2
Definition at line 47 of file ConstraintQuadrupole.c.
Referenced by main().
Constraintod ConstraintEQ2od
Definition at line 55 of file ConstraintQuadrupole.c.
Referenced by main().
Constraint ConstraintNQ2
Definition at line 65 of file ConstraintQuadrupole.c.
Referenced by main().
Constraintod ConstraintNQ2od
Definition at line 73 of file ConstraintQuadrupole.c.
Constraint ConstraintQ2
Definition at line 29 of file ConstraintQuadrupole.c.
Referenced by main().
Constraintod ConstraintQ2od
Definition at line 37 of file ConstraintQuadrupole.c.
Referenced by main().
Constraint ConstraintQ2offdiagonal
Definition at line 91 of file ConstraintQuadrupole.c.
Referenced by main().