FMD: fmd/ConstraintLS.h File Reference
fmd/ConstraintLS.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Constraint.h"
Functions
void calcConstraintLS (const SlaterDet *Q, const SlaterDetAux *X, double *ls)
void calcgradConstraintLS (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dls)
void calcConstraintLSod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *ls)
void calcgradConstraintLSod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *dummy, gradSlaterDet *dls)
double outputConstraintLS (double val)
Variables
Constraint ConstraintLS
Constraintod ConstraintLSod
Function Documentation
void calcConstraintLS (const SlaterDet * Q, const SlaterDetAux * X, double * ls)
Definition at line 279 of file ConstraintLS.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), calcSlaterDetTBME(), dim, CMpara::Vcm, and CMpara::Xcm.
{
  CMpara para;
  double lsone, lstwo;
  calcCMPosition(Q, X, para.Xcm);
  calcCMVelocity(Q, X, para.Vcm);
  OneBodyOperator op_ob_ls = {dim: 1, opt: 1, par: &para, me: ob_ls};
  TwoBodyOperator op_tb_ls = {dim: 1, opt: 1, par: &para, me: tb_ls};
  calcSlaterDetOBME(Q, X, &op_ob_ls, &lsone);
  calcSlaterDetTBME(Q, X, &op_tb_ls, &lstwo);
  *ls = lsone + lstwo;
}
void calcConstraintLSod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * ls)
Definition at line 327 of file ConstraintLS.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), and dim.
{
  CMpara para = { { 0.0, 0.0, 0.0}, {0.0, 0.0, 0.0} };
  complex double lsone, lstwo;
  OneBodyOperator op_ob_ls = {dim: 1, opt: 1, par: &para, me: ob_ls};
  TwoBodyOperator op_tb_ls = {dim: 1, opt: 1, par: &para, me: tb_ls};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_ls, &lsone);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_ls, &lstwo);
  *ls = lsone + lstwo;
}
void calcgradConstraintLS (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dls)
Definition at line 299 of file ConstraintLS.c.
References calcCMPosition(), calcCMVelocity(), calcgradCMSlaterDetOBME(), calcgradCMSlaterDetTBME(), calcgradSlaterDetOBME(), calcgradSlaterDetTBME(), dim, gcmob_ls(), gcmtb_ls(), gradSlaterDet::val, CMpara::Vcm, and CMpara::Xcm.
{
  CMpara para;
  double ls;
  calcCMPosition(Q, X, para.Xcm);
  calcCMVelocity(Q, X, para.Vcm);
  gradOneBodyOperator gop_ob_ls = {opt: 1, par: &para, me: gob_ls};
  gradTwoBodyOperator gop_tb_ls = {opt: 1, par: &para, me: gtb_ls};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_ls, dls);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_ls, dls);
  ls = dls->val;
  OneBodyOperator gcmop_ob_ls = {dim: 6, opt: 1, par: &para, me: gcmob_ls};
  TwoBodyOperator gcmop_tb_ls = {dim: 6, opt: 1, par: &para, me: gcmtb_ls};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_ls, dls);
  calcgradCMSlaterDetTBME(Q, X, dX, &gcmop_tb_ls, dls);
  dls->val = ls;
}
void calcgradConstraintLSod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, const double * dummy, gradSlaterDet * dls)
Definition at line 344 of file ConstraintLS.c.
References calcgradSlaterDetOBMEod(), and calcgradSlaterDetTBMEod().
{
  CMpara para = { {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0} };
  gradOneBodyOperator gop_ob_ls = {opt: 1, par: &para, me: gob_ls};
  gradTwoBodyOperator gop_tb_ls = {opt: 1, par: &para, me: gtb_ls};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_ls, dls);
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_ls, dls);
}
double outputConstraintLS (double val)
Definition at line 360 of file ConstraintLS.c.
{
  return (val);
}
Variable Documentation
Constraint ConstraintLS
Definition at line 29 of file ConstraintLS.c.
Referenced by main().
Constraintod ConstraintLSod
Definition at line 38 of file ConstraintLS.c.
Referenced by main().