FMD: fmd/ConstraintDipole.h File Reference
fmd/ConstraintDipole.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Constraint.h"
Defines
#define _CONSTRAINTEDPOLE_H
Functions
void calcConstraintED2 (const SlaterDet *Q, const SlaterDetAux *X, double *ed2)
void calcgradConstraintED2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *ded2)
double outputConstraintED2 (double val)
Variables
Constraint ConstraintED2
Detailed Description
Constrain dipole moment
(c) 2003 Thomas Neff
Definition in file ConstraintDipole.h.
Define Documentation
#define _CONSTRAINTEDPOLE_H
Definition at line 14 of file ConstraintDipole.h.
Function Documentation
void calcConstraintED2 (const SlaterDet * Q, const SlaterDetAux * X, double * ed2)
Definition at line 98 of file ConstraintDipole.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, par, and SQR.
Referenced by main().
{
  double Xcm[3];
  double ed[3], edsq = 0.0;
  int i;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_d = {dim: 3, opt: 1, par: Xcm, me: ob_edipole};
  calcSlaterDetOBME(Q, X, &op_ob_d, ed);
  for (i=0; i<3; i++)
    edsq += SQR(ed[i]);
  *ed2 = sqrt(edsq);
}
void calcgradConstraintED2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * ded2)
Definition at line 118 of file ConstraintDipole.c.
References calcCMPosition(), calcgradCMSlaterDetOBME(), calcgradSlaterDetOBME(), calcSlaterDetOBME(), dipolepara::d, dim, par, SQR, gradSlaterDet::val, and dipolepara::Xcm.
{
  double Xcm[3];
  double ed[3], edsq = 0.0;
  int i;
  dipolepara ed2par;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_d = {dim: 3, opt: 1, par: Xcm, me: ob_edipole};
  calcSlaterDetOBME(Q, X, &op_ob_d, ed);
  for (i=0; i<3; i++)
    edsq += SQR(ed[i]);
  for (i=0; i<3; i++)
    ed2par.Xcm[i] = Xcm[i];
  for (i=0; i<3; i++)
    ed2par.d[i] = ed[i]/sqrt(edsq);
  gradOneBodyOperator gop_ob_d2 = {opt: 1, par: &ed2par, me: gob_edipole};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_d2, ded2);
  OneBodyOperator gcmop_ob_d2 = {dim: 6, opt: 1, par: &ed2par, me: gcmob_edipole};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_d2, ded2);
  ded2->val = sqrt(edsq);
}
double outputConstraintED2 (double val)
Definition at line 153 of file ConstraintDipole.c.
{
  return val;
}
Variable Documentation
Constraint ConstraintED2
Definition at line 28 of file ConstraintDipole.c.
Referenced by main().