FMD: fmd/ConstraintOctupole.h File Reference
fmd/ConstraintOctupole.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Constraint.h"
Functions
void calcConstraintO2 (const SlaterDet *Q, const SlaterDetAux *X, double *o2)
void calcConstraintEO2 (const SlaterDet *Q, const SlaterDetAux *X, double *o2)
void calcConstraintNO2 (const SlaterDet *Q, const SlaterDetAux *X, double *o2)
void calcgradConstraintO2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *do2)
void calcgradConstraintEO2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *do2)
void calcgradConstraintNO2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *do2)
double outputConstraintO2 (double val)
double outputConstraintEO2 (double val)
double outputConstraintNO2 (double val)
Variables
Constraint ConstraintO2
Constraint ConstraintEO2
Constraint ConstraintNO2
Detailed Description
Constrain Mass Octupole center of mass corrected by substraction of Xcm expectation value
(c) 2003 Thomas Neff
Definition in file ConstraintOctupole.h.
Function Documentation
void calcConstraintEO2 (const SlaterDet * Q, const SlaterDetAux * X, double * o2)
Definition at line 492 of file ConstraintOctupole.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, par, and SQR.
Referenced by main().
{
  double Xcm[3];
  double o[27], osq = 0.0;
  int i;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_o = {dim: 27, opt: 1, par: Xcm, me: ob_eoctupole};
  calcSlaterDetOBME(Q, X, &op_ob_o, o);
  for (i=0; i<27; i++)
    osq += SQR(o[i]);
  *o2 = sqrt(osq);
}
void calcConstraintNO2 (const SlaterDet * Q, const SlaterDetAux * X, double * o2)
Definition at line 512 of file ConstraintOctupole.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, par, and SQR.
Referenced by main().
{
  double Xcm[3];
  double o[27], osq = 0.0;
  int i;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_o = {dim: 27, opt: 1, par: Xcm, me: ob_noctupole};
  calcSlaterDetOBME(Q, X, &op_ob_o, o);
  for (i=0; i<27; i++)
    osq += SQR(o[i]);
  *o2 = sqrt(osq);
}
void calcConstraintO2 (const SlaterDet * Q, const SlaterDetAux * X, double * o2)
Definition at line 472 of file ConstraintOctupole.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, par, and SQR.
Referenced by main().
{
  double Xcm[3];
  double o[27], osq = 0.0;
  int i;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_o = {dim: 27, opt: 1, par: Xcm, me: ob_octupole};
  calcSlaterDetOBME(Q, X, &op_ob_o, o);
  for (i=0; i<27; i++)
    osq += SQR(o[i]);
  *o2 = sqrt(osq);
}
void calcgradConstraintEO2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * do2)
Definition at line 566 of file ConstraintOctupole.c.
References calcCMPosition(), calcgradCMSlaterDetOBME(), calcgradSlaterDetOBME(), calcSlaterDetOBME(), dim, octupolepara::o, par, SQR, gradSlaterDet::val, and octupolepara::Xcm.
{
  double Xcm[3];
  double o[27], osq = 0.0;
  int i;
  octupolepara o2para;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_o = {dim: 27, opt: 1, par: Xcm, me: ob_eoctupole};
  calcSlaterDetOBME(Q, X, &op_ob_o, o);
  for (i=0; i<27; i++)
    osq += SQR(o[i]);
  for (i=0; i<3; i++)
    o2para.Xcm[i] = Xcm[i];
  for (i=0; i<27; i++)
    o2para.o[i] = o[i]/sqrt(osq);
  gradOneBodyOperator gop_ob_o2 = {opt: 1, par: &o2para, me: gob_eoctupole};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_o2, do2);
  OneBodyOperator gcmop_ob_o2 = {dim: 6, opt: 1, par: &o2para, me: gcmob_octupole};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_o2, do2);
  do2->val = sqrt(osq);
}
void calcgradConstraintNO2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * do2)
Definition at line 600 of file ConstraintOctupole.c.
References calcCMPosition(), calcgradCMSlaterDetOBME(), calcgradSlaterDetOBME(), calcSlaterDetOBME(), dim, octupolepara::o, par, SQR, gradSlaterDet::val, and octupolepara::Xcm.
{
  double Xcm[3];
  double o[27], osq = 0.0;
  int i;
  octupolepara o2para;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_o = {dim: 27, opt: 1, par: Xcm, me: ob_noctupole};
  calcSlaterDetOBME(Q, X, &op_ob_o, o);
  for (i=0; i<27; i++)
    osq += SQR(o[i]);
  for (i=0; i<3; i++)
    o2para.Xcm[i] = Xcm[i];
  for (i=0; i<27; i++)
    o2para.o[i] = o[i]/sqrt(osq);
  gradOneBodyOperator gop_ob_o2 = {opt: 1, par: &o2para, me: gob_noctupole};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_o2, do2);
  OneBodyOperator gcmop_ob_o2 = {dim: 6, opt: 1, par: &o2para, me: gcmob_octupole};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_o2, do2);
  do2->val = sqrt(osq);
}
void calcgradConstraintO2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * do2)
Definition at line 532 of file ConstraintOctupole.c.
References calcCMPosition(), calcgradCMSlaterDetOBME(), calcgradSlaterDetOBME(), calcSlaterDetOBME(), dim, octupolepara::o, par, SQR, gradSlaterDet::val, and octupolepara::Xcm.
{
  double Xcm[3];
  double o[27], osq = 0.0;
  int i;
  octupolepara o2para;
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_o = {dim: 27, opt: 1, par: Xcm, me: ob_octupole};
  calcSlaterDetOBME(Q, X, &op_ob_o, o);
  for (i=0; i<27; i++)
    osq += SQR(o[i]);
  for (i=0; i<3; i++)
    o2para.Xcm[i] = Xcm[i];
  for (i=0; i<27; i++)
    o2para.o[i] = o[i]/sqrt(osq);
  gradOneBodyOperator gop_ob_o2 = {opt: 1, par: &o2para, me: gob_octupole};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_o2, do2);
  OneBodyOperator gcmop_ob_o2 = {dim: 6, opt: 1, par: &o2para, me: gcmob_octupole};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_o2, do2);
  do2->val = sqrt(osq);
}
double outputConstraintEO2 (double val)
Definition at line 641 of file ConstraintOctupole.c.
{
  return val;
}
double outputConstraintNO2 (double val)
Definition at line 647 of file ConstraintOctupole.c.
{
  return val;
}
double outputConstraintO2 (double val)
Definition at line 635 of file ConstraintOctupole.c.
{
  return val;
}
Variable Documentation
Constraint ConstraintEO2
Definition at line 37 of file ConstraintOctupole.c.
Referenced by main().
Constraint ConstraintNO2
Definition at line 45 of file ConstraintOctupole.c.
Referenced by main().
Constraint ConstraintO2
Definition at line 29 of file ConstraintOctupole.c.
Referenced by main().