FMD: fmd/Constraintl2.c File Reference
fmd/Constraintl2.c File Reference
#include <math.h>
#include <complex.h>
#include "Gaussian.h"
#include "gradGaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "CenterofMass.h"
#include "gradCMSlaterDet.h"
#include "Constraint.h"
#include "Constraintl2.h"
#include "numerics/cmath.h"
#include "misc/physics.h"
Data Structures
struct CMpara
Functions
void calcConstraintl2 (const SlaterDet *Q, const SlaterDetAux *X, double *l2)
void calcgradConstraintl2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dl2)
double outputConstraintl2 (double val)
Variables
Constraint Constraintl2
Detailed Description
Constrain expectation value of l2
(c) 2004,2007 Thomas Neff
Constrain expectation value of l2
(c) 2003 Thomas Neff
Definition in file Constraintl2.c.
Function Documentation
void calcConstraintl2 (const SlaterDet * Q, const SlaterDetAux * X, double * l2)
Definition at line 187 of file Constraintl2.c.
References calcCMPosition(), calcCMVelocity(), calcSlaterDetOBME(), dim, CMpara::Vcm, and CMpara::Xcm.
{
  CMpara para;
  calcCMPosition(Q, X, para.Xcm);
  calcCMVelocity(Q, X, para.Vcm);
  OneBodyOperator op_ob_l2 = {dim: 1, opt: 1, par: &para, me: ob_l2};
  calcSlaterDetOBME(Q, X, &op_ob_l2, l2);
}
void calcgradConstraintl2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dl2)
Definition at line 202 of file Constraintl2.c.
References calcCMPosition(), calcCMVelocity(), calcgradCMSlaterDetOBME(), calcgradSlaterDetOBME(), dim, gradSlaterDet::val, CMpara::Vcm, and CMpara::Xcm.
{
  CMpara para;
  double l2;
  calcCMPosition(Q, X, para.Xcm);
  calcCMVelocity(Q, X, para.Vcm);
  gradOneBodyOperator gop_ob_l2 = {opt: 1, par: &para, me: gob_l2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_l2, dl2);
  l2 = dl2->val;
  OneBodyOperator gcmop_ob_l2 = {dim: 6, opt: 1, par: &para, me: gcmob_l2};
  calcgradCMSlaterDetOBME(Q, X, dX, &gcmop_ob_l2, dl2);
  dl2->val = l2;
}
double outputConstraintl2 (double val)
Definition at line 226 of file Constraintl2.c.
{
  return (val);
}
Variable Documentation
Constraint Constraintl2
Initial value:
 {
  val : 0.0,
  label : "l2",
  me : calcConstraintl2,
  gradme : calcgradConstraintl2,
  output : outputConstraintl2
}
Definition at line 29 of file Constraintl2.c.