FMD: fmd/Densities.c File Reference
fmd/Densities.c File Reference
#include <complex.h>
#include <math.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "Densities.h"
#include "numerics/cmath.h"
#include "numerics/zcw.h"
Data Structures
struct densparameters
struct rdensparameters
Functions
void calcDensitiesCoordinate (const SlaterDet *Q, int v, int n, double x, double *dens)
void calcDensitiesCoordinateParity (const SlaterDet *Q, int par, int v, int n, double x, double *dens)
void calcRadialDensitiesCoordinate (const SlaterDet *Q, int izcw, int n, double r, double *dens)
void calcDensitiesMomentum (const SlaterDet *Q, int v, int n, double p, double *dens)
void calcRadialDensitiesMomentum (const SlaterDet *Q, int izcw, int n, double p, double *dens)
void calcDensitiesCoordinateHF (const SlaterDet *Q, const SlaterDetAux *X, const int v, const int n, const double x, void *mes)
void calcDensitiesMomentumHF (const SlaterDet *Q, const SlaterDetAux *X, const int v, const int n, const double x, void *mes)
Detailed Description
calculate one-body densities in coordinate and momentum space
(c) 2003 Thomas Neff
Definition in file Densities.c.
Function Documentation
void calcDensitiesCoordinate (const SlaterDet * Q, int v, int n, double x, double * dens)
Definition at line 208 of file Densities.c.
References calcSlaterDetAux(), calcSlaterDetOBME(), dim, freeSlaterDetAux(), initSlaterDetAux(), and P.
Referenced by main().
{
  SlaterDetAux X;
  initSlaterDetAux(Q, &X);
  calcSlaterDetAux(Q, &X);
  densparameters P = { normal: v, npoints: n, range: x };
  OneBodyOperator op_ob_dens = {dim: 3*n*n, opt: 1, par: &P, me: ob_densx};
  calcSlaterDetOBME(Q, &X, &op_ob_dens, dens);
  freeSlaterDetAux(&X);
}
void calcDensitiesCoordinateHF (const SlaterDet * Q, const SlaterDetAux * X, const int v, const int n, const double x, void * mes)
Definition at line 326 of file Densities.c.
References calcSlaterDetOBHFMEs(), dim, and P.
Referenced by main().
{
  densparameters P = { normal: v, npoints: n, range: x };
  OneBodyOperator op_ob_dens = {dim: 3*n*n, opt: 1, par: &P, me: ob_densx};
  calcSlaterDetOBHFMEs(Q, X, &op_ob_dens, mes);
}
void calcDensitiesCoordinateParity (const SlaterDet * Q, int par, int v, int n, double x, double * dens)
Definition at line 224 of file Densities.c.
References calcSlaterDetAuxod(), calcSlaterDetOBMEod(), copySlaterDet(), dim, freeSlaterDet(), freeSlaterDetAux(), initSlaterDet(), initSlaterDetAux(), invertSlaterDet(), k, SlaterDetAux::ovlap, and P.
Referenced by main().
{
  double nlr;
  complex double ovllr;
  complex double denslr[3*n*n];
  SlaterDet Ql, Qr;
  initSlaterDet(Q, &Ql);
  initSlaterDet(Q, &Qr);
  SlaterDetAux X;
  initSlaterDetAux(Q, &X);
  densparameters P = { normal: v, npoints: n, range: x };
  OneBodyOperator op_ob_dens = {dim: 3*n*n, opt: 1, par: &P, me: ob_densx};
  int ipl, ipr, k;
  nlr = 0;
  copySlaterDet(Q, &Ql);
  for (ipl=0; ipl<=1; ipl++) {
    if (ipl)
      invertSlaterDet(&Ql);
    copySlaterDet(Q, &Qr);
    for (ipr=0; ipr<=1; ipr++) {
      if (ipr)
        invertSlaterDet(&Qr);
      calcSlaterDetAuxod(&Ql, &Qr, &X);
      ovllr = X.ovlap;
      calcSlaterDetOBMEod(&Ql, &Qr, &X, &op_ob_dens, denslr);
      nlr += ((par == -1 && (ipl+ipr)%2) ? -1 : 1)* ovllr;
      for (k=0; k<3*n*n; k++)
        dens[k] += ((par == -1 && (ipl+ipr)%2) ? -1 : 1)* denslr[k];
    }
  }
  for (k=0; k<3*n*n; k++)
    dens[k] = dens[k]/nlr;
  freeSlaterDet(&Ql); freeSlaterDet(&Qr);
  freeSlaterDetAux(&X);
}
void calcDensitiesMomentum (const SlaterDet * Q, int v, int n, double p, double * dens)
Definition at line 294 of file Densities.c.
References calcSlaterDetAux(), calcSlaterDetOBME(), dim, freeSlaterDetAux(), initSlaterDetAux(), and P.
Referenced by main().
{
  SlaterDetAux X;
  initSlaterDetAux(Q, &X);
  calcSlaterDetAux(Q, &X);
  densparameters P = { normal: v, npoints: n, range: p };
  OneBodyOperator op_ob_dens = {dim: 3*n*n, opt: 1, par: &P, me: ob_densp};
  calcSlaterDetOBME(Q, &X, &op_ob_dens, dens);
  freeSlaterDetAux(&X);
}
void calcDensitiesMomentumHF (const SlaterDet * Q, const SlaterDetAux * X, const int v, const int n, const double x, void * mes)
Definition at line 337 of file Densities.c.
References calcSlaterDetOBHFMEs(), dim, and P.
Referenced by main().
{
  densparameters P = { normal: v, npoints: n, range: x };
  OneBodyOperator op_ob_dens = {dim: 3*n*n, opt: 1, par: &P, me: ob_densp};
  calcSlaterDetOBHFMEs(Q, X, &op_ob_dens, mes);
}
void calcRadialDensitiesCoordinate (const SlaterDet * Q, int izcw, int n, double r, double * dens)
Definition at line 278 of file Densities.c.
References calcSlaterDetAux(), calcSlaterDetOBME(), dim, freeSlaterDetAux(), initSlaterDetAux(), and P.
Referenced by main().
{
  SlaterDetAux X;
  initSlaterDetAux(Q, &X);
  calcSlaterDetAux(Q, &X);
  rdensparameters P = { izcw: izcw, npoints: n, range: r };
  OneBodyOperator op_ob_rdens = {dim: 3*n, opt: 1, par: &P, me: ob_rdensx};
  calcSlaterDetOBME(Q, &X, &op_ob_rdens, dens);
  freeSlaterDetAux(&X);
}
void calcRadialDensitiesMomentum (const SlaterDet * Q, int izcw, int n, double p, double * dens)
Definition at line 310 of file Densities.c.
References calcSlaterDetAux(), calcSlaterDetOBME(), dim, freeSlaterDetAux(), initSlaterDetAux(), and P.
{
  SlaterDetAux X;
  initSlaterDetAux(Q, &X);
  calcSlaterDetAux(Q, &X);
  rdensparameters P = { izcw: izcw, npoints: n, range: p };
  OneBodyOperator op_ob_rdens = {dim: 3*n, opt: 1, par: &P, me: ob_rdensp};
  calcSlaterDetOBME(Q, &X, &op_ob_rdens, dens);
  freeSlaterDetAux(&X);
}