FMD: fmdmpi/DiagonalDensityHOSlave.h File Reference
fmdmpi/DiagonalDensityHOSlave.h File Reference
Defines
#define _DIAGONALDENSITYHISLAVE_H
Functions
void DiagonalDensityHOSlave (void)
Detailed Description
MPI slave for calculation of Density Matrix in HO basis
(c) 2008 Thomas Neff
Definition in file DiagonalDensityHOSlave.h.
Define Documentation
#define _DIAGONALDENSITYHISLAVE_H
Definition at line 14 of file DiagonalDensityHOSlave.h.
Function Documentation
void DiagonalDensityHOSlave (void)
Definition at line 26 of file DiagonalDensityHOSlave.c.
References allocateSlaterDet(), allocateSlaterDetAux(), BroadcastA(), BroadcastParameters(), BroadcastSlaterDet(), BroadcastTask(), calcDiagonalDensityMatrixHOod(), calcSlaterDetAuxod(), copySlaterDet(), initHOBasis(), invertSlaterDet(), moveSlaterDet(), DensityMatrixHOPar::nmax, projpar, Q, Qp, Qpp, rotateSlaterDet(), TAGMEOD, TAGPROJECT6, TASKPROJECTEDDIAGONALDENSITYMATRIXHOOD, TASKSTART, and X.
Referenced by main().
{
  MPI_Status status;
  DensityMatrixHOPar DMpar;
  int A;
  SlaterDet Q, Qp, Qpp;
  SlaterDetAux X;
  complex double* dmme;
  int dimdm;
  int task;
  BroadcastTask(&task);
  if (task != TASKSTART)
    return;
  BroadcastParameters(&DMpar, sizeof(DensityMatrixHOPar));
  initHOBasis(DMpar.nmax);
  dimdm = (DMpar.nmax+1)*(DMpar.nmax+2);
  dmme = malloc(2*dimdm*sizeof(complex double));
  BroadcastA(&A);
  allocateSlaterDet(&Q, A);
  allocateSlaterDet(&Qp, A);
  allocateSlaterDet(&Qpp, A);
  allocateSlaterDetAux(&X, A);
  while (1) {
    BroadcastTask(&task);
    if (task != TASKPROJECTEDDIAGONALDENSITYMATRIXHOOD)
      return;
    double projpar[6];
    double *angle, *R;
    BroadcastSlaterDet(&Q);
    BroadcastSlaterDet(&Qp);
    while (1) {
      MPI_Recv(projpar, 6, MPI_DOUBLE, 0, TAGPROJECT6, MPI_COMM_WORLD, &status);
      if (projpar[0] < 0.0)
        break;
      angle = &projpar[0];
      R = &projpar[3];
      copySlaterDet(&Qp, &Qpp);
      moveSlaterDet(&Qpp, R);
      rotateSlaterDet(&Qpp, angle[0], angle[1], angle[2]);
      calcSlaterDetAuxod(&Q, &Qpp, &X);
      calcDiagonalDensityMatrixHOod(&DMpar, &Q, &Qpp, &X, &dmme[0]);
      invertSlaterDet(&Qpp);
      calcSlaterDetAuxod(&Q, &Qpp, &X);
      calcDiagonalDensityMatrixHOod(&DMpar, &Q, &Qpp, &X, &dmme[dimdm]);
      MPI_Send(dmme, 2*dimdm*sizeof(complex double), MPI_BYTE,
               0, TAGMEOD, MPI_COMM_WORLD);
    }
  }
}