FMD: fmd/DiClusterProjSlaterDet.h File Reference
fmd/DiClusterProjSlaterDet.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "SlaterDet.h"
#include "Symmetry.h"
#include "MultiSlaterDet.h"
Functions
Symmetry DiClusterProjSlaterDetSymmetry (const MultiSlaterDet *MSD, int iM)
complex double DiClusterProjSlaterDetWeight (const MultiSlaterDet *MSD, int iM, int i)
void DiClusterProjSlaterDetGet (const MultiSlaterDet *MSD, int i, SlaterDet *Q)
int DiClusterProjSlaterDetRead (FILE *fp, MultiSlaterDet *MSD)
Variables
MultiSlaterDet DiClusterProjSlaterDet
Detailed Description
implement Di-Cluster SlaterDet as MultiSlaterDet
(c) 2005
Definition in file DiClusterProjSlaterDet.h.
Function Documentation
void DiClusterProjSlaterDetGet (const MultiSlaterDet * MSD, int i, SlaterDet * Q)
Definition at line 116 of file DiClusterProjParSlaterDet.c.
References _MSD_::A, allocateSlaterDet(), alpha, copySlaterDet(), DiClusterProjSlaterDetInternals::d, getangles3(), _MSD_::internals, invertSlaterDet(), DiClusterProjSlaterDetInternals::izcw, joinintoSlaterDets(), mneutron, moveSlaterDet(), mproton, SlaterDet::N, DiClusterProjSlaterDetInternals::Qa, DiClusterProjSlaterDetInternals::Qb, rotateSlaterDet(), and SlaterDet::Z.
{
  // initialize workspace
  if (!tmpQa) {
    tmpQa = malloc(sizeof(SlaterDet));
    tmpQb = malloc(sizeof(SlaterDet));
    allocateSlaterDet(tmpQa, MSD->A);
    allocateSlaterDet(tmpQb, MSD->A);
  }
  DiClusterProjSlaterDetInternals* internals = MSD->internals;
  int izcw = internals->izcw;
  double alpha,beta,gamma;
  getangles3(izcw, i, &alpha, &beta, &gamma);
  copySlaterDet(internals->Qa, tmpQa);
  copySlaterDet(internals->Qb, tmpQb);
  double massa = tmpQa->Z*mproton + tmpQa->N*mneutron;
  double massb = tmpQb->Z*mproton + tmpQb->N*mneutron;
  double mass = massa + massb;
  double xa[3] = {0,0,0};
  double xb[3] = {0,0,0};
  xa[2] = massb/mass* internals->d;
  xb[2] = -massa/mass* internals->d;
  moveSlaterDet(tmpQa, xa);
  rotateSlaterDet(tmpQb, alpha, beta, gamma);
  moveSlaterDet(tmpQb, xb);
  joinintoSlaterDets(tmpQa, tmpQb, Q);
}
int DiClusterProjSlaterDetRead (FILE * fp, MultiSlaterDet * MSD)
Definition at line 155 of file DiClusterProjParSlaterDet.c.
References SlaterDet::A, _MSD_::A, BUFSIZE, cloneSlaterDet(), DiClusterProjSlaterDetInternals::d, _MSD_::internals, DiClusterProjSlaterDetInternals::izcw, DiClusterProjSlaterDetInternals::Jb, DiClusterProjSlaterDetInternals::Kb, DiClusterProjSlaterDetInternals::Ma, DiClusterProjSlaterDetInternals::Mb, md5hash(), _MSD_::n, _MSD_::N, N, DiClusterProjSlaterDetInternals::nangles, nangles, nangles3(), DiClusterProjSlaterDetInternals::Pib, DiClusterProjSlaterDetInternals::Qa, DiClusterProjSlaterDetInternals::Qb, and readSlaterDetfromFile().
Referenced by readMultiSlaterDetfromFile().
{
  *MSD = DiClusterProjSlaterDet;
  double d;
  int izcw;
  int N;
  SlaterDet Qa, Qb;
  char fnamea[255], fnameb[255];
  char md5hasha[255], md5hashb[255];
  int Ma;
  char buf[BUFSIZE];
  fgets(buf, BUFSIZE, fp);
  sscanf(buf, "<DiClusterProjSlaterDet d=%lf izcw=%d N=%d>", &d, &izcw, &N);
  int nangles=nangles3(izcw);
  int Jb[N];
  int Mb[N];
  int Kb[N];
  int Pib[N];
  int i;
  for (i=0; i<N; i++) {
    fgets(buf, BUFSIZE, fp);
    sscanf(buf, "<Projection %d %d %d %d>", &Jb[i], &Mb[i], &Kb[i], &Pib[i]);
  }
  fgets(buf, BUFSIZE, fp);
  sscanf(buf, "<Cluster %s %s %d>", fnamea, md5hasha, &Ma);
  fgets(buf, BUFSIZE, fp);
  sscanf(buf, "<Cluster %s %s>", fnameb, md5hashb);
  if (strncmp(md5hasha, md5hash(fnamea), 32)) {
    fprintf(stderr, "...  SlaterDetFile does not match with existing hash\n");
    return -1;
  }
  if (strncmp(md5hashb, md5hash(fnameb), 32)) {
    fprintf(stderr, "...  SlaterDetFile does not match with existing hash\n");
    return -1;
  }
  if (readSlaterDetfromFile(&Qa, fnamea)) {
    fprintf(stderr, "... couldn't open %s for reading\n", fnamea);
    return -1;
  }
  if (readSlaterDetfromFile(&Qb, fnameb)) {
    fprintf(stderr, "... couldn't open %s for reading\n", fnameb);
    return -1;
  }
  DiClusterProjSlaterDetInternals* internals =
    malloc(sizeof(DiClusterProjSlaterDetInternals));
  internals->Qa = malloc(sizeof(SlaterDet));
  cloneSlaterDet(&Qa, internals->Qa);
  internals->Qb = malloc(sizeof(SlaterDet));
  cloneSlaterDet(&Qb, internals->Qb);
  internals->d = d;
  internals->Ma = Ma;
  internals->Jb = malloc(N*sizeof(int));
  internals->Mb = malloc(N*sizeof(int));
  internals->Kb = malloc(N*sizeof(int));
  internals->Pib = malloc(N*sizeof(int));
  for (i=0; i<N; i++) {
    internals->Jb[i] = Jb[i];
    internals->Mb[i] = Mb[i];
    internals->Kb[i] = Kb[i];
    internals->Pib[i] = Pib[i];
  }
  internals->izcw = izcw;
  internals->nangles = nangles;
  MSD->A = Qa.A + Qb.A;
  MSD->N = N;
  MSD->n = nangles;
  MSD->internals = internals;
  return 0;
}
Symmetry DiClusterProjSlaterDetSymmetry (const MultiSlaterDet * MSD, int iM)
Definition at line 58 of file DiClusterProjParSlaterDet.c.
References axial0, _MSD_::internals, DiClusterProjSlaterDetInternals::Ma, and DiClusterProjSlaterDetInternals::Mb.
{
  DiClusterProjSlaterDetInternals* internals = MSD->internals;
  Symmetry S=0;
  setSymmetry(&S, axial0 + internals->Ma + internals->Mb[iM]);
  return S;
}
complex double DiClusterProjSlaterDetWeight (const MultiSlaterDet * MSD, int iM, int i)
Definition at line 69 of file DiClusterProjParSlaterDet.c.
References alpha, getangles3(), _MSD_::internals, DiClusterProjSlaterDetInternals::izcw, DiClusterProjSlaterDetInternals::Jb, DiClusterProjSlaterDetInternals::Kb, DiClusterProjSlaterDetInternals::Mb, DiClusterProjSlaterDetInternals::nangles, nangles, and DiClusterProjSlaterDetInternals::Pib.
{
  DiClusterProjSlaterDetInternals* internals = MSD->internals;
  int izcw = internals->izcw;
  int nangles = internals->nangles;
  int J, M, K;
  J = internals->Jb[iM];
  M = internals->Mb[iM];
  K = internals->Kb[iM];
  double alpha,beta,gamma;
  getangles3(izcw, i, &alpha, &beta, &gamma);
  return 1.0/nangles* (J+1)* Djmkstar(J,M,K,alpha,beta,gamma);
}
Variable Documentation
MultiSlaterDet DiClusterProjSlaterDet
Definition at line 46 of file DiClusterProjParSlaterDet.c.