FMD: fmd/DiClusterMulticonfig.h File Reference
fmd/DiClusterMulticonfig.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "SlaterDet.h"
#include "Symmetry.h"
#include "MultiSlaterDet.h"
Functions
Symmetry DiClusterMulticonfigSymmetry (const MultiSlaterDet *MSD, int iM)
complex double DiClusterMulticonfigWeight (const MultiSlaterDet *MSD, int iM, int i)
void DiClusterMulticonfigGet (const MultiSlaterDet *MSD, int i, SlaterDet *Q)
int DiClusterMulticonfigRead (FILE *fp, MultiSlaterDet *MSD)
Variables
MultiSlaterDet DiClusterMulticonfig
Detailed Description
set of MultiSlaterDet built out of two Clusters
each cluster is a multiconfig state projected on a set of (J, Jz) values
(c) 2009 Thomas Neff
Definition in file DiClusterMulticonfig.h.
Function Documentation
void DiClusterMulticonfigGet (const MultiSlaterDet * MSD, int i, SlaterDet * Q)
Definition at line 182 of file DiClusterMulticonfig.c.
References _MSD_::A, allocateSlaterDet(), DiClusterMulticonfigInternals::alphaa, DiClusterMulticonfigInternals::alphab, DiClusterMulticonfigInternals::betaa, DiClusterMulticonfigInternals::betab, copySlaterDet(), DiClusterMulticonfigInternals::d, DiClusterMulticonfigInternals::gammaa, DiClusterMulticonfigInternals::gammab, _MSD_::internals, invertSlaterDet(), joinintoSlaterDets(), mneutron, moveSlaterDet(), mproton, SlaterDet::N, DiClusterMulticonfigInternals::na, DiClusterMulticonfigInternals::nanga, DiClusterMulticonfigInternals::nangb, DiClusterMulticonfigInternals::npia, DiClusterMulticonfigInternals::npib, DiClusterMulticonfigInternals::Qa, DiClusterMulticonfigInternals::Qb, rotateSlaterDet(), and SlaterDet::Z.
{
  // initialize workspace
  if (!tmpQa) {
    tmpQa = malloc(sizeof(SlaterDet));
    tmpQb = malloc(sizeof(SlaterDet));
    allocateSlaterDet(tmpQa, MSD->A);
    allocateSlaterDet(tmpQb, MSD->A);
  }
  DiClusterMulticonfigInternals* internals = MSD->internals;
  int npia = internals->npia;
  int nanglespa = internals->nanga*npia;
  int npib = internals->npib;
  int nanglespb = internals->nangb*npib;
  int ia = i % (nanglespa*internals->na);
  int ib = i / (nanglespa*internals->na);
  // fprintf(stderr, "get: i=%d, na=%d, nb=%d, nanglespa=%d, nanglespb=%d, ia=%d, ib=%d\n",     i, internals->na, internals->nb, nanglespa, nanglespb, ia, ib);
  double alphaa, betaa, gammaa;
  alphaa = internals->alphaa[(ia % nanglespa)/npia];
  betaa = internals->betaa[(ia % nanglespa)/npia];
  gammaa = internals->gammaa[(ia % nanglespa)/npia];
  double alphab, betab, gammab;
  alphab = internals->alphab[(ib % nanglespb)/npib];
  betab = internals->betab[(ib % nanglespb)/npib];
  gammab = internals->gammab[(ib % nanglespb)/npib];
  // fprintf(stderr, "tmpQa->A : %d\n", tmpQa->A);
  // fprintf(stderr, "Qa[%d].A : %d\n", ia/nanglespa, internals->Qa[ia/nanglespa].A);
  // fprintf(stderr, "tmpQb->A: %d\n", tmpQb->A);
  // fprintf(stderr, "Qb[%d].A : %d\n", ib/nanglespb, internals->Qb[ib/nanglespb].A);
  copySlaterDet(&internals->Qa[ia/nanglespa], tmpQa);
  copySlaterDet(&internals->Qb[ib/nanglespb], tmpQb);
  double massa = tmpQa->Z*mproton + tmpQa->N*mneutron;
  double massb = tmpQb->Z*mproton + tmpQb->N*mneutron;
  double mass = massa + massb;
  double xa[3] = {0,0,0};
  double xb[3] = {0,0,0};
  xa[2] = massb/mass* internals->d;
  xb[2] = -massa/mass* internals->d;
  rotateSlaterDet(tmpQa, alphaa, betaa, gammaa);
  if (npia==2 && ia%2)
    invertSlaterDet(tmpQa);
  moveSlaterDet(tmpQa, xa);
  rotateSlaterDet(tmpQb, alphab, betab, gammab);
  if (npib==2 && ib%2)
    invertSlaterDet(tmpQb);
  moveSlaterDet(tmpQb, xb);
  joinintoSlaterDets(tmpQa, tmpQb, Q);
}
int DiClusterMulticonfigRead (FILE * fp, MultiSlaterDet * MSD)
Definition at line 362 of file DiClusterMulticonfig.c.
References SlaterDet::A, _MSD_::A, DiClusterMulticonfigInternals::alphaa, DiClusterMulticonfigInternals::alphab, DiClusterMulticonfigInternals::betaa, DiClusterMulticonfigInternals::betab, BUFSIZE, CLMAX, cloneSlaterDet(), DiClusterMulticonfigInternals::d, DiClusterMulticonfigInternals::gammaa, DiClusterMulticonfigInternals::gammab, _MSD_::internals, DiClusterMulticonfigInternals::Ja, DiClusterMulticonfigInternals::Jb, JMAX, DiClusterMulticonfigInternals::Ma, DiClusterMulticonfigInternals::Mb, md5hash(), _MSD_::n, _MSD_::N, DiClusterMulticonfigInternals::Na, DiClusterMulticonfigInternals::na, DiClusterMulticonfigInternals::nanga, DiClusterMulticonfigInternals::nangb, DiClusterMulticonfigInternals::Nb, DiClusterMulticonfigInternals::nb, DiClusterMulticonfigInternals::npia, DiClusterMulticonfigInternals::npib, DiClusterMulticonfigInternals::Pia, DiClusterMulticonfigInternals::Pib, DiClusterMulticonfigInternals::Qa, DiClusterMulticonfigInternals::Qb, readSlaterDetfromFile(), DiClusterMulticonfigInternals::wa, DiClusterMulticonfigInternals::wb, DiClusterMulticonfigInternals::weighta, and DiClusterMulticonfigInternals::weightb.
Referenced by readMultiSlaterDetfromFile().
{
  *MSD = DiClusterMulticonfig;
  DiClusterMulticonfigInternals* internals =
    malloc(sizeof(DiClusterMulticonfigInternals));
  SlaterDet Qa, Qb;
  char fnamea[255], fnameb[255];
  char md5hasha[255], md5hashb[255];
  double d;
  int na, nb;
  char anga[15], angb[15];
  int npia, npib;
  int Na, Nb;
  char buf[BUFSIZE];
  fgets(buf, BUFSIZE, fp);
  sscanf(buf, "<DiClusterMulticonfig d=%lf na=%d anga=%s npia=%d Na=%d nb=%d angb=%s npib=%d Nb=%d>",
         &d, &na, anga, &npia, &Na, &nb, angb, &npib, &Nb);
  internals->d = d;
  internals->na = na;
  internals->npia = npia;
  internals->Na = Na;
  internals->nb = nb;
  internals->npib = npib;
  internals->Nb = Nb;
  // decode angular projection parameters
  initangles(anga, &internals->nanga,
             &internals->alphaa, &internals->betaa, &internals->gammaa, &internals->weighta);
  initangles(angb, &internals->nangb,
             &internals->alphab, &internals->betab, &internals->gammab, &internals->weightb);
  {
    int i;
    fprintf(stderr, "Angles Cluster A:\n");
    for (i=0; i<internals->nanga; i++)
      fprintf(stderr, "(alpha, beta, gamma): weight = (%8.3f, %8.3f, %8.3f): %8.5f\n",
              internals->alphaa[i], internals->betaa[i], internals->gammaa[i],
              internals->weighta[i]);
    fprintf(stderr, "Angles Cluster B:\n");
    for (i=0; i<internals->nangb; i++)
      fprintf(stderr, "(alpha, beta, gamma): weight = (%8.3f, %8.3f, %8.3f): %8.5f\n",
              internals->alphab[i], internals->betab[i], internals->gammab[i],
              internals->weightb[i]);
  }
  // Slater dets for Cluster a
  internals->Qa = malloc(na*sizeof(SlaterDet));
  int ia;
  for (ia=0; ia<na; ia++) {
    fgets(buf, BUFSIZE, fp);
    sscanf(buf, "<Cluster %s %s>", fnamea, md5hasha);
    if (strncmp(md5hasha, md5hash(fnamea), 32)) {
      fprintf(stderr, "...  SlaterDetFile does not match with existing hash\n");
      return -1;
    }
    if (readSlaterDetfromFile(&Qa, fnamea)) {
      fprintf(stderr, "... couldn't open %s for reading\n", fnamea);
      return -1;
    }
    cloneSlaterDet(&Qa, &internals->Qa[ia]);
  }
  internals->Ja = malloc(Na*sizeof(int));
  internals->Ma = malloc(Na*sizeof(int));
  internals->Pia = malloc(Na*sizeof(int));
  internals->wa = malloc(Na*CLMAX*(JMAX+1)*sizeof(complex double));
  int Ja;
  int Ma;
  int Pia;
  char ca[BUFSIZE];
  int Ia;
  for (Ia=0; Ia<Na; Ia++) {
    fgets(buf, BUFSIZE, fp);
    sscanf(buf, "<Projection %d %d %d %[() ,.0-9eE+-]>", &Ja, &Ma, &Pia, ca);
    // fprintf(stderr, "Ja: %d, Ma: %d, Pia: %d, coefficients: %s\n",
    //      Ja, Ma, Pia, ca);
    internals->Ja[Ia] = Ja;
    internals->Ma[Ia] = Ma;
    internals->Pia[Ia] = Pia;
    sreadcvec(ca, na*(Ja+1), internals->wa[Ia]);
  }
  // Slater dets for Cluster b
  internals->Qb = malloc(nb*sizeof(SlaterDet));
  int ib;
  for (ib=0; ib<nb; ib++) {
    fgets(buf, BUFSIZE, fp);
    sscanf(buf, "<Cluster %s %s>", fnameb, md5hashb);
    if (strncmp(md5hashb, md5hash(fnameb), 32)) {
      fprintf(stderr, "...  SlaterDetFile does not match with existing hash\n");
      return -1;
    }
    if (readSlaterDetfromFile(&Qb, fnameb)) {
      fprintf(stderr, "... couldn't open %s for reading\n", fnameb);
      return -1;
    }
    cloneSlaterDet(&Qb, &internals->Qb[ib]);
  }
  internals->Jb = malloc(Nb*sizeof(int));
  internals->Mb = malloc(Nb*sizeof(int));
  internals->Pib = malloc(Nb*sizeof(int));
  internals->wb = malloc(Nb*CLMAX*(JMAX+1)*sizeof(complex double));
  int Jb;
  int Mb;
  int Pib;
  char cb[BUFSIZE];
  int Ib;
  for (Ib=0; Ib<Nb; Ib++) {
    fgets(buf, BUFSIZE, fp);
    sscanf(buf, "<Projection %d %d %d %[() ,.0-9eE+-]>", &Jb, &Mb, &Pib, cb);
    internals->Jb[Ib] = Jb;
    internals->Mb[Ib] = Mb;
    internals->Pib[Ib] = Pib;
    sreadcvec(cb, nb*(Jb+1), internals->wb[Ib]);
  }
  MSD->A = internals->Qa[0].A + internals->Qb[0].A;
  MSD->N = Na*Nb;
  MSD->n = na*npia*internals->nanga*nb*npib*internals->nangb;
  MSD->internals = internals;
  fprintf(stderr, "N: %d, n: %d\n", MSD->N, MSD->n);
  return 0;
}
Symmetry DiClusterMulticonfigSymmetry (const MultiSlaterDet * MSD, int iM)
Definition at line 78 of file DiClusterMulticonfig.c.
References axial0, _MSD_::internals, DiClusterMulticonfigInternals::Ma, DiClusterMulticonfigInternals::Mb, and DiClusterMulticonfigInternals::Na.
{
  DiClusterMulticonfigInternals* internals = MSD->internals;
  int iMa = iM % internals->Na;
  int iMb = iM / internals->Na;
  Symmetry S=0;
  setSymmetry(&S, axial0 + internals->Ma[iMa] + internals->Mb[iMb]);
  return S;
}
complex double DiClusterMulticonfigWeight (const MultiSlaterDet * MSD, int iM, int i)
Definition at line 91 of file DiClusterMulticonfig.c.
References DiClusterMulticonfigInternals::alphaa, DiClusterMulticonfigInternals::alphab, DiClusterMulticonfigInternals::betaa, DiClusterMulticonfigInternals::betab, DiClusterMulticonfigInternals::gammaa, DiClusterMulticonfigInternals::gammab, _MSD_::internals, DiClusterMulticonfigInternals::Ja, DiClusterMulticonfigInternals::Jb, DiClusterMulticonfigInternals::Ma, DiClusterMulticonfigInternals::Mb, DiClusterMulticonfigInternals::na, DiClusterMulticonfigInternals::Na, DiClusterMulticonfigInternals::nanga, DiClusterMulticonfigInternals::nangb, DiClusterMulticonfigInternals::npia, DiClusterMulticonfigInternals::npib, DiClusterMulticonfigInternals::Pia, DiClusterMulticonfigInternals::Pib, DiClusterMulticonfigInternals::wa, DiClusterMulticonfigInternals::wb, DiClusterMulticonfigInternals::weighta, and DiClusterMulticonfigInternals::weightb.
{
  DiClusterMulticonfigInternals* internals = MSD->internals;
  int iMa = iM % internals->Na;
  int iMb = iM / internals->Na;
  int npia = internals->npia;
  int nanglespa = internals->nanga*npia;
  int npib = internals->npib;
  int nanglespb = internals->nangb*npib;
  int Ja, Ma, Pia;
  Ja = internals->Ja[iMa];
  Ma = internals->Ma[iMa];
  Pia = internals->Pia[iMa];
  int Jb, Mb, Pib;
  Jb = internals->Jb[iMb];
  Mb = internals->Mb[iMb];
  Pib = internals->Pib[iMb];
  int ia = i % (nanglespa*internals->na);
  int ib = i / (nanglespa*internals->na);
  int iangpa = ia % nanglespa;
  int iangpb = ib % nanglespb;
  double alphaa, betaa, gammaa, weighta;
  alphaa = internals->alphaa[iangpa/npia];
  betaa = internals->betaa[iangpa/npia];
  gammaa = internals->gammaa[iangpa/npia];
  weighta = internals->weighta[iangpa/npia];
  // fprintf(stderr, "i: %d, iangpa: %d, alphaa: %5.2f, betaa: %5.2f, gammaa: %5.2f\n",
  //     i, iangpa, alphaa, betaa, gammaa);
  double alphab, betab, gammab, weightb;
  alphab = internals->alphab[iangpb/npib];
  betab = internals->betab[iangpb/npib];
  gammab = internals->gammab[iangpb/npib];
  weightb = internals->weightb[iangpb/npib];
  //  fprintf(stderr, "i: %d, iangpb: %d, alphab: %5.2f, betab: %5.2f, gammab: %5.2f\n",
  //      i, iangpb, alphab, betab, gammab);
  complex double ca = 0.0;
  int Ka;
  for (Ka=-Ja; Ka<=Ja; Ka=Ka+2)
    ca += 1.0/npia* (npia==2 && Pia==-1 && ia%2 ? -1.0 : 1.0)* weighta* (Ja+1)/(8*M_PI*M_PI)* Djmkstar(Ja,Ma,Ka,alphaa,betaa,gammaa)*internals->wa[iMa][idxjm(Ja,Ka)+ia/nanglespa*(Ja+1)];
  complex double cb = 0.0;
  int Kb;
  for (Kb=-Jb; Kb<=Jb; Kb=Kb+2)
    cb += 1.0/npib* (npib==2 && Pib==-1 && ib%2 ? -1.0 : 1.0)* weightb* (Jb+1)/(8*M_PI*M_PI)* Djmkstar(Jb,Mb,Kb,alphab,betab,gammab)*internals->wb[iMb][idxjm(Jb,Kb)+ib/nanglespb*(Jb+1)];
  //fprintf(stderr, "Ja: %d, Ma: %d, ca: (%8.3f, %8.3f), Jb: %d, Mb: %d, cb: (%8.3f, %8.3f)\n",
  //        Ja, Ma, creal(ca), cimag(ca), Jb, Mb, creal(cb), cimag(cb));
  return ca*cb;
}
Variable Documentation
MultiSlaterDet DiClusterMulticonfig
Definition at line 66 of file DiClusterMulticonfig.c.