FMD: numerics/donlp2.h File Reference
numerics/donlp2.h File Reference
#include "fortranc.h"
Defines
#define NX 1200
#define NRESM 100
#define MAXIT 10000
#define NSTEP 40
Functions
struct {
double x [NX]
double x0 [NX]
double x1 [NX]
double xmin [NX]
} FORTRAN (o8xdat)
struct {
double xst [NX]
} FORTRAN (o8stv)
struct {
int nreset
int numsm
} FORTRAN (o8rst)
struct {
int n
int nh
int ng
int nr
int nres
} FORTRAN (o8dim)
struct {
int val [NRESM+1]
int gconst [NRESM+1]
int gunit [NRESM+1][3]
int LLOW [NX]
int LUP [NX]
} FORTRAN (o8gri)
struct {
double del0
double del01
double del
double delmin
double tau0
double tau
double smalld
double smallw
double rho
double rho1
double eta
double ny
double epsx
double epshi
double c1d
double scfmax
double tauqp
double taufac
double taumax
double updmy0
int iterma
int ifill1
} FORTRAN (o8par)
struct {
int intakt
int inx
int std
int te0
int te1
int te2
int te3
int singul
int ident
int eqres
int silent
int analyt
int cold
} FORTRAN (o8stpa)
struct {
int icf
int icgf
int cfincr
int cres [NRESM]
int cgres [NRESM]
} FORTRAN (o8cnt)
struct {
float optite
int itstep
int phase
float runtim
double accinf [32][MAXIT+1]
} FORTRAN (o8itin)
struct {
int ffuerr
int cfuerr [NRESM]
} FORTRAN (o8err)
void FORTRAN() donlp2 (void)
void FORTRAN() ef (const double *x, double *fx)
void FORTRAN() egradf (const double *x, double *gradf)
void FORTRAN() eg (int *i, const double *x, double *gxi)
void FORTRAN() egradg (int *i, const double *x, double *gradgi)
void FORTRAN() eh (int *i, const double *x, double *hxi)
void FORTRAN() egradh (int *i, const double *x, double *gradhi)
void FORTRAN() setup0 (void)
void FORTRAN() setup (void)
Define Documentation
#define MAXIT 10000
Definition at line 25 of file donlp2.h.
#define NRESM 100
Definition at line 24 of file donlp2.h.
#define NSTEP 40
Definition at line 26 of file donlp2.h.
#define NX 1200
Definition at line 23 of file donlp2.h.
Function Documentation
void FORTRAN() donlp2 (void)
Referenced by MinimizeDONLP2(), MinimizeDONLP2multivapp(), MinimizeDONLP2orthogonalvapp(), MinimizeDONLP2orthproj(), MinimizeDONLP2p(), MinimizeDONLP2par(), MinimizeDONLP2proj(), MinimizeDONLP2vap(), MinimizeDONLP2vapp(), and MinimizeDONLP2vappiso().
void FORTRAN() ef (const double * x, double * fx)
Definition at line 131 of file MinimizerDONLP2.c.
References calcHamiltonian(), calcHamiltonianmpi(), calcHamiltonianod(), calcHamiltonianodmpi(), calcorthprojectedHamiltonian(), calcprojectedHamiltonian(), calcSlaterDetAux(), calcSlaterDetAuxod(), copySlaterDet(), env, FORTRAN, hbc, invertSlaterDet(), moveboostSlaterDet(), sigterminate, and x.
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAux(Min.Q, Min.X);
#ifdef MPI
  calcHamiltonianmpi(Min.Int, Min.Q, Min.X, fx);
#else
  calcHamiltonian(Min.Int, Min.Q, Min.X, fx);
#endif
  FORTRAN(o8cnt).icf++;
  // fprintf(stderr, "ef:     \tE = %8.3f MeV\n", hbc*(*fx));
}
void FORTRAN() eg (int * i, const double * x, double * gxi)
Definition at line 192 of file MinimizerDONLP2.c.
References AMIN, APOS, MINIMUMA, NGAUSS, and x.
{
  if (!strcmp(Min.P->name, "FMD")) {
    *gxi = x[(*i-1)*NGAUSS+APOS];
  }
}
void FORTRAN() egradf (const double * x, double * gradf)
Definition at line 150 of file MinimizerDONLP2.c.
References addmulttogradSlaterDet(), calcgradHamiltonian(), calcgradHamiltonianmpi(), calcgradHamiltonianod(), calcgradHamiltonianodmpi(), calcgradorthprojectedHamiltonian(), calcgradOvlapod(), calcgradprojectedHamiltonian(), calcgradSlaterDetAux(), calcgradSlaterDetAuxod(), calcSlaterDetAux(), calcSlaterDetAuxod(), copySlaterDet(), env, FORTRAN, fprintinfo(), hbc, icgf, invertSlaterDet(), moveboostSlaterDet(), N, sigterminate, writeSlaterDet(), x, and zerogradSlaterDet().
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAux(Min.Q, Min.X);
  calcgradSlaterDetAux(Min.Q, Min.X, Min.dX);
#ifdef MPI
  calcgradHamiltonianmpi(Min.Int, Min.Q, Min.X, Min.dX, Min.dH);
#else
  calcgradHamiltonian(Min.Int, Min.Q, Min.X, Min.dX, Min.dH);
#endif
  Min.P->ParaprojectgradSlaterDet(Min.q, Min.dH, gradf);
  FORTRAN(o8cnt).icgf++;
  fprintf(stderr, "step %3d: \tE = %8.3f MeV\n",
          FORTRAN(o8cnt).icgf, hbc*creal(Min.dH->val));
  if (Min.log && !(FORTRAN(o8cnt).icgf % Min.log)) {
    char logfname[255];
    sprintf(logfname, "%s.min.%03d.log", Min.logfile, FORTRAN(o8cnt).icgf);
    FILE* logfp;
    if (!(logfp = fopen(logfname, "w"))) {
      fprintf(stderr, "couldn't open %s for writing\n", logfname);
    } else {
      fprintinfo(logfp);
      fprintf(logfp, "# step %3d: \tE = %8.3f MeV\n",
              FORTRAN(o8cnt).icgf, hbc*creal(Min.dH->val));
      fprintf(logfp, "\n# Parameterization\n");
      fprintf(logfp, "<Parameterization %s>\n", Min.P->name);
      Min.P->Parawrite(logfp, Min.q);
      fprintf(logfp, "\n# SlaterDet\n");
      writeSlaterDet(logfp, Min.Q);
      fclose(logfp);
    }
  }
}
void FORTRAN() egradg (int * i, const double * x, double * gradgi)
Definition at line 200 of file MinimizerDONLP2.c.
{
}
void FORTRAN() egradh (int * i, const double * x, double * gradhi)
Definition at line 224 of file MinimizerDONLP2.c.
References addmulttogradSlaterDet(), calcgradOvlapod(), calcgradSlaterDetAux(), calcgradSlaterDetAuxod(), calcSlaterDetAux(), calcSlaterDetAuxod(), ConstraintCM, copySlaterDet(), Constraintod::dim, env, Constraintod::gradme, Constraint::gradme, Constraintod::gradneedsme, invertSlaterDet(), j, Constraintod::label, Constraint::label, Constraintod::me, moveboostSlaterDet(), N, Constraintod::output, Constraint::output, sigterminate, x, and zerogradSlaterDet().
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAux(Min.Q, Min.X);
  calcgradSlaterDetAux(Min.Q, Min.X, Min.dX);
  zerogradSlaterDet(Min.dH);
  Min.Const[*i-1].gradme(Min.Q, Min.X, Min.dX, Min.dH);
  Min.P->ParaprojectgradSlaterDet(Min.q, Min.dH, gradhi);
  fprintf(stderr, "\t\t\tgrad %4s = %8.3f\n",
          Min.Const[*i-1].label, Min.Const[*i-1].output(Min.dH->val));
}
void FORTRAN() eh (int * i, const double * x, double * hxi)
Definition at line 205 of file MinimizerDONLP2.c.
References calcSlaterDetAux(), calcSlaterDetAuxod(), ConstraintCM, copySlaterDet(), Constraintod::dim, env, invertSlaterDet(), j, Constraintod::me, Constraint::me, moveboostSlaterDet(), sigterminate, SQR, Constraintod::val, and x.
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAux(Min.Q, Min.X);
  Min.Const[*i-1].me(Min.Q, Min.X, hxi);
  fprintf(stderr, "\t\t\tme   %4s = %8.3f\n",
          Min.Const[*i-1].label, Min.Const[*i-1].output(*hxi));
  *hxi -= Min.Const[*i-1].val;
}
struct @38 FORTRAN (o8rst)
struct @42 FORTRAN (o8stpa)
struct @40 FORTRAN (o8gri)
struct @45 FORTRAN (o8err)
struct @36 FORTRAN (o8xdat)
struct @44 FORTRAN (o8itin)
struct @39 FORTRAN (o8dim)
struct @41 FORTRAN (o8par)
struct @37 FORTRAN (o8stv)
struct @43 FORTRAN (o8cnt)
void FORTRAN() setup (void)
Definition at line 278 of file MinimizerDONLP2.c.
References FORTRAN.
{
  FORTRAN(o8stpa).te0 = 0;
  FORTRAN(o8stpa).te1 = 0;
  FORTRAN(o8par).iterma = Min.maxsteps-1;
}
void FORTRAN() setup0 (void)
Definition at line 242 of file MinimizerDONLP2.c.
References APOS, FORTRAN, and NGAUSS.
{
  int i;
  FORTRAN(o8dim).n = Min.q->n;
  FORTRAN(o8dim).nh = Min.nconst;
  // in case of FMD parametrization use bound constraints for Re{a}
  if (!strcmp(Min.P->name, "FMD")) {
    FORTRAN(o8dim).ng = Min.q->ngauss;
    for (i=0; i<Min.nconst+1; i++) {
      FORTRAN(o8gri).gunit[i][0] = -1;
      FORTRAN(o8gri).gunit[i][1] = 0;
      FORTRAN(o8gri).gunit[i][2] = 0;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      FORTRAN(o8gri).gunit[i+Min.nconst+1][0] = 1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][1] = i*NGAUSS+APOS+1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][2] = 1;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      if (Min.q->x[i*NGAUSS+APOS] < 0)
        Min.q->x[i*NGAUSS+APOS] = 1.0+1.0*rand()/RAND_MAX;
    }
  } else
    FORTRAN(o8dim).ng = 0;
  FORTRAN(o8stpa).analyt = 1;
  FORTRAN(o8stpa).cold = 1;
  FORTRAN(o8par).tau0 = 10.0;  // 20.0
  FORTRAN(o8par).del0 = 0.0;
  FORTRAN(o8stpa).silent = 1;
  for (i=0; i<Min.q->n; i++)
    FORTRAN(o8xdat).x[i] = Min.q->x[i];
}
Variable Documentation
double accinf
Definition at line 119 of file donlp2.h.
int analyt
Definition at line 102 of file donlp2.h.
double c1d
Definition at line 79 of file donlp2.h.
int cfincr
Definition at line 109 of file donlp2.h.
int cfuerr
Definition at line 124 of file donlp2.h.
int cgres
Definition at line 111 of file donlp2.h.
int cold
Definition at line 103 of file donlp2.h.
int cres
Definition at line 110 of file donlp2.h.
double del
Definition at line 67 of file donlp2.h.
double del0
Definition at line 65 of file donlp2.h.
double del01
Definition at line 66 of file donlp2.h.
double delmin
Definition at line 68 of file donlp2.h.
double epshi
Definition at line 78 of file donlp2.h.
double epsx
Definition at line 77 of file donlp2.h.
int eqres
Definition at line 100 of file donlp2.h.
double eta
Definition at line 75 of file donlp2.h.
int ffuerr
Definition at line 123 of file donlp2.h.
int gconst
Definition at line 58 of file donlp2.h.
int gunit
Definition at line 59 of file donlp2.h.
int icf
Definition at line 107 of file donlp2.h.
int icgf
Definition at line 108 of file donlp2.h.
Referenced by egradf().
int ident
Definition at line 99 of file donlp2.h.
int ifill1
Definition at line 86 of file donlp2.h.
int intakt
Definition at line 91 of file donlp2.h.
int inx
Definition at line 92 of file donlp2.h.
int iterma
Definition at line 85 of file donlp2.h.
int itstep
Definition at line 116 of file donlp2.h.
int LLOW
Definition at line 60 of file donlp2.h.
int LUP
Definition at line 61 of file donlp2.h.
int n
Definition at line 49 of file donlp2.h.
int ng
Definition at line 51 of file donlp2.h.
Referenced by amplitudesHOGaussian(), BroadcastSlaterDet(), calcDensityMatrixHOod(), calcgradOvlapod(), calcgradSlaterDetAux(), calcgradSlaterDetAuxod(), calcgradSlaterDetOBME(), calcgradSlaterDetOBMEod(), calcgradSlaterDetTBME(), calcgradSlaterDetTBMEod(), calcgradSlaterDetTBMEodrowcol(), calcgradSlaterDetTBMErowcol(), calcShellOccupationsod(), calcSlaterDetAux(), calcSlaterDetAuxod(), calcSlaterDetAuxodsingular(), calcSlaterDetOBHFMEs(), calcSlaterDetOBME(), calcSlaterDetOBMEod(), calcSlaterDetTBHFMEs(), calcSlaterDetTBME(), calcSlaterDetTBMEod(), calcSlaterDetTBMEodrowcol(), calcSlaterDetTBMErowcol(), and main().
int nh
Definition at line 50 of file donlp2.h.
int nr
Definition at line 52 of file donlp2.h.
Referenced by _initcmintegration(), initCMintegration(), initProjection(), and reinitcmintegration().
int nres
Definition at line 53 of file donlp2.h.
int nreset
Definition at line 44 of file donlp2.h.
int numsm
Definition at line 45 of file donlp2.h.
double ny
Definition at line 76 of file donlp2.h.
float optite
Definition at line 115 of file donlp2.h.
Referenced by MinimizeDONLP2multivapp(), MinimizeDONLP2orthogonalvapp(), MinimizeDONLP2orthproj(), MinimizeDONLP2proj(), MinimizeDONLP2vap(), MinimizeDONLP2vapp(), and MinimizeDONLP2vappiso().
int phase
Definition at line 117 of file donlp2.h.
Referenced by ClustersFMDprojectgradSlaterDet(), writeprojectedDiagonalTransitionDensityMatrixHO(), writeTransitionChargeDensities(), writeTransitionChargeFormfactors(), writeTransitionChargeFourierBessel(), writeTransitionPointDensities(), and writeTransitionPointFormfactors().
double rho
Definition at line 73 of file donlp2.h.
double rho1
Definition at line 74 of file donlp2.h.
float runtim
Definition at line 118 of file donlp2.h.
double scfmax
Definition at line 80 of file donlp2.h.
int silent
Definition at line 101 of file donlp2.h.
int singul
Definition at line 98 of file donlp2.h.
double smalld
Definition at line 71 of file donlp2.h.
double smallw
Definition at line 72 of file donlp2.h.
int std
Definition at line 93 of file donlp2.h.
double tau
Definition at line 70 of file donlp2.h.
double tau0
Definition at line 69 of file donlp2.h.
double taufac
Definition at line 82 of file donlp2.h.
double taumax
Definition at line 83 of file donlp2.h.
double tauqp
Definition at line 81 of file donlp2.h.
int te0
Definition at line 94 of file donlp2.h.
int te1
Definition at line 95 of file donlp2.h.
int te2
Definition at line 96 of file donlp2.h.
int te3
Definition at line 97 of file donlp2.h.
double updmy0
Definition at line 84 of file donlp2.h.
int val
Definition at line 57 of file donlp2.h.
Referenced by calcenergyeigenvalue(), calcgradSlaterDetOBME(), calcgradSlaterDetOBMEod(), calcgradSlaterDetTBME(), calcgradSlaterDetTBMEod(), calcgradSlaterDetTBMEodrowcol(), calcgradSlaterDetTBMErowcol(), calcprojectedMBME(), calcprojectedMBMEmpi(), calcprojectedMBMEs(), calcprojectedMBMEsmpi(), calcprojectedMultiMBME(), calcprojectedMultiMBMEmpi(), hermitizeprojectedMBME(), kmixingstates(), main(), MinimizerprojSlave(), sorteigenstates(), and sortEigenstates().
double x
Definition at line 31 of file donlp2.h.
Referenced by ef(), eg(), egradf(), egradh(), eh(), main(), MinimizeDONLP2(), MinimizeDONLP2p(), and MinimizeDONLP2par().
double x0
Definition at line 32 of file donlp2.h.
double x1
Definition at line 33 of file donlp2.h.
double xmin
Definition at line 34 of file donlp2.h.
double xst
Definition at line 40 of file donlp2.h.