FMD: fmd/Formfactors.c File Reference
fmd/Formfactors.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <complex.h>
#include <math.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "CenterofMass.h"
#include "Formfactors.h"
#include "numerics/cmath.h"
#include "numerics/gaussquad.h"
#include "numerics/sphericalharmonics.h"
#include "numerics/sphericalbessel.h"
#include "misc/utils.h"
#include "misc/physics.h"
Defines
#define SQR(x) ((x)*(x))
Functions
void initOpFormfactors (FormfactorPara *par)
void calcFormfactorod (double q[3], int recoil, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double ffactor[2])
void calcMultipoleFormfactorsod (FormfactorPara *par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *ffactor)
void writePointFormfactors (FILE *fp, const Projection *P, const FormfactorPara *p, int l, int j, int pi, int a, void *ffactorme, const Eigenstates *E)
void writeChargeFormfactors (FILE *fp, const Projection *P, const FormfactorPara *p, int l, int j, int pi, int a, void *ffactorme, const Eigenstates *E)
void writeTransitionPointFormfactors (FILE *fp, const Projection *P, const FormfactorPara *p, int l, int jfin, int pfin, int afin, int jini, int pini, int aini, void *ffactorme, const Eigenstates *E)
void writeTransitionChargeFormfactors (FILE *fp, const Projection *P, const FormfactorPara *p, int l, int jfin, int pfin, int afin, int jini, int pini, int aini, void *ffactorme, const Eigenstates *E)
void writePointDensities (FILE *fp, const Projection *P, const FormfactorPara *p, double rmax, int npointsr, int A, int l, int j, int pi, int a, void *ffactorme, const Eigenstates *E)
void writeMatterDensities (FILE *fp, const Projection *P, const FormfactorPara *p, double rmax, int npointsr, int A, int l, int j, int pi, int a, void *ffactorme, const Eigenstates *E)
void writeChargeDensities (FILE *fp, const Projection *P, const FormfactorPara *p, double rmax, int npointsr, int Z, int l, int j, int pi, int a, void *ffactorme, const Eigenstates *E)
void writeChargeFourierBessel (FILE *fp, const Projection *P, const FormfactorPara *p, double rmax, int npointsr, int Z, int l, int j, int pi, int a, void *ffactorme, const Eigenstates *E)
void writeTransitionPointDensities (FILE *fp, const Projection *P, const FormfactorPara *p, double rmax, int npointsr, int A, int l, int jfin, int pfin, int afin, int jini, int pini, int aini, void *ffactorme, const Eigenstates *E)
void writeTransitionChargeDensities (FILE *fp, const Projection *P, const FormfactorPara *p, double rmax, int npointsr, int Z, int l, int jfin, int pfin, int afin, int jini, int pini, int aini, void *ffactorme, const Eigenstates *E)
void writeTransitionChargeFourierBessel (FILE *fp, const Projection *P, const FormfactorPara *p, double rmax, int npointsr, int Z, int l, int jfin, int pfin, int afin, int jini, int pini, int aini, void *ffactorme, const Eigenstates *E)
Variables
char * fflabel [NMULTIPOLES]
ManyBodyOperator OpMultipoleFormfactor [NMULTIPOLES]
ManyBodyOperators OpMultipoleFormfactors
int il [NMULTIPOLES] = {0, 1, 4, 9}
int diml [NMULTIPOLES] = {1, 3, 5, 7}
Detailed Description
calculate formfactors center of mass motion is treated exactly
(c) 2004-2007 Thomas Neff
Definition in file Formfactors.c.
Define Documentation
#define SQR (x) ((x)*(x))
Definition at line 33 of file Formfactors.c.
Function Documentation
void calcFormfactorod (double q[3], int recoil, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double ffactor[2])
Definition at line 101 of file Formfactors.c.
References boostSlaterDet(), calcSlaterDetAuxod(), calcSlaterDetOBMEod(), copySlaterDet(), dim, initSlaterDet(), initSlaterDetAux(), mneutron, mproton, SlaterDet::N, par, and SlaterDet::Z.
Referenced by calcMultipoleFormfactorsod().
{
  // inititialize workspace if necessary
  if (recoil && !Qboost) {
    Qboost = malloc(sizeof(SlaterDet));
    initSlaterDet(Qp, Qboost);
    Xboost = malloc(sizeof(SlaterDetAux));
    initSlaterDetAux(Qp, Xboost);
  }
  OneBodyOperator op_ob_formfactorq = {dim: 2, opt: 1, par: q,
                                       me : ob_formfactorq};
  if (recoil) {
    double mass = Q->Z*mproton+Q->N*mneutron;
    double Vcm[3] = {-q[0]/mass, -q[1]/mass, -q[2]/mass};
    copySlaterDet(Qp, Qboost);
    boostSlaterDet(Qboost, Vcm);
    calcSlaterDetAuxod(Q, Qboost, Xboost);
    calcSlaterDetOBMEod(Q, Qboost, Xboost, &op_ob_formfactorq, ffactor);
  } else
    calcSlaterDetOBMEod(Q, Qp, X, &op_ob_formfactorq, ffactor);
}
void calcMultipoleFormfactorsod (FormfactorPara * par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * ffactor)
Definition at line 133 of file Formfactors.c.
References alpha, calcFormfactorod(), GaussLegendrePoints(), k, l, m, FormfactorPara::nalpha, FormfactorPara::ncosb, FormfactorPara::npoints, FormfactorPara::qmax, FormfactorPara::recoil, ShiftedPeriodicTrapezoidalPoints(), and Y().
{
  double qmax = par->qmax;
  int ialpha, nalpha = par->nalpha;
  int icosb, ncosb = par->ncosb;
  int npoints = par->npoints;
  int recoil = par->recoil;
  int m, i, t, l;
  double alpha, beta, weight;
  double q, k[3];
  complex double ff[2];
  for (l=0; l<NMULTIPOLES; l++)
    for (t=0; t<2; t++)
      for (i=0; i<npoints; i++)
        for (m=0; m<diml[l]; m++)
          ffactor[m + i*diml[l] + t*diml[l]*npoints + il[l]*2*npoints] = 0.0;
  double alphal[nalpha], walphal[nalpha];
  double cosbl[ncosb], wcosbl[ncosb];
  ShiftedPeriodicTrapezoidalPoints(nalpha, 0, 2*M_PI, 0.0, alphal, walphal);
  GaussLegendrePoints(ncosb, -1, 1, cosbl, wcosbl);
  for (i=0; i<npoints; i++) {
    q = qmax* i/(npoints-1);
    for (ialpha=0; ialpha<nalpha; ialpha++)
      for (icosb=0; icosb<ncosb; icosb++) {
        alpha = alphal[ialpha];
        beta = acos(cosbl[icosb]);
        weight = walphal[ialpha]*wcosbl[icosb];
        k[0] = q*cos(alpha)*sin(beta);
        k[1] = q*sin(alpha)*sin(beta);
        k[2] = q*cos(beta);
        calcFormfactorod(k, recoil, Q, Qp, X, ff);
        for (l=0; l<NMULTIPOLES; l++)
          for (t=0; t<2; t++)
            for (m=-l; m<=l; m++)
              ffactor[m+l + i*diml[l] + t*diml[l]*npoints + il[l]*2*npoints] +=
                weight* ff[t]* Y(2*l,2*m,beta,alpha);
        }
    }
}
void initOpFormfactors (FormfactorPara * par)
Definition at line 55 of file Formfactors.c.
References ManyBodyOperator::dim, ManyBodyOperators::dim, fflabel, ManyBodyOperator::me, FormfactorPara::nalpha, ManyBodyOperator::name, FormfactorPara::ncosb, FormfactorPara::npoints, ManyBodyOperator::par, ManyBodyOperators::par, ManyBodyOperator::pi, FormfactorPara::qmax, ManyBodyOperator::rank, FormfactorPara::recoil, ManyBodyOperator::size, and ManyBodyOperators::size.
Referenced by main().
{
  int i;
  OpMultipoleFormfactors.dim = 2*par->npoints;
  OpMultipoleFormfactors.size = 2*par->npoints;
  OpMultipoleFormfactors.par = par;
  for (i=0; i<NMULTIPOLES; i++) {
    char* name = malloc(60);
    sprintf(name, "%sFormfactors-%05.2f-%d-%d-%d%s",
            fflabel[i],
            par->qmax, par->npoints, par->nalpha, par->ncosb,
            par->recoil ? "-recoil" : "");
    OpMultipoleFormfactor[i].name = name;
    OpMultipoleFormfactor[i].rank = 2*i;
    OpMultipoleFormfactor[i].pi = i % 2;
    OpMultipoleFormfactor[i].dim = 2*par->npoints;
    OpMultipoleFormfactor[i].size = 2*par->npoints;
    OpMultipoleFormfactor[i].par = par;
    OpMultipoleFormfactor[i].me = NULL;
  }
}
void writeChargeDensities (FILE * fp, const Projection * P, const FormfactorPara * p, double rmax, int npointsr, int Z, int l, int j, int pi, int a, void * ffactorme, const Eigenstates * E)
Definition at line 470 of file Formfactors.c.
References besselj0(), fneutron(), fproton(), Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, FormfactorPara::qmax, rho, and SQR.
Referenced by main().
{
  int jmax = P->jmax;
  int ipj = idxpij(jmax,pi,j);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idx = E->index[ipj][a];
  complex double norm = E->norm[ipj][idx];
  complex double (**ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] = ffctme[ipj][idx];
  double anu[npoints];
  int i, nu;
  double qnu[npoints];
  double Rc = M_PI*(npoints-1)/qmax;
  if (l != 0) {
    fprintf(stderr, "writeChargeDensities not yet implemented for l != 0\n");
    exit(-1);
  }
  // calculate coefficients anu
  for (nu=1; nu<npoints; nu++) {
    qnu[nu] = M_PI*nu/Rc;
    anu[nu] = 1/sqrt(4*M_PI)*SQR(qnu[nu])/(2*M_PI*Rc)*
      (ff[0][nu]*fproton(qnu[nu])+ff[1][nu]*fneutron(qnu[nu]))/norm;
  }
  // calculate densities
  double deltar=rmax/(npointsr-1);
  double rho;
  // charge densities
  for (i=0; i<npointsr; i++) {
    rho = 0.0;
    for (nu=1; nu<npoints; nu++)
      rho += anu[nu]*besselj0(qnu[nu]*i*deltar);
    fprintf(fp, "%6.3f\t%15.8g\n", i*deltar, rho);
  }
}
void writeChargeFormfactors (FILE * fp, const Projection * P, const FormfactorPara * p, int l, int j, int pi, int a, void * ffactorme, const Eigenstates * E)
Definition at line 221 of file Formfactors.c.
References fneutron(), fproton(), Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, and FormfactorPara::qmax.
Referenced by main().
{
  int jmax = P->jmax;
  int ipj = idxpij(jmax,pi,j);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idx = E->index[ipj][a];
  double norm = E->norm[ipj][idx];
  complex double (**ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] = ffctme[ipj][idx];
  int i;
  double q;
  double ml;
  for (i=0; i<npoints; i++) {
    q = qmax*i/(npoints-1);
    ml = creal((ff[0][i]*fproton(q) + ff[1][i]*fneutron(q))/norm);
    fprintf(fp, "%6.3f\t%13.5g\n", q, sqrt(j+1.0)*ml);
  }
}
void writeChargeFourierBessel (FILE * fp, const Projection * P, const FormfactorPara * p, double rmax, int npointsr, int Z, int l, int j, int pi, int a, void * ffactorme, const Eigenstates * E)
Definition at line 520 of file Formfactors.c.
References fneutron(), fproton(), Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, FormfactorPara::qmax, and SQR.
Referenced by main().
{
  int jmax = P->jmax;
  int ipj = idxpij(jmax,pi,j);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idx = E->index[ipj][a];
  complex double norm = E->norm[ipj][idx];
  complex double (**ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] = ffctme[ipj][idx];
  double anu[npoints];
  int nu;
  double qnu[npoints];
  double Rc = M_PI*(npoints-1)/qmax;
  if (l != 0) {
    fprintf(stderr, "writeChargeFourierBessel not yet implemented for l != 0\n");
    exit(-1);
  }
  // calculate coefficients anu
  for (nu=1; nu<npoints; nu++) {
    qnu[nu] = M_PI*nu/Rc;
    anu[nu] = 1/sqrt(4*M_PI)*SQR(qnu[nu])/(2*M_PI*Rc)*
      (ff[0][nu]*fproton(qnu[nu])+ff[1][nu]*fneutron(qnu[nu]))/norm;
  }
  // write fourier bessel coefficients
  fprintf(fp, "# Rc      = %8.3f\n", Rc);
  fprintf(fp, "# qmax    = %8.3f\n", qmax);
  fprintf(fp, "# npoints = %d\n", npoints-1);
  fprintf(fp, "\n#nu\tq[nu]\ta[nu]\n");
  for (nu=1; nu<npoints; nu++)
    fprintf(fp, "%d\t%8.3f\t%15.8g\n", nu, qnu[nu], anu[nu]);
}
void writeMatterDensities (FILE * fp, const Projection * P, const FormfactorPara * p, double rmax, int npointsr, int A, int l, int j, int pi, int a, void * ffactorme, const Eigenstates * E)
Definition at line 410 of file Formfactors.c.
References besselj0(), fproton(), Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, FormfactorPara::qmax, rho, and SQR.
Referenced by main().
{
  int jmax = P->jmax;
  int ipj = idxpij(jmax,pi,j);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idx = E->index[ipj][a];
  complex double norm = E->norm[ipj][idx];
  complex double (**ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] = ffctme[ipj][idx];
  complex double anu[npoints][2];
  int i, nu;
  double qnu[npoints];
  double Rc = M_PI*(npoints-1)/qmax;
  if (l != 0) {
    fprintf(stderr, "writeMatterDensities not yet implemented for l != 0\n");
    exit(-1);
  }
  // calculate coefficients anu
  for (nu=1; nu<npoints; nu++) {
    qnu[nu] = M_PI*nu/Rc;
    anu[nu][0] = 1/sqrt(4*M_PI)*SQR(qnu[nu])/(2*M_PI*Rc)*ff[0][nu]*fproton(qnu[nu])/norm;
    anu[nu][1] = 1/sqrt(4*M_PI)*SQR(qnu[nu])/(2*M_PI*Rc)*ff[1][nu]*fproton(qnu[nu])/norm;
  }
  // calculate densities
  double deltar=rmax/(npointsr-1);
  double rho, rhop, rhon;
  for (i=0; i<npointsr; i++) {
    rho = 0.0;
    for (nu=1; nu<npoints; nu++)
      rho += (anu[nu][0]+anu[nu][1])*besselj0(qnu[nu]*i*deltar);
    rhop = 0.0;
    for (nu=1; nu<npoints; nu++)
      rhop += anu[nu][0]* besselj0(qnu[nu]*i*deltar);
    rhon = 0.0;
    for (nu=1; nu<npoints; nu++)
      rhon += anu[nu][1]* besselj0(qnu[nu]*i*deltar);
    fprintf(fp, "%6.3f\t%15.8g\t%15.8g\t%15.8g\n",
            i*deltar, rho, rhop, rhon);
  }
}
void writePointDensities (FILE * fp, const Projection * P, const FormfactorPara * p, double rmax, int npointsr, int A, int l, int j, int pi, int a, void * ffactorme, const Eigenstates * E)
Definition at line 348 of file Formfactors.c.
References besselj0(), Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, FormfactorPara::qmax, rho, and SQR.
Referenced by main().
{
  int jmax = P->jmax;
  int ipj = idxpij(jmax,pi,j);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idx = E->index[ipj][a];
  complex double norm = E->norm[ipj][idx];
  complex double (**ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] = ffctme[ipj][idx];
  complex double anu[npoints][2];
  int i, nu;
  double qnu[npoints];
  double Rc = M_PI*(npoints-1)/qmax;
  if (l != 0) {
    fprintf(stderr, "writePointDensities not yet implemented for l != 0\n");
    exit(-1);
  }
  // calculate coefficients anu
  for (nu=1; nu<npoints; nu++) {
    qnu[nu] = M_PI*nu/Rc;
    anu[nu][0] = 1/sqrt(4*M_PI)*SQR(qnu[nu])/(2*M_PI*Rc)*ff[0][nu]/norm;
    anu[nu][1] = 1/sqrt(4*M_PI)*SQR(qnu[nu])/(2*M_PI*Rc)*ff[1][nu]/norm;
  }
  // calculate densities
  double deltar=rmax/(npointsr-1);
  double rho, rhop, rhon;
  for (i=0; i<npointsr; i++) {
    rho = 0.0;
    for (nu=1; nu<npoints; nu++)
      rho += (anu[nu][0]+anu[nu][1])*besselj0(qnu[nu]*i*deltar);
    rhop = 0.0;
    for (nu=1; nu<npoints; nu++)
      rhop += anu[nu][0]* besselj0(qnu[nu]*i*deltar);
    rhon = 0.0;
    for (nu=1; nu<npoints; nu++)
      rhon += anu[nu][1]* besselj0(qnu[nu]*i*deltar);
    fprintf(fp, "%6.3f\t%15.8g\t%15.8g\t%15.8g\n",
            i*deltar, rho, rhop, rhon);
  }
}
void writePointFormfactors (FILE * fp, const Projection * P, const FormfactorPara * p, int l, int j, int pi, int a, void * ffactorme, const Eigenstates * E)
Definition at line 187 of file Formfactors.c.
References Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, and FormfactorPara::qmax.
Referenced by main().
{
  int jmax = P->jmax;
  int ipj = idxpij(jmax,pi,j);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idx = E->index[ipj][a];
  complex double norm = E->norm[ipj][idx];
  complex double (**ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] = ffctme[ipj][idx];
  int i;
  double q, ml, mlp, mln;
  for (i=0; i<npoints; i++) {
    q = qmax*i/(npoints-1);
    mlp = ff[0][i]/norm;
    mln = ff[1][i]/norm;
    ml = (ff[0][i]+ff[1][i])/norm;
    fprintf(fp, "%6.3f\t%13.8g\t%13.8g\t%13.8g\n",
            q,
            sqrt(j+1.0)*ml,
            sqrt(j+1.0)*mlp,
            sqrt(j+1.0)*mln);
  }
}
void writeTransitionChargeDensities (FILE * fp, const Projection * P, const FormfactorPara * p, double rmax, int npointsr, int Z, int l, int jfin, int pfin, int afin, int jini, int pini, int aini, void * ffactorme, const Eigenstates * E)
Definition at line 645 of file Formfactors.c.
References besselj0(), fneutron(), fproton(), ifix, Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, phase, FormfactorPara::qmax, rho, and SQR.
Referenced by main().
{
  int jmax = P->jmax;
  int ipjini = idxpij(jmax,pini,jini);
  int ipjfin = idxpij(jmax,pfin,jfin);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idxfin = E->index[ipjfin][afin];
  int idxini = E->index[ipjini][aini];
  double normfin = E->norm[ipjfin][idxfin];
  double normini = E->norm[ipjini][idxini];
  complex double (****ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] =
    ffctme[ipjfin][ipjini][idxfin][idxini];
  complex double anu[npoints];
  int i, nu;
  complex double ff0, phase;
  double qnu[npoints];
  double Rc = M_PI*(npoints-1)/qmax;
  if (l != 0) {
    fprintf(stderr, "writeChargeDensities not yet implemented for l != 0\n");
    exit(-1);
  }
  // get rid of possible phase factor
  int ifix=npoints/3;
  double qfix=qmax*ifix/(npoints-1);
  ff0 = ff[0][ifix]*fproton(qfix)+ff[1][ifix]*fneutron(qfix);
  phase = ff0/cabs(ff0);
  // calculate coefficients anu
  for (nu=1; nu<npoints; nu++) {
    qnu[nu] = M_PI*nu/Rc;
    anu[nu] = 1/sqrt(4*M_PI)*SQR(qnu[nu])/(2*M_PI*Rc)*
      creal((ff[0][nu]*fproton(qnu[nu])+ff[1][nu]*fneutron(qnu[nu]))/phase)/
      sqrt(normfin*normini);
  }
  // calculate densities
  double deltar=rmax/(npointsr-1);
  double rho;
  // charge densities
  for (i=0; i<npointsr; i++) {
    rho = 0.0;
    for (nu=1; nu<npoints; nu++)
      rho += anu[nu]*besselj0(qnu[nu]*i*deltar);
    fprintf(fp, "%6.3f\t%15.8g\n", i*deltar, rho);
  }
}
void writeTransitionChargeFormfactors (FILE * fp, const Projection * P, const FormfactorPara * p, int l, int jfin, int pfin, int afin, int jini, int pini, int aini, void * ffactorme, const Eigenstates * E)
Definition at line 302 of file Formfactors.c.
References fneutron(), fproton(), ifix, Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, phase, and FormfactorPara::qmax.
Referenced by main().
{
  int jmax = P->jmax;
  int ipjfin = idxpij(jmax,pfin,jfin);
  int ipjini = idxpij(jmax,pini,jini);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idxfin = E->index[ipjfin][afin];
  int idxini = E->index[ipjini][aini];
  double normfin = E->norm[ipjfin][idxfin];
  double normini = E->norm[ipjini][idxini];
  complex double (****ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] =
    ffctme[ipjfin][ipjini][idxfin][idxini];
  int i;
  double q;
  double ml;
  complex double ff0, phase;
  // get rid of possible phase factors
  // formfactor should be real and positive for q=0
  int ifix=npoints/3;
  double qfix=qmax*ifix/(npoints-1);
  ff0 = ff[0][ifix]*fproton(qfix)+ff[1][ifix]*fneutron(qfix);
  phase = ff0/cabs(ff0);
  for (i=0; i<npoints; i++) {
    q = qmax*i/(npoints-1);
    ml = creal((ff[0][i]*fproton(q) + ff[1][i]*fneutron(q))/phase)/
      sqrt(normfin*normini);
    fprintf(fp, "%6.3f\t%13.5g\n", q, sqrt(jfin+1)*ml);
  }
}
void writeTransitionChargeFourierBessel (FILE * fp, const Projection * P, const FormfactorPara * p, double rmax, int npointsr, int Z, int l, int jfin, int pfin, int afin, int jini, int pini, int aini, void * ffactorme, const Eigenstates * E)
Definition at line 711 of file Formfactors.c.
References fneutron(), fproton(), ifix, Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, phase, FormfactorPara::qmax, and SQR.
Referenced by main().
{
  int jmax = P->jmax;
  int ipjini = idxpij(jmax,pini,jini);
  int ipjfin = idxpij(jmax,pfin,jfin);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idxfin = E->index[ipjfin][afin];
  int idxini = E->index[ipjini][aini];
  double normfin = E->norm[ipjfin][idxfin];
  double normini = E->norm[ipjini][idxini];
  complex double (****ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] =
    ffctme[ipjfin][ipjini][idxfin][idxini];
  double anu[npoints];
  int nu;
  complex double ff0, phase;
  double qnu[npoints];
  double Rc = M_PI*(npoints-1)/qmax;
  if (l != 0) {
    fprintf(stderr, "writeChargeDensities not yet implemented for l != 0\n");
    exit(-1);
  }
  // get rid of possible phase factor
  int ifix=npoints/3;
  double qfix=qmax*ifix/(npoints-1);
  ff0 = ff[0][ifix]*fproton(qfix)+ff[1][ifix]*fneutron(qfix);
  phase = ff0/cabs(ff0);
  // calculate coefficients anu
  for (nu=1; nu<npoints; nu++) {
    qnu[nu] = M_PI*nu/Rc;
    anu[nu] = 1/sqrt(4*M_PI)*SQR(qnu[nu])/(2*M_PI*Rc)*
      creal((ff[0][nu]*fproton(qnu[nu])+ff[1][nu]*fneutron(qnu[nu]))/phase)/
      sqrt(normfin*normini);
  }
  // write fourier bessel coefficients
  fprintf(fp, "# Rc      = %8.3f\n", Rc);
  fprintf(fp, "# qmax    = %8.3f\n", qmax);
  fprintf(fp, "# npoints = %d\n", npoints-1);
  fprintf(fp, "\n#nu\tq[nu]\ta[nu]\n");
  for (nu=1; nu<npoints; nu++)
    fprintf(fp, "%d\t%8.3f\t%15.8g\n", nu, qnu[nu], anu[nu]);
}
void writeTransitionPointDensities (FILE * fp, const Projection * P, const FormfactorPara * p, double rmax, int npointsr, int A, int l, int jfin, int pfin, int afin, int jini, int pini, int aini, void * ffactorme, const Eigenstates * E)
Definition at line 569 of file Formfactors.c.
References besselj0(), fneutron(), fproton(), ifix, Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, phase, FormfactorPara::qmax, rho, and SQR.
Referenced by main().
{
  int jmax = P->jmax;
  int ipjini = idxpij(jmax,pini,jini);
  int ipjfin = idxpij(jmax,pfin,jfin);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idxfin = E->index[ipjfin][afin];
  int idxini = E->index[ipjini][aini];
  double normfin = E->norm[ipjfin][idxfin];
  double normini = E->norm[ipjini][idxini];
  complex double (****ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] =
    ffctme[ipjfin][ipjini][idxfin][idxini];
  complex double anu[npoints][2];
  int i, nu;
  complex double ff0, phase;
  double qnu[npoints];
  double Rc = M_PI*(npoints-1)/qmax;
  if (l != 0) {
    fprintf(stderr, "writeTransitionPointDensities not yet implemented for l != 0\n");
    exit(-1);
  }
  // get rid of possible phase factor
  int ifix=npoints/3;
  double qfix=qmax*ifix/(npoints-1);
  ff0 = ff[0][ifix]*fproton(qfix)+ff[1][ifix]*fneutron(qfix);
  phase = ff0/cabs(ff0);
  // calculate coefficients anu
  for (nu=1; nu<npoints; nu++) {
    qnu[nu] = M_PI*nu/Rc;
    anu[nu][0] = 1/sqrt(4*M_PI)*SQR(qnu[nu])/(2*M_PI*Rc)*
      creal(ff[0][nu]/phase)/sqrt(normfin*normini);
    anu[nu][1] = 1/sqrt(4*M_PI)*SQR(qnu[nu])/(2*M_PI*Rc)*
      creal(ff[1][nu]/phase)/sqrt(normfin*normini);
  }
  // calculate densities
  double deltar=rmax/(npointsr-1);
  double rho, rhop, rhon;
  for (i=0; i<npointsr; i++) {
    rho = 0.0;
    for (nu=1; nu<npoints; nu++)
      rho += (anu[nu][0]+anu[nu][1])*besselj0(qnu[nu]*i*deltar);
    rhop = 0.0;
    for (nu=1; nu<npoints; nu++)
      rhop += anu[nu][0]*besselj0(qnu[nu]*i*deltar);
    rhon = 0.0;
    for (nu=1; nu<npoints; nu++)
      rhon += anu[nu][1]*besselj0(qnu[nu]*i*deltar);
    fprintf(fp, "%6.3f\t%15.8g\t%15.8g\t%15.8g\n",
            i*deltar, rho, rhop, rhon);
  }
}
void writeTransitionPointFormfactors (FILE * fp, const Projection * P, const FormfactorPara * p, int l, int jfin, int pfin, int afin, int jini, int pini, int aini, void * ffactorme, const Eigenstates * E)
Definition at line 251 of file Formfactors.c.
References ifix, Eigenstates::index, Projection::jmax, Eigenstates::norm, FormfactorPara::npoints, phase, and FormfactorPara::qmax.
Referenced by main().
{
  int jmax = P->jmax;
  int ipjfin = idxpij(jmax,pfin,jfin);
  int ipjini = idxpij(jmax,pini,jini);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idxfin = E->index[ipjfin][afin];
  int idxini = E->index[ipjini][aini];
  double normfin = E->norm[ipjfin][idxfin];
  double normini = E->norm[ipjini][idxini];
  complex double (****ffctme)[2*npoints] = ffactorme;
  complex double (*ff)[npoints] =
    ffctme[ipjfin][ipjini][idxfin][idxini];
  int i;
  double q;
  double mlp, mln, ml;
  complex double ff0p, ff0n, phase;
  // get rid of possible phase factors
  // formfactor should be real and positive for q=0
  int ifix=npoints/3;
  // average over proton and neutron phasese (is this correct ?)
  ff0p = ff[0][ifix]; ff0n = ff[1][ifix];
  phase = 0.5*(ff0p/cabs(ff0p)+ff0n/cabs(ff0n));
  for (i=0; i<npoints; i++) {
    q = qmax*i/(npoints-1);
    mlp = creal(ff[0][i]/phase)/sqrt(normfin*normini);
    mln = creal(ff[1][i]/phase)/sqrt(normfin*normini);
    ml = creal((ff[0][i]+ff[1][i])/phase)/sqrt(normfin*normini);
    fprintf(fp, "%6.3f\t%13.8g\t%13.8g\t%13.8g\n",
            q,
            sqrt(jfin+1.0)*ml,
            sqrt(jfin+1.0)*mlp,
            sqrt(jfin+1.0)*mln);
  }
}
Variable Documentation
int diml[NMULTIPOLES] = {1, 3, 5, 7}
Definition at line 131 of file Formfactors.c.
char* fflabel[NMULTIPOLES]
Initial value:
 { "EMonopole",
                               "EDipole",
                               "EQuadrupole",
                               "EOctupole" }
Definition at line 39 of file Formfactors.c.
Referenced by initOpFormfactors().
int il[NMULTIPOLES] = {0, 1, 4, 9}
Definition at line 130 of file Formfactors.c.
Referenced by calcDensityMatrixHOod().
ManyBodyOperator OpMultipoleFormfactor[NMULTIPOLES]
Definition at line 45 of file Formfactors.c.
Referenced by main().
ManyBodyOperators OpMultipoleFormfactors
Initial value:
 {
 n : NMULTIPOLES,
 Op : OpMultipoleFormfactor,
 me : calcMultipoleFormfactorsod
}
Definition at line 48 of file Formfactors.c.
Referenced by main().