FMD: fmd/GamovTeller.h File Reference
fmd/GamovTeller.h File Reference
#include "SlaterDet.h"
#include "Projection.h"
Functions
void calcGTplusod (void *Par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double GTplus[3])
void calcGTminusod (void *Par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double GTminus[3])
void writeprojectedtransitionGTplus (FILE *fp, const Projection *P, const complex double ****gtp, const Eigenstates *E, const Eigenstates *Ep)
Variables
ManyBodyOperator OpGTplus
ManyBodyOperator OpGTminus
Detailed Description
GamovTeller transitions
calculates Gamov Teller transition matrix elements in spherical basis
(c) 2004 Thomas Neff
Definition in file GamovTeller.h.
Function Documentation
void calcGTminusod (void * Par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double GTminus[3])
Definition at line 97 of file GamovTeller.c.
References calcSlaterDetOBMEod(), dim, and I.
{
  complex double gtm[3];
  OneBodyOperator op_ob_gtm = {dim: 3, opt: 0, par: NULL, me: ob_gtminus};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_gtm, gtm);
  // spherical components -1, 0, +1
  GTminus[0] =   sqrt(0.5)*(gtm[0] - I*gtm[1]);
  GTminus[1] =   gtm[2];
  GTminus[2] = - sqrt(0.5)*(gtm[0] + I*gtm[1]);
}
void calcGTplusod (void * Par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double GTplus[3])
Definition at line 78 of file GamovTeller.c.
References calcSlaterDetOBMEod(), dim, and I.
{
  complex double gtp[3];
  OneBodyOperator op_ob_gtp = {dim: 3, opt: 0, par: NULL, me: ob_gtplus};
  // SlaterDetAux X calculated by calcSlaterDetAuxodSingular needed here
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_gtp, gtp);
  // spherical components -1, 0, +1
  GTplus[0] =   sqrt(0.5)*(gtp[0] - I*gtp[1]);
  GTplus[1] =   gtp[2];
  GTplus[2] = - sqrt(0.5)*(gtp[0] + I*gtp[1]);
}
void writeprojectedtransitionGTplus (FILE * fp, const Projection * P, const complex double **** gtp, const Eigenstates * E, const Eigenstates * Ep)
Definition at line 180 of file GamovTeller.c.
References writeprojectedtransitions().
Referenced by main().
{
  fprintf(fp, "\n ########### Gamov Teller plus transitions\n");
  writeprojectedtransitions(fp, P, 2, 0, "B(GT+)", "", gtp, Efin, Eini);
}
Variable Documentation
ManyBodyOperator OpGTminus
Definition at line 42 of file GamovTeller.c.
Referenced by main().
ManyBodyOperator OpGTplus
Definition at line 31 of file GamovTeller.c.
Referenced by main().