FMD: fmd/Gaussian.c File Reference
fmd/Gaussian.c File Reference
#include "Gaussian.h"
#include <math.h>
#include <complex.h>
#include "misc/physics.h"
#include "numerics/cmath.h"
#include "numerics/rotationmatrices.h"
Defines
#define SQR(x) (x)*(x)
Functions
void moveGaussian (Gaussian *g, double d[3])
move Gaussian by d
void boostGaussian (Gaussian *g, double v[3])
boost Gaussian by v
void rotateGaussian (Gaussian *G, const double R3[3][3], const complex double R2[2][2])
void invertGaussian (Gaussian *G)
parity operation with respect to origin
void timerevertGaussian (Gaussian *G)
time reversal operator
void scaleGaussian (Gaussian *G, double kappa)
scale lengths by kappa
void spinflipGaussian (Gaussian *G)
spin flip
void calcGaussianAux (const Gaussian *G1, const Gaussian *G2, GaussianAux *X)
calculate auxiliary quantities for two Gaussians
Detailed Description
Parameters of a Gaussian Wavepacket
(c) 2003 Thomas Neff
Definition in file Gaussian.c.
Define Documentation
#define SQR (x) (x)*(x)
Definition at line 22 of file Gaussian.c.
Function Documentation
void boostGaussian (Gaussian * g, double v[3])
boost Gaussian by v
Definition at line 33 of file Gaussian.c.
References Gaussian::a, Gaussian::b, Gaussian::chi, I, SQR, and Gaussian::xi.
Referenced by boostSlaterDet(), and ClustersFMDtoSlaterDet().
{
  int i;
  for (i=0; i<2; i++)
    g->chi[i] *= cexp(I*mass(g->xi)*(v[0]*g->b[0]+v[1]*g->b[1]+v[2]*g->b[2])
                      -0.5*g->a*SQR(mass(g->xi))*(SQR(v[0])+SQR(v[1])+SQR(v[2])));
  for (i=0; i<3; i++)
    g->b[i] += I*mass(g->xi)*g->a*v[i];
}
void calcGaussianAux (const Gaussian * G1, const Gaussian * G2, GaussianAux * X)
calculate auxiliary quantities for two Gaussians
Definition at line 96 of file Gaussian.c.
References Gaussian::a, GaussianAux::alpha, Gaussian::b, Gaussian::chi, I, GaussianAux::lambda, GaussianAux::pi, GaussianAux::pi2, GaussianAux::Q, GaussianAux::R, GaussianAux::rho, GaussianAux::rho2, GaussianAux::rhopi, GaussianAux::rhoxpi, GaussianAux::S, GaussianAux::sig, GaussianAux::T, and Gaussian::xi.
Referenced by calcSlaterDetAux(), calcSlaterDetAuxod(), calcSlaterDetAuxodsingular(), and ob_parity().
{
  int i;
  X->sig[0] = conj(G1->chi[0])*G2->chi[1] + conj(G1->chi[1])*G2->chi[0];
  X->sig[1] = I*(conj(G1->chi[1])*G2->chi[0] - conj(G1->chi[0])*G2->chi[1]);
  X->sig[2] = conj(G1->chi[0])*G2->chi[0] - conj(G1->chi[1])*G2->chi[1];
  X->lambda = 1.0/(conj(G1->a)+G2->a);
  X->alpha = conj(G1->a)*G2->a*X->lambda;
  for (i=0; i<3; i++)
    X->rho[i] = X->lambda*(G2->a*conj(G1->b[i])+conj(G1->a)*G2->b[i]);
  X->rho2 = cvec3sqr(X->rho);
  for (i=0; i<3; i++)
    X->pi[i] = X->lambda*I*(conj(G1->b[i]) - G2->b[i]);
  X->pi2 = cvec3sqr(X->pi);
  X->rhopi = cvec3mult(X->rho, X->pi);
  cvec3cross(X->rho, X->pi, X->rhoxpi);
  X->T = (1+G1->xi*G2->xi)/2;
  X->S = conj(G1->chi[0])*G2->chi[0] + conj(G1->chi[1])*G2->chi[1];
  X->R = cpow32(2*M_PI*X->alpha)*cexp(0.5*X->pi2/X->lambda);
  X->Q = X->T*X->S*X->R;
}
void invertGaussian (Gaussian * G)
parity operation with respect to origin
Definition at line 54 of file Gaussian.c.
References Gaussian::b.
Referenced by doublegaussianSlaterDetParity(), invertSlaterDet(), and ob_parity().
{
  int i;
  for (i=0; i<3; i++)
    G->b[i] *= -1;
}
void moveGaussian (Gaussian * g, double d[3])
move Gaussian by d
Definition at line 24 of file Gaussian.c.
References Gaussian::b.
Referenced by ClusterFMDtoSlaterDet(), ClustersFMDtoSlaterDet(), ClustertoSlaterDet(), CoreFMDtoSlaterDet(), and moveSlaterDet().
{
  int i;
  for (i=0; i<3; i++)
    g->b[i] += d[i];
}
void rotateGaussian (Gaussian * G, const double R3[3][3], const complex double R2[2][2])
rotate Gaussian using rotation matrices R3 in coordinate and R2 in spin space
Definition at line 46 of file Gaussian.c.
References Gaussian::b, Gaussian::chi, cm2mult(), and m3mult().
Referenced by ClusterFMDtoSlaterDet(), ClustersFMDtoSlaterDet(), ClustertoSlaterDet(), and rotateSlaterDet().
{
  cm2mult(R2, G->chi);
  m3mult(R3, G->b);
}
void scaleGaussian (Gaussian * G, double kappa)
scale lengths by kappa
Definition at line 77 of file Gaussian.c.
References Gaussian::a, and Gaussian::b.
Referenced by scaleSlaterDet().
{
  int i;
  G->a *= kappa*kappa;
  for (i=0; i<3; i++)
    G->b[i] *= kappa;
}
void spinflipGaussian (Gaussian * G)
spin flip
Definition at line 87 of file Gaussian.c.
References Gaussian::chi.
Referenced by main().
{
  complex double c;
  c = G->chi[0];
  G->chi[0] = conj(G->chi[1]);
  G->chi[1] = -conj(c);
}
void timerevertGaussian (Gaussian * G)
time reversal operator
Definition at line 63 of file Gaussian.c.
References Gaussian::a, Gaussian::b, and Gaussian::chi.
Referenced by timerevertSlaterDet().
{
  int i;
  G->a = conj(G->a);
  for (i=0; i<3; i++)
    G->b[i] = conj(G->b[i]);
  complex double tmp = G->chi[0];
  G->chi[0] = -conj(G->chi[1]);
  G->chi[1] = conj(tmp);
}