FMD: fmd/gradHamiltonian.h File Reference
fmd/gradHamiltonian.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Interaction.h"
Functions
void calcgradHamiltonian (const Interaction *P, const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dh)
void calcgradHamiltonianod (const Interaction *P, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dh)
Detailed Description
calculate gradients of Hamiltonian matrix element
(c) 2003 Thomas Neff
Definition in file gradHamiltonian.h.
Function Documentation
void calcgradHamiltonian (const Interaction * P, const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dh)
calculates gradient of Hamiltonian overwrites gradient dh
Definition at line 20 of file gradHamiltonian.c.
References calcgradPotential(), calcgradT(), calcgradTCM(), Interaction::cm, SlaterDet::ngauss, gradSlaterDet::ngauss, gradSlaterDet::val, and zerogradSlaterDet().
Referenced by calcgradprojectedHamiltonian(), egradf(), and main().
{
  dh->ngauss = Q->ngauss;
  dh->val = 0.0;
  zerogradSlaterDet(dh);
  calcgradT(Q, X, dX, dh);
  if (P->cm)
    calcgradTCM(Q, X, dX, dh);
  calcgradPotential(P, Q, X, dX, dh);
}
void calcgradHamiltonianod (const Interaction * P, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dh)
Definition at line 36 of file gradHamiltonian.c.
References calcgradPotentialod(), calcgradTCMod(), calcgradTod(), Interaction::cm, SlaterDet::ngauss, gradSlaterDet::ngauss, gradSlaterDet::val, and zerogradSlaterDet().
Referenced by calcgradorthprojectedHamiltonian(), calcgradprojectedHamiltonian(), calcgradprojectedHamiltonianmatrix(), egradf(), main(), and MinimizerprojSlave().
{
  dh->ngauss = Q->ngauss;
  dh->val = 0.0;
  zerogradSlaterDet(dh);
  calcgradTod(Q, Qp, X, dX, dh);
  if (P->cm)
    calcgradTCMod(Q, Qp, X, dX, dh);
  calcgradPotentialod(P, Q, Qp, X, dX, dh);
}