FMD: fmd/gradKineticEnergy.h File Reference
fmd/gradKineticEnergy.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
Functions
void calcgradT (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dt)
void calcgradTod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dt)
Detailed Description
calculate gradient of kinetic energy
(c) 2003 Thomas Neff
Definition in file gradKineticEnergy.h.
Function Documentation
void calcgradT (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dt)
Definition at line 49 of file gradKineticEnergy.c.
References calcgradSlaterDetOBME().
Referenced by calcgradHamiltonian(), and calcgradHamiltonianmpi().
{
  gradOneBodyOperator gop_ob_t = {opt: 1, par: NULL, me: gob_t};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_t, dt);
}
void calcgradTod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dt)
Definition at line 59 of file gradKineticEnergy.c.
References calcgradSlaterDetOBMEod().
Referenced by calcgradHamiltonianod(), and calcgradHamiltonianodmpi().
{
  gradOneBodyOperator gop_ob_t = {opt: 1, par: NULL, me: gob_t};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_t, dt);
}