FMD: fmd/gradOscillator.c File Reference
fmd/gradOscillator.c File Reference
#include <complex.h>
#include "Gaussian.h"
#include "gradGaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "gradOscillator.h"
#include "numerics/cmath.h"
#include "misc/physics.h"
Functions
void calcgradOsci2 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, double omega, gradSlaterDet *dhosci)
void calcgradOsci4 (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, double kappa, gradSlaterDet *dhosci)
Detailed Description
external quadratic and quartic oscillator
(c) 2003 Thomas Neff
Definition in file gradOscillator.c.
Function Documentation
void calcgradOsci2 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, double omega, gradSlaterDet * dhosci)
Definition at line 71 of file gradOscillator.c.
References calcgradSlaterDetOBME(), mnucleon, and par.
Referenced by main().
{
  double kosci = mnucleon* omega*omega;
  gradOneBodyOperator gop_ob_osci2 = {opt: 1, par: &kosci, me: gob_osci2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_osci2, dhosci);
}
void calcgradOsci4 (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, double kappa, gradSlaterDet * dhosci)
Definition at line 82 of file gradOscillator.c.
References calcgradSlaterDetOBME(), mnucleon, and par.
{
  double kosci = mnucleon*kappa;
  gradOneBodyOperator gop_ob_osci4 = {opt: 1, par: &kosci, me: gob_osci4};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_osci4, dhosci);
}