FMD: fmd/gradCMSlaterDet.h File Reference
fmd/gradCMSlaterDet.h File Reference
#include "Gaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
Data Structures
struct gradCM
Functions
void calcgradCMSlaterDetOBME (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, const OneBodyOperator *op, gradSlaterDet *grad)
void calcgradCMSlaterDetTBME (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, const TwoBodyOperator *op, gradSlaterDet *grad)
Detailed Description
gradients of matrix elements that that depend on the expectation values of Center of Mass coordinate and momentum
(c) 2003 Thomas Neff
Definition in file gradCMSlaterDet.h.
Function Documentation
void calcgradCMSlaterDetOBME (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, const OneBodyOperator * op, gradSlaterDet * grad)
Definition at line 61 of file gradCMSlaterDet.c.
References SlaterDet::A, gcmpara::A, calcSlaterDetOBME(), gob_dcm(), SlaterDet::N, gcmpara::N, OneBodyOperator::opt, par, gcmpara::V, gcmpara::X, SlaterDet::Z, and gcmpara::Z.
Referenced by calcgradConstraintED2(), calcgradConstraintEO2(), calcgradConstraintEQ2(), calcgradConstraintJ2(), calcgradConstraintJ2(), calcgradConstraintl2(), calcgradConstraintls(), calcgradConstraintLS(), calcgradConstraintNO2(), calcgradConstraintNQ2(), and calcgradConstraintO2().
{
  int i;
  double dcm[6];
  calcSlaterDetOBME(Q, X, op, dcm);
  gcmpara para;
  para.A = Q->A; para.Z = Q->Z; para.N = Q->N;
  for (i=0; i<3; i++)
    para.X[i] = dcm[i];
  for (i=0; i<3; i++)
    para.V[i] = dcm[i+3];
  gradOneBodyOperator gop_ob_dcm = {opt: op->opt, par: &para, me: gob_dcm};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_dcm, grad);
}
void calcgradCMSlaterDetTBME (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, const TwoBodyOperator * op, gradSlaterDet * grad)
Definition at line 83 of file gradCMSlaterDet.c.
References SlaterDet::A, gcmpara::A, calcSlaterDetTBME(), gob_dcm(), SlaterDet::N, gcmpara::N, TwoBodyOperator::opt, par, gcmpara::V, gcmpara::X, SlaterDet::Z, and gcmpara::Z.
Referenced by calcgradConstraintJ2(), and calcgradConstraintLS().
{
  int i;
  double dcm[6];
  calcSlaterDetTBME(Q, X, op, dcm);
  gcmpara para;
  para.A = Q->A; para.Z = Q->Z; para.N = Q->N;
  for (i=0; i<3; i++)
    para.X[i] = dcm[i];
  for (i=0; i<3; i++)
    para.V[i] = dcm[i+3];
  gradOneBodyOperator gop_ob_dcm = {opt: op->opt, par: &para, me: gob_dcm};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_dcm, grad);
}