FMD: fmd/gradCenterofMass.c File Reference
fmd/gradCenterofMass.c File Reference
#include <stdlib.h>
#include <complex.h>
#include "Gaussian.h"
#include "gradGaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "gradCenterofMass.h"
#include "numerics/cmath.h"
#include "misc/physics.h"
Functions
void calcgradTCM (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dtcm)
calculate the gradient of -Tcm !
void calcgradTCMod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dtcm)
Detailed Description
calculate gradient of center of mass energy
(c) 2003 Thomas Neff
Definition in file gradCenterofMass.c.
Function Documentation
void calcgradTCM (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dtcm)
calculate the gradient of -Tcm !
Definition at line 77 of file gradCenterofMass.c.
References calcgradSlaterDetOBME(), calcgradSlaterDetTBME(), and par.
Referenced by calcgradHamiltonian(), calcgradHamiltonianmpi(), and calcgradprojectedHamiltonian().
{
  gradOneBodyOperator gop_ob_P2 = {opt: 1, par: Q, me: gob_P2};
  gradTwoBodyOperator gop_tb_P2 = {opt: 1, par: Q, me: gtb_P2};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_P2, dtcm);
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_P2, dtcm);
}
void calcgradTCMod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dtcm)
Definition at line 90 of file gradCenterofMass.c.
References calcgradSlaterDetOBMEod(), calcgradSlaterDetTBMEod(), and par.
Referenced by calcgradHamiltonianod(), and calcgradHamiltonianodmpi().
{
  gradOneBodyOperator gop_ob_P2 = {opt: 1, par: Q, me: gob_P2};
  gradTwoBodyOperator gop_tb_P2 = {opt: 1, par: Q, me: gtb_P2};
  calcgradSlaterDetOBMEod(Q, Qp, X, dX, &gop_ob_P2, dtcm);
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_P2, dtcm);
}