FMD: fmd/gradPotential.h File Reference
fmd/gradPotential.h File Reference
#include <complex.h>
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Interaction.h"
Functions
void calcgradPotential (const Interaction *P, const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dv)
void calcgradPotentialod (const Interaction *P, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dv)
void calcgradPotentialrowcol (const Interaction *P, const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dv, int k, int l)
void calcgradPotentialodrowcol (const Interaction *P, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dv, int k, int l)
Function Documentation
void calcgradPotential (const Interaction * P, const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dv)
Definition at line 1278 of file gradPotential.c.
References calcgradSlaterDetTBME(), and par.
Referenced by calcgradHamiltonian().
{
  gradTwoBodyOperator gop_tb_pot = {opt: 0, par: P, me: gtb_pot};
  calcgradSlaterDetTBME(Q, X, dX, &gop_tb_pot, dv);
}
void calcgradPotentialod (const Interaction * P, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dv)
Definition at line 1289 of file gradPotential.c.
References calcgradSlaterDetTBMEod(), and par.
Referenced by calcgradHamiltonianod().
{
  gradTwoBodyOperator gop_tb_pot = {opt: 0, par: P, me: gtb_pot};
  calcgradSlaterDetTBMEod(Q, Qp, X, dX, &gop_tb_pot, dv);
}
void calcgradPotentialodrowcol (const Interaction * P, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dv, int k, int l)
Definition at line 1313 of file gradPotential.c.
References calcgradSlaterDetTBMEodrowcol(), and par.
Referenced by MinimizerSlaveod().
{
  gradTwoBodyOperator gop_tb_pot = {opt: 0, par: P, me: gtb_pot};
  calcgradSlaterDetTBMEodrowcol(Q, Qp, X, dX, &gop_tb_pot, dv, k, l);
}
void calcgradPotentialrowcol (const Interaction * P, const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, gradSlaterDet * dv, int k, int l)
Definition at line 1301 of file gradPotential.c.
References calcgradSlaterDetTBMErowcol(), and par.
Referenced by MinimizerSlave().
{
  gradTwoBodyOperator gop_tb_pot = {opt: 0, par: P, me: gtb_pot};
  calcgradSlaterDetTBMErowcol(Q, X, dX, &gop_tb_pot, dv, k, l);
}