FMD: fmd/gradCMSlaterDet.c File Reference
fmd/gradCMSlaterDet.c File Reference
#include "Gaussian.h"
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "gradCMSlaterDet.h"
#include "misc/physics.h"
Data Structures
struct gcmpara
Functions
void gob_dcm (const gcmpara *para, const Gaussian *G1, const Gaussian *G2, const GaussianAux *X, const gradGaussianAux *dX, complex double *dcm, gradGaussian *ddcm)
void calcgradCMSlaterDetOBME (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, const OneBodyOperator *op, gradSlaterDet *grad)
void calcgradCMSlaterDetTBME (const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, const TwoBodyOperator *op, gradSlaterDet *grad)
Detailed Description
gradients of matrix elements that that depend on the expectation values of Center of Mass coordinate and momentum
(c) 2003 Thomas Neff
Definition in file gradCMSlaterDet.c.
Function Documentation
void calcgradCMSlaterDetOBME (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, const OneBodyOperator * op, gradSlaterDet * grad)
Definition at line 61 of file gradCMSlaterDet.c.
References SlaterDet::A, gcmpara::A, calcSlaterDetOBME(), gob_dcm(), SlaterDet::N, gcmpara::N, OneBodyOperator::opt, par, gcmpara::V, gcmpara::X, SlaterDet::Z, and gcmpara::Z.
Referenced by calcgradConstraintED2(), calcgradConstraintEO2(), calcgradConstraintEQ2(), calcgradConstraintJ2(), calcgradConstraintJ2(), calcgradConstraintl2(), calcgradConstraintls(), calcgradConstraintLS(), calcgradConstraintNO2(), calcgradConstraintNQ2(), and calcgradConstraintO2().
{
  int i;
  double dcm[6];
  calcSlaterDetOBME(Q, X, op, dcm);
  gcmpara para;
  para.A = Q->A; para.Z = Q->Z; para.N = Q->N;
  for (i=0; i<3; i++)
    para.X[i] = dcm[i];
  for (i=0; i<3; i++)
    para.V[i] = dcm[i+3];
  gradOneBodyOperator gop_ob_dcm = {opt: op->opt, par: &para, me: gob_dcm};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_dcm, grad);
}
void calcgradCMSlaterDetTBME (const SlaterDet * Q, const SlaterDetAux * X, const gradSlaterDetAux * dX, const TwoBodyOperator * op, gradSlaterDet * grad)
Definition at line 83 of file gradCMSlaterDet.c.
References SlaterDet::A, gcmpara::A, calcSlaterDetTBME(), gob_dcm(), SlaterDet::N, gcmpara::N, TwoBodyOperator::opt, par, gcmpara::V, gcmpara::X, SlaterDet::Z, and gcmpara::Z.
Referenced by calcgradConstraintJ2(), and calcgradConstraintLS().
{
  int i;
  double dcm[6];
  calcSlaterDetTBME(Q, X, op, dcm);
  gcmpara para;
  para.A = Q->A; para.Z = Q->Z; para.N = Q->N;
  for (i=0; i<3; i++)
    para.X[i] = dcm[i];
  for (i=0; i<3; i++)
    para.V[i] = dcm[i+3];
  gradOneBodyOperator gop_ob_dcm = {opt: op->opt, par: &para, me: gob_dcm};
  calcgradSlaterDetOBME(Q, X, dX, &gop_ob_dcm, grad);
}
void gob_dcm (const gcmpara * para, const Gaussian * G1, const Gaussian * G2, const GaussianAux * X, const gradGaussianAux * dX, complex double * dcm, gradGaussian * ddcm)
Definition at line 29 of file gradCMSlaterDet.c.
References gradVector::a, gradGaussian::a, gradVector::b, gradGaussian::b, gradGaussian::chi, gradGaussianAux::dpi, gradGaussianAux::dQ, gradGaussianAux::drho, mneutron, mproton, gcmpara::N, GaussianAux::pi, GaussianAux::Q, GaussianAux::rho, gcmpara::V, gcmpara::X, Gaussian::xi, and gcmpara::Z.
Referenced by calcgradCMSlaterDetOBME(), and calcgradCMSlaterDetTBME().
{
  int i;
  double M;
  double* dXcm = para->X;
  double* dVcm = para->V;
  complex double meXVcm = 0.0;
  M=para->Z*mproton+para->N*mneutron;
  for (i=0; i<3; i++) {
    meXVcm += dXcm[i]*mass(G1->xi)/M* X->rho[i];
    meXVcm += dVcm[i]/M* X->pi[i];
  }
  *dcm += meXVcm* X->Q;
  for (i=0; i<2; i++)
    ddcm->chi[i] += meXVcm* dX->dQ.chi[i];
  for (i=0; i<3; i++)
    ddcm->a += (dXcm[i]*mass(G1->xi)/M* dX->drho.a[i] +
               dVcm[i]/M* dX->dpi.a[i])* X->Q;
  ddcm->a += meXVcm* dX->dQ.a;
  for (i=0; i<3; i++)
    ddcm->b[i] += (dXcm[i]*mass(G1->xi)/M* dX->drho.b +
                  dVcm[i]/M *dX->dpi.b)* X->Q + meXVcm* dX->dQ.b[i];
}