FMD: fmd/Hamiltonian.h File Reference
fmd/Hamiltonian.h File Reference
#include <complex.h>
#include "SlaterDet.h"
#include "Interaction.h"
Functions
void calcHamiltonian (const Interaction *Int, const SlaterDet *Q, const SlaterDetAux *X, double *h)
void calcHamiltonianod (const Interaction *Int, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *h)
void calcHamiltonianHF (const Interaction *Int, const SlaterDet *Q, const SlaterDetAux *X, void *mes)
Detailed Description
calculate matrix element of Hamiltonian
(c) 2003 Thomas Neff
Definition in file Hamiltonian.h.
Function Documentation
void calcHamiltonian (const Interaction * Int, const SlaterDet * Q, const SlaterDetAux * X, double * h)
Definition at line 23 of file Hamiltonian.c.
References calcPotential(), calcT(), calcTCM(), Interaction::cm, and Interaction::n.
Referenced by ef(), and main().
{
  double v[Int->n];
  double t, tcm = 0.0;
  calcT(Q, X, &t);
  if (Int->cm)
    calcTCM(Q, X, &tcm);
  calcPotential(Int, Q, X, v);
  *h = t - tcm + v[0];
}
void calcHamiltonianHF (const Interaction * Int, const SlaterDet * Q, const SlaterDetAux * X, void * mes)
Definition at line 57 of file Hamiltonian.c.
References SlaterDet::A, calcPotentialHF(), calcTCMHF(), calcTHF(), Interaction::cm, k, and m.
Referenced by main().
{
  int A=Q->A;
  complex double t[A*A];
  complex double tcm[A*A];
  complex double v[A*A];
  calcTHF(Q, X, t);
  if (Int->cm)
    calcTCMHF(Q, X, tcm);
  calcPotentialHF(Int, Q, X, v);
  complex double *h = mes;
  int k,m;
  for (m=0; m<A; m++)
    for (k=0; k<A; k++) {
      h[k+m*A] = t[k+m*A] + v[k+m*A];
      if (Int->cm)
        h[k+m*A] -= tcm[k+m*A];
    }
}
void calcHamiltonianod (const Interaction * Int, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * h)
Definition at line 39 of file Hamiltonian.c.
References calcPotentialod(), calcTCMod(), calcTod(), Interaction::cm, and Interaction::n.
Referenced by calcgradorthprojectedHamiltonian(), calcgradprojectedHamiltonian(), calcorthprojectedHamiltonian(), calcprojectedHamiltonian(), calcprojectedHamiltonianmatrix(), ef(), main(), and MinimizerprojSlave().
{
  complex double v[Int->n];
  complex double t, tcm = 0.0;
  calcTod(Q, Qp, X, &t);
  if (Int->cm)
    calcTCMod(Q, Qp, X, &tcm);
  calcPotentialod(Int, Q, Qp, X, v);
  *h = t - tcm + v[0];
}