FMD: fmd/HOBasis.h File Reference
fmd/HOBasis.h File Reference
#include <fmd/Gaussian.h>
Data Structures
struct HOSPState
Defines
#define HONMAX 8
#define HODIMMAX (HONMAX+1)*(HONMAX+2)*(HONMAX+3)/6
Functions
void initHOBasis (int nmax)
int dimHOBasis (int nmax)
HOSPState * getHOspstate (int idx)
int HOspstateidx (const HOSPState *spstate)
int HOxinljmidx (int xi, int n, int l, int twoj, int twom)
char * labelHOshell (int N)
char * labelHOorbit (int n, int l, int twoj)
char * labelHOspstate (const HOSPState *spstate)
void amplitudesHOGaussian (const Gaussian *G, int nmax, double omega, complex double *amp)
Detailed Description
define single-particle Harmonic oscillator basis
(c) 2006 Thomas Neff
Definition in file HOBasis.h.
Define Documentation
#define HODIMMAX (HONMAX+1)*(HONMAX+2)*(HONMAX+3)/6
Definition at line 25 of file HOBasis.h.
#define HONMAX 8
Definition at line 21 of file HOBasis.h.
Referenced by main(), writeprojectedDiagonalDensityMatrixHO(), and writeprojectedDiagonalTransitionDensityMatrixHO().
Function Documentation
void amplitudesHOGaussian (const Gaussian * G, int nmax, double omega, complex double * amp)
Definition at line 1104 of file HOBasis.c.
References Gaussian::a, ABS, ampcart, Gaussian::b, Gaussian::chi, clebsch(), dim, dimHOBasis(), HOnlm, HOnxnynz, invHOBasis, mnucleon, N, n0, ng, and Gaussian::xi.
Referenced by calcDensityMatrixHOod().
{
  double alpha = 1/(mnucleon*omega);
  int d = dimHOBasis(nmax);
  int i;
  for (i=0; i<d; i++)
    amp[i] = 0.0;
  // first calculate ovlaps with cartesian HO basis states
  for (i=0; i<3; i++)
    ampcart[0][i] = ng0(alpha, G->a, G->b[i]);
  int n;
  for (n=1; n<=nmax; n++)
    for (i=0; i<3; i++)
      ampcart[n][i] = ampcart[0][i]* ng(n, alpha, G->a, G->b[i]);
  // transform into ovlaps in xinljm basis with Smirnov and
  // Clebsch-Gordan coefficients
  int N, inxnynz, inlm, ixi, twol, twoml, twoms, twom, twoj, lj, ixinljm;
  complex double ampnlm, ampchi;
  for (N=0; N<=nmax; N++) {
    for (inlm=n0[N]; inlm<n0[N]+dim[N]; inlm++) {
      ampnlm = 0.0;
      for (inxnynz=n0[N]; inxnynz<n0[N]+dim[N]; inxnynz++) {
        ampnlm += smirnov[N][(inxnynz-n0[N])+(inlm-n0[N])*dim[N]]*
          ampcart[HOnxnynz[inxnynz].nx][0]*
          ampcart[HOnxnynz[inxnynz].ny][1]*
          ampcart[HOnxnynz[inxnynz].nz][2];
      }
      ixi = (G->xi == +1 ? 0 : 1);
      n = HOnlm[inlm].n;
      twol = 2*HOnlm[inlm].l; twoml = 2*HOnlm[inlm].m;
      for (twoms=-1; twoms<=+1; twoms=twoms+2) {
        twom = twoml + twoms;
        ampchi = G->chi[twoms == +1 ? 0 : 1];
        for (twoj=ABS(twol-1); twoj<=twol+1; twoj = twoj+2) {
          if (ABS(twom) <= twoj) {
            lj = (twol+twoj-1)/2;
            ixinljm = invHOBasis[ixi][n][lj][(twoj+twom)/2];
            amp[ixinljm] += clebsch(twol, 1, twoj, twoml, twoms, twom)* ampchi*ampnlm;
          }
        }
      }
    }
  }
}
int dimHOBasis (int nmax)
Definition at line 135 of file HOBasis.c.
Referenced by amplitudesHOGaussian(), calcDiagonalDensityMatrixHOod(), and main().
{
  return 2*2*(nmax+1)*(nmax+2)*(nmax+3)/6;
}
HOSPState* getHOspstate (int idx)
Definition at line 141 of file HOBasis.c.
{
  return &HOBasis[idx];
}
int HOspstateidx (const HOSPState * spstate)
Definition at line 147 of file HOBasis.c.
References invHOBasis, HOSPState::lj, HOSPState::m, HOSPState::n, and HOSPState::xi.
{
  return invHOBasis[sp->xi][sp->n][sp->lj][(ljtotwoj(sp->lj)+sp->m)/2];
}
int HOxinljmidx (int xi, int n, int l, int twoj, int twom)
Definition at line 153 of file HOBasis.c.
References invHOBasis.
Referenced by calcDiagonalDensityMatrixHOod(), and main().
{
  return invHOBasis[xi == +1 ? 0 : 1][n][(2*l+twoj-1)/2][(twoj+twom)/2];
}
void initHOBasis (int nmax)
Definition at line 64 of file HOBasis.c.
References ABS, dim, HOnlm, HOnxnynz, invHOBasis, l, HOSPState::lj, HOSPState::m, m, HOSPState::n, n, N, n0, nx, ny, nz, and HOSPState::xi.
Referenced by DiagonalDensityHOSlave(), and main().
{
  int N;
  int nx, ny, nz;
  int n, l, m;
  int xi, twoj, lj, twom;
  int i;
  i=0;
  for (N=0; N<=nmax; N++) {
    dim[N] = (N+1)*(N+2)/2;
    n0[N] = i;
    for (nx=N; nx>=0; nx--)
      for (ny=N-nx; ny>=0; ny--) {
        nz = N-nx-ny;
        // fprintf(stderr, "%d: (nx,ny,nz) = (%d,%d,%d)\n", i, nx, ny, nz);
        HOnxnynz[i].nx = nx;
        HOnxnynz[i].ny = ny;
        HOnxnynz[i].nz = nz;
        i++;
      }
  }
  i=0;
  for (N=0; N<=nmax; N++) {
    for (n=N/2; n>=0; n--) {
      l=N-2*n;
      for (m=-l; m<=l; m++) {
        // fprintf(stderr, "%d: (n, l, m) = (%d,%d,%d)\n", i, n, l, m);
        HOnlm[i].n = n;
        HOnlm[i].l = l;
        HOnlm[i].m = m;
        i++;
      }
    }
  }
  i=0;
  for (xi=0; xi<=1; xi++) {
    for (N=0; N<=nmax; N++) {
      for (n=N/2; n>=0; n--) {
        l=N-2*n;
        for (twoj=ABS(2*l-1); twoj<=2*l+1; twoj=twoj+2) {
          lj = (2*l+twoj-1)/2;
          for (twom=-twoj; twom<=twoj; twom=twom+2) {
            HOBasis[i].xi = xi ? -1 : +1;
            HOBasis[i].n = n;
            HOBasis[i].lj = lj;
            HOBasis[i].m = twom;
            invHOBasis[xi][n][lj][(twoj+twom)/2] = i;
            i++;
          }
        }
      }
    }
  }
}
char* labelHOorbit (int n, int l, int twoj)
Definition at line 171 of file HOBasis.c.
References jlabel.
Referenced by main(), writeprojectedDiagonalDensityMatrixHO(), and writeprojectedDiagonalTransitionDensityMatrixHO().
{
  char* label = malloc(7*sizeof(char));
  sprintf(label, "%d%c%d/2",
          n, jlabel[l], twoj);
  return label;
}
char* labelHOshell (int N)
Definition at line 162 of file HOBasis.c.
References shelllabel.
{
  return shelllabel[N];
}
char* labelHOspstate (const HOSPState * spstate)
Definition at line 180 of file HOBasis.c.
References jlabel, HOSPState::lj, HOSPState::m, HOSPState::n, and HOSPState::xi.
{
  char* label = malloc(14*sizeof(char));
  sprintf(label, "%c%d%c%d/2,%+d/2",
          sp->xi == +1 ? 'p' : 'n',
          sp->n,
          jlabel[ljtotwol(sp->lj)/2],
          ljtotwoj(sp->lj),
          sp->m);
  return label;
}