FMD: numerics/interpol.c File Reference
numerics/interpol.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "fortranc.h"
#include "interpol.h"
Functions
void FORTRAN() dcsint (int *IENT, double *H, int *N, double *TNODE, double *G, double *END1, double *ENDN, double *B, double *C, double *D)
void initInterpolzeroderivative (interpolpara *ipp, int n, double h, double *x, double *f)
void freeInterpol (interpolpara *ipp)
double sqr (double x)
double cbe (double x)
double calcInterpol (const interpolpara *p, double x)
Detailed Description
interpolate data by cubic spline uses routine from toms 547
2006 Thomas Neff
Definition in file interpol.c.
Function Documentation
double calcInterpol (const interpolpara * p, double x)
Definition at line 62 of file interpol.c.
References interpolpara::B, interpolpara::C, cbe(), interpolpara::D, interpolpara::G, n, interpolpara::n, sqr(), and interpolpara::T.
{
  int i=0;
  if (x < p->T[0] || x > p->T[p->n-1]) {
    fprintf(stderr, "interpol: argument %f outside interpolation range\n", x);
    return 0.0;
  }
  while (i < p->n - 1) {
    if (x <= p->T[i+1])
      break;
    i++;
  }
  return (p->G[i] +
          p->B[i]*(x - p->T[i]) +
          p->C[i]*sqr(x - p->T[i]) +
          p->D[i]*cbe(x - p->T[i]));
}
double cbe (double x) [inline]
Definition at line 60 of file interpol.c.
Referenced by calcInterpol().
{ return x*x*x; }
void FORTRAN() dcsint (int * IENT, double * H, int * N, double * TNODE, double * G, double * END1, double * ENDN, double * B, double * C, double * D)
Referenced by initInterpolzeroderivative().
void freeInterpol (interpolpara * ipp)
Definition at line 49 of file interpol.c.
References interpolpara::B, interpolpara::C, interpolpara::D, interpolpara::G, and interpolpara::T.
{
  free(ipp->T);
  free(ipp->G);
  free(ipp->B);
  free(ipp->C);
  free(ipp->D);
}
void initInterpolzeroderivative (interpolpara * ipp, int n, double h, double * x, double * f)
Definition at line 24 of file interpol.c.
References interpolpara::B, interpolpara::C, interpolpara::D, dcsint(), FORTRAN, interpolpara::G, interpolpara::h, interpolpara::n, and interpolpara::T.
{
  ipp->n = n;
  ipp->h = h;
  ipp->T = malloc(n*sizeof(double));
  ipp->G = malloc(n*sizeof(double));
  ipp->B = malloc(n*sizeof(double));
  ipp->C = malloc(n*sizeof(double));
  ipp->D = malloc(n*sizeof(double));
  int i;
  for (i=0; i<n; i++)
    ipp->T[i] = x[i];
  for (i=0; i<n; i++)
    ipp->G[i] = f[i];
  int IENT=1;
  double END1=0.0; double ENDN=0.0;
  FORTRAN(dcsint)(&IENT, &h, &n, ipp->T, ipp->G, &END1, &ENDN,
                  ipp->B, ipp->C, ipp->D);
}
double sqr (double x) [inline]
Definition at line 59 of file interpol.c.
{ return x*x; }