FMD: fmd/Isospin.c File Reference
fmd/Isospin.c File Reference
#include <complex.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "Isospin.h"
#include "numerics/cmath.h"
Functions
void calcIsospin (const SlaterDet *Q, const SlaterDetAux *X, double *t2)
void calcIsospinod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *t2)
void calct3HF (const SlaterDet *Q, const SlaterDetAux *X, void *mes)
Detailed Description
calculate T^2
(c) 2003 Thomas Neff
Definition in file Isospin.c.
Function Documentation
void calcIsospin (const SlaterDet * Q, const SlaterDetAux * X, double * t2)
Definition at line 49 of file Isospin.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), and dim.
Referenced by calcObservables().
{
  double isoone, isotwo;
  OneBodyOperator op_ob_isospin = {dim: 1, opt: 1, par: NULL, me: ob_isospin};
  TwoBodyOperator op_tb_isospin = {dim: 1, opt: 0, par: NULL, me: tb_isospin};
  calcSlaterDetOBME(Q, X, &op_ob_isospin, &isoone);
  calcSlaterDetTBME(Q, X, &op_tb_isospin, &isotwo);
  *t2 = isoone+isotwo;
}
void calcIsospinod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * t2)
Definition at line 64 of file Isospin.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), and dim.
Referenced by calcObservablesod().
{
  complex double isoone, isotwo;
  OneBodyOperator op_ob_isospin = {dim: 1, opt: 1, par: NULL, me: ob_isospin};
  TwoBodyOperator op_tb_isospin = {dim: 1, opt: 0, par: NULL, me: tb_isospin};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_isospin, &isoone);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_isospin, &isotwo);
  *t2 = isoone+isotwo;
}
void calct3HF (const SlaterDet * Q, const SlaterDetAux * X, void * mes)
Definition at line 79 of file Isospin.c.
References calcSlaterDetOBHFMEs(), and dim.
Referenced by main().
{
  OneBodyOperator op_ob_t3 = {dim: 1, opt: 1, par: NULL, me: ob_t3};
  calcSlaterDetOBHFMEs(Q, X, &op_ob_t3, mes);
}