FMD: fmd/KineticEnergy.h File Reference
fmd/KineticEnergy.h File Reference
#include "SlaterDet.h"
Functions
void calcT (const SlaterDet *Q, const SlaterDetAux *X, double *t)
void calcTod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *t)
void calcTHF (const SlaterDet *Q, const SlaterDetAux *X, void *mes)
Detailed Description
calculate kinetic energy
(c) 2003 Thomas Neff
Definition in file KineticEnergy.h.
Function Documentation
void calcT (const SlaterDet * Q, const SlaterDetAux * X, double * t)
Definition at line 32 of file KineticEnergy.c.
References calcSlaterDetOBME(), dim, and par.
Referenced by calcHamiltonian(), calcHamiltonianmpi(), and calcObservables().
{
  OneBodyOperator op_ob_t = {dim: 1, opt: 1, par: NULL, me: ob_t};
  calcSlaterDetOBME(Q, X, &op_ob_t, t);
}
void calcTHF (const SlaterDet * Q, const SlaterDetAux * X, void * mes)
Definition at line 49 of file KineticEnergy.c.
References calcSlaterDetOBHFMEs(), dim, and par.
Referenced by calcHamiltonianHF().
{
  OneBodyOperator op_ob_t = {dim: 1, opt: 1, par: NULL, me: ob_t};
  calcSlaterDetOBHFMEs(Q, X, &op_ob_t, mes);
}
void calcTod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * t)
Definition at line 40 of file KineticEnergy.c.
References calcSlaterDetOBMEod(), dim, and par.
Referenced by calcHamiltonianod(), calcHamiltonianodmpi(), and calcObservablesod().
{
  OneBodyOperator op_ob_t = {dim: 1, opt: 1, par: NULL, me: ob_t};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_t, t);
}