FMD: numerics/lapack.h File Reference
numerics/lapack.h File Reference
#include <complex.h>
#include "fortranc.h"
Functions
void FORTRAN() dposv (const char *UPLO, const int *N, const int *NRHS, double *A, const int *LDA, double *B, const int *LDB, int *INFO)
compute the solution to a real system of linear equations A*X = B
void FORTRAN() dsyev (const char *JOBZ, const char *UPLO, const int *N, double *A, const int *LDA, double *W, double *WORK, const int *LWORK, int *INFO)
void FORTRAN() zpotrf (const char *UPLO, const int *N, complex double *A, const int *LDA, int *INFO)
cholesky factorization of complex Hermitian positive definite matrix A
void FORTRAN() zpotri (const char *UPLO, const int *N, complex double *A, const int *LDA, int *INFO)
void FORTRAN() zgetrf (const int *M, const int *N, complex double *A, const int *LDA, int *IPIV, int *INFO)
compute an LU factorization of a general M-by-N matrix A
void FORTRAN() zgetri (const int *N, complex double *A, const int *LDA, int *IPIV, complex double *WORK, const int *LWORK, int *INFO)
void FORTRAN() zdet (const complex double *A, const int *LDA, const int *N, int *IPIV, complex double *DET)
void FORTRAN() zgesvd (const char *JOBU, const char *JOBVT, const int *M, const int *N, complex double *A, const int *LDA, double *S, complex double *U, const int *LDU, complex double *VT, const int *LDVT, complex double *WORK, const int *LWORK, double *RWORK, int *INFO)
compute the singular value decomposition (SVD) of a complex matrix
void FORTRAN() zgeev (const char *JOBVL, const char *JOBVR, const int *N, complex double *A, const int *LDA, complex double *W, complex double *VL, const int *LDVL, complex double *VR, const int *LDVR, complex double *WORK, const int *LWORK, double *RWORK, int *INFO)
compute the eigenvalues and eigenvectors of complex matrix A
Function Documentation
void FORTRAN() dposv (const char * UPLO, const int * N, const int * NRHS, double * A, const int * LDA, double * B, const int * LDB, int * INFO)
compute the solution to a real system of linear equations A*X = B
void FORTRAN() dsyev (const char * JOBZ, const char * UPLO, const int * N, double * A, const int * LDA, double * W, double * WORK, const int * LWORK, int * INFO)
compute all eigenvalues and, optionally, eigenvectors of a real symmetric matrix A
Referenced by calcOrientedOrientation(), and calcSpatialOrientation().
void FORTRAN() zdet (const complex double * A, const int * LDA, const int * N, int * IPIV, complex double * DET)
calculate determinant of matrix using the LU factorization computed by zgetrf
Referenced by calcSlaterDetAuxod(), and calcSlaterDetAuxodsingular().
void FORTRAN() zgeev (const char * JOBVL, const char * JOBVR, const int * N, complex double * A, const int * LDA, complex double * W, complex double * VL, const int * LDVL, complex double * VR, const int * LDVR, complex double * WORK, const int * LWORK, double * RWORK, int * INFO)
compute the eigenvalues and eigenvectors of complex matrix A
Referenced by eigensystem(), and generalizedeigensystem().
void FORTRAN() zgesvd (const char * JOBU, const char * JOBVT, const int * M, const int * N, complex double * A, const int * LDA, double * S, complex double * U, const int * LDU, complex double * VT, const int * LDVT, complex double * WORK, const int * LWORK, double * RWORK, int * INFO)
compute the singular value decomposition (SVD) of a complex matrix
Referenced by calcSlaterDetAuxodsingular(), generalizedeigensystem(), and pseudoinverse().
void FORTRAN() zgetrf (const int * M, const int * N, complex double * A, const int * LDA, int * IPIV, int * INFO)
compute an LU factorization of a general M-by-N matrix A
Referenced by calcSlaterDetAuxod(), and calcSlaterDetAuxodsingular().
void FORTRAN() zgetri (const int * N, complex double * A, const int * LDA, int * IPIV, complex double * WORK, const int * LWORK, int * INFO)
computes the inverse of a matrix using the LU factorization computed by zgetrf
Referenced by calcSlaterDetAuxod().
void FORTRAN() zpotrf (const char * UPLO, const int * N, complex double * A, const int * LDA, int * INFO)
cholesky factorization of complex Hermitian positive definite matrix A
Referenced by calcSlaterDetAux().
void FORTRAN() zpotri (const char * UPLO, const int * N, complex double * A, const int * LDA, int * INFO)
inverse of complex Hermitian positive definite matrix A using Cholesky factorization computed by zpotrf
Referenced by calcSlaterDetAux().