FMD: minenergyconorthogonalproj.c File Reference
minenergyconorthogonalproj.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <math.h>
#include <complex.h>
#include "fmd/Parameterization.h"
#include "fmd/ParameterizationFMD.h"
#include "fmd/SlaterDet.h"
#include "fmd/Interaction.h"
#include "fmd/Hamiltonian.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/gradHamiltonian.h"
#include "fmd/Oscillator.h"
#include "fmd/gradOscillator.h"
#include "fmd/Constraint.h"
#include "fmd/ConstraintCM.h"
#include "fmd/ConstraintT2.h"
#include "fmd/ConstraintS2.h"
#include "fmd/ConstraintJ2.h"
#include "fmd/ConstraintJ2.h"
#include "fmd/ConstraintR2.h"
#include "fmd/ConstraintDipole.h"
#include "fmd/ConstraintQuadrupole.h"
#include "fmd/ConstraintOctupole.h"
#include "fmd/CenterofMass.h"
#include "fmd/SpatialOrientation.h"
#include "fmd/Observables.h"
#include "MinimizerDONLP2orthogonalproj.h"
#include "misc/physics.h"
#include "misc/utils.h"
#include "numerics/zcw.h"
Defines
#define SQR(x) (x)*(x)
#define MAXCONSTRAINT 10
Functions
void cleanup (int ret)
int main (int argc, char *argv[])
Detailed Description
minimize energy of constrained and projected Slater determinant that is orthogonal to a given projected Slater determinant
(c) 2003-2006 Thomas Neff
Definition in file minenergyconorthogonalproj.c.
Define Documentation
#define MAXCONSTRAINT 10
Definition at line 64 of file minenergyconorthogonalproj.c.
#define SQR (x) (x)*(x)
Definition at line 62 of file minenergyconorthogonalproj.c.
Function Documentation
void cleanup (int ret)
Definition at line 67 of file minenergyconorthogonalproj.c.
References BroadcastTask().
{
  // stop all mpi clients
#ifdef MPI
  int task=TASKFIN;
  BroadcastTask(&task);
  MPI_Finalize();
#endif
  // terminate program with return code
  exit(ret);
}
int main (int argc, char * argv[])
Definition at line 83 of file minenergyconorthogonalproj.c.
References SlaterDet::A, AngmomtoStr(), backup(), BroadcastA(), BroadcastInteraction(), BroadcastTask(), calcObservables(), calcorthprojectedHamiltonian(), calcprojectedHamiltonian(), cleanup(), Interaction::cm, Const, ConstraintCM, ConstraintDetQ, ConstraintED2, ConstraintEO2, ConstraintEQ2, ConstraintER2, ConstraintJ2, ConstraintJ2, ConstraintO2, ConstraintQ2, ConstraintR2, ConstraintS2, ConstraintT2, createinfo(), fprintinfo(), fprintObservables(), h0, hbc, initAngintegration(), initSlaterDetAux(), initWork(), Int, j, k, log, maxsteps, MinimizeDONLP2orthproj(), MinimizerprojSlave(), moveboostorientSlaterDet(), mpirank, mpisize, n0, Interaction::name, Para::name, Parameterization::name, nconst, P, par, Parameterization::Paraclone, Parameterization::ParainitSlaterDet, Parameterization::ParatoSlaterDet, Parameterization::Parawrite, projpar, q, Q, Q0, readInteractionfromFile(), readParafromFile(), readSlaterDetfromFile(), shakePara(), SlaterDetinitFMD(), SQR, usertime(), val, Constraint::val, writeSlaterDet(), and X.
{
  createinfo(argc, argv);
#ifdef MPI
  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &mpirank);
  MPI_Comm_size(MPI_COMM_WORLD, &mpisize);
  // fprintf(stderr, "... [%2d] %s\n", mpirank, hostname());
  if (mpirank != 0) {
    MinimizerprojSlave();
    MPI_Finalize();
  } else {
#endif
  int c;
  int cm=1;
  int j=0;
  int selk=0, k;
  int par=0;
  int overwrite=0;
  int log=0;
  int maxsteps=250;
  double shakemag=0.0;
  int constcm=1, constT2=0, constS2=0, constL2=0, constLS=0, constJ2=0;
  int constj2=0;
  int constmradius=0, constmquadrupole=0, constmoctupole=0;
  int consteradius=0, constedipole=0, constequadrupole=0, consteoctupole=0;
  int constbeta=0, constgamma=0;
  double constT2val=0.0, constS2val=0.0;
  double constL2val=0.0, constLSval=0.0, constJ2val=0.0;
  double constj2val=0.0;
  double constmrval=0.0, constmqval=0.0, constmoval=0.0;
  double consterval=0.0, constedval=0.0, consteqval=0.0, consteoval=0.0;
  double constbval=0.0, constgval=0.0;
  Constraint Const[MAXCONSTRAINT];
  int nconst = 0;
  if (argc < 5) {
    fprintf(stderr, "\nusage: %s PROJPARA interaction fixslaterdetfile slaterdetfile\n"
            "\n   -j J            project onto angular momentum"
            "\n   -K K            project onto K"
            "\n   -p[+1|-1]       project onto parity"
            "\n   -l EVERY        log EVERY step"
            "\n   -o              overwrite in all cases"
            "\n   -m MAXSTEPS     maximum number of steps (default %d)"
            "\n   -s MAGNITUDE    shake parameters before minimization"
            "\n   -T T2           constrain isospin"
            "\n   -L l2           constrain single-particle l2"
            "\n   -S ls           constrain single-particle ls"
            "\n   -J J2           constrain angular momentum"
            "\n   -j j2           constrain single-particle angular momentum"
            "\n   -R RADIUS       constrain radius"
            "\n   -D DIPOLE       constrain dipole moments"
            "\n   -Q QUADRUPOLE   constrain quadrupole moments"
            "\n   -O OCTUPOLE     constrain octupole moments"
            "\n   -B BETA         constrain quadrupole deformation"
            "\n   -G GAMMA        constrain quadrupole deformation\n"
            // "\n   -I Jz           cranking constrain"
            , argv[0], maxsteps);
    cleanup(-1);
  }
  while((c = getopt(argc, argv, "j:K:p:Lol:m:s:T:L:S:J:R:D:Q:O:B:G:")) != -1)
    switch (c) {
    case 'j':
      j = atoi(optarg);
      break;
    case 'K':
      selk = 1;
      k = atoi(optarg);
      break;
    case 'p':
      par = atoi(optarg);
      break;
    case 'o':
      overwrite = 1;
      break;
    case 'l':
      log = atoi(optarg);
      break;
    case 'm':
      maxsteps = atoi(optarg);
      break;
    case 's':
      shakemag = atof(optarg);
      break;
    case 'T':
      constT2 = 1;
      constT2val = atof(optarg);
      break;
    case 'L':
      constL2 = 1;
      constL2val = atof(optarg);
      break;
    case 'S':
      constS2 = 1;
      constS2val = atof(optarg);
      break;
    case 'J':
      constJ2 = 1;
      constJ2val = atof(optarg);
      break;
      /*
    case 'j':
      constj2 = 1;
      constj2val = atof(optarg);
      break;
      */
    case 'R':
      if (optarg[0] == 'E') {
        consteradius = 1;
        consterval = atof(optarg+2);
      } else {
        constmradius = 1;
        constmrval = atof(optarg);
      }
      break;
    case 'D':
      constedipole = 1;
      constedval = atof(optarg);
      break;
    case 'Q':
      if (optarg[0] == 'E') {
        constequadrupole = 1;
        consteqval = atof(optarg+2);
      } else {
        constmquadrupole = 1;
        constmqval = atof(optarg);
      }
      break;
    case 'O':
      if (optarg[0] == 'E') {
        consteoctupole = 1;
        consteoval = atof(optarg+2);
      } else {
        constmoctupole = 1;
        constmoval = atof(optarg);
      }
      break;
    case 'B':
      constbeta = 1;
      constbval = atof(optarg);
      break;
    case 'G':
      constgamma = 1;
      constgval = atof(optarg);
      break;
    }
  if (constcm) {
    Const[nconst] = ConstraintCM;
    nconst++;
  }
  if (constT2) {
    Const[nconst] = ConstraintT2;
    Const[nconst].val = constT2val;
    nconst++;
  }
  if (constS2) {
    Const[nconst] = ConstraintS2;
    Const[nconst].val = constS2val;
    nconst++;
  }
/*   if (constL2) { */
/*     Const[nconst] = ConstraintL2; */
/*     Const[nconst].val = constL2val; */
/*     nconst++; */
/*   } */
/*   if (constLS) { */
/*     Const[nconst] = ConstraintLS; */
/*     Const[nconst].val = constLSval; */
/*     nconst++; */
/*   } */
  if (constJ2) {
    Const[nconst] = ConstraintJ2;
    Const[nconst].val = constJ2val;
    nconst++;
  }
  if (constj2) {
    Const[nconst] = ConstraintJ2;
    Const[nconst].val = constj2val;
    nconst++;
  }
  if (constmradius) {
    Const[nconst] = ConstraintR2;
    Const[nconst].val = SQR(constmrval);
    nconst++;
  }
  if (consteradius) {
    Const[nconst] = ConstraintER2;
    Const[nconst].val = SQR(consterval);
    nconst++;
  }
  if (constedipole) {
    Const[nconst] = ConstraintED2;
    Const[nconst].val = constedval;
    nconst++;
  }
  if (constmquadrupole) {
    Const[nconst] = ConstraintQ2;
    Const[nconst].val = constmqval;
    nconst++;
  }
  if (constequadrupole) {
    Const[nconst] = ConstraintEQ2;
    Const[nconst].val = consteqval;
    nconst++;
  }
  if (constmoctupole) {
    Const[nconst] = ConstraintO2;
    Const[nconst].val = constmoval;
    nconst++;
  }
  if (consteoctupole) {
    Const[nconst] = ConstraintEO2;
    Const[nconst].val = consteoval;
    nconst++;
  }
  if (constbeta) {
    Const[nconst] = ConstraintQ2;
    Const[nconst].val = sqrt(24*M_PI/5)*constbval;
    nconst++;
  }
  if (constgamma) {
    if (!constbeta) {
      fprintf(stderr, "gamma constraint only in combination with beta constraint\n");
      exit(-1);
    }
    Const[nconst] = ConstraintDetQ;
    Const[nconst].val = sqrt(4*M_PI/5)*constbval*cbrt(2*cos(3*constgval*M_PI/180));
    nconst++;
  }
  char* projpar = argv[optind];
  char* interactionfile = argv[optind+1];
  char* fixmbfile = argv[optind+2];
  char* parafile = argv[optind+3];
  // set up angular integration
  angintegrationpara AngPar;
  initAngintegration(&AngPar, projpar);
  Interaction Int;
  if (readInteractionfromFile(&Int, interactionfile))
    cleanup(-1);
  Int.cm = cm;
  SlaterDet Q0;
  if (readSlaterDetfromFile(&Q0, fixmbfile)) {
    fprintf(stderr, "couldn't read %s\n", fixmbfile);
    cleanup(-1);
  }
  if (!par)
    par = (Q0.A % 2) ? -1 : +1;
  if (!selk)
    k = (Q0.A % 2) ? 1 : 0;
  Parameterization P;
  Para qinitial;
  if (readParafromFile(&P, &qinitial, parafile)) {
    fprintf(stderr, "couldn't read %s\n", parafile);
    cleanup(-1);
  }
#ifdef MPI
  int task=TASKSTART;
  BroadcastTask(&task);
  BroadcastInteraction(&Int);
  BroadcastA(&Q0.A);
#endif
  initWork(&Q0);
  double n0, h0;
#ifdef MPI
  calcprojectedHamiltonianmpi(&Q0, &Int,
                              j, k, par, &AngPar,
                              &h0, &n0);
#else
  calcprojectedHamiltonian(&Q0, &Int,
                           j, k, par, &AngPar,
                           &h0, &n0);
#endif
  SlaterDet Q;
  SlaterDetAux X;
  P.ParainitSlaterDet(&qinitial, &Q);
  initSlaterDetAux(&Q, &X);
  P.ParatoSlaterDet(&qinitial, &Q);
  double einitial, eintr;
  moveboostorientSlaterDet(&Q, &X);
#ifdef MPI
  calcorthprojectedHamiltonianmpi(&Q0, h0, n0,
                                  &Q, &Int,
                                  j, k, par, &AngPar,
                                  &eintr, &einitial);
#else
  calcorthprojectedHamiltonian(&Q0, h0, n0,
                               &Q, &Int,
                               j, k, par, &AngPar,
                               &eintr, &einitial);
#endif
  for (int i=0; i<nconst; i++)
    fprintf(stderr, "# constraining %4s to %8.3f\n",
            Const[i].label, Const[i].output(Const[i].val));
  fprintf(stderr, "\ninitial:\tE = %8.3f MeV,   Eintr = %8.3f MeV\n\n",
          hbc*einitial, hbc*eintr);
  Para q;
  P.Paraclone(&qinitial, &q);
  // shaking the parameters ?
  if (shakemag) {
    shakePara(&q, shakemag);
  }
  // in FMD parameterization move SlaterDet to origin in phase space
  // if (!strcmp(P.name, "FMD")) {
  //   P.ParatoSlaterDet(&q, &Q);
  //   moveboostorientSlaterDet(&Q, &X);
  //   SlaterDetinitFMD(&Q, &q);
  // }
  // minimize !
  MinimizeDONLP2orthproj(&Int, j, k, par, &AngPar, &Q0, h0, n0,
                         Const, nconst, &P, &q, maxsteps,
                         log, parafile);
  double e;
  P.ParatoSlaterDet(&q, &Q);
#ifdef MPI
  calcorthprojectedHamiltonianmpi(&Q0, h0, n0,
                                  &Q, &Int,
                                  j, k, par, &AngPar,
                                  &eintr, &e);
#else
  calcorthprojectedHamiltonian(&Q0, h0, n0,
                               &Q, &Int,
                               j, k, par, &AngPar,
                               &eintr, &e);
#endif
  fprintf(stderr, "\nfinal:  \tE = %8.3f MeV\n\n", hbc*e);
  // no improvement ? then write initial parameters
  if (!overwrite && einitial < e)
    P.Paraclone(&qinitial, &q);
  P.ParatoSlaterDet(&q, &Q);
  // orient SlaterDet
  // in FMD parameterization we copy the relocated SlaterDet
  moveboostorientSlaterDet(&Q, &X);
  // moveboostSlaterDet(&Q, &X);
  if (!strcmp(P.name, "FMD"))
    SlaterDetinitFMD(&Q, &q);
  // calculate the observables
  Observables Obs;
  calcObservables(&Int, &Q, &Obs);
  backup(parafile);
  fprintf(stderr, "... writing Parameters to file %s\n", parafile);
  FILE* outfp;
  if (!(outfp = fopen(parafile, "w"))) {
    fprintf(stderr, "couldn't open %s for writing\n", parafile);
    exit(-1);
  }
  fprintinfo(outfp);
  fprintf(outfp, "\n# minimized %s for %s in %s parameterization\n"
          "# orthogonal to state %s\n"
          "# using %s interaction\n",
          cm ? "< Hintr >" : "< H >", q.name, P.name, fixmbfile, Int.name);
  fprintf(outfp, "\n# projected on J^pi = %s, K = %d\n",
          AngmomtoStr(j, par == +1 ? 0 : 1), k);
  fprintf(outfp, "\n# projected energy: %8.3f\n", e*hbc);
  fprintObservables(outfp, &Int, &Q, &Obs);
  fprintf(outfp, "\n# Parameterization\n");
  fprintf(outfp, "<Parameterization %s>\n", P.name);
  P.Parawrite(outfp, &q);
  fprintf(outfp, "\n# SlaterDet\n");
  writeSlaterDet(outfp, &Q);
  fclose(outfp);
  fprintf(stderr, "... %4.2f minutes computing time used\n", usertime()/60.0);
  cleanup(0);
#ifdef MPI
  }
#endif
}