FMD: MinimizerDONLP2.h File Reference
MinimizerDONLP2.h File Reference
#include "fmd/Interaction.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/Parameterization.h"
#include "fmd/Constraint.h"
#include "numerics/donlp2.h"
Functions
void MinimizeDONLP2 (const Interaction *Int, const Constraint *Const, int nconst, Parameterization *P, Para *q, int maxsteps, int log, const char *logfile)
Detailed Description
using the minimization routine donlp2
(c) 2003 Thomas Neff
Definition in file MinimizerDONLP2.h.
Function Documentation
void MinimizeDONLP2 (const Interaction * Int, const Constraint * Const, int nconst, Parameterization * P, Para * q, int maxsteps, int log, const char * logfile)
Definition at line 92 of file MinimizerDONLP2.c.
References catchterminate(), donlp2(), env, FORTRAN, initgradSlaterDet(), initgradSlaterDetAux(), initSlaterDetAux(), and x.
Referenced by main().
{
#ifndef MPI
  // handler for INT and TERM signals
  signal(SIGINT, catchterminate);
  signal(SIGTERM, catchterminate);
#endif
  Min.log = log;
  Min.logfile = logfile;
  Min.maxsteps = maxsteps;
  Min.Int = Int;
  Min.Const = Const;
  Min.nconst = nconst;
  Min.q = q;
  Min.P = P;
  Min.Q = (SlaterDet*) malloc(sizeof(SlaterDet));
  Min.X = (SlaterDetAux*) malloc(sizeof(SlaterDetAux));
  Min.dX = (gradSlaterDetAux*) malloc(sizeof(gradSlaterDetAux));
  Min.dH = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.P->ParainitSlaterDet(q, Min.Q);
  initSlaterDetAux(Min.Q, Min.X);
  initgradSlaterDetAux(Min.Q, Min.dX);
  initgradSlaterDet(Min.Q, Min.dH);
#ifndef MPI
  // regular program execution or catched signal ?
  if (!setjmp(env))
#endif
    FORTRAN(donlp2)();
  copyxtopara(FORTRAN(o8xdat).x, Min.q);
}