FMD: MinimizerDONLP2par.c File Reference
MinimizerDONLP2par.c File Reference
#include <signal.h>
#include <stdlib.h>
#include <setjmp.h>
#include <string.h>
#include <math.h>
#include "fmd/Interaction.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/Parameterization.h"
#include "fmd/Constraint.h"
#include "fmd/ConstraintCM.h"
#include "numerics/donlp2.h"
#include "fmd/Hamiltonian.h"
#include "fmd/gradHamiltonian.h"
#include "MinimizerDONLP2par.h"
#include "numerics/fortranc.h"
#include "misc/physics.h"
Defines
#define NGAUSS 12
#define APOS 4
#define SQR(x) ((x)*(x))
Functions
void catchterminate (int sig)
void MinimizeDONLP2par (const Interaction *Int, int par, const Constraintod *Const, int nconst, Parameterization *P, Para *q, int maxsteps)
void FORTRAN() ef (const double *x, double *fx)
void FORTRAN() egradf (const double *x, double *gradf)
void FORTRAN() eg (int *i, const double *x, double *gxi)
void FORTRAN() egradg (int *i, const double *x, double *gradgi)
void FORTRAN() eh (int *i, const double *x, double *hxi)
void FORTRAN() egradh (int *i, const double *x, double *gradhi)
void FORTRAN() setup0 (void)
void FORTRAN() setup (void)
Variables
jmp_buf env
volatile sig_atomic_t sigterminate
Detailed Description
using the minimization routine donlp2
this is ugly as hell, but it works !
(c) 2003 Thomas Neff
Definition in file MinimizerDONLP2par.c.
Define Documentation
#define APOS 4
Definition at line 20 of file MinimizerDONLP2par.c.
Referenced by eg(), and setup0().
#define NGAUSS 12
Definition at line 19 of file MinimizerDONLP2par.c.
Referenced by eg(), and setup0().
#define SQR (x) ((x)*(x))
Definition at line 228 of file MinimizerDONLP2par.c.
Function Documentation
void catchterminate (int sig)
Definition at line 54 of file MinimizerDONLP2par.c.
References catchterminate(), and sigterminate.
{
  sigterminate = 1;
  fprintf(stderr, "... catched signal - terminate minimization\n");
  signal(sig, catchterminate);
}
void FORTRAN() ef (const double * x, double * fx)
Definition at line 136 of file MinimizerDONLP2par.c.
References calcHamiltonianod(), calcHamiltonianodmpi(), calcSlaterDetAuxod(), copySlaterDet(), env, FORTRAN, invertSlaterDet(), sigterminate, and x.
{
  complex double hd, hp, nd, np;
  if (sigterminate)
    longjmp(env, 1);
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAuxod(Min.Q, Min.Q, Min.X);
  nd = Min.X->ovlap;
#ifdef MPI
  calcHamiltonianodmpi(Min.Int, Min.Q, Min.Q, Min.X, &hd);
#else
  calcHamiltonianod(Min.Int, Min.Q, Min.Q, Min.X, &hd);
#endif
  copySlaterDet(Min.Q, Min.Qp);
  invertSlaterDet(Min.Qp);
  calcSlaterDetAuxod(Min.Q, Min.Qp, Min.X);
  np = Min.X->ovlap;
#ifdef MPI
  calcHamiltonianodmpi(Min.Int, Min.Q, Min.Qp, Min.X, &hp);
#else
  calcHamiltonianod(Min.Int, Min.Q, Min.Qp, Min.X, &hp);
#endif
  *fx = (hd+Min.par*hp)/(nd+Min.par*np);
  FORTRAN(o8cnt).icf++;
}
void FORTRAN() eg (int * i, const double * x, double * gxi)
Definition at line 215 of file MinimizerDONLP2par.c.
References APOS, NGAUSS, and x.
{
  if (!strcmp(Min.P->name, "FMD")) {
    *gxi = x[(*i-1)*NGAUSS+APOS];
  }
}
void FORTRAN() egradf (const double * x, double * gradf)
Definition at line 166 of file MinimizerDONLP2par.c.
References addmulttogradSlaterDet(), calcgradHamiltonianod(), calcgradHamiltonianodmpi(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcSlaterDetAuxod(), copySlaterDet(), env, FORTRAN, hbc, icgf, invertSlaterDet(), N, sigterminate, x, and zerogradSlaterDet().
{
  complex double hd, hp, nd, np;
  complex double H, N;
  if (sigterminate)
    longjmp(env, 1);
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAuxod(Min.Q, Min.Q, Min.X);
  calcgradSlaterDetAuxod(Min.Q, Min.Q, Min.X, Min.dX);
  calcgradOvlapod(Min.Q, Min.Q, Min.X, Min.dX, Min.dNd);
#ifdef MPI
  calcgradHamiltonianodmpi(Min.Int, Min.Q, Min.Q, Min.X, Min.dX, Min.dHd);
#else
  calcgradHamiltonianod(Min.Int, Min.Q, Min.Q, Min.X, Min.dX, Min.dHd);
#endif
  hd = Min.dHd->val;
  nd = Min.X->ovlap;
  copySlaterDet(Min.Q, Min.Qp);
  invertSlaterDet(Min.Qp);
  calcSlaterDetAuxod(Min.Q, Min.Qp, Min.X);
  calcgradSlaterDetAuxod(Min.Q, Min.Qp, Min.X, Min.dX);
  calcgradOvlapod(Min.Q, Min.Qp, Min.X, Min.dX, Min.dNp);
#ifdef MPI
  calcgradHamiltonianodmpi(Min.Int, Min.Q, Min.Qp, Min.X, Min.dX, Min.dHp);
#else
  calcgradHamiltonianod(Min.Int, Min.Q, Min.Qp, Min.X, Min.dX, Min.dHp);
#endif
  hp = Min.dHp->val;
  np = Min.X->ovlap;
  H = hd+Min.par*hp;
  N = nd+Min.par*np;
  zerogradSlaterDet(Min.dH);
  addmulttogradSlaterDet(Min.dH, Min.dHd, 1.0/N);
  addmulttogradSlaterDet(Min.dH, Min.dHp, Min.par* 1.0/N);
  addmulttogradSlaterDet(Min.dH, Min.dNd, -H/(N*N));
  addmulttogradSlaterDet(Min.dH, Min.dNp, -Min.par*H/(N*N));
  Min.P->ParaprojectgradSlaterDet(Min.q, Min.dH, gradf);
  FORTRAN(o8cnt).icgf++;
  fprintf(stderr, "step %3d: \tE = %8.3f (%8.3f) MeV\n",
          FORTRAN(o8cnt).icgf, hbc*creal(H/N), hbc*creal(hd/nd));
}
void FORTRAN() egradg (int * i, const double * x, double * gradgi)
Definition at line 223 of file MinimizerDONLP2par.c.
{
}
void FORTRAN() egradh (int * i, const double * x, double * gradhi)
Definition at line 284 of file MinimizerDONLP2par.c.
References addmulttogradSlaterDet(), calcgradOvlapod(), calcgradSlaterDetAux(), calcgradSlaterDetAuxod(), calcSlaterDetAux(), calcSlaterDetAuxod(), ConstraintCM, copySlaterDet(), Constraintod::dim, env, Constraintod::gradme, Constraint::gradme, Constraintod::gradneedsme, invertSlaterDet(), j, Constraintod::label, Constraint::label, Constraintod::me, N, Constraintod::output, Constraint::output, sigterminate, x, and zerogradSlaterDet().
{
  if (sigterminate)
    longjmp(env, 1);
  // First constraint is CM constraint
  if (*i == 1) {
    Constraint* cnst = &ConstraintCM;
    copyxtopara(x, Min.q);
    Min.P->ParatoSlaterDet(Min.q, Min.Q);
    calcSlaterDetAux(Min.Q, Min.X);
    calcgradSlaterDetAux(Min.Q, Min.X, Min.dX);
    zerogradSlaterDet(Min.dH);
    cnst->gradme(Min.Q, Min.X, Min.dX, Min.dH);
    Min.P->ParaprojectgradSlaterDet(Min.q, Min.dH, gradhi);
    fprintf(stderr, "\t\t\t\t\t%4s = %8.3f\n",
            cnst->label, cnst->output(Min.dH->val));
  } else {
    Constraintod* cnst = &Min.Const[*i-1];
    complex double nd, np, hd, hp;
    complex double N, H;
    double expme[cnst->dim];
    copyxtopara(x, Min.q);
    Min.P->ParatoSlaterDet(Min.q, Min.Q);
    copySlaterDet(Min.Q, Min.Qp);
    invertSlaterDet(Min.Qp);
    calcSlaterDetAuxod(Min.Q, Min.Q, Min.X);
    nd = Min.X->ovlap;
    calcSlaterDetAuxod(Min.Q, Min.Qp, Min.Xp);
    np = Min.Xp->ovlap;
    N = nd+Min.par*np;
    if (cnst->gradneedsme) {
      complex double med[cnst->dim], mep[cnst->dim];
      cnst->me(Min.Q, Min.Q, Min.X, med);
      cnst->me(Min.Q, Min.Qp, Min.Xp, mep);
      int j;
      for (j=0; j<cnst->dim; j++)
        expme[j] = (med[j] + Min.par* mep[j])/N;
    }
    calcgradSlaterDetAuxod(Min.Q, Min.Q, Min.X, Min.dX);
    calcgradOvlapod(Min.Q, Min.Q, Min.X, Min.dX, Min.dNd);
    zerogradSlaterDet(Min.dHd);
    cnst->gradme(Min.Q, Min.Q, Min.X, Min.dX, expme, Min.dHd);
    hd = Min.dHd->val;
    calcgradSlaterDetAuxod(Min.Q, Min.Qp, Min.Xp, Min.dX);
    calcgradOvlapod(Min.Q, Min.Qp, Min.Xp, Min.dX, Min.dNp);
    zerogradSlaterDet(Min.dHp);
    cnst->gradme(Min.Q, Min.Qp, Min.Xp, Min.dX, expme, Min.dHp);
    hp = Min.dHp->val;
    H = hd+Min.par*hp;
    zerogradSlaterDet(Min.dH);
    addmulttogradSlaterDet(Min.dH, Min.dHd, 1.0/N);
    addmulttogradSlaterDet(Min.dH, Min.dHp, Min.par* 1.0/N);
    addmulttogradSlaterDet(Min.dH, Min.dNd, -H/(N*N));
    addmulttogradSlaterDet(Min.dH, Min.dNp, -Min.par*H/(N*N));
    Min.P->ParaprojectgradSlaterDet(Min.q, Min.dH, gradhi);
    fprintf(stderr, "\t\t\t\t\t%4s = %8.3f (%8.3f)\n",
            cnst->label, cnst->output(creal(H/N)), cnst->output(creal(hd/nd)));
  }
}
void FORTRAN() eh (int * i, const double * x, double * hxi)
Definition at line 230 of file MinimizerDONLP2par.c.
References calcSlaterDetAux(), calcSlaterDetAuxod(), ConstraintCM, copySlaterDet(), Constraintod::dim, env, invertSlaterDet(), j, Constraintod::me, Constraint::me, sigterminate, SQR, Constraintod::val, and x.
{
  if (sigterminate)
    longjmp(env, 1);
  // First Constraint is CM constraint
  if (*i == 1) {
    Constraint* cnst = &ConstraintCM;
    copyxtopara(x, Min.q);
    Min.P->ParatoSlaterDet(Min.q, Min.Q);
    calcSlaterDetAux(Min.Q, Min.X);
    cnst->me(Min.Q, Min.X, hxi);
  } else {
    Constraintod* cnst = &Min.Const[*i-1];
    complex double nd, np;
    complex double med[cnst->dim], mep[cnst->dim];
    double expme[cnst->dim];
    int j;
    copyxtopara(x, Min.q);
    Min.P->ParatoSlaterDet(Min.q, Min.Q);
    calcSlaterDetAuxod(Min.Q, Min.Q, Min.X);
    nd = Min.X->ovlap;
    copySlaterDet(Min.Q, Min.Qp);
    invertSlaterDet(Min.Qp);
    calcSlaterDetAuxod(Min.Q, Min.Qp, Min.Xp);
    np = Min.Xp->ovlap;
    cnst->me(Min.Q, Min.Q, Min.X, med);
    cnst->me(Min.Q, Min.Qp, Min.Xp, mep);
    for (j=0; j<cnst->dim; j++)
      expme[j] = (med[j] + Min.par* mep[j])/(nd + Min.par* np);
    if (cnst->dim==1)
      *hxi = expme[0];
    else {
      double hctcr = 0.0;
      for (j=0; j<cnst->dim; j++)
        hctcr += SQR(expme[j]);
      *hxi = sqrt(hctcr);
    }
    *hxi -= cnst->val;
  }
}
void MinimizeDONLP2par (const Interaction * Int, int par, const Constraintod * Const, int nconst, Parameterization * P, Para * q, int maxsteps)
Definition at line 90 of file MinimizerDONLP2par.c.
References catchterminate(), donlp2(), env, FORTRAN, initgradSlaterDet(), initgradSlaterDetAux(), initSlaterDetAux(), and x.
Referenced by main().
{
  // handler for INT and TERM signals
  signal(SIGINT, catchterminate);
  signal(SIGTERM, catchterminate);
  Min.maxsteps = maxsteps;
  Min.Int = Int;
  Min.par = par;
  Min.Const = Const;
  Min.nconst = nconst;
  Min.q = q;
  Min.P = P;
  Min.Q = (SlaterDet*) malloc(sizeof(SlaterDet));
  Min.Qp = (SlaterDet*) malloc(sizeof(SlaterDet));
  Min.X = (SlaterDetAux*) malloc(sizeof(SlaterDetAux));
  Min.Xp = (SlaterDetAux*) malloc(sizeof(SlaterDetAux));
  Min.dX = (gradSlaterDetAux*) malloc(sizeof(gradSlaterDetAux));
  Min.dH = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.dHd = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.dHp = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.dNd = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.dNp = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.P->ParainitSlaterDet(q, Min.Q);
  Min.P->ParainitSlaterDet(q, Min.Qp);
  initSlaterDetAux(Min.Q, Min.X);
  initSlaterDetAux(Min.Q, Min.Xp);
  initgradSlaterDetAux(Min.Q, Min.dX);
  initgradSlaterDet(Min.Q, Min.dH);
  initgradSlaterDet(Min.Q, Min.dHd);
  initgradSlaterDet(Min.Q, Min.dHp);
  initgradSlaterDet(Min.Q, Min.dNd);
  initgradSlaterDet(Min.Q, Min.dNp);
  // regular program execution or catched signal ?
  if (!setjmp(env))
    FORTRAN(donlp2)();
  copyxtopara(FORTRAN(o8xdat).x, Min.q);
}
void FORTRAN() setup (void)
Definition at line 399 of file MinimizerDONLP2par.c.
References FORTRAN.
{
  FORTRAN(o8stpa).te0 = 0;
  FORTRAN(o8stpa).te1 = 0;
  FORTRAN(o8par).iterma = Min.maxsteps-1;
}
void FORTRAN() setup0 (void)
Definition at line 363 of file MinimizerDONLP2par.c.
References APOS, FORTRAN, and NGAUSS.
{
  int i;
  FORTRAN(o8dim).n = Min.q->n;
  FORTRAN(o8dim).nh = Min.nconst;
  // in case of FMD parametrization use bound constraints for Re{a}
  if (!strcmp(Min.P->name, "FMD")) {
    FORTRAN(o8dim).ng = Min.q->ngauss;
    for (i=0; i<Min.nconst+1; i++) {
      FORTRAN(o8gri).gunit[i][0] = -1;
      FORTRAN(o8gri).gunit[i][1] = 0;
      FORTRAN(o8gri).gunit[i][2] = 0;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      FORTRAN(o8gri).gunit[i+Min.nconst+1][0] = 1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][1] = i*NGAUSS+APOS+1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][2] = 1;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      if (Min.q->x[i*NGAUSS+APOS] < 0)
        Min.q->x[i*NGAUSS+APOS] = 1.0+1.0*rand()/RAND_MAX;
    }
  } else
    FORTRAN(o8dim).ng = 0;
  FORTRAN(o8stpa).analyt = 1;
  FORTRAN(o8stpa).cold = 1;
  FORTRAN(o8par).tau0 = 20.0;
  FORTRAN(o8par).del0 = 0.0;
  FORTRAN(o8stpa).silent = 1;
  for (i=0; i<Min.q->n; i++)
    FORTRAN(o8xdat).x[i] = Min.q->x[i];
}
Variable Documentation
const Constraintod* Const
Definition at line 68 of file MinimizerDONLP2par.c.
gradSlaterDet* dH
Definition at line 77 of file MinimizerDONLP2par.c.
gradSlaterDet * dHd
Definition at line 77 of file MinimizerDONLP2par.c.
gradSlaterDet * dHp
Definition at line 77 of file MinimizerDONLP2par.c.
gradSlaterDet * dNd
Definition at line 77 of file MinimizerDONLP2par.c.
gradSlaterDet * dNp
Definition at line 77 of file MinimizerDONLP2par.c.
gradSlaterDetAux* dX
Definition at line 76 of file MinimizerDONLP2par.c.
jmp_buf env
Definition at line 50 of file MinimizerDONLP2par.c.
const Interaction* Int
Definition at line 66 of file MinimizerDONLP2par.c.
int maxsteps
Definition at line 65 of file MinimizerDONLP2par.c.
int nconst
Definition at line 69 of file MinimizerDONLP2par.c.
Parameterization* P
Definition at line 71 of file MinimizerDONLP2par.c.
int par
Definition at line 67 of file MinimizerDONLP2par.c.
Para* q
Definition at line 70 of file MinimizerDONLP2par.c.
SlaterDet* Q
Definition at line 72 of file MinimizerDONLP2par.c.
SlaterDet* Qp
Definition at line 73 of file MinimizerDONLP2par.c.
volatile sig_atomic_t sigterminate
Definition at line 52 of file MinimizerDONLP2par.c.
SlaterDetAux* X
Definition at line 74 of file MinimizerDONLP2par.c.
SlaterDetAux* Xp
Definition at line 75 of file MinimizerDONLP2par.c.
Referenced by ob_parity().