FMD: MinimizerDONLP2p.c File Reference
MinimizerDONLP2p.c File Reference
#include <signal.h>
#include <stdlib.h>
#include <setjmp.h>
#include <string.h>
#include "fmd/Interaction.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/Parameterization.h"
#include "fmd/Constraint.h"
#include "numerics/donlp2.h"
#include "fmd/Hamiltonian.h"
#include "fmd/gradHamiltonian.h"
#include "MinimizerDONLP2p.h"
#include "numerics/fortranc.h"
#include "misc/physics.h"
#include "misc/utils.h"
Defines
#define NGAUSS 12
#define APOS 4
#define AMIN 1.0
Functions
void catchterminate (int sig)
void MinimizeDONLP2p (const Interaction *Int, int par, const Constraint *Const, int nconst, Parameterization *P, Para *q, int maxsteps, int log, const char *logfile)
void FORTRAN() ef (const double *x, double *fx)
void FORTRAN() egradf (const double *x, double *gradf)
void FORTRAN() eg (int *i, const double *x, double *gxi)
void FORTRAN() egradg (int *i, const double *x, double *gradgi)
void FORTRAN() eh (int *i, const double *x, double *hxi)
void FORTRAN() egradh (int *i, const double *x, double *gradhi)
void FORTRAN() setup0 (void)
void FORTRAN() setup (void)
Variables
jmp_buf env
volatile sig_atomic_t sigterminate
Detailed Description
using the minimization routine donlp2
this is ugly as hell, but it works !
(c) 2003 Thomas Neff
Definition in file MinimizerDONLP2p.c.
Define Documentation
#define AMIN 1.0
Definition at line 238 of file MinimizerDONLP2p.c.
Referenced by eg().
#define APOS 4
Definition at line 20 of file MinimizerDONLP2p.c.
Referenced by eg(), and setup0().
#define NGAUSS 12
Definition at line 19 of file MinimizerDONLP2p.c.
Referenced by eg(), and setup0().
Function Documentation
void catchterminate (int sig)
Definition at line 53 of file MinimizerDONLP2p.c.
References catchterminate(), and sigterminate.
{
  sigterminate = 1;
  fprintf(stderr, "... catched signal - terminate minimization\n");
  signal(sig, catchterminate);
}
void FORTRAN() ef (const double * x, double * fx)
Definition at line 136 of file MinimizerDONLP2p.c.
References calcHamiltonianod(), calcHamiltonianodmpi(), calcSlaterDetAuxod(), copySlaterDet(), env, FORTRAN, hbc, invertSlaterDet(), sigterminate, and x.
{
  complex double hd, hp, nd, np;
  if (sigterminate)
    longjmp(env, 1);
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAuxod(Min.Q, Min.Q, Min.X);
  nd = Min.X->ovlap;
#ifdef MPI
  calcHamiltonianodmpi(Min.Int, Min.Q, Min.Q, Min.X, &hd);
#else
  calcHamiltonianod(Min.Int, Min.Q, Min.Q, Min.X, &hd);
#endif
  copySlaterDet(Min.Q, Min.Qp);
  invertSlaterDet(Min.Qp);
  calcSlaterDetAuxod(Min.Q, Min.Qp, Min.X);
  np = Min.X->ovlap;
#ifdef MPI
  calcHamiltonianodmpi(Min.Int, Min.Q, Min.Qp, Min.X, &hp);
#else
  calcHamiltonianod(Min.Int, Min.Q, Min.Qp, Min.X, &hp);
#endif
  *fx = (hd+Min.par*hp)/(nd+Min.par*np);
  FORTRAN(o8cnt).icf++;
  fprintf(stderr, "\t\t\tme      E = %8.3f MeV,   Eintr = %8.3f MeV\n",
          hbc* (*fx), hbc*creal(hd/nd));
}
void FORTRAN() eg (int * i, const double * x, double * gxi)
Definition at line 240 of file MinimizerDONLP2p.c.
References AMIN, APOS, NGAUSS, and x.
{
  if (!strcmp(Min.P->name, "FMD")) {
    *gxi = (x[(*i-1)*NGAUSS+APOS] - AMIN);
  } else if (!strcmp(Min.P->name, "AMD") || !strcmp(Min.P->name, "AMDS")) {
    // only i=1 possible
    *gxi = (x[Min.q->n] - AMIN);
  }
}
void FORTRAN() egradf (const double * x, double * gradf)
Definition at line 169 of file MinimizerDONLP2p.c.
References addmulttogradSlaterDet(), calcgradHamiltonianod(), calcgradHamiltonianodmpi(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcSlaterDetAuxod(), copySlaterDet(), env, FORTRAN, fprintinfo(), hbc, icgf, invertSlaterDet(), N, sigterminate, writeSlaterDet(), x, and zerogradSlaterDet().
{
  complex double hd, hp, nd, np;
  complex double H, N;
  if (sigterminate)
    longjmp(env, 1);
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAuxod(Min.Q, Min.Q, Min.X);
  calcgradSlaterDetAuxod(Min.Q, Min.Q, Min.X, Min.dX);
  calcgradOvlapod(Min.Q, Min.Q, Min.X, Min.dX, Min.dNd);
#ifdef MPI
  calcgradHamiltonianodmpi(Min.Int, Min.Q, Min.Q, Min.X, Min.dX, Min.dHd);
#else
  calcgradHamiltonianod(Min.Int, Min.Q, Min.Q, Min.X, Min.dX, Min.dHd);
#endif
  hd = Min.dHd->val;
  nd = Min.X->ovlap;
  copySlaterDet(Min.Q, Min.Qp);
  invertSlaterDet(Min.Qp);
  calcSlaterDetAuxod(Min.Q, Min.Qp, Min.X);
  calcgradSlaterDetAuxod(Min.Q, Min.Qp, Min.X, Min.dX);
  calcgradOvlapod(Min.Q, Min.Qp, Min.X, Min.dX, Min.dNp);
#ifdef MPI
  calcgradHamiltonianodmpi(Min.Int, Min.Q, Min.Qp, Min.X, Min.dX, Min.dHp);
#else
  calcgradHamiltonianod(Min.Int, Min.Q, Min.Qp, Min.X, Min.dX, Min.dHp);
#endif
  hp = Min.dHp->val;
  np = Min.X->ovlap;
  H = hd+Min.par*hp;
  N = nd+Min.par*np;
  zerogradSlaterDet(Min.dH);
  addmulttogradSlaterDet(Min.dH, Min.dHd, 1.0/N);
  addmulttogradSlaterDet(Min.dH, Min.dHp, Min.par* 1.0/N);
  addmulttogradSlaterDet(Min.dH, Min.dNd, -H/(N*N));
  addmulttogradSlaterDet(Min.dH, Min.dNp, -Min.par*H/(N*N));
  Min.P->ParaprojectgradSlaterDet(Min.q, Min.dH, gradf);
  FORTRAN(o8cnt).icgf++;
  fprintf(stderr, "grad %3d: \tE = %8.3f MeV,   Eintr = %8.3f MeV\n",
          FORTRAN(o8cnt).icgf, hbc*creal(H/N), hbc*creal(hd/nd));
  if (Min.log && !(FORTRAN(o8cnt).icgf % Min.log)) {
    char logfname[255];
    sprintf(logfname, "%s.minp.%03d.log", Min.logfile, FORTRAN(o8cnt).icgf);
    FILE* logfp;
    if (!(logfp = fopen(logfname, "w"))) {
      fprintf(stderr, "couldn't open %s for writing\n", logfname);
    } else {
      fprintinfo(logfp);
      fprintf(logfp, "# step %3d: \tE = %8.3f MeV,   Eintr = %8.3f MeV\n",
              FORTRAN(o8cnt).icgf, hbc*creal(H/N), hbc*creal(hd/nd));
      fprintf(logfp, "\n# Parameterization\n");
      fprintf(logfp, "<Parameterization %s>\n", Min.P->name);
      Min.P->Parawrite(logfp, Min.q);
      fprintf(logfp, "\n# SlaterDet\n");
      writeSlaterDet(logfp, Min.Q);
      fclose(logfp);
    }
  }
}
void FORTRAN() egradg (int * i, const double * x, double * gradgi)
Definition at line 251 of file MinimizerDONLP2p.c.
{
}
void FORTRAN() egradh (int * i, const double * x, double * gradhi)
Definition at line 273 of file MinimizerDONLP2p.c.
References calcgradSlaterDetAux(), calcSlaterDetAux(), env, sigterminate, x, and zerogradSlaterDet().
{
  if (sigterminate)
    longjmp(env, 1);
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAux(Min.Q, Min.X);
  calcgradSlaterDetAux(Min.Q, Min.X, Min.dX);
  zerogradSlaterDet(Min.dH);
  Min.Const[*i-1].gradme(Min.Q, Min.X, Min.dX, Min.dH);
  Min.P->ParaprojectgradSlaterDet(Min.q, Min.dH, gradhi);
  fprintf(stderr, "\t\t\tgrad %4s = %8.3f\n",
          Min.Const[*i-1].label, Min.Const[*i-1].output(Min.dH->val));
}
void FORTRAN() eh (int * i, const double * x, double * hxi)
Definition at line 256 of file MinimizerDONLP2p.c.
References calcSlaterDetAux(), env, sigterminate, and x.
{
  if (sigterminate)
    longjmp(env, 1);
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAux(Min.Q, Min.X);
  Min.Const[*i-1].me(Min.Q, Min.X, hxi);
  fprintf(stderr, "\t\t\tme   %4s = %8.3f\n",
          Min.Const[*i-1].label, Min.Const[*i-1].output(*hxi));
  *hxi -= Min.Const[*i-1].val;
}
void MinimizeDONLP2p (const Interaction * Int, int par, const Constraint * Const, int nconst, Parameterization * P, Para * q, int maxsteps, int log, const char * logfile)
Definition at line 90 of file MinimizerDONLP2p.c.
References catchterminate(), donlp2(), env, FORTRAN, initgradSlaterDet(), initgradSlaterDetAux(), initSlaterDetAux(), and x.
Referenced by main().
{
  // handler for INT and TERM signals
  signal(SIGINT, catchterminate);
  signal(SIGTERM, catchterminate);
  Min.log = log;
  Min.logfile = logfile;
  Min.maxsteps = maxsteps;
  Min.Int = Int;
  Min.par = par;
  Min.Const = Const;
  Min.nconst = nconst;
  Min.q = q;
  Min.P = P;
  Min.Q = (SlaterDet*) malloc(sizeof(SlaterDet));
  Min.Qp = (SlaterDet*) malloc(sizeof(SlaterDet));
  Min.X = (SlaterDetAux*) malloc(sizeof(SlaterDetAux));
  Min.dX = (gradSlaterDetAux*) malloc(sizeof(gradSlaterDetAux));
  Min.dH = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.dHd = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.dHp = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.dNd = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.dNp = (gradSlaterDet*) malloc(sizeof(gradSlaterDet));
  Min.P->ParainitSlaterDet(q, Min.Q);
  Min.P->ParainitSlaterDet(q, Min.Qp);
  initSlaterDetAux(Min.Q, Min.X);
  initgradSlaterDetAux(Min.Q, Min.dX);
  initgradSlaterDet(Min.Q, Min.dH);
  initgradSlaterDet(Min.Q, Min.dHd);
  initgradSlaterDet(Min.Q, Min.dHp);
  initgradSlaterDet(Min.Q, Min.dNd);
  initgradSlaterDet(Min.Q, Min.dNp);
  // regular program execution or catched signal ?
  if (!setjmp(env))
    FORTRAN(donlp2)();
  copyxtopara(FORTRAN(o8xdat).x, Min.q);
}
void FORTRAN() setup (void)
Definition at line 338 of file MinimizerDONLP2p.c.
References FORTRAN.
{
  FORTRAN(o8stpa).te0 = 0;
  FORTRAN(o8stpa).te1 = 0;
  FORTRAN(o8par).iterma = Min.maxsteps-1;
}
void FORTRAN() setup0 (void)
Definition at line 289 of file MinimizerDONLP2p.c.
References APOS, FORTRAN, and NGAUSS.
{
  int i;
  FORTRAN(o8dim).n = Min.q->n;
  FORTRAN(o8dim).nh = Min.nconst;
  // in case of FMD parametrization use bound constraints for Re{a_i}
  if (!strcmp(Min.P->name, "FMD")) {
    FORTRAN(o8dim).ng = Min.q->ngauss;
    for (i=0; i<Min.nconst+1; i++) {
      FORTRAN(o8gri).gunit[i][0] = -1;
      FORTRAN(o8gri).gunit[i][1] = 0;
      FORTRAN(o8gri).gunit[i][2] = 0;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      FORTRAN(o8gri).gunit[i+Min.nconst+1][0] = 1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][1] = i*NGAUSS+APOS+1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][2] = 1;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      if (Min.q->x[i*NGAUSS+APOS] < 0)
        Min.q->x[i*NGAUSS+APOS] = 1.0+1.0*rand()/RAND_MAX;
    }
  // for AMD parameterizations use bound constraints for Re{a}
  } else if (!strcmp(Min.P->name, "AMD") || !strcmp(Min.P->name, "AMDS")) {
    FORTRAN(o8dim).ng = 1;
    for (i=0; i<Min.nconst+1; i++) {
      FORTRAN(o8gri).gunit[i][0] = -1;
      FORTRAN(o8gri).gunit[i][1] = 0;
      FORTRAN(o8gri).gunit[i][2] = 0;
    }
    FORTRAN(o8gri).gunit[Min.nconst+1][0] = 1;
    FORTRAN(o8gri).gunit[Min.nconst+1][1] = Min.q->n;
    FORTRAN(o8gri).gunit[Min.nconst+1][2] = 1;
    if (Min.q->x[Min.q->n-1] < 0)
      Min.q->x[Min.q->n-1] = 1.0+1.0*rand()/RAND_MAX;
  } else
    FORTRAN(o8dim).ng = 0;
  FORTRAN(o8stpa).analyt = 1;
  FORTRAN(o8stpa).cold = 1;
  FORTRAN(o8par).tau0 = 20.0;
  FORTRAN(o8par).del0 = 0.0;
  FORTRAN(o8stpa).silent = 1;
  for (i=0; i<Min.q->n; i++)
    FORTRAN(o8xdat).x[i] = Min.q->x[i];
}
Variable Documentation
const Constraint* Const
Definition at line 69 of file MinimizerDONLP2p.c.
gradSlaterDet* dH
Definition at line 77 of file MinimizerDONLP2p.c.
gradSlaterDet * dHd
Definition at line 77 of file MinimizerDONLP2p.c.
gradSlaterDet * dHp
Definition at line 77 of file MinimizerDONLP2p.c.
gradSlaterDet * dNd
Definition at line 77 of file MinimizerDONLP2p.c.
gradSlaterDet * dNp
Definition at line 77 of file MinimizerDONLP2p.c.
gradSlaterDetAux* dX
Definition at line 76 of file MinimizerDONLP2p.c.
jmp_buf env
Definition at line 49 of file MinimizerDONLP2p.c.
const Interaction* Int
Definition at line 67 of file MinimizerDONLP2p.c.
int log
Definition at line 64 of file MinimizerDONLP2p.c.
const char* logfile
Definition at line 65 of file MinimizerDONLP2p.c.
int maxsteps
Definition at line 66 of file MinimizerDONLP2p.c.
int nconst
Definition at line 70 of file MinimizerDONLP2p.c.
Parameterization* P
Definition at line 72 of file MinimizerDONLP2p.c.
int par
Definition at line 68 of file MinimizerDONLP2p.c.
Para* q
Definition at line 71 of file MinimizerDONLP2p.c.
SlaterDet* Q
Definition at line 73 of file MinimizerDONLP2p.c.
SlaterDet* Qp
Definition at line 74 of file MinimizerDONLP2p.c.
volatile sig_atomic_t sigterminate
Definition at line 51 of file MinimizerDONLP2p.c.
SlaterDetAux* X
Definition at line 75 of file MinimizerDONLP2p.c.