FMD: MinimizerDONLP2vapp.h File Reference
MinimizerDONLP2vapp.h File Reference
#include "fmd/Interaction.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/Parameterization.h"
#include "fmd/Constraint.h"
#include "fmd/Projection.h"
Functions
void initWork (int j, int par, angintegrationpara *angpara, const Interaction *Int, const SlaterDet *Q)
void calcprojectedHamiltonian (const SlaterDet *Q, const Interaction *Int, int j, int par, int ival, angintegrationpara *angpara, double *eintr, double *eproj)
void MinimizeDONLP2vapp (const Interaction *Int, int j, int par, int ival, double threshkmix, double minnormkmix, double alpha, angintegrationpara *projpar, const Constraint *Const, int nconst, Parameterization *P, Para *q, int maxsteps, int log, const char *logfile)
Detailed Description
using the minimization routine donlp2
(c) 2003-2006 Thomas Neff
Definition in file MinimizerDONLP2vapp.h.
Function Documentation
void calcprojectedHamiltonian (const SlaterDet * Q, const Interaction * Int, int j, int par, int ival, angintegrationpara * angpara, double * eintr, double * eproj)
Definition at line 179 of file MinimizerDONLP2orthogonalproj.c.
References ALLOWEDJ2DEVIATION, calcConstraintJ2od(), calcHamiltonianod(), calcOrientedOrientation(), calcprojectedHamiltonianmatrix(), calcSlaterDetAuxod(), calcTCMod(), copySlaterDet(), dim, expect(), getangintegrationpoint(), H, hbc, invertangles(), invertSlaterDet(), J2, kmixingstates(), multcmat(), N, angintegrationpara::n, n, orientationinverted(), SlaterDetAux::ovlap, Qp, Qpp, rotateSlaterDet(), V, and X.
{
  SlaterDet* Qp = Work.Qp;
  SlaterDet* Qpp = Work.Qpp;
  SlaterDetAux* X = Work.X;
  int n = projpar->n;
  double alpha, beta, gamma, w;
#ifdef ORIENTED
  double alpha0, beta0, gamma0;
#endif
  complex double hme, nme, j2me;
  complex double H=0.0, N=0.0, J2=0.0;
  complex double hintr, nintr;
  copySlaterDet(Q, Qp);
#ifdef ORIENTED
  calcSlaterDetAuxod(Qp, Qp, X);
  calcOrientedOrientation(Qp, X, &alpha0, &beta0, &gamma0);
  if (orientationinverted(alpha0, beta0, gamma0, lalpha0, lbeta0, lgamma0))
    invertangles(&alpha0, &beta0, &gamma0);
  fprintf(stderr, "... (alpha, beta, gamma) = (%5.2f, %5.2f, %5.2f)\n",
          alpha0*180/M_PI, beta0*180/M_PI, gamma0*180/M_PI);
  rotateSlaterDet(Qp, -gamma0, -beta0, -alpha0);
#endif
  calcSlaterDetAuxod(Qp, Qp, X);
  nintr = X->ovlap;
  calcHamiltonianod(Int, Qp, Qp, X, &hintr);
#ifdef RANDOMIZED
  double alpharan, gammaran;
  alpharan = 0.005*2*M_PI*rand()/RAND_MAX;
  gammaran = 0.005*2*M_PI*rand()/RAND_MAX;
#endif
  int i, ip;
  for (i=0; i<n; i++) {
    copySlaterDet(Qp, Qpp);
    getangintegrationpoint(i, projpar, &alpha, &beta, &gamma, &w);
#ifdef RANDOMIZED
    alpha += alpharan;
    gamma += gammaran;
#endif
    rotateSlaterDet(Qpp, alpha, beta, gamma);
    for (ip=0; ip<=1; ip++) {
      if (ip) invertSlaterDet(Qpp);
      calcSlaterDetAuxod(Qp, Qpp, X);
      nme = X->ovlap;
      calcHamiltonianod(Int, Qp, Qpp, X, &hme);
      calcConstraintJ2od(Qp, Qpp, X, &j2me);
      H += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*Djmkstar(j,k,k,alpha,beta,gamma)*hme;
      N += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*Djmkstar(j,k,k,alpha,beta,gamma)*nme;
      J2 += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*Djmkstar(j,k,k,alpha,beta,gamma)*j2me;
    }
  }
  fprintf(stderr, "... n: %9.7f, J2: %6.3f\n",
          creal(N/nintr),
          creal(J2/N));
  *hproj = creal(H);
  *nproj = creal(N);
}
void initWork (int j, int par, angintegrationpara * angpara, const Interaction * Int, const SlaterDet * Q)
Definition at line 713 of file MinimizerDONLP2vapp.c.
References initgradSlaterDet(), initgradSlaterDetAux(), initSlaterDet(), and initSlaterDetAux().
{
  int k;
  Work.Qp = malloc(sizeof(SlaterDet));
  Work.Qpp = malloc(sizeof(SlaterDet));
  Work.X = malloc(sizeof(SlaterDetAux));
  Work.dX = malloc(sizeof(gradSlaterDetAux));
  initSlaterDet(Q, Work.Qp);
  initSlaterDet(Q, Work.Qpp);
  initSlaterDetAux(Q, Work.X);
  initgradSlaterDetAux(Q, Work.dX);
  Work.dH = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
  Work.dN = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
  for (k=0; k<(j+1)*(j+1); k++) {
    initgradSlaterDet(Q, &Work.dH[k]);
    initgradSlaterDet(Q, &Work.dN[k]);
  }
  Work.dhproj = malloc(sizeof(gradSlaterDet));
  Work.dnproj = malloc(sizeof(gradSlaterDet));
  initgradSlaterDet(Q, Work.dhproj);
  initgradSlaterDet(Q, Work.dnproj);
  Work.V = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.H = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.N = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.J2 = malloc((j+1)*(j+1)*sizeof(complex double));
}
void MinimizeDONLP2vapp (const Interaction * Int, int j, int par, int ival, double threshkmix, double minnormkmix, double alpha, angintegrationpara * projpar, const Constraint * Const, int nconst, Parameterization * P, Para * q, int maxsteps, int log, const char * logfile)
Definition at line 949 of file MinimizerDONLP2vapp.c.
References catchterminate(), donlp2(), env, FORTRAN, optite, and Parameterization::ParainitSlaterDet.
Referenced by main().
{
#ifndef MPI
  // handler for INT and TERM signals
  signal(SIGINT, catchterminate);
  signal(SIGTERM, catchterminate);
#endif
  Min.maxsteps = maxsteps;
  Min.log = log;
  Min.logfile = logfile;
  Min.Int = Int;
  Min.j = j;
  Min.par = par;
  Min.ival = ival;
  Min.threshkmix = threshkmix;
  Min.minnormkmix = minnormkmix;
  Min.alpha = alpha;
  Min.projpar = projpar;
  Min.Const = Const;
  Min.nconst = nconst;
  Min.q = q;
  Min.P = P;
  Min.Q = malloc(sizeof(SlaterDet));
  P->ParainitSlaterDet(q, Min.Q);
#ifndef MPI
  // regular program execution or catched signal ?
  if (!setjmp(env))
#endif
    FORTRAN(donlp2)();
  fprintf(stderr, "donlp2 terminated because of criterium %d\n",
          (int) FORTRAN(o8itin).optite + 11);
  copyxtopara(FORTRAN(o8xdat).x, Min.q);
}