FMD: MinimizerDONLP2vappiso.c File Reference
MinimizerDONLP2vappiso.c File Reference
#include <signal.h>
#include <stdlib.h>
#include <setjmp.h>
#include <string.h>
#include <math.h>
#include "fmd/Interaction.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/Parameterization.h"
#include "fmd/Constraint.h"
#include "fmd/ConstraintJ2.h"
#include "fmd/Projection.h"
#include "numerics/donlp2.h"
#include "fmd/Hamiltonian.h"
#include "fmd/gradHamiltonian.h"
#include "MinimizerDONLP2vappiso.h"
#include "numerics/fortranc.h"
#include "numerics/wignerd.h"
#include "numerics/lapack.h"
#include "numerics/cmat.h"
#include "misc/physics.h"
#include "misc/utils.h"
Defines
#define NGAUSS 12
#define APOS 4
#define MINIMUMA 0.0001
#define ALLOWEDJ2DEVIATION 0.1
#define ENERGYPENALTY 10000.0/hbc
#define THRESHKMIX 0.1
#define MINNORMKMIX 0.01
#define THRESHMULTI 0.0000001
#define ORIENTED
#define M_2PI (2*M_PI)
#define M_PI2 (M_PI*M_PI)
Functions
void catchterminate (int sig)
void kmixingstates (complex double *H, complex double *N, int j, double thresh, double *egood, complex double *Vgood, int *ngood)
void calcprojectedHamiltonianmatrix (const SlaterDet *Q, const SlaterDet *Qp, const Interaction *Int, int j, int par, int iso, angintegrationpara *angpara, complex double *H, complex double *N, complex double *J2)
void calcgradprojectedHamiltonianmatrix (const SlaterDet *Q, const SlaterDet *Qp, const Interaction *Int, int j, int par, int iso, angintegrationpara *angpara, complex double *H, complex double *N, gradSlaterDet *dH, gradSlaterDet *dN)
void initWork (int j, int par, int iso, angintegrationpara *AngPar, const Interaction *Int, const SlaterDet *Q)
void calcprojectedHamiltonian (const SlaterDet *Q, const Interaction *Int, int j, int par, int iso, int ival, angintegrationpara *angpara, double *eintr, double *eproj)
void calcgradprojectedHamiltonian (const SlaterDet *Q, const Interaction *Int, int j, int par, int iso, int ival, angintegrationpara *angpara, double *eintr, double *eproj)
void MinimizeDONLP2vappiso (const Interaction *Int, int j, int par, int iso, int ival, double alpha, angintegrationpara *projpar, const Constraint *Const, int nconst, Parameterization *P, Para *q, int maxsteps, int log, const char *logfile)
void FORTRAN() ef (const double *x, double *fx)
void FORTRAN() egradf (const double *x, double *gradf)
void FORTRAN() eg (int *i, const double *x, double *gxi)
void FORTRAN() egradg (int *i, const double *x, double *gradgi)
void FORTRAN() eh (int *i, const double *x, double *hxi)
void FORTRAN() egradh (int *i, const double *x, double *gradhi)
void FORTRAN() setup0 (void)
void FORTRAN() setup (void)
Variables
jmp_buf env
volatile sig_atomic_t sigterminate
Define Documentation
#define ALLOWEDJ2DEVIATION 0.1
Definition at line 57 of file MinimizerDONLP2vappiso.c.
#define APOS 4
Definition at line 21 of file MinimizerDONLP2vappiso.c.
Referenced by eg(), and setup0().
#define ENERGYPENALTY 10000.0/hbc
Definition at line 58 of file MinimizerDONLP2vappiso.c.
#define M_2PI (2*M_PI)
Definition at line 138 of file MinimizerDONLP2vappiso.c.
#define M_PI2 (M_PI*M_PI)
Definition at line 139 of file MinimizerDONLP2vappiso.c.
Referenced by calcgradprojectedHamiltonianmatrix(), and calcprojectedHamiltonianmatrix().
#define MINIMUMA 0.0001
Definition at line 56 of file MinimizerDONLP2vappiso.c.
Referenced by eg().
#define MINNORMKMIX 0.01
Definition at line 62 of file MinimizerDONLP2vappiso.c.
Referenced by kmixingstates().
#define NGAUSS 12
Definition at line 20 of file MinimizerDONLP2vappiso.c.
Referenced by eg(), and setup0().
#define ORIENTED
Definition at line 73 of file MinimizerDONLP2vappiso.c.
#define THRESHKMIX 0.1
Definition at line 61 of file MinimizerDONLP2vappiso.c.
Referenced by calcgradprojectedHamiltonian(), and calcprojectedHamiltonian().
#define THRESHMULTI 0.0000001
Definition at line 65 of file MinimizerDONLP2vappiso.c.
Function Documentation
void calcgradprojectedHamiltonian (const SlaterDet * Q, const Interaction * Int, int j, int par, int iso, int ival, angintegrationpara * angpara, double * eintr, double * eproj)
Definition at line 1096 of file MinimizerDONLP2vappiso.c.
References addmulttogradSlaterDet(), calcgradprojectedHamiltonianmatrix(), calcHamiltonianod(), calcOrientedOrientation(), calcSlaterDetAuxod(), copySlaterDet(), dhproj, dim, dnproj, expect(), hbc, invertangles(), kmixingstates(), multcmat(), multgradSlaterDet(), orientationinverted(), SlaterDetAux::ovlap, rotategradSlaterDet(), rotateSlaterDet(), THRESHKMIX, V, and X.
{
  SlaterDet* Qp = Work.Qp;
  SlaterDetAux* X = Work.X;
  complex double* H = Work.H;
  complex double* N = Work.N;
  complex double* J2 = Work.J2;
  complex double* V = Work.V;
  int dim = Work.dim;
  gradSlaterDet* dH = Work.dH;
  gradSlaterDet* dN = Work.dN;
  gradSlaterDet* dhproj = Work.dhproj;
  gradSlaterDet* dnproj = Work.dnproj;
#ifdef ORIENTED
  double alpha0, beta0, gamma0;
#endif
  copySlaterDet(Q, Qp);
#ifdef ORIENTED
  calcSlaterDetAuxod(Qp, Qp, X);
  calcOrientedOrientation(Qp, X, &alpha0, &beta0, &gamma0);
  if (orientationinverted(alpha0, beta0, gamma0, lalpha0, lbeta0, lgamma0)) {
    fprintf(stderr, "... angles inverted\n");
    invertangles(&alpha0, &beta0, &gamma0);
  }
  fprintf(stderr, "... (alpha, beta, gamma) = (%5.2f, %5.2f, %5.2f)\n",
          alpha0*180/M_PI, beta0*180/M_PI, gamma0*180/M_PI);
  rotateSlaterDet(Qp, -gamma0, -beta0, -alpha0);
  lalpha0 = alpha0; lbeta0 = beta0; lgamma0 = gamma0;
#endif
  complex double hintr, nintr;
  calcSlaterDetAuxod(Qp, Qp, X);
  nintr = X->ovlap;
  calcHamiltonianod(Int, Qp, Qp, X, &hintr);
  *eintr= creal(hintr/nintr);
  // projected matrix elements for Qp
  calcgradprojectedHamiltonianmatrix(Qp, Qp, Int, j, par, iso, angpara,
                                     H, N,
                                     dH, dN);
  // K-mixing for Qp
  double ed[j+1];
  kmixingstates(H, N, j, THRESHKMIX,
                ed, V, &dim);
  if (!dim) {
    fprintf(stderr, "no good eigenstate for Q !\n");
  }
  complex double N2[(j+1)*(j+1)];
  multcmat(N, N, N2, j+1);
  complex double hproj[j+1], nproj[j+1], n2proj[j+1], j2proj[j+1];
  int i;
  for (i=0; i<dim; i++) {
    hproj[i] = expect(j+1, H, &V[i*(j+1)]);
    nproj[i] = expect(j+1, N, &V[i*(j+1)]);
    n2proj[i] = expect(j+1, N2, &V[i*(j+1)]);
    j2proj[i] = expect(j+1, J2, &V[i*(j+1)]);
  }
  for (i=0; i<dim; i++)
    fprintf(stderr, "Q eigenstate %d: E = %8.3f MeV, n = %8.7f, J2 = %6.3f\n", i,
            hbc*creal(hproj[i]/nproj[i]), creal(n2proj[i]/(nintr*nproj[i])), creal(j2proj[i]/nproj[i]));
  *eproj = creal(hproj[ival]/nproj[ival]);
  // gradients
  gradexpect(j+1, dH, &V[ival*(j+1)], dhproj);
  gradexpect(j+1, dN, &V[ival*(j+1)], dnproj);
  multgradSlaterDet(dhproj, 1.0/nproj[ival]);
  addmulttogradSlaterDet(dhproj, dnproj, -hproj[ival]/(nproj[ival]*nproj[ival]));
#ifdef ORIENTED
  rotategradSlaterDet(dhproj, alpha0, beta0, gamma0);
#endif
}
void calcgradprojectedHamiltonianmatrix (const SlaterDet * Q, const SlaterDet * Qp, const Interaction * Int, int j, int par, int iso, angintegrationpara * angpara, complex double * H, complex double * N, gradSlaterDet * dH, gradSlaterDet * dN)
Definition at line 617 of file MinimizerDONLP2vappiso.c.
References addmulttogradSlaterDet(), calcgradHamiltonianod(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcSlaterDetAuxod(), copySlaterDet(), dh, dn, dX, getangintegrationpoint(), invertSlaterDet(), M_PI2, mirrorSlaterDet(), angintegrationpara::n, SlaterDetAux::ovlap, reinitangintegration(), rotateSlaterDet(), gradSlaterDet::val, X, and zerogradSlaterDet().
{
  SlaterDet* Qpp = Work.Qpp;
  SlaterDetAux* X = Work.X;
  gradSlaterDet* dh = Work.dhproj;
  gradSlaterDet* dn = Work.dnproj;
  gradSlaterDetAux* dX = Work.dX;
  int nang = angpara->n;
  reinitangintegration(Q, Qp, 0, 0, angpara);
  int k,kp;
  for (kp=-j; kp<=j; kp=kp+2)
    for (k=-j; k<=j; k=k+2) {
      H[idxjmk(j,k,kp)] = 0.0;
      N[idxjmk(j,k,kp)] = 0.0;
      zerogradSlaterDet(&dH[idxjmk(j,k,kp)]);
      zerogradSlaterDet(&dN[idxjmk(j,k,kp)]);
    }
  double alpha, beta, gamma, w;
  int i, ip, iiso;
  for (i=0; i<nang; i++) {
    for (ip=0; ip<=1; ip++) {
      for (iiso=0; iiso<=1; iiso++) {
        copySlaterDet(Qp, Qpp);
        getangintegrationpoint(i, angpara, &alpha, &beta, &gamma, &w);
        rotateSlaterDet(Qpp, alpha, beta, gamma);
        if (ip) invertSlaterDet(Qpp);
        if (iiso) mirrorSlaterDet(Qpp);
        calcSlaterDetAuxod(Q, Qpp, X);
        calcgradSlaterDetAuxod(Q, Qpp, X, dX);
        calcgradOvlapod(Q, Qpp, X, dX, dn);
        dn->val = X->ovlap;
        calcgradHamiltonianod(Int, Q, Qpp, X, dX, dh);
        for (kp=-j; kp<=j; kp=kp+2)
          for (k=-j; k<=j; k=k+2) {
            H[idxjmk(j,k,kp)] += w/4*(ip ? par : 1)*(iiso ? iso : 1)*
              (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma)*dh->val;
            N[idxjmk(j,k,kp)] += w/4*(ip ? par : 1)*(iiso ? iso : 1)*
              (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma)*dn->val;
            addmulttogradSlaterDet(&dH[idxjmk(j,k,kp)], dh,
                                   w/4*(ip ? par : +1)*(iiso ? iso : 1)*
                                   (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma));
            addmulttogradSlaterDet(&dN[idxjmk(j,k,kp)], dn,
                                   w/4*(ip ? par : +1)*(iiso ? iso : 1)*
                                   (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma));
          }
      }
    }
  }
}
void calcprojectedHamiltonian (const SlaterDet * Q, const Interaction * Int, int j, int par, int iso, int ival, angintegrationpara * angpara, double * eintr, double * eproj)
Definition at line 1006 of file MinimizerDONLP2vappiso.c.
References calcHamiltonianod(), calcOrientedOrientation(), calcprojectedHamiltonianmatrix(), calcSlaterDetAuxod(), copySlaterDet(), dim, expect(), hbc, invertangles(), kmixingstates(), multcmat(), orientationinverted(), SlaterDetAux::ovlap, rotateSlaterDet(), THRESHKMIX, V, and X.
{
  complex double* H = Work.H;
  complex double* N = Work.N;
  complex double* J2 = Work.J2;
  complex double* V = Work.V;
  int dim = Work.dim;
  // Q is intrinsic state to be varied
  // orient properly
  // then calculate needed matrix elements
  // solve eigenvalue problem in smaller subspace spanned by K-mixing eigenstates
  SlaterDet* Qp = Work.Qp;
  SlaterDetAux* X = Work.X;
#ifdef ORIENTED
  double alpha0, beta0, gamma0;
#endif
  complex double hintr, nintr;
  copySlaterDet(Q, Qp);
#ifdef ORIENTED
  calcSlaterDetAuxod(Qp, Qp, X);
  calcOrientedOrientation(Qp, X, &alpha0, &beta0, &gamma0);
  if (orientationinverted(alpha0, beta0, gamma0, lalpha0, lbeta0, lgamma0))
    invertangles(&alpha0, &beta0, &gamma0);
  fprintf(stderr, "... (alpha, beta, gamma) = (%5.2f, %5.2f, %5.2f)\n",
          alpha0*180/M_PI, beta0*180/M_PI, gamma0*180/M_PI);
  rotateSlaterDet(Qp, -gamma0, -beta0, -alpha0);
#endif
  // intrinsic state
  calcSlaterDetAuxod(Qp, Qp, X);
  if (isnan(X->ovlap)) {
    *eintr = ENERGYPENALTY;
    *eproj = ENERGYPENALTY;
    return;
  }
  nintr = X->ovlap;
  calcHamiltonianod(Int, Qp, Qp, X, &hintr);
  // projected matrix elements for Qp
  calcprojectedHamiltonianmatrix(Qp, Qp, Int, j, par, iso, angpara,
                                 H, N, J2);
  // K-mixing for Qp
  double ed[j+1];
  kmixingstates(H, N, j, THRESHKMIX, ed, V, &dim);
  if (!dim) {
    fprintf(stderr, "no good eigenstate for Q !\n");
  }
  complex double N2[(j+1)*(j+1)];
  multcmat(N, N, N2, j+1);
  complex double hproj[j+1], nproj[j+1], n2proj[j+1], j2proj[j+1];
  int i;
  for (i=0; i<dim; i++) {
    hproj[i] = expect(j+1, H, &V[i*(j+1)]);
    nproj[i] = expect(j+1, N, &V[i*(j+1)]);
    n2proj[i] = expect(j+1, N2, &V[i*(j+1)]);
    j2proj[i] = expect(j+1, J2, &V[i*(j+1)]);
  }
  for (i=0; i<dim; i++)
    fprintf(stderr, "Q eigenstate %d: E = %8.3f MeV, n = %8.7f, J2 = %6.3f\n", i,
            hbc*creal(hproj[i]/nproj[i]), creal(n2proj[i]/(nintr*nproj[i])), creal(j2proj[i]/nproj[i]));
  *eintr = hintr/nintr;
  *eproj = creal(hproj[ival]/nproj[ival]);
}
void calcprojectedHamiltonianmatrix (const SlaterDet * Q, const SlaterDet * Qp, const Interaction * Int, int j, int par, int iso, angintegrationpara * angpara, complex double * H, complex double * N, complex double * J2)
Definition at line 360 of file MinimizerDONLP2vappiso.c.
References calcConstraintJ2od(), calcHamiltonianod(), calcSlaterDetAuxod(), copySlaterDet(), getangintegrationpoint(), invertSlaterDet(), k, M_PI2, mirrorSlaterDet(), angintegrationpara::n, SlaterDetAux::ovlap, Qpp, reinitangintegration(), rotateSlaterDet(), and X.
{
  SlaterDet* Qpp = Work.Qpp;
  SlaterDetAux* X = Work.X;
  int nang = angpara->n;
  reinitangintegration(Q, Qp, 0, 0, angpara);
  int k,kp;
  for (kp=-j; kp<=j; kp=kp+2)
    for (k=-j; k<=j; k=k+2) {
      H[idxjmk(j,k,kp)] = 0.0;
      N[idxjmk(j,k,kp)] = 0.0;
      J2[idxjmk(j,k,kp)] = 0.0;
    }
  complex double nme, hme, j2me;
  double alpha, beta, gamma, w;
  int i, ip, iiso;
  for (i=0; i<nang; i++) {
    for (ip=0; ip<=1; ip++) {
      for (iiso=0; iiso<=1; iiso++) {
        copySlaterDet(Qp, Qpp);
        getangintegrationpoint(i, angpara, &alpha, &beta, &gamma, &w);
        rotateSlaterDet(Qpp, alpha, beta, gamma);
        if (ip) invertSlaterDet(Qpp);
        if (iiso) mirrorSlaterDet(Qpp);
        calcSlaterDetAuxod(Q, Qpp, X);
        nme = X->ovlap;
        calcHamiltonianod(Int, Q, Qpp, X, &hme);
        calcConstraintJ2od(Q, Qpp, X, &j2me);
        for (kp=-j; kp<=j; kp=kp+2)
          for (k=-j; k<=j; k=k+2) {
            H[idxjmk(j,k,kp)] += w/4*(ip ? par : 1)*(iiso ? iso : 1)*
              (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma)*hme;
            N[idxjmk(j,k,kp)] += w/4*(ip ? par : 1)*(iiso ? iso : 1)*
              (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma)*nme;
            J2[idxjmk(j,k,kp)] += w/4*(ip ? par : 1)*(iiso ? iso : 1)*
              (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma)*j2me;
          }
      }
    }
  }
}
void catchterminate (int sig)
Definition at line 87 of file MinimizerDONLP2vappiso.c.
References catchterminate(), and sigterminate.
{
  sigterminate = 1;
  fprintf(stderr, "... catched signal - terminate minimization\n");
  signal(sig, catchterminate);
}
void FORTRAN() ef (const double * x, double * fx)
Definition at line 1242 of file MinimizerDONLP2vappiso.c.
References calcHamiltonian(), calcHamiltonianmpi(), calcprojectedHamiltonian(), calcSlaterDetAux(), env, FORTRAN, hbc, sigterminate, and x.
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  double eintr, eproj;
  calcprojectedHamiltonian(Min.Q,
                           Min.Int,
                           Min.j, Min.par, Min.iso, Min.ival,
                           Min.projpar,
                           &eintr, &eproj);
  *fx = (eproj+Min.alpha*eintr);
  FORTRAN(o8cnt).icf++;
  fprintf(stderr, "\tme      E = % 8.3f MeV, Eproj = %8.3f MeV, Eintr = %8.3f MeV,\n",
          hbc*(*fx), hbc*eproj, hbc*eintr);
}
void FORTRAN() eg (int * i, const double * x, double * gxi)
Definition at line 1323 of file MinimizerDONLP2vappiso.c.
References APOS, MINIMUMA, NGAUSS, and x.
{
  if (!strcmp(Min.P->name, "FMD")) {
    *gxi = x[(*i-1)*NGAUSS+APOS]-MINIMUMA;
  }
}
void FORTRAN() egradf (const double * x, double * gradf)
Definition at line 1269 of file MinimizerDONLP2vappiso.c.
References addmulttogradSlaterDet(), calcgradHamiltonian(), calcgradHamiltonianmpi(), calcgradprojectedHamiltonian(), calcgradSlaterDetAux(), calcSlaterDetAux(), env, FORTRAN, fprintinfo(), hbc, icgf, sigterminate, writeSlaterDet(), and x.
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  double eintr, eproj;
  calcgradprojectedHamiltonian(Min.Q,
                               Min.Int,
                               Min.j, Min.par, Min.iso, Min.ival,
                               Min.projpar,
                               &eintr, &eproj);
  // add gradient from intrinsic energy
  calcSlaterDetAux(Min.Q, Work.X);
  calcgradSlaterDetAux(Min.Q, Work.X, Work.dX);
  calcgradHamiltonian(Min.Int, Min.Q, Work.X, Work.dX, Work.dH);
  addmulttogradSlaterDet(Work.dhproj, Work.dH, Min.alpha);
  Min.P->ParaprojectgradSlaterDet(Min.q, Work.dhproj, gradf);
  FORTRAN(o8cnt).icgf++;
  fprintf(stderr, "grad %3d: \tE = %8.3f MeV, Eproj = %8.3f MeV, Eintr = %8.3f MeV\n",
          FORTRAN(o8cnt).icgf, hbc*(eproj+Min.alpha*eintr), hbc*eproj, hbc*eintr);
  if (Min.log && !(FORTRAN(o8cnt).icgf % Min.log)) {
    char logfname[255];
    sprintf(logfname, "%s.minvapp.%03d.log", Min.logfile, FORTRAN(o8cnt).icgf);
    FILE* logfp;
    if (!(logfp = fopen(logfname, "w"))) {
      fprintf(stderr, "couldn't open %s for writing\n", logfname);
    } else {
      fprintinfo(logfp);
      fprintf(logfp, "# step %3d: \tE = %8.3f MeV, Eproj = %8.3f MeV, Eintr = %8.3f MeV\n",
              FORTRAN(o8cnt).icgf, hbc*(eproj+Min.alpha*eintr), hbc*eproj, hbc*eintr);
      fprintf(logfp, "\n# Parameterization\n");
      fprintf(logfp, "<Parameterization %s>\n", Min.P->name);
      Min.P->Parawrite(logfp, Min.q);
      fprintf(logfp, "\n# SlaterDet\n");
      writeSlaterDet(logfp, Min.Q);
      fclose(logfp);
    }
  }
}
void FORTRAN() egradg (int * i, const double * x, double * gradgi)
Definition at line 1331 of file MinimizerDONLP2vappiso.c.
{
}
void FORTRAN() egradh (int * i, const double * x, double * gradhi)
Definition at line 1356 of file MinimizerDONLP2vappiso.c.
References calcgradSlaterDetAux(), calcSlaterDetAux(), env, sigterminate, x, and zerogradSlaterDet().
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAux(Min.Q, Work.X);
  calcgradSlaterDetAux(Min.Q, Work.X, Work.dX);
  zerogradSlaterDet(Work.dH);
  Min.Const[*i-1].gradme(Min.Q, Work.X, Work.dX, Work.dH);
  Min.P->ParaprojectgradSlaterDet(Min.q, Work.dH, gradhi);
  fprintf(stderr, "\t\t\tgrad %4s = %8.3f\n",
          Min.Const[*i-1].label, Min.Const[*i-1].output(Work.dH->val));
}
void FORTRAN() eh (int * i, const double * x, double * hxi)
Definition at line 1336 of file MinimizerDONLP2vappiso.c.
References calcSlaterDetAux(), env, sigterminate, and x.
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAux(Min.Q, Work.X);
  Min.Const[*i-1].me(Min.Q, Work.X, hxi);
  fprintf(stderr, "\t\t\tme   %4s = %8.3f\n",
          Min.Const[*i-1].label, Min.Const[*i-1].output(*hxi));
  *hxi -= Min.Const[*i-1].val;
}
void initWork (int j, int par, int iso, angintegrationpara * AngPar, const Interaction * Int, const SlaterDet * Q)
Definition at line 962 of file MinimizerDONLP2vappiso.c.
References initgradSlaterDet(), initgradSlaterDetAux(), initSlaterDet(), and initSlaterDetAux().
{
  int k;
  Work.Qp = malloc(sizeof(SlaterDet));
  Work.Qpp = malloc(sizeof(SlaterDet));
  Work.X = malloc(sizeof(SlaterDetAux));
  Work.dX = malloc(sizeof(gradSlaterDetAux));
  initSlaterDet(Q, Work.Qp);
  initSlaterDet(Q, Work.Qpp);
  initSlaterDetAux(Q, Work.X);
  initgradSlaterDetAux(Q, Work.dX);
  Work.dH = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
  Work.dN = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
  for (k=0; k<(j+1)*(j+1); k++) {
    initgradSlaterDet(Q, &Work.dH[k]);
    initgradSlaterDet(Q, &Work.dN[k]);
  }
  Work.dhproj = malloc(sizeof(gradSlaterDet));
  Work.dnproj = malloc(sizeof(gradSlaterDet));
  initgradSlaterDet(Q, Work.dhproj);
  initgradSlaterDet(Q, Work.dnproj);
  Work.V = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.H = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.N = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.J2 = malloc((j+1)*(j+1)*sizeof(complex double));
}
void kmixingstates (complex double * H, complex double * N, int j, double thresh, double * egood, complex double * Vgood, int * ngood)
Definition at line 229 of file MinimizerDONLP2vappiso.c.
References generalizedeigensystem(), k, l, MINNORMKMIX, multcmat(), V, and val.
{
  complex double e[j+1];
  complex double V[(j+1)*(j+1)];
  int d;
  generalizedeigensystem(H, N, j+1, thresh, e, V, &d);
  // we got d eigenstates, filter out the noise
  // sort eigenstates according to energy and norm
  // calculate norms
  complex double N2[(j+1)*(j+1)];
  multcmat(N, N, N2, j+1);
  double n, n2, norm[d];
  int i, k, l;
  for (i=0; i<d; i++) {
    n=0.0; n2=0.0;
    for (l=0; l<j+1; l++)
      for (k=0; k<j+1; k++) {
        n += conj(V[k+i*(j+1)])*N[k+l*(j+1)]*V[l+i*(j+1)];
        n2 += conj(V[k+i*(j+1)])*N2[k+l*(j+1)]*V[l+i*(j+1)];
      }
    norm[i] = n2/n;
  }
  double maxnorm = 0.0;
  for (i=0; i<d; i++)
    maxnorm = fmax(maxnorm, creal(norm[i]));
  double mine = 0.0;
  for (i=0; i<d; i++)
    mine = fmin(mine, creal(e[i]));
  // merits
  struct merit {
    double val;
    int idx;
  } merits[d];
  // how should we sort the eigenstates ?
  // according to energy, according to overlap with intrinsic state ?
  // problematic as ordering may change during minimization
  for (i=0; i<d; i++) {
    merits[i].idx = i;
    if (creal(norm[i]) < MINNORMKMIX*maxnorm)
      merits[i].val = -100000.0;
    else
      merits[i].val = e[i]/mine + 0.1*norm[i]/maxnorm;
  }
  // sort according to merits value
  qsort(merits, d, sizeof(struct merit), cmpmerit);
  // now write good eigenvalues and eigenvectors into egood, Vgood
  i=0; while(i<d && merits[i].val > -100000.0) {
    egood[i] = e[merits[i].idx];
    for (k=0; k<j+1; k++)
      Vgood[k+i*(j+1)] = V[k+merits[i].idx*(j+1)];
    i++;
  }
  *ngood = i;
}
void MinimizeDONLP2vappiso (const Interaction * Int, int j, int par, int iso, int ival, double alpha, angintegrationpara * projpar, const Constraint * Const, int nconst, Parameterization * P, Para * q, int maxsteps, int log, const char * logfile)
Definition at line 1198 of file MinimizerDONLP2vappiso.c.
References catchterminate(), donlp2(), env, FORTRAN, optite, and Parameterization::ParainitSlaterDet.
Referenced by main().
{
#ifndef MPI
  // handler for INT and TERM signals
  signal(SIGINT, catchterminate);
  signal(SIGTERM, catchterminate);
#endif
  Min.maxsteps = maxsteps;
  Min.log = log;
  Min.logfile = logfile;
  Min.Int = Int;
  Min.j = j;
  Min.par = par;
  Min.iso = iso;
  Min.ival = ival;
  Min.alpha = alpha;
  Min.projpar = projpar;
  Min.Const = Const;
  Min.nconst = nconst;
  Min.q = q;
  Min.P = P;
  Min.Q = malloc(sizeof(SlaterDet));
  P->ParainitSlaterDet(q, Min.Q);
#ifndef MPI
  // regular program execution or catched signal ?
  if (!setjmp(env))
#endif
    FORTRAN(donlp2)();
  fprintf(stderr, "donlp2 terminated because of criterium %d\n",
          (int) FORTRAN(o8itin).optite + 11);
  copyxtopara(FORTRAN(o8xdat).x, Min.q);
}
void FORTRAN() setup (void)
Definition at line 1413 of file MinimizerDONLP2vappiso.c.
References FORTRAN.
{
  FORTRAN(o8stpa).te0 = 0;
  FORTRAN(o8stpa).te1 = 0;
  FORTRAN(o8par).iterma = Min.maxsteps-1;
}
void FORTRAN() setup0 (void)
Definition at line 1376 of file MinimizerDONLP2vappiso.c.
References APOS, FORTRAN, and NGAUSS.
{
  int i;
  FORTRAN(o8dim).n = Min.q->n;
  FORTRAN(o8dim).nh = Min.nconst;
  // in case of FMD parametrization use bound constraints for Re{a}
  if (!strcmp(Min.P->name, "FMD")) {
    FORTRAN(o8dim).ng = Min.q->ngauss;
    for (i=0; i<Min.nconst+1; i++) {
      FORTRAN(o8gri).gunit[i][0] = -1;
      FORTRAN(o8gri).gunit[i][1] = 0;
      FORTRAN(o8gri).gunit[i][2] = 0;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      FORTRAN(o8gri).gunit[i+Min.nconst+1][0] = 1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][1] = i*NGAUSS+APOS+1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][2] = 1;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      if (Min.q->x[i*NGAUSS+APOS] < 0)
        Min.q->x[i*NGAUSS+APOS] = 1.0+1.0*rand()/RAND_MAX;
    }
  } else
    FORTRAN(o8dim).ng = 0;
  FORTRAN(o8stpa).analyt = 1;
  FORTRAN(o8stpa).cold = 1;
  FORTRAN(o8par).tau0 = 20.0;
  FORTRAN(o8par).del0 = 1.0;
  FORTRAN(o8rst).nreset = 20;
  FORTRAN(o8stpa).silent = 1;
  for (i=0; i<Min.q->n; i++)
    FORTRAN(o8xdat).x[i] = Min.q->x[i];
}
Variable Documentation
double alpha
finestructure constant
Definition at line 107 of file MinimizerDONLP2vappiso.c.
const Constraint* Const
Definition at line 110 of file MinimizerDONLP2vappiso.c.
gradSlaterDet* dH
Definition at line 125 of file MinimizerDONLP2vappiso.c.
gradSlaterDet* dhproj
Definition at line 133 of file MinimizerDONLP2vappiso.c.
int dim
Definition at line 120 of file MinimizerDONLP2vappiso.c.
gradSlaterDet* dN
Definition at line 126 of file MinimizerDONLP2vappiso.c.
gradSlaterDet* dnproj
Definition at line 134 of file MinimizerDONLP2vappiso.c.
gradSlaterDetAux* dX
Definition at line 131 of file MinimizerDONLP2vappiso.c.
jmp_buf env
Definition at line 83 of file MinimizerDONLP2vappiso.c.
complex double* H
Definition at line 121 of file MinimizerDONLP2vappiso.c.
const Interaction* Int
Definition at line 102 of file MinimizerDONLP2vappiso.c.
int iso
Definition at line 105 of file MinimizerDONLP2vappiso.c.
Referenced by main().
int ival
Definition at line 106 of file MinimizerDONLP2vappiso.c.
int j
Definition at line 103 of file MinimizerDONLP2vappiso.c.
complex double* J2
Definition at line 123 of file MinimizerDONLP2vappiso.c.
int log
Definition at line 99 of file MinimizerDONLP2vappiso.c.
const char* logfile
Definition at line 100 of file MinimizerDONLP2vappiso.c.
int maxsteps
Definition at line 101 of file MinimizerDONLP2vappiso.c.
complex double* N
Definition at line 122 of file MinimizerDONLP2vappiso.c.
int nangles
Definition at line 109 of file MinimizerDONLP2vappiso.c.
int nconst
Definition at line 111 of file MinimizerDONLP2vappiso.c.
Parameterization* P
Definition at line 113 of file MinimizerDONLP2vappiso.c.
int par
Definition at line 104 of file MinimizerDONLP2vappiso.c.
angintegrationpara* projpar
Definition at line 108 of file MinimizerDONLP2vappiso.c.
SlaterDet* Q
Definition at line 114 of file MinimizerDONLP2vappiso.c.
Para* q
Definition at line 112 of file MinimizerDONLP2vappiso.c.
SlaterDet* Qp
Definition at line 128 of file MinimizerDONLP2vappiso.c.
SlaterDet* Qpp
Definition at line 129 of file MinimizerDONLP2vappiso.c.
volatile sig_atomic_t sigterminate
Definition at line 85 of file MinimizerDONLP2vappiso.c.
complex double* V
Definition at line 119 of file MinimizerDONLP2vappiso.c.
SlaterDetAux* X
Definition at line 130 of file MinimizerDONLP2vappiso.c.