FMD: MinimizerDONLP2vap.c File Reference
MinimizerDONLP2vap.c File Reference
#include <signal.h>
#include <stdlib.h>
#include <setjmp.h>
#include <string.h>
#include <math.h>
#include "fmd/Interaction.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/Parameterization.h"
#include "fmd/Constraint.h"
#include "fmd/ConstraintJ2.h"
#include "fmd/Projection.h"
#include "numerics/donlp2.h"
#include "fmd/Hamiltonian.h"
#include "fmd/gradHamiltonian.h"
#include "MinimizerDONLP2vap.h"
#include "numerics/fortranc.h"
#include "numerics/wignerd.h"
#include "numerics/lapack.h"
#include "numerics/cmat.h"
#include "misc/physics.h"
#include "misc/utils.h"
Defines
#define NGAUSS 12
#define APOS 4
#define MINIMUMA 0.0001
#define ALLOWEDJ2DEVIATION 0.1
#define ENERGYPENALTY 10000.0/hbc
#define THRESHKMIX 0.01
#define ORIENTED
Functions
void catchterminate (int sig)
void initWork (const SlaterDet *Q)
void calcprojectedHamiltonian (const SlaterDet *Q, const Interaction *Int, int j, int par, angintegrationpara *angpara, double *eintr, double *eproj)
void calcgradprojectedHamiltonian (const SlaterDet *Q, const Interaction *Int, int j, int par, angintegrationpara *angpara, double *eintr, double *eproj)
void MinimizeDONLP2vap (const Interaction *Int, int j, int par, angintegrationpara *projpar, const Constraint *Const, int nconst, Parameterization *P, Para *q, int maxsteps, int log, const char *logfile)
void FORTRAN() ef (const double *x, double *fx)
void FORTRAN() egradf (const double *x, double *gradf)
void FORTRAN() eg (int *i, const double *x, double *gxi)
void FORTRAN() egradg (int *i, const double *x, double *gradgi)
void FORTRAN() eh (int *i, const double *x, double *hxi)
void FORTRAN() egradh (int *i, const double *x, double *gradhi)
void FORTRAN() setup0 (void)
void FORTRAN() setup (void)
Variables
jmp_buf env
volatile sig_atomic_t sigterminate
Detailed Description
using the minimization routine donlp2
this is ugly as hell, but it works !
(c) 2003-2007 Thomas Neff
Definition in file MinimizerDONLP2vap.c.
Define Documentation
#define ALLOWEDJ2DEVIATION 0.1
Definition at line 55 of file MinimizerDONLP2vap.c.
Referenced by calcprojectedHamiltonian().
#define APOS 4
Definition at line 19 of file MinimizerDONLP2vap.c.
Referenced by eg(), and setup0().
#define ENERGYPENALTY 10000.0/hbc
Definition at line 56 of file MinimizerDONLP2vap.c.
#define MINIMUMA 0.0001
Definition at line 54 of file MinimizerDONLP2vap.c.
Referenced by eg().
#define NGAUSS 12
Definition at line 18 of file MinimizerDONLP2vap.c.
Referenced by eg(), and setup0().
#define ORIENTED
Definition at line 67 of file MinimizerDONLP2vap.c.
#define THRESHKMIX 0.01
Definition at line 59 of file MinimizerDONLP2vap.c.
Referenced by calcgradprojectedHamiltonian(), and calcprojectedHamiltonian().
Function Documentation
void calcgradprojectedHamiltonian (const SlaterDet * Q, const Interaction * Int, int j, int par, angintegrationpara * angpara, double * eintr, double * eproj)
Definition at line 569 of file MinimizerDONLP2vap.c.
References addmulttogradSlaterDet(), calcgradHamiltonianod(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcHamiltonianod(), calcOrientedOrientation(), calcSlaterDetAuxod(), copySlaterDet(), dH, dh, dhproj, dN, dn, dnproj, dX, expect(), getangintegrationpoint(), invertangles(), invertSlaterDet(), M_PI2, multgradSlaterDet(), angintegrationpara::n, orientationinverted(), SlaterDetAux::ovlap, Qpp, reinitangintegration(), rotategradSlaterDet(), rotateSlaterDet(), THRESHKMIX, gradSlaterDet::val, and zerogradSlaterDet().
{
  SlaterDet* Qp = Min.Qp;
  SlaterDet* Qpp = Min.Qpp;
  SlaterDetAux* X = Min.X;
  gradSlaterDetAux* dX = Min.dX;
  gradSlaterDet* dh = Min.dh;
  gradSlaterDet* dn = Min.dn;
  gradSlaterDet* dH = Min.dH;
  gradSlaterDet* dN = Min.dN;
  gradSlaterDet* dhproj = Min.dhproj;
  gradSlaterDet* dnproj = Min.dnproj;
  int n = angpara->n;
  double alpha, beta, gamma, w;
#ifdef ORIENTED
  double alpha0, beta0, gamma0;
#endif
  complex double H[(j+1)*(j+1)], N[(j+1)*(j+1)];
  int k, kp;
  for (kp=-j; kp<=j; kp=kp+2)
    for (k=-j; k<=j; k=k+2) {
      H[idxjmk(j,k,kp)] = 0.0; N[idxjmk(j,k,kp)] = 0.0;
      zerogradSlaterDet(&dH[idxjmk(j,k,kp)]);
      zerogradSlaterDet(&dN[idxjmk(j,k,kp)]);
    }
  copySlaterDet(Q, Qp);
#ifdef ORIENTED
  calcSlaterDetAuxod(Qp, Qp, X);
  calcOrientedOrientation(Qp, X, &alpha0, &beta0, &gamma0);
  if (orientationinverted(alpha0, beta0, gamma0, lalpha0, lbeta0, lgamma0)) {
    fprintf(stderr, "... angles inverted\n");
    invertangles(&alpha0, &beta0, &gamma0);
  }
  fprintf(stderr, "... (alpha, beta, gamma) = (%5.2f, %5.2f, %5.2f)\n",
          alpha0*180/M_PI, beta0*180/M_PI, gamma0*180/M_PI);
  rotateSlaterDet(Qp, -gamma0, -beta0, -alpha0);
  lalpha0 = alpha0; lbeta0 = beta0; lgamma0 = gamma0;
#endif
  reinitangintegration(Q, Q, 0, 0, angpara);
  complex double hintr, nintr;
  calcSlaterDetAuxod(Qp, Qp, X);
  nintr = X->ovlap;
  calcHamiltonianod(Int, Qp, Qp, X, &hintr);
  *eintr= creal(hintr/nintr);
#ifdef RANDOMIZED
  double alpharan, gammaran;
  alpharan = 0.005*2*M_PI*rand()/RAND_MAX;
  gammaran = 0.005*2*M_PI*rand()/RAND_MAX;
#endif
  int i, ip;
  for (i=0; i<n; i++) {
    copySlaterDet(Qp, Qpp);
    getangintegrationpoint(i, angpara, &alpha, &beta, &gamma, &w);
#ifdef RANDOMIZED
    alpha += alpharan;
    gamma += gammaran;
#endif
    rotateSlaterDet(Qpp, alpha, beta, gamma);
    for (ip=0; ip<=1; ip++) {
      if (ip) invertSlaterDet(Qpp);
      calcSlaterDetAuxod(Qp, Qpp, X);
      calcgradSlaterDetAuxod(Qp, Qpp, X, dX);
      calcgradOvlapod(Qp, Qpp, X, dX, dn);
      dn->val = X->ovlap;
      calcgradHamiltonianod(Int, Qp, Qpp, X, dX, dh);
      for (kp=-j; kp<=j; kp=kp+2)
        for (k=-j; k<=j; k=k+2) {
          H[idxjmk(j,k,kp)] += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*
            Djmkstar(j,k,kp,alpha,beta,gamma)*dh->val;
          N[idxjmk(j,k,kp)] += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*
            Djmkstar(j,k,kp,alpha,beta,gamma)*dn->val;
          addmulttogradSlaterDet(&dH[idxjmk(j,k,kp)], dh, w/2*(ip ? par : +1)*
                                 (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma));
          addmulttogradSlaterDet(&dN[idxjmk(j,k,kp)], dn, w/2*(ip ? par : +1)*
                                 (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma));
        }
    }
  }
  complex double c[j+1];
  complex double e;
  geneigproblem(j+1, H, N, THRESHKMIX, &e, c);
  complex double hproj, nproj;
  hproj = expect(j+1, H, c);
  nproj = expect(j+1, N, c);
  *eproj = creal(hproj/nproj);
  gradexpect(j+1, dH, c, dhproj);
  gradexpect(j+1, dN, c, dnproj);
  multgradSlaterDet(dhproj, 1.0/nproj);
  addmulttogradSlaterDet(dhproj, dnproj, -hproj/(nproj*nproj));
#ifdef ORIENTED
  rotategradSlaterDet(dhproj, alpha0, beta0, gamma0);
#endif
}
void calcprojectedHamiltonian (const SlaterDet * Q, const Interaction * Int, int j, int par, angintegrationpara * angpara, double * eintr, double * eproj)
Definition at line 289 of file MinimizerDONLP2vap.c.
References ALLOWEDJ2DEVIATION, calcConstraintJ2od(), calcHamiltonianod(), calcOrientedOrientation(), calcSlaterDetAuxod(), copySlaterDet(), expect(), getangintegrationpoint(), H, invertangles(), invertSlaterDet(), J2, N, angintegrationpara::n, orientationinverted(), SlaterDetAux::ovlap, Qp, Qpp, reinitangintegration(), rotateSlaterDet(), THRESHKMIX, and X.
{
  SlaterDet* Qp = Work.Qp;
  SlaterDet* Qpp = Work.Qpp;
  SlaterDetAux* X = Work.X;
  int n = angpara->n;
  double alpha, beta, gamma, w;
#ifdef ORIENTED
  double alpha0, beta0, gamma0;
#endif
  complex double hme, nme, j2me;
  complex double H[(j+1)*(j+1)], N[(j+1)*(j+1)], J2[(j+1)*(j+1)];
  int k,kp;
  for (kp=-j; kp<=j; kp=kp+2)
    for (k=-j; k<=j; k=k+2) {
      H[idxjmk(j,k,kp)] = 0.0;
      N[idxjmk(j,k,kp)] = 0.0;
      J2[idxjmk(j,k,kp)] = 0.0;
    }
  complex double hintr, nintr;
  copySlaterDet(Q, Qp);
#ifdef ORIENTED
  calcSlaterDetAuxod(Qp, Qp, X);
  calcOrientedOrientation(Qp, X, &alpha0, &beta0, &gamma0);
  if (orientationinverted(alpha0, beta0, gamma0, lalpha0, lbeta0, lgamma0))
    invertangles(&alpha0, &beta0, &gamma0);
  fprintf(stderr, "... (alpha, beta, gamma) = (%5.2f, %5.2f, %5.2f)\n",
          alpha0*180/M_PI, beta0*180/M_PI, gamma0*180/M_PI);
  rotateSlaterDet(Qp, -gamma0, -beta0, -alpha0);
#endif
  reinitangintegration(Qp, Qp, 0, 0, angpara);
  calcSlaterDetAuxod(Qp, Qp, X);
  if (isnan(X->ovlap)) {
    *eintr = ENERGYPENALTY;
    *eproj = ENERGYPENALTY;
    return;
  }
  nintr = X->ovlap;
  calcHamiltonianod(Int, Qp, Qp, X, &hintr);
  *eintr = hintr/nintr;
#ifdef RANDOMIZED
  double alpharan, gammaran;
  alpharan = 0.005*2*M_PI*rand()/RAND_MAX;
  gammaran = 0.005*2*M_PI*rand()/RAND_MAX;
#endif
  int i, ip;
  for (i=0; i<n; i++) {
    copySlaterDet(Qp, Qpp);
    getangintegrationpoint(i, angpara, &alpha, &beta, &gamma, &w);
#ifdef RANDOMIZED
    alpha += alpharan;
    gamma += gammaran;
#endif
    rotateSlaterDet(Qpp, alpha, beta, gamma);
    for (ip=0; ip<=1; ip++) {
      if (ip) invertSlaterDet(Qpp);
      calcSlaterDetAuxod(Qp, Qpp, X);
      nme = X->ovlap;
      calcHamiltonianod(Int, Qp, Qpp, X, &hme);
      calcConstraintJ2od(Qp, Qpp, X, &j2me);
      for (kp=-j; kp<=j; kp=kp+2)
        for (k=-j; k<=j; k=k+2) {
          H[idxjmk(j,k,kp)] += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*
            Djmkstar(j,k,kp,alpha,beta,gamma)*hme;
          N[idxjmk(j,k,kp)] += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*
            Djmkstar(j,k,kp,alpha,beta,gamma)*nme;
          J2[idxjmk(j,k,kp)] += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*
            Djmkstar(j,k,kp,alpha,beta,gamma)*j2me;
        }
    }
  }
  complex double c[j+1];
  complex double e;
  geneigproblem(j+1, H, N, THRESHKMIX, &e, c);
  complex double hproj, nproj, j2proj;
  hproj = expect(j+1, H, c);
  nproj = expect(j+1, N, c);
  j2proj = expect(j+1, J2, c);
  fprintf(stderr, "... n: %9.7f, J2: %6.3f\n",
          creal(nproj/nintr),
          creal(j2proj/nproj));
  if (dabs(j2proj/nproj - 0.5*j*(0.5*j+1.0)) > ALLOWEDJ2DEVIATION) {
    *eintr = ENERGYPENALTY;
    *eproj = ENERGYPENALTY;
    return;
  }
  *eproj = creal(hproj/nproj);
}
void catchterminate (int sig)
Definition at line 81 of file MinimizerDONLP2vap.c.
References catchterminate(), and sigterminate.
{
  sigterminate = 1;
  fprintf(stderr, "... catched signal - terminate minimization\n");
  signal(sig, catchterminate);
}
void FORTRAN() ef (const double * x, double * fx)
Definition at line 964 of file MinimizerDONLP2vap.c.
References calcprojectedHamiltonian(), env, FORTRAN, hbc, and sigterminate.
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  double eintr, eproj;
#ifdef MPI
  calcprojectedHamiltonianmpi(Min.Q,
                           Min.Int,
                           Min.j, Min.par, Min.projpar,
                           &eintr, &eproj);
#else
  calcprojectedHamiltonian(Min.Q,
                           Min.Int,
                           Min.j, Min.par, Min.projpar,
                           &eintr, &eproj);
#endif
  *fx = eproj;
  FORTRAN(o8cnt).icf++;
  fprintf(stderr, "\t\t\tme      E = %8.3f MeV,   Eintr = %8.3f MeV\n",
          hbc*eproj, hbc*eintr);
}
void FORTRAN() eg (int * i, const double * x, double * gxi)
Definition at line 1048 of file MinimizerDONLP2vap.c.
References APOS, MINIMUMA, and NGAUSS.
{
  if (!strcmp(Min.P->name, "FMD")) {
    *gxi = x[(*i-1)*NGAUSS+APOS]-MINIMUMA;
  }
}
void FORTRAN() egradf (const double * x, double * gradf)
Definition at line 996 of file MinimizerDONLP2vap.c.
References calcgradprojectedHamiltonian(), env, FORTRAN, fprintinfo(), hbc, icgf, sigterminate, and writeSlaterDet().
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  double eintr, eproj;
#ifdef MPI
  calcgradprojectedHamiltonianmpi(Min.Q,
                               Min.Int,
                               Min.j, Min.par, Min.projpar,
                               &eintr, &eproj);
#else
  calcgradprojectedHamiltonian(Min.Q,
                               Min.Int,
                               Min.j, Min.par, Min.projpar,
                               &eintr, &eproj);
#endif
  Min.P->ParaprojectgradSlaterDet(Min.q, Min.dhproj, gradf);
  FORTRAN(o8cnt).icgf++;
  fprintf(stderr, "grad %3d: \tE = %8.3f MeV,   Eintr = %8.3f MeV\n",
          FORTRAN(o8cnt).icgf, hbc*eproj, hbc*eintr);
  if (Min.log && !(FORTRAN(o8cnt).icgf % Min.log)) {
    char logfname[255];
    sprintf(logfname, "%s.minvap.%03d.log", Min.logfile, FORTRAN(o8cnt).icgf);
    FILE* logfp;
    if (!(logfp = fopen(logfname, "w"))) {
      fprintf(stderr, "couldn't open %s for writing\n", logfname);
    } else {
      fprintinfo(logfp);
      fprintf(logfp, "# step %3d: \tE = %8.3f MeV,   Eintr = %8.3f MeV\n",
              FORTRAN(o8cnt).icgf, hbc*eproj, hbc*eintr);
      fprintf(logfp, "\n# Parameterization\n");
      fprintf(logfp, "<Parameterization %s>\n", Min.P->name);
      Min.P->Parawrite(logfp, Min.q);
      fprintf(logfp, "\n# SlaterDet\n");
      writeSlaterDet(logfp, Min.Q);
      fclose(logfp);
    }
  }
}
void FORTRAN() egradg (int * i, const double * x, double * gradgi)
Definition at line 1056 of file MinimizerDONLP2vap.c.
{
}
void FORTRAN() egradh (int * i, const double * x, double * gradhi)
Definition at line 1081 of file MinimizerDONLP2vap.c.
References calcgradSlaterDetAux(), calcSlaterDetAux(), env, sigterminate, and zerogradSlaterDet().
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAux(Min.Q, Min.X);
  calcgradSlaterDetAux(Min.Q, Min.X, Min.dX);
  zerogradSlaterDet(Min.dH);
  Min.Const[*i-1].gradme(Min.Q, Min.X, Min.dX, Min.dH);
  Min.P->ParaprojectgradSlaterDet(Min.q, Min.dH, gradhi);
  fprintf(stderr, "\t\t\tgrad %4s = %8.3f\n",
          Min.Const[*i-1].label, Min.Const[*i-1].output(Min.dH->val));
}
void FORTRAN() eh (int * i, const double * x, double * hxi)
Definition at line 1061 of file MinimizerDONLP2vap.c.
References calcSlaterDetAux(), env, and sigterminate.
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  calcSlaterDetAux(Min.Q, Min.X);
  Min.Const[*i-1].me(Min.Q, Min.X, hxi);
  fprintf(stderr, "\t\t\tme   %4s = %8.3f\n",
          Min.Const[*i-1].label, Min.Const[*i-1].output(*hxi));
  *hxi -= Min.Const[*i-1].val;
}
void initWork (const SlaterDet * Q)
Definition at line 163 of file MinimizerDONLP2vap.c.
References initSlaterDet(), and initSlaterDetAux().
{
  Work.Qp = malloc(sizeof(SlaterDet));
  Work.Qpp = malloc(sizeof(SlaterDet));
  Work.X = malloc(sizeof(SlaterDetAux));
  initSlaterDet(Q, Work.Qp);
  initSlaterDet(Q, Work.Qpp);
  initSlaterDetAux(Q, Work.X);
}
void MinimizeDONLP2vap (const Interaction * Int, int j, int par, angintegrationpara * projpar, const Constraint * Const, int nconst, Parameterization * P, Para * q, int maxsteps, int log, const char * logfile)
Definition at line 903 of file MinimizerDONLP2vap.c.
References catchterminate(), donlp2(), env, FORTRAN, initgradSlaterDet(), initgradSlaterDetAux(), initSlaterDetAux(), and optite.
Referenced by main().
{
#ifndef MPI
  // handler for INT and TERM signals
  signal(SIGINT, catchterminate);
  signal(SIGTERM, catchterminate);
#endif
  Min.maxsteps = maxsteps;
  Min.log = log;
  Min.logfile = logfile;
  Min.Int = Int;
  Min.j = j;
  Min.par = par;
  Min.projpar = projpar;
  Min.Const = Const;
  Min.nconst = nconst;
  Min.q = q;
  Min.P = P;
  Min.Q = malloc(sizeof(SlaterDet));
  Min.Qp = malloc(sizeof(SlaterDet));
  Min.Qpp = malloc(sizeof(SlaterDet));
  Min.X = malloc(sizeof(SlaterDetAux));
  Min.dX = malloc(sizeof(gradSlaterDetAux));
  Min.dh = malloc(sizeof(gradSlaterDet));
  Min.dn = malloc(sizeof(gradSlaterDet));
  Min.dH = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
  Min.dN = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
  Min.dhproj = malloc(sizeof(gradSlaterDet));
  Min.dnproj = malloc(sizeof(gradSlaterDet));
  Min.P->ParainitSlaterDet(q, Min.Q);
  Min.P->ParainitSlaterDet(q, Min.Qp);
  Min.P->ParainitSlaterDet(q, Min.Qpp);
  initSlaterDetAux(Min.Q, Min.X);
  initgradSlaterDetAux(Min.Q, Min.dX);
  initgradSlaterDet(Min.Q, Min.dh);
  initgradSlaterDet(Min.Q, Min.dn);
  for (int i=0; i<(j+1)*(j+1); i++) {
    initgradSlaterDet(Min.Q, &Min.dH[i]);
    initgradSlaterDet(Min.Q, &Min.dN[i]);
  }
  initgradSlaterDet(Min.Q, Min.dhproj);
  initgradSlaterDet(Min.Q, Min.dnproj);
#ifndef MPI
  // regular program execution or catched signal ?
  if (!setjmp(env))
#endif
    FORTRAN(donlp2)();
  fprintf(stderr, "donlp2 terminated because of criterium %d\n",
          (int) FORTRAN(o8itin).optite + 11);
  copyxtopara(FORTRAN(o8xdat).x, Min.q);
}
void FORTRAN() setup (void)
Definition at line 1138 of file MinimizerDONLP2vap.c.
References FORTRAN.
{
  FORTRAN(o8stpa).te0 = 0;
  FORTRAN(o8stpa).te1 = 0;
  FORTRAN(o8par).iterma = Min.maxsteps-1;
}
void FORTRAN() setup0 (void)
Definition at line 1101 of file MinimizerDONLP2vap.c.
References APOS, FORTRAN, and NGAUSS.
{
  int i;
  FORTRAN(o8dim).n = Min.q->n;
  FORTRAN(o8dim).nh = Min.nconst;
  // in case of FMD parametrization use bound constraints for Re{a}
  if (!strcmp(Min.P->name, "FMD")) {
    FORTRAN(o8dim).ng = Min.q->ngauss;
    for (i=0; i<Min.nconst+1; i++) {
      FORTRAN(o8gri).gunit[i][0] = -1;
      FORTRAN(o8gri).gunit[i][1] = 0;
      FORTRAN(o8gri).gunit[i][2] = 0;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      FORTRAN(o8gri).gunit[i+Min.nconst+1][0] = 1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][1] = i*NGAUSS+APOS+1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][2] = 1;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      if (Min.q->x[i*NGAUSS+APOS] < 0)
        Min.q->x[i*NGAUSS+APOS] = 1.0+1.0*rand()/RAND_MAX;
    }
  } else
    FORTRAN(o8dim).ng = 0;
  FORTRAN(o8stpa).analyt = 1;
  FORTRAN(o8stpa).cold = 1;
  FORTRAN(o8par).tau0 = 20.0;
  FORTRAN(o8par).del0 = 1.0;
  FORTRAN(o8rst).nreset = 20;
  FORTRAN(o8stpa).silent = 1;
  for (i=0; i<Min.q->n; i++)
    FORTRAN(o8xdat).x[i] = Min.q->x[i];
}
Variable Documentation
const Constraint* Const
Definition at line 101 of file MinimizerDONLP2vap.c.
gradSlaterDet* dh
Definition at line 110 of file MinimizerDONLP2vap.c.
gradSlaterDet * dH
Definition at line 110 of file MinimizerDONLP2vap.c.
gradSlaterDet * dhproj
Definition at line 110 of file MinimizerDONLP2vap.c.
Referenced by calcgradprojectedHamiltonian().
gradSlaterDet * dn
Definition at line 110 of file MinimizerDONLP2vap.c.
gradSlaterDet * dN
Definition at line 110 of file MinimizerDONLP2vap.c.
gradSlaterDet * dnproj
Definition at line 110 of file MinimizerDONLP2vap.c.
Referenced by calcgradprojectedHamiltonian().
gradSlaterDetAux* dX
Definition at line 109 of file MinimizerDONLP2vap.c.
jmp_buf env
Definition at line 77 of file MinimizerDONLP2vap.c.
const Interaction* Int
Definition at line 96 of file MinimizerDONLP2vap.c.
int j
Definition at line 97 of file MinimizerDONLP2vap.c.
int log
Definition at line 93 of file MinimizerDONLP2vap.c.
const char* logfile
Definition at line 94 of file MinimizerDONLP2vap.c.
int maxsteps
Definition at line 95 of file MinimizerDONLP2vap.c.
int nangles
Definition at line 100 of file MinimizerDONLP2vap.c.
int nconst
Definition at line 102 of file MinimizerDONLP2vap.c.
Parameterization* P
Definition at line 104 of file MinimizerDONLP2vap.c.
int par
Definition at line 98 of file MinimizerDONLP2vap.c.
angintegrationpara* projpar
Definition at line 99 of file MinimizerDONLP2vap.c.
SlaterDet* Q
Definition at line 105 of file MinimizerDONLP2vap.c.
Para* q
Definition at line 103 of file MinimizerDONLP2vap.c.
SlaterDet* Qp
Definition at line 106 of file MinimizerDONLP2vap.c.
SlaterDet* Qpp
Definition at line 107 of file MinimizerDONLP2vap.c.
volatile sig_atomic_t sigterminate
Definition at line 79 of file MinimizerDONLP2vap.c.
SlaterDetAux* X
Definition at line 108 of file MinimizerDONLP2vap.c.