FMD: MinimizerLBFGS.c File Reference
MinimizerLBFGS.c File Reference
#include <stdlib.h>
#include <float.h>
#include "MinimizerLBFGS.h"
#include "numerics/lbfgs.h"
Functions
void initMinimizer (Minimizer *mini, int n, double precision)
int MinimizerStep (Minimizer *mini, double *x, const double H, const double *dH)
Function Documentation
void initMinimizer (Minimizer * mini, int n, double precision)
Definition at line 17 of file MinimizerLBFGS.c.
References Minimizer::diag, Minimizer::diagco, Minimizer::eps, Minimizer::iflag, Minimizer::iprint, Minimizer::m, Minimizer::n, Minimizer::w, and Minimizer::xtol.
Referenced by main().
{
  mini->n = n;;
  mini->m = 6;
  mini->diag = (double*) malloc(mini->n*sizeof(double));
  mini->w = (double*) malloc((mini->n*(2*mini->m+1)+2*mini->m)*sizeof(double));
  mini->diagco = 0;
  mini->iprint[0] = -1;
  mini->iprint[1] = 0;
  mini->eps = precision;
  mini->xtol = DBL_EPSILON;
  mini->iflag = 0;
}
int MinimizerStep (Minimizer * mini, double * x, const double H, const double * dH)
Definition at line 32 of file MinimizerLBFGS.c.
References Minimizer::diag, Minimizer::diagco, Minimizer::eps, FORTRAN, Minimizer::iflag, Minimizer::iprint, lbfgs(), Minimizer::m, Minimizer::n, Minimizer::w, and Minimizer::xtol.
Referenced by main().
{
  FORTRAN(lbfgs)(&mini->n, &mini->m, x, &H, dH,
                 &mini->diagco, mini->diag, mini->iprint,
                 &mini->eps, &mini->xtol, mini->w, &mini->iflag);
  return (mini->iflag == 1);
}