FMD: MinimizerDONLP2orthogonalvapp.c File Reference
MinimizerDONLP2orthogonalvapp.c File Reference
#include <signal.h>
#include <stdlib.h>
#include <setjmp.h>
#include <string.h>
#include <math.h>
#include "fmd/Interaction.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/Parameterization.h"
#include "fmd/Constraint.h"
#include "fmd/ConstraintJ2.h"
#include "fmd/Projection.h"
#include "numerics/donlp2.h"
#include "fmd/Hamiltonian.h"
#include "fmd/gradHamiltonian.h"
#include "MinimizerDONLP2orthogonalvapp.h"
#include "numerics/fortranc.h"
#include "numerics/wignerd.h"
#include "numerics/lapack.h"
#include "numerics/cmat.h"
#include "misc/physics.h"
#include "misc/utils.h"
Defines
#define NGAUSS 12
#define APOS 4
#define MINIMUMA 0.0001
#define ALLOWEDJ2DEVIATION 0.1
#define ENERGYPENALTY 10000.0/hbc
#define THRESHKMIX 0.01
#define MINNORMKMIX 0.01
#define THRESHMULTI 0.0
#define ORIENTED
#define M_2PI (2*M_PI)
#define M_PI2 (M_PI*M_PI)
#define INVTHRESH 1e-9
Functions
void catchterminate (int sig)
void kmixingstates (complex double *H, complex double *N, int j, double thresh, double *egood, complex double *Vgood, int *ngood)
void calcsubspaceoverlap (int n, complex double *N, complex double *V, int ngood, int imin, int imax, double *ovl)
void hermiteancopy (int j, const complex double *A, complex double *B)
void calcprojectedHamiltonianmatrix (const SlaterDet *Q, const SlaterDet *Qp, const Interaction *Int, int j, int par, angintegrationpara *angpara, complex double *H, complex double *N, complex double *J2)
void calcgradprojectedHamiltonianmatrix (const SlaterDet *Q, const SlaterDet *Qp, const Interaction *Int, int j, int par, angintegrationpara *angpara, complex double *H, complex double *N, gradSlaterDet *dH, gradSlaterDet *dN)
void initWork (int nfix, const SlaterDet *Qfix, int j, int par, angintegrationpara *AngPar, const Interaction *Int, const SlaterDet *Q)
void calcprojectedHamiltonian (int nfix, const SlaterDet *Qfix, const SlaterDet *Q, const Interaction *Int, int j, int par, int ifix, angintegrationpara *angpara, double *eintr, double *emulti)
void calcgradprojectedHamiltonian (int nfix, const SlaterDet *Qfix, const SlaterDet *Q, const Interaction *Int, int j, int par, int ifix, angintegrationpara *angpara, double *eintr, double *emulti)
void MinimizeDONLP2orthogonalvapp (const Interaction *Int, int j, int par, int ifix, double alpha, angintegrationpara *projpar, const Constraint *Const, int nconst, int nfix, SlaterDet *Qfix, Parameterization *P, Para *q, int maxsteps, int log, const char *logfile)
void FORTRAN() ef (const double *x, double *fx)
void FORTRAN() egradf (const double *x, double *gradf)
void FORTRAN() eg (int *i, const double *x, double *gxi)
void FORTRAN() egradg (int *i, const double *x, double *gradgi)
void FORTRAN() eh (int *i, const double *x, double *hxi)
void FORTRAN() egradh (int *i, const double *x, double *gradhi)
void FORTRAN() setup0 (void)
void FORTRAN() setup (void)
Variables
jmp_buf env
volatile sig_atomic_t sigterminate
Detailed Description
Minimize Eproj + alpha Eintr in order to improve overlap of projected and intrinsic state
using the minimization routine donlp2
this is ugly as hell, but it works !
(c) 2003-2008 Thomas Neff
Definition in file MinimizerDONLP2orthogonalvapp.c.
Define Documentation
#define ALLOWEDJ2DEVIATION 0.1
Definition at line 57 of file MinimizerDONLP2orthogonalvapp.c.
Referenced by calcprojectedHamiltonian().
#define APOS 4
Definition at line 21 of file MinimizerDONLP2orthogonalvapp.c.
Referenced by eg(), and setup0().
#define ENERGYPENALTY 10000.0/hbc
Definition at line 58 of file MinimizerDONLP2orthogonalvapp.c.
#define INVTHRESH 1e-9
Definition at line 269 of file MinimizerDONLP2orthogonalvapp.c.
Referenced by calcsubspaceoverlap().
#define M_2PI (2*M_PI)
Definition at line 146 of file MinimizerDONLP2orthogonalvapp.c.
#define M_PI2 (M_PI*M_PI)
Definition at line 147 of file MinimizerDONLP2orthogonalvapp.c.
Referenced by calcgradprojectedHamiltonianmatrix().
#define MINIMUMA 0.0001
Definition at line 56 of file MinimizerDONLP2orthogonalvapp.c.
Referenced by eg().
#define MINNORMKMIX 0.01
Definition at line 62 of file MinimizerDONLP2orthogonalvapp.c.
Referenced by kmixingstates().
#define NGAUSS 12
Definition at line 20 of file MinimizerDONLP2orthogonalvapp.c.
Referenced by eg(), and setup0().
#define ORIENTED
Definition at line 76 of file MinimizerDONLP2orthogonalvapp.c.
#define THRESHKMIX 0.01
Definition at line 61 of file MinimizerDONLP2orthogonalvapp.c.
Referenced by calcgradprojectedHamiltonian(), calcprojectedHamiltonian(), and initWork().
#define THRESHMULTI 0.0
Definition at line 68 of file MinimizerDONLP2orthogonalvapp.c.
Referenced by calcgradprojectedHamiltonian(), calcprojectedHamiltonian(), and initWork().
Function Documentation
void calcgradprojectedHamiltonian (int nfix, const SlaterDet * Qfix, const SlaterDet * Q, const Interaction * Int, int j, int par, int ifix, angintegrationpara * angpara, double * eintr, double * emulti)
Definition at line 1059 of file MinimizerDONLP2orthogonalvapp.c.
References addmulttogradSlaterDet(), calcgradprojectedHamiltonianmatrix(), calcHamiltonianod(), calcOrientedOrientation(), calcSlaterDetAuxod(), copySlaterDet(), dhmulti, dim, dnmulti, expect(), generalizedeigensystem(), hbc, hermiteancopy(), invertangles(), kmixingstates(), multcmat(), multgradSlaterDet(), orientationinverted(), SlaterDetAux::ovlap, rotategradSlaterDet(), rotateSlaterDet(), sorteigenstates(), THRESHKMIX, THRESHMULTI, V, X, and zerogradSlaterDet().
{
  SlaterDet* Qp = Work.Qp;
  SlaterDetAux* X = Work.X;
  complex double** H = Work.H;
  complex double** N = Work.N;
  complex double** J2 = Work.J2;
  complex double** V = Work.V;
  int* dim = Work.dim;
  gradSlaterDet** dH = Work.dH;
  gradSlaterDet** dN = Work.dN;
  gradSlaterDet* dhmulti = Work.dhmulti;
  gradSlaterDet* dnmulti = Work.dnmulti;
  int n = nfix+1;
#ifdef ORIENTED
  double alpha0, beta0, gamma0;
#endif
  int a, b, k, kp;
  copySlaterDet(Q, Qp);
#ifdef ORIENTED
  calcSlaterDetAuxod(Qp, Qp, X);
  calcOrientedOrientation(Qp, X, &alpha0, &beta0, &gamma0);
  if (orientationinverted(alpha0, beta0, gamma0, lalpha0, lbeta0, lgamma0)) {
    fprintf(stderr, "... angles inverted\n");
    invertangles(&alpha0, &beta0, &gamma0);
  }
  fprintf(stderr, "... (alpha, beta, gamma) = (%5.2f, %5.2f, %5.2f)\n",
          alpha0*180/M_PI, beta0*180/M_PI, gamma0*180/M_PI);
  rotateSlaterDet(Qp, -gamma0, -beta0, -alpha0);
  lalpha0 = alpha0; lbeta0 = beta0; lgamma0 = gamma0;
#endif
  complex double hintr, nintr;
  calcSlaterDetAuxod(Qp, Qp, X);
  nintr = X->ovlap;
  calcHamiltonianod(Int, Qp, Qp, X, &hintr);
  *eintr= creal(hintr/nintr);
  // projected matrix elements, off-diagonals
  int i;
  for (i=0; i<nfix; i++) {
    calcgradprojectedHamiltonianmatrix(Qp, &Qfix[i], Int, j, par, angpara,
                                       H[(n-1)+i*n], N[(n-1)+i*n],
                                       dH[i], dN[i]);
    hermiteancopy(j, H[(n-1)+i*n], H[i+(n-1)*n]);
    hermiteancopy(j, N[(n-1)+i*n], N[i+(n-1)*n]);
  }
  // projected matrix elements for Qp
  calcgradprojectedHamiltonianmatrix(Qp, Qp, Int, j, par, angpara,
                                     H[(n-1)+(n-1)*n], N[(n-1)+(n-1)*n],
                                     dH[n-1], dN[n-1]);
  // K-mixing for Qp
  double ed[j+1];
  kmixingstates(H[(n-1)+(n-1)*n], N[(n-1)+(n-1)*n], j, THRESHKMIX,
                ed, V[n-1], &dim[n-1]);
  if (!dim[n-1]) {
    fprintf(stderr, "no good eigenstate for Q !\n");
  }
  // dim[n-1] = 1;
  // ovlap of k-mixing states with intrinsic state
  complex double N2[(j+1)*(j+1)];
  multcmat(N[(n-1)+(n-1)*n], N[(n-1)+(n-1)*n], N2, j+1);
  complex double hproj[j+1], nproj[j+1], n2proj[j+1], j2proj[j+1];
  for (i=0; i<dim[n-1]; i++) {
    hproj[i] = expect(j+1, H[(n-1)+(n-1)*n], &V[n-1][i*(j+1)]);
    nproj[i] = expect(j+1, N[(n-1)+(n-1)*n], &V[n-1][i*(j+1)]);
    n2proj[i] = expect(j+1, N2, &V[n-1][i*(j+1)]);
    j2proj[i] = expect(j+1, J2[(n-1)+(n-1)*n], &V[n-1][i*(j+1)]);
  }
  for (i=0; i<dim[n-1]; i++)
    fprintf(stderr, "Q eigenstate %d: E = %8.3f MeV, n = %8.7f, J2 = %6.3f\n", i,
            hbc*creal(hproj[i]/nproj[i]), creal(n2proj[i]/(nintr*nproj[i])), creal(j2proj[i]/nproj[i]));
  // build H and N matrix in subspace from K-mixing eigenstates
  int dimsub=dim[n-1];
  complex double C[ifix][dimsub];
  int idxa, idxb, kpp;
  for (i=0; i<ifix; i++) {
    for (idxa=0; idxa<dimsub; idxa++)
      C[i][idxa] = 0.0;
    for (a=0; a<nfix; a++)
      for (kp=0; kp<j+1; kp++)
        for (kpp=0; kpp<j+1; kpp++) {
          for (idxa=0; idxa<dimsub; idxa++)
            C[i][idxa] +=
              conj(Work.Vo[kp+a*(j+1)+i*nfix*(j+1)])*
              N[a+(n-1)*n][kp+kpp*(j+1)]*
              V[n-1][kpp+idxa*(j+1)];
        }
  }
  complex double W[dimsub][n*(j+1)];
  for (idxa=0; idxa<dimsub; idxa++) {
    for (a=0; a<n; a++)
      for (k=0; k<j+1; k++)
        W[idxa][k+a*(j+1)] = 0.0;
    for (a=0; a<nfix; a++)
      for (k=0; k<j+1; k++)
        for (i=0; i<ifix; i++)
          W[idxa][k+a*(j+1)] += -Work.Vo[k+a*(j+1)+i*nfix*(j+1)]*C[i][idxa];
    a=n-1;
    for (k=0; k<j+1; k++)
      W[idxa][k+a*(j+1)] = V[a][k+idxa*(j+1)];
  }
  complex double Hsub[dimsub*dimsub], Nsub[dimsub*dimsub];
  for (idxb=0; idxb<dimsub; idxb++)
    for (idxa=0; idxa<dimsub; idxa++) {
      Hsub[idxa+idxb*dimsub] = 0.0;
      Nsub[idxa+idxb*dimsub] = 0.0;
      for (b=0; b<n; b++)
        for (a=0; a<n; a++) {
          for (kp=0; kp<j+1; kp++)
            for (k=0; k<j+1; k++)
              Hsub[idxa+idxb*dimsub] +=
                conj(W[idxa][k+a*(j+1)])*
                H[a+b*n][k+kp*(j+1)]*
                W[idxb][kp+b*(j+1)];
          for (kp=0; kp<j+1; kp++)
            for (k=0; k<j+1; k++)
              Nsub[idxa+idxb*dimsub] +=
                conj(W[idxa][k+a*(j+1)])*
                N[a+b*n][k+kp*(j+1)]*
                W[idxb][kp+b*(j+1)];
        }
    }
  // solve eigenvalue problem in subspace
  complex double esub[dimsub];
  complex double Vsub[dimsub*dimsub];
  int dsub;
  generalizedeigensystem(Hsub, Nsub, dimsub, THRESHMULTI, esub, Vsub, &dsub);
  sorteigenstates(dimsub, esub, Vsub, dsub);
  for (i=0; i<dsub; i++)
    fprintf(stderr, "Multiconfig eigenstate %d = %8.3f\n",
            i, hbc*creal(esub[i]));
  // expectation values for first eigenstate
  complex double* csub = Vsub;
  complex double hmulti, nmulti;
  hmulti = expect(dimsub, Hsub, csub);
  nmulti = expect(dimsub, Nsub, csub);
  *emulti = creal(hmulti/nmulti);
  // gradients
  zerogradSlaterDet(dhmulti);
  zerogradSlaterDet(dnmulti);
  complex double cak, cbkp;
  for (b=0; b<n; b++) {
    a=n-1;
    for (kp=0; kp<j+1; kp++)
      for (k=0; k<j+1; k++) {
        cak = 0.0; cbkp = 0.0;
        for (i=0; i<dimsub; i++) {
          cak += csub[i]*W[i][k+a*(j+1)];
          cbkp += csub[i]*W[i][kp+b*(j+1)];
        }
        addmulttogradSlaterDet(dhmulti, &dH[b][k+kp*(j+1)], conj(cak)*cbkp);
        addmulttogradSlaterDet(dnmulti, &dN[b][k+kp*(j+1)], conj(cak)*cbkp);
      }
  }
  multgradSlaterDet(dhmulti, 1.0/nmulti);
  addmulttogradSlaterDet(dhmulti, dnmulti, -hmulti/(nmulti*nmulti));
#ifdef ORIENTED
  rotategradSlaterDet(dhmulti, alpha0, beta0, gamma0);
#endif
}
void calcgradprojectedHamiltonianmatrix (const SlaterDet * Q, const SlaterDet * Qp, const Interaction * Int, int j, int par, angintegrationpara * angpara, complex double * H, complex double * N, gradSlaterDet * dH, gradSlaterDet * dN)
Definition at line 480 of file MinimizerDONLP2orthogonalvapp.c.
References addmulttogradSlaterDet(), calcgradHamiltonianod(), calcgradOvlapod(), calcgradSlaterDetAuxod(), calcSlaterDetAuxod(), copySlaterDet(), dh, dn, dX, getangintegrationpoint(), invertSlaterDet(), M_PI2, angintegrationpara::n, SlaterDetAux::ovlap, Qpp, reinitangintegration(), rotateSlaterDet(), gradSlaterDet::val, X, and zerogradSlaterDet().
{
  SlaterDet* Qpp = Work.Qpp;
  SlaterDetAux* X = Work.X;
  gradSlaterDet* dh = Work.dh;
  gradSlaterDet* dn = Work.dn;
  gradSlaterDetAux* dX = Work.dX;
  int nang = angpara->n;
  reinitangintegration(Q, Qp, 0, 0, angpara);
  int k,kp;
  for (kp=-j; kp<=j; kp=kp+2)
    for (k=-j; k<=j; k=k+2) {
      H[idxjmk(j,k,kp)] = 0.0;
      N[idxjmk(j,k,kp)] = 0.0;
      zerogradSlaterDet(&dH[idxjmk(j,k,kp)]);
      zerogradSlaterDet(&dN[idxjmk(j,k,kp)]);
    }
  double alpha, beta, gamma, w;
  int i, ip;
  for (i=0; i<nang; i++) {
    copySlaterDet(Qp, Qpp);
    getangintegrationpoint(i, angpara, &alpha, &beta, &gamma, &w);
    rotateSlaterDet(Qpp, alpha, beta, gamma);
    for (ip=0; ip<=1; ip++) {
      if (ip) invertSlaterDet(Qpp);
      calcSlaterDetAuxod(Q, Qpp, X);
      calcgradSlaterDetAuxod(Q, Qpp, X, dX);
      calcgradOvlapod(Q, Qpp, X, dX, dn);
      dn->val = X->ovlap;
      calcgradHamiltonianod(Int, Q, Qpp, X, dX, dh);
      for (kp=-j; kp<=j; kp=kp+2)
        for (k=-j; k<=j; k=k+2) {
          H[idxjmk(j,k,kp)] += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*
            Djmkstar(j,k,kp,alpha,beta,gamma)*dh->val;
          N[idxjmk(j,k,kp)] += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*
            Djmkstar(j,k,kp,alpha,beta,gamma)*dn->val;
          addmulttogradSlaterDet(&dH[idxjmk(j,k,kp)], dh, w/2*(ip ? par : +1)*
                                 (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma));
          addmulttogradSlaterDet(&dN[idxjmk(j,k,kp)], dn, w/2*(ip ? par : +1)*
                                 (j+1)/(8*M_PI2)*Djmkstar(j,k,kp,alpha,beta,gamma));
        }
    }
  }
}
void calcprojectedHamiltonian (int nfix, const SlaterDet * Qfix, const SlaterDet * Q, const Interaction * Int, int j, int par, int ifix, angintegrationpara * angpara, double * eintr, double * emulti)
Definition at line 854 of file MinimizerDONLP2orthogonalvapp.c.
References ALLOWEDJ2DEVIATION, calcHamiltonianod(), calcOrientedOrientation(), calcprojectedHamiltonianmatrix(), calcSlaterDetAuxod(), calcsubspaceoverlap(), copySlaterDet(), dim, expect(), generalizedeigensystem(), hbc, hermiteancopy(), invertangles(), kmixingstates(), multcmat(), orientationinverted(), SlaterDetAux::ovlap, rotateSlaterDet(), sorteigenstates(), THRESHKMIX, THRESHMULTI, V, and X.
{
  complex double** H = Work.H;
  complex double** N = Work.N;
  complex double** J2 = Work.J2;
  complex double** V = Work.V;
  int* dim = Work.dim;
  // Q is intrinsic state to be varied
  // orient properly
  // then calculate needed matrix elements
  // solve eigenvalue problem in smaller subspace spanned by K-mixing eigenstates
  int n = nfix+1;
  SlaterDet* Qp = Work.Qp;
  SlaterDetAux* X = Work.X;
#ifdef ORIENTED
  double alpha0, beta0, gamma0;
#endif
  complex double hintr, nintr;
  copySlaterDet(Q, Qp);
#ifdef ORIENTED
  calcSlaterDetAuxod(Qp, Qp, X);
  calcOrientedOrientation(Qp, X, &alpha0, &beta0, &gamma0);
  if (orientationinverted(alpha0, beta0, gamma0, lalpha0, lbeta0, lgamma0))
    invertangles(&alpha0, &beta0, &gamma0);
  fprintf(stderr, "... (alpha, beta, gamma) = (%5.2f, %5.2f, %5.2f)\n",
          alpha0*180/M_PI, beta0*180/M_PI, gamma0*180/M_PI);
  rotateSlaterDet(Qp, -gamma0, -beta0, -alpha0);
#endif
  // intrinsic state
  calcSlaterDetAuxod(Qp, Qp, X);
  if (isnan(X->ovlap)) {
    *eintr = ENERGYPENALTY;
    *emulti = ENERGYPENALTY;
    return;
  }
  nintr = X->ovlap;
  calcHamiltonianod(Int, Qp, Qp, X, &hintr);
  // projected matrix elements, off-diagonals
  int i;
  for (i=0; i<nfix; i++) {
    calcprojectedHamiltonianmatrix(Qp, &Qfix[i], Int, j, par, angpara,
                                   H[(n-1)+i*n], N[(n-1)+i*n], J2[(n-1)+i*n]);
    hermiteancopy(j, H[(n-1)+i*n], H[i+(n-1)*n]);
    hermiteancopy(j, N[(n-1)+i*n], N[i+(n-1)*n]);
    hermiteancopy(j, J2[(n-1)+i*n], J2[i+(n-1)*n]);
  }
  // projected matrix elements for Qp
  calcprojectedHamiltonianmatrix(Qp, Qp, Int, j, par, angpara,
                                 H[(n-1)+(n-1)*n], N[(n-1)+(n-1)*n], J2[(n-1)+(n-1)*n]);
  // K-mixing for Qp
  double ed[j+1];
  kmixingstates(H[(n-1)+(n-1)*n], N[(n-1)+(n-1)*n], j, THRESHKMIX,
                ed, V[n-1], &dim[n-1]);
  if (!dim[n-1]) {
    fprintf(stderr, "no good eigenstate for Q !\n");
  }
  // dim[n-1] = 1;
  // ovlap of k-mixing states with intrinsic state
  complex double N2[(j+1)*(j+1)];
  multcmat(N[(n-1)+(n-1)*n], N[(n-1)+(n-1)*n], N2, j+1);
  complex double hproj[j+1], nproj[j+1], n2proj[j+1], j2proj[j+1];
  for (i=0; i<dim[n-1]; i++) {
    hproj[i] = expect(j+1, H[(n-1)+(n-1)*n], &V[n-1][i*(j+1)]);
    nproj[i] = expect(j+1, N[(n-1)+(n-1)*n], &V[n-1][i*(j+1)]);
    n2proj[i] = expect(j+1, N2, &V[n-1][i*(j+1)]);
    j2proj[i] = expect(j+1, J2[(n-1)+(n-1)*n], &V[n-1][i*(j+1)]);
  }
  for (i=0; i<dim[n-1]; i++)
    fprintf(stderr, "Q eigenstate %d: E = %8.3f MeV, n = %8.7f, J2 = %6.3f\n", i,
            hbc*creal(hproj[i]/nproj[i]), creal(n2proj[i]/(nintr*nproj[i])), creal(j2proj[i]/nproj[i]));
  // build H and N matrix in subspace from K-mixing eigenstates
  int dimsub=dim[n-1];
  complex double C[ifix][dimsub];
  int idxa, idxb, a, b, k, kp, kpp;
  for (i=0; i<ifix; i++) {
    for (idxa=0; idxa<dimsub; idxa++)
      C[i][idxa] = 0.0;
    for (a=0; a<nfix; a++)
      for (kp=0; kp<j+1; kp++)
        for (kpp=0; kpp<j+1; kpp++) {
          for (idxa=0; idxa<dimsub; idxa++)
            C[i][idxa] +=
              conj(Work.Vo[kp+a*(j+1)+i*nfix*(j+1)])*
              N[a+(n-1)*n][kp+kpp*(j+1)]*
              V[n-1][kpp+idxa*(j+1)];
        }
  }
  complex double W[dimsub][n*(j+1)];
  for (idxa=0; idxa<dimsub; idxa++) {
    for (a=0; a<n; a++)
      for (k=0; k<j+1; k++)
        W[idxa][k+a*(j+1)] = 0.0;
    for (a=0; a<nfix; a++)
      for (k=0; k<j+1; k++)
        for (i=0; i<ifix; i++)
          W[idxa][k+a*(j+1)] += -Work.Vo[k+a*(j+1)+i*nfix*(j+1)]*C[i][idxa];
    a=n-1;
    for (k=0; k<j+1; k++)
      W[idxa][k+a*(j+1)] = V[a][k+idxa*(j+1)];
  }
  complex double Hsub[dimsub*dimsub], Nsub[dimsub*dimsub];
  for (idxb=0; idxb<dimsub; idxb++)
    for (idxa=0; idxa<dimsub; idxa++) {
      Hsub[idxa+idxb*dimsub] = 0.0;
      Nsub[idxa+idxb*dimsub] = 0.0;
      for (b=0; b<n; b++)
        for (a=0; a<n; a++) {
          for (kp=0; kp<j+1; kp++)
            for (k=0; k<j+1; k++)
              Hsub[idxa+idxb*dimsub] +=
                conj(W[idxa][k+a*(j+1)])*
                H[a+b*n][k+kp*(j+1)]*
                W[idxb][kp+b*(j+1)];
          for (kp=0; kp<j+1; kp++)
            for (k=0; k<j+1; k++)
              Nsub[idxa+idxb*dimsub] +=
                conj(W[idxa][k+a*(j+1)])*
                N[a+b*n][k+kp*(j+1)]*
                W[idxb][kp+b*(j+1)];
        }
    }
  // solve eigenvalue problem in subspace
  complex double esub[dimsub];
  complex double Vsub[dimsub*dimsub];
  int dsub;
  generalizedeigensystem(Hsub, Nsub, dimsub, THRESHMULTI, esub, Vsub, &dsub);
  sorteigenstates(dimsub, esub, Vsub, dsub);
  for (i=0; i<dsub; i++)
    fprintf(stderr, "Multiconfig eigenstate %d = %8.3f\n",
            i, hbc*creal(esub[i]));
  // expectation values for first eigenstate
  complex double* csub = Vsub;
  complex double hmulti, nmulti;
  hmulti = expect(dimsub, Hsub, csub);
  nmulti = expect(dimsub, Nsub, csub);
  if (dabs(j2proj[0]/nproj[0] - 0.5*j*(0.5*j+1.0)) > ALLOWEDJ2DEVIATION) {
    *eintr = ENERGYPENALTY;
    *emulti = ENERGYPENALTY;
    return;
  }
  *eintr = hintr/nintr;
  *emulti = creal(hmulti/nmulti);
}
void calcprojectedHamiltonianmatrix (const SlaterDet * Q, const SlaterDet * Qp, const Interaction * Int, int j, int par, angintegrationpara * angpara, complex double * H, complex double * N, complex double * J2)
Definition at line 319 of file MinimizerDONLP2orthogonalvapp.c.
References calcConstraintJ2od(), calcHamiltonianod(), calcSlaterDetAuxod(), copySlaterDet(), getangintegrationpoint(), invertSlaterDet(), k, angintegrationpara::n, SlaterDetAux::ovlap, Qpp, reinitangintegration(), rotateSlaterDet(), and X.
{
  SlaterDet* Qpp = Work.Qpp;
  SlaterDetAux* X = Work.X;
  int nang = angpara->n;
  reinitangintegration(Q, Qp, 0, 0, angpara);
  int k,kp;
  for (kp=-j; kp<=j; kp=kp+2)
    for (k=-j; k<=j; k=k+2) {
      H[idxjmk(j,k,kp)] = 0.0;
      N[idxjmk(j,k,kp)] = 0.0;
      J2[idxjmk(j,k,kp)] = 0.0;
    }
  complex double nme, hme, j2me;
  double alpha, beta, gamma, w;
  int i, ip;
  for (i=0; i<nang; i++) {
    copySlaterDet(Qp, Qpp);
    getangintegrationpoint(i, angpara, &alpha, &beta, &gamma, &w);
    rotateSlaterDet(Qpp, alpha, beta, gamma);
    for (ip=0; ip<=1; ip++) {
      if (ip) invertSlaterDet(Qpp);
      calcSlaterDetAuxod(Q, Qpp, X);
      nme = X->ovlap;
      calcHamiltonianod(Int, Q, Qpp, X, &hme);
      calcConstraintJ2od(Q, Qpp, X, &j2me);
      for (kp=-j; kp<=j; kp=kp+2)
        for (k=-j; k<=j; k=k+2) {
          H[idxjmk(j,k,kp)] += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*
            Djmkstar(j,k,kp,alpha,beta,gamma)*hme;
          N[idxjmk(j,k,kp)] += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*
            Djmkstar(j,k,kp,alpha,beta,gamma)*nme;
          J2[idxjmk(j,k,kp)] += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*
            Djmkstar(j,k,kp,alpha,beta,gamma)*j2me;
        }
    }
  }
}
void calcsubspaceoverlap (int n, complex double * N, complex double * V, int ngood, int imin, int imax, double * ovl)
Definition at line 270 of file MinimizerDONLP2orthogonalvapp.c.
References INVTHRESH, k, l, and pseudoinverse().
{
  if (ngood == 0 || imin==imax) return;
  int nsub=imax-imin;
  complex double Nsub[nsub*nsub], Osub[nsub*nsub];
  int i,j;
  for (j=0; j<nsub; j++)
    for (i=0; i<nsub; i++)
      Nsub[i+j*nsub] = N[(i+imin)+(j+imin)*n];
  pseudoinverse(Nsub, Osub, nsub, INVTHRESH);
  int alpha, k,l;
  double ovlap, norm;
  for (alpha=0; alpha<ngood; alpha++) {
    ovlap = 0.0;
    norm = 0.0;
    for (l=0; l<n; l++)
      for (k=0; k<n; k++) {
        norm += conj(V[k+alpha*n])*N[k+l*n]*V[l+alpha*n];
        for (j=0; j<nsub; j++)
          for (i=0; i<nsub; i++) {
            ovlap += conj(V[k+alpha*n])*N[k+(i+imin)*n]*Osub[i+j*nsub]*N[(j+imin)+l*n]*V[l+alpha*n];
          }
      }
    ovl[alpha] = ovlap/norm;
  }
}
void catchterminate (int sig)
Definition at line 90 of file MinimizerDONLP2orthogonalvapp.c.
References catchterminate(), and sigterminate.
{
  sigterminate = 1;
  fprintf(stderr, "... catched signal - terminate minimization\n");
  signal(sig, catchterminate);
}
void FORTRAN() ef (const double * x, double * fx)
Definition at line 1335 of file MinimizerDONLP2orthogonalvapp.c.
References calcprojectedHamiltonian(), env, FORTRAN, hbc, moveboostSlaterDet(), and sigterminate.
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  // nail to center-of-mass
  moveboostSlaterDet(Min.Q, Work.X);
  double eintr, eortho;
  calcprojectedHamiltonian(Min.nfix,
                           Min.Qfix,
                           Min.Q,
                           Min.Int,
                           Min.j, Min.par, Min.ifix,
                           Min.projpar,
                           &eintr, &eortho);
  *fx = (eortho+Min.alpha*eintr);
  FORTRAN(o8cnt).icf++;
  fprintf(stderr, "\tme      E = % 8.3f MeV, Eortho = %8.3f MeV, Eintr = %8.3f MeV,\n",
          hbc*(*fx), hbc*eortho, hbc*eintr);
}
void FORTRAN() eg (int * i, const double * x, double * gxi)
Definition at line 1426 of file MinimizerDONLP2orthogonalvapp.c.
References APOS, MINIMUMA, and NGAUSS.
{
  if (!strcmp(Min.P->name, "FMD")) {
    *gxi = x[(*i-1)*NGAUSS+APOS]-MINIMUMA;
  }
}
void FORTRAN() egradf (const double * x, double * gradf)
Definition at line 1367 of file MinimizerDONLP2orthogonalvapp.c.
References addmulttogradSlaterDet(), calcgradHamiltonian(), calcgradprojectedHamiltonian(), calcgradSlaterDetAux(), calcSlaterDetAux(), env, FORTRAN, fprintinfo(), hbc, icgf, moveboostSlaterDet(), sigterminate, and writeSlaterDet().
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  // nail to center-of-mass
  moveboostSlaterDet(Min.Q, Work.X);
  double eintr, eortho;
  calcgradprojectedHamiltonian(Min.nfix,
                               Min.Qfix,
                               Min.Q,
                               Min.Int,
                               Min.j, Min.par, Min.ifix,
                               Min.projpar,
                               &eintr, &eortho);
  // add gradient from intrinsic energy
  calcSlaterDetAux(Min.Q, Work.X);
  calcgradSlaterDetAux(Min.Q, Work.X, Work.dX);
  calcgradHamiltonian(Min.Int, Min.Q, Work.X, Work.dX, Work.dh);
  addmulttogradSlaterDet(Work.dhmulti, Work.dh, Min.alpha);
  Min.P->ParaprojectgradSlaterDet(Min.q, Work.dhmulti, gradf);
  FORTRAN(o8cnt).icgf++;
  fprintf(stderr, "grad %3d: \tE = %8.3f MeV, Eortho = %8.3f MeV, Eintr = %8.3f MeV\n",
          FORTRAN(o8cnt).icgf, hbc*(eortho+Min.alpha*eintr), hbc*eortho, hbc*eintr);
  if (Min.log && !(FORTRAN(o8cnt).icgf % Min.log)) {
    char logfname[255];
    sprintf(logfname, "%s.minovap.%03d.log", Min.logfile, FORTRAN(o8cnt).icgf);
    FILE* logfp;
    if (!(logfp = fopen(logfname, "w"))) {
      fprintf(stderr, "couldn't open %s for writing\n", logfname);
    } else {
      fprintinfo(logfp);
      fprintf(logfp, "# step %3d: \tE = %8.3f MeV, Eortho = %8.3f MeV, Eintr = %8.3f MeV\n",
              FORTRAN(o8cnt).icgf, hbc*(eortho+Min.alpha*eintr), hbc*eortho, hbc*eintr);
      fprintf(logfp, "\n# Parameterization\n");
      fprintf(logfp, "<Parameterization %s>\n", Min.P->name);
      Min.P->Parawrite(logfp, Min.q);
      fprintf(logfp, "\n# SlaterDet\n");
      writeSlaterDet(logfp, Min.Q);
      fclose(logfp);
    }
  }
}
void FORTRAN() egradg (int * i, const double * x, double * gradgi)
Definition at line 1434 of file MinimizerDONLP2orthogonalvapp.c.
{
}
void FORTRAN() egradh (int * i, const double * x, double * gradhi)
Definition at line 1464 of file MinimizerDONLP2orthogonalvapp.c.
References calcgradSlaterDetAux(), calcSlaterDetAux(), env, moveboostSlaterDet(), sigterminate, and zerogradSlaterDet().
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  if (*i > 1) {
    // nail to center-of-mass
    moveboostSlaterDet(Min.Q, Work.X);
  }
  calcSlaterDetAux(Min.Q, Work.X);
  calcgradSlaterDetAux(Min.Q, Work.X, Work.dX);
  zerogradSlaterDet(Work.dh);
  Min.Const[*i-1].gradme(Min.Q, Work.X, Work.dX, Work.dh);
  Min.P->ParaprojectgradSlaterDet(Min.q, Work.dh, gradhi);
  fprintf(stderr, "\t\t\tgrad %4s = %8.3f\n",
          Min.Const[*i-1].label, Min.Const[*i-1].output(Work.dh->val));
}
void FORTRAN() eh (int * i, const double * x, double * hxi)
Definition at line 1439 of file MinimizerDONLP2orthogonalvapp.c.
References calcSlaterDetAux(), env, moveboostSlaterDet(), and sigterminate.
{
#ifndef MPI
  if (sigterminate)
    longjmp(env, 1);
#endif
  copyxtopara(x, Min.q);
  Min.P->ParatoSlaterDet(Min.q, Min.Q);
  if (*i > 1) {
    // nail to center-of-mass
    moveboostSlaterDet(Min.Q, Work.X);
  }
  calcSlaterDetAux(Min.Q, Work.X);
  Min.Const[*i-1].me(Min.Q, Work.X, hxi);
  fprintf(stderr, "\t\t\tme   %4s = %8.3f\n",
          Min.Const[*i-1].label, Min.Const[*i-1].output(*hxi));
  *hxi -= Min.Const[*i-1].val;
}
void hermiteancopy (int j, const complex double * A, complex double * B)
Definition at line 307 of file MinimizerDONLP2orthogonalvapp.c.
References k.
{
  int k,kp;
  for (kp=0; kp<j+1; kp++)
    for (k=0; k<j+1; k++)
      B[k+kp*(j+1)] = conj(A[kp+k*(j+1)]);
}
void initWork (int nfix, const SlaterDet * Qfix, int j, int par, angintegrationpara * AngPar, const Interaction * Int, const SlaterDet * Q)
Definition at line 691 of file MinimizerDONLP2orthogonalvapp.c.
References calcprojectedHamiltonianmatrix(), expect(), generalizedeigensystem(), hbc, hermiteancopy(), initgradSlaterDet(), initgradSlaterDetAux(), initSlaterDet(), initSlaterDetAux(), kmixingstates(), sorteigenstates(), THRESHKMIX, and THRESHMULTI.
{
  int n=nfix+1;
  int a,b;
  int k;
  Work.Qp = malloc(sizeof(SlaterDet));
  Work.Qpp = malloc(sizeof(SlaterDet));
  Work.X = malloc(sizeof(SlaterDetAux));
  Work.dX = malloc(sizeof(gradSlaterDetAux));
  initSlaterDet(Q, Work.Qp);
  initSlaterDet(Q, Work.Qpp);
  initSlaterDetAux(Q, Work.X);
  initgradSlaterDetAux(Q, Work.dX);
  Work.dH = malloc(n*sizeof(void*));
  Work.dN = malloc(n*sizeof(void*));
  for (b=0; b<n; b++) {
    Work.dH[b] = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
    Work.dN[b] = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
    for (k=0; k<(j+1)*(j+1); k++) {
      initgradSlaterDet(Q, &Work.dH[b][k]);
      initgradSlaterDet(Q, &Work.dN[b][k]);
    }
  }
  Work.dh = malloc(sizeof(gradSlaterDet));
  Work.dn = malloc(sizeof(gradSlaterDet));
  Work.dhmulti = malloc(sizeof(gradSlaterDet));
  Work.dnmulti = malloc(sizeof(gradSlaterDet));
  initgradSlaterDet(Q, Work.dh);
  initgradSlaterDet(Q, Work.dn);
  initgradSlaterDet(Q, Work.dhmulti);
  initgradSlaterDet(Q, Work.dnmulti);
  Work.V = malloc(n*sizeof(void*));
  for (a=0; a<n; a++)
    Work.V[a] = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.dim = malloc(n*sizeof(int));
  Work.H = malloc(n*n*sizeof(void*));
  Work.N = malloc(n*n*sizeof(void*));
  Work.J2 = malloc(n*n*sizeof(void*));
  for (b=0; b<n; b++)
    for (a=0; a<n; a++) {
      Work.H[a+b*n] = malloc((j+1)*(j+1)*sizeof(complex double));
      Work.N[a+b*n] = malloc((j+1)*(j+1)*sizeof(complex double));
      Work.J2[a+b*n] = malloc((j+1)*(j+1)*sizeof(complex double));
    }
  // calculate diagonal matrix elements for fix configs
  int ia;
  for (a=0; a<nfix; a++) {
    calcprojectedHamiltonianmatrix(&Qfix[a], &Qfix[a], Int, j, par, AngPar,
                                   Work.H[a+a*n], Work.N[a+a*n], Work.J2[a+a*n]);
    double efix[j+1];
    kmixingstates(Work.H[a+a*n], Work.N[a+a*n], j, THRESHKMIX,
                  efix, Work.V[a], &Work.dim[a]);
    for (ia=0; ia<Work.dim[a]; ia++)
      fprintf(stderr, "Qfix[%d]:  E[%d] = %8.3f MeV\n", a, ia, hbc*efix[ia]);
  }
  // calculate upper part of off-diagonal matrix elements for fix configs
  for (b=1; b<nfix; b++) {
    for (a=0; a<=b; a++) {
      calcprojectedHamiltonianmatrix(&Qfix[a], &Qfix[b], Int, j, par, AngPar,
                                     Work.H[a+b*n], Work.N[a+b*n], Work.J2[a+b*n]);
      hermiteancopy(j, Work.H[a+b*n], Work.H[b+a*n]);
      hermiteancopy(j, Work.N[a+b*n], Work.N[b+a*n]);
    }
  }
  // build H and N matrix in subspace from K-mixing eigenstates
  int i, dimfix=0;
  for (i=0; i<nfix; i++)
    dimfix += Work.dim[i];
  complex double Hfix[dimfix*dimfix], Nfix[dimfix*dimfix];
  int ib, idxa, idxb, kp;
  idxb=-1;
  for (b=0; b<nfix; b++)
    for (ib=0; ib<Work.dim[b]; ib++) {
      idxb++;
      idxa=-1;
      for (a=0; a<nfix; a++)
        for (ia=0; ia<Work.dim[a]; ia++) {
          idxa++;
          Hfix[idxa+idxb*dimfix] = 0.0;
          Nfix[idxa+idxb*dimfix] = 0.0;
          for (kp=0; kp<j+1; kp++)
            for (k=0; k<j+1; k++)
              Hfix[idxa+idxb*dimfix] +=
                conj(Work.V[a][k+ia*(j+1)])*
                Work.H[a+b*n][k+kp*(j+1)]*
                Work.V[b][kp+ib*(j+1)];
          for (kp=0; kp<j+1; kp++)
            for (k=0; k<j+1; k++)
              Nfix[idxa+idxb*dimfix] +=
                conj(Work.V[a][k+ia*(j+1)])*
                Work.N[a+b*n][k+kp*(j+1)]*
                Work.V[b][kp+ib*(j+1)];
        }
    }
  // solve eigenvalue problem in subspace
  complex double efix[dimfix];
  complex double Vfix[dimfix*dimfix];
  int dfix;
  generalizedeigensystem(Hfix, Nfix, dimfix, THRESHMULTI, efix, Vfix, &dfix);
  sorteigenstates(dimfix, efix, Vfix, dfix);
  // normalize eigenstates
  double normfix[dfix];
  for (i=0; i<dfix; i++) {
    normfix [i] = expect(dimfix, Nfix, &Vfix[i*dimfix]);
    for (idxa=0; idxa<dimfix; idxa++)
      Vfix[idxa+i*dimfix] /= sqrt(normfix[i]);
  }
  // eigenstates of fix configs
  Work.Vo = malloc(dfix*nfix*(j+1)*sizeof(complex double));
  for (i=0; i<dfix; i++) {
    for (a=0; a<nfix; a++)
      for (k=0; k<j+1; k++)
        Work.Vo[k+a*(j+1)+i*nfix*(j+1)] = 0.0;
    idxa=-1;
    for (a=0; a<nfix; a++)
      for (ia=0; ia<Work.dim[a]; ia++) {
        idxa++;
        for (k=0; k<j+1; k++)
          Work.Vo[k+a*(j+1)+i*nfix*(j+1)] += Vfix[idxa+i*dimfix]*Work.V[a][k+ia*(j+1)];
    }
  }
}
void kmixingstates (complex double * H, complex double * N, int j, double thresh, double * egood, complex double * Vgood, int * ngood)
Definition at line 211 of file MinimizerDONLP2orthogonalvapp.c.
References generalizedeigensystem(), k, l, MINNORMKMIX, V, and val.
{
  complex double e[j+1];
  complex double V[(j+1)*(j+1)];
  int d;
  generalizedeigensystem(H, N, j+1, thresh, e, V, &d);
  // we got d eigenstates, filter out the noise
  // see sortEigenstates
  double norm[d];
  int i, k, l;
  for (i=0; i<d; i++) {
      norm[i] = 0.0;
      for (l=0; l<j+1; l++)
        for (k=0; k<j+1; k++)
          norm[i] += conj(V[k+i*(j+1)])*N[k+l*(j+1)]*V[l+i*(j+1)];
    }
  double maxnorm = 0.0;
  for (i=0; i<d; i++)
    maxnorm = fmax(maxnorm, creal(norm[i]));
  // merits
  struct merit {
    double val;
    int idx;
  } merits[d];
  for (i=0; i<d; i++) {
    merits[i].idx = i;
    if (creal(norm[i]) < MINNORMKMIX*maxnorm)
      merits[i].val = -100000.0;
    else
      merits[i].val = -creal(e[i]);
  }
  // sort according to merits value
  qsort(merits, d, sizeof(struct merit), cmpmerit);
  // now write good eigenvalues and eigenvectors into egood, Vgood
  i=0; while(i<d && merits[i].val > -100000.0) {
    egood[i] = -merits[i].val;
    for (k=0; k<j+1; k++)
      Vgood[k+i*(j+1)] = V[k+merits[i].idx*(j+1)];
    i++;
  }
  *ngood = i;
}
void MinimizeDONLP2orthogonalvapp (const Interaction * Int, int j, int par, int ifix, double alpha, angintegrationpara * projpar, const Constraint * Const, int nconst, int nfix, SlaterDet * Qfix, Parameterization * P, Para * q, int maxsteps, int log, const char * logfile)
Definition at line 1289 of file MinimizerDONLP2orthogonalvapp.c.
References catchterminate(), donlp2(), env, FORTRAN, optite, and Parameterization::ParainitSlaterDet.
Referenced by main().
{
#ifndef MPI
  // handler for INT and TERM signals
  signal(SIGINT, catchterminate);
  signal(SIGTERM, catchterminate);
#endif
  Min.maxsteps = maxsteps;
  Min.log = log;
  Min.logfile = logfile;
  Min.Int = Int;
  Min.j = j;
  Min.par = par;
  Min.ifix = ifix;
  Min.alpha = alpha;
  Min.projpar = projpar;
  Min.Const = Const;
  Min.nconst = nconst;
  Min.nfix = nfix;
  Min.Qfix = Qfix;
  Min.q = q;
  Min.P = P;
  Min.Q = malloc(sizeof(SlaterDet));
  P->ParainitSlaterDet(q, Min.Q);
#ifndef MPI
  // regular program execution or catched signal ?
  if (!setjmp(env))
#endif
    FORTRAN(donlp2)();
  fprintf(stderr, "donlp2 terminated because of criterium %d\n",
          (int) FORTRAN(o8itin).optite + 11);
  copyxtopara(FORTRAN(o8xdat).x, Min.q);
}
void FORTRAN() setup (void)
Definition at line 1526 of file MinimizerDONLP2orthogonalvapp.c.
References FORTRAN.
{
  FORTRAN(o8stpa).te0 = 0;
  FORTRAN(o8stpa).te1 = 0;
  FORTRAN(o8par).iterma = Min.maxsteps-1;
}
void FORTRAN() setup0 (void)
Definition at line 1489 of file MinimizerDONLP2orthogonalvapp.c.
References APOS, FORTRAN, and NGAUSS.
{
  int i;
  FORTRAN(o8dim).n = Min.q->n;
  FORTRAN(o8dim).nh = Min.nconst;
  // in case of FMD parametrization use bound constraints for Re{a}
  if (!strcmp(Min.P->name, "FMD")) {
    FORTRAN(o8dim).ng = Min.q->ngauss;
    for (i=0; i<Min.nconst+1; i++) {
      FORTRAN(o8gri).gunit[i][0] = -1;
      FORTRAN(o8gri).gunit[i][1] = 0;
      FORTRAN(o8gri).gunit[i][2] = 0;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      FORTRAN(o8gri).gunit[i+Min.nconst+1][0] = 1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][1] = i*NGAUSS+APOS+1;
      FORTRAN(o8gri).gunit[i+Min.nconst+1][2] = 1;
    }
    for (i=0; i<Min.q->ngauss; i++) {
      if (Min.q->x[i*NGAUSS+APOS] < 0)
        Min.q->x[i*NGAUSS+APOS] = 1.0+1.0*rand()/RAND_MAX;
    }
  } else
    FORTRAN(o8dim).ng = 0;
  FORTRAN(o8stpa).analyt = 1;
  FORTRAN(o8stpa).cold = 1;
  FORTRAN(o8par).tau0 = 20.0;
  FORTRAN(o8par).del0 = 1.0;
  FORTRAN(o8rst).nreset = 20;
  FORTRAN(o8stpa).silent = 1;
  for (i=0; i<Min.q->n; i++)
    FORTRAN(o8xdat).x[i] = Min.q->x[i];
}
Variable Documentation
double alpha
finestructure constant
Definition at line 109 of file MinimizerDONLP2orthogonalvapp.c.
const Constraint* Const
Definition at line 112 of file MinimizerDONLP2orthogonalvapp.c.
gradSlaterDet* dh
Definition at line 139 of file MinimizerDONLP2orthogonalvapp.c.
gradSlaterDet** dH
Definition at line 129 of file MinimizerDONLP2orthogonalvapp.c.
gradSlaterDet* dhmulti
Definition at line 141 of file MinimizerDONLP2orthogonalvapp.c.
int* dim
Definition at line 124 of file MinimizerDONLP2orthogonalvapp.c.
gradSlaterDet* dn
Definition at line 140 of file MinimizerDONLP2orthogonalvapp.c.
gradSlaterDet** dN
Definition at line 130 of file MinimizerDONLP2orthogonalvapp.c.
gradSlaterDet* dnmulti
Definition at line 142 of file MinimizerDONLP2orthogonalvapp.c.
gradSlaterDetAux* dX
Definition at line 137 of file MinimizerDONLP2orthogonalvapp.c.
jmp_buf env
Definition at line 86 of file MinimizerDONLP2orthogonalvapp.c.
complex double** H
Definition at line 125 of file MinimizerDONLP2orthogonalvapp.c.
int ifix
Definition at line 108 of file MinimizerDONLP2orthogonalvapp.c.
Referenced by main(), writeTransitionChargeDensities(), writeTransitionChargeFormfactors(), writeTransitionChargeFourierBessel(), writeTransitionPointDensities(), and writeTransitionPointFormfactors().
const Interaction* Int
Definition at line 105 of file MinimizerDONLP2orthogonalvapp.c.
int j
Definition at line 106 of file MinimizerDONLP2orthogonalvapp.c.
complex double** J2
Definition at line 127 of file MinimizerDONLP2orthogonalvapp.c.
int log
Definition at line 102 of file MinimizerDONLP2orthogonalvapp.c.
const char* logfile
Definition at line 103 of file MinimizerDONLP2orthogonalvapp.c.
int maxsteps
Definition at line 104 of file MinimizerDONLP2orthogonalvapp.c.
complex double** N
Definition at line 126 of file MinimizerDONLP2orthogonalvapp.c.
int nangles
Definition at line 111 of file MinimizerDONLP2orthogonalvapp.c.
int nconst
Definition at line 113 of file MinimizerDONLP2orthogonalvapp.c.
int nfix
Definition at line 114 of file MinimizerDONLP2orthogonalvapp.c.
Parameterization* P
Definition at line 117 of file MinimizerDONLP2orthogonalvapp.c.
int par
Definition at line 107 of file MinimizerDONLP2orthogonalvapp.c.
angintegrationpara* projpar
Definition at line 110 of file MinimizerDONLP2orthogonalvapp.c.
SlaterDet* Q
Definition at line 118 of file MinimizerDONLP2orthogonalvapp.c.
Para* q
Definition at line 116 of file MinimizerDONLP2orthogonalvapp.c.
SlaterDet* Qfix
Definition at line 115 of file MinimizerDONLP2orthogonalvapp.c.
SlaterDet* Qp
Definition at line 134 of file MinimizerDONLP2orthogonalvapp.c.
SlaterDet* Qpp
Definition at line 135 of file MinimizerDONLP2orthogonalvapp.c.
volatile sig_atomic_t sigterminate
Definition at line 88 of file MinimizerDONLP2orthogonalvapp.c.
complex double** V
Definition at line 123 of file MinimizerDONLP2orthogonalvapp.c.
complex double* Vo
Definition at line 132 of file MinimizerDONLP2orthogonalvapp.c.
SlaterDetAux* X
Definition at line 136 of file MinimizerDONLP2orthogonalvapp.c.