FMD: MinimizerDONLP2proj.h File Reference
MinimizerDONLP2proj.h File Reference
#include "fmd/Interaction.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/Parameterization.h"
#include "fmd/Constraint.h"
#include "fmd/Projection.h"
Functions
void initWork (const SlaterDet *Q)
void calcprojectedHamiltonian (const SlaterDet *Q, const Interaction *Int, int j, int k, int par, angintegrationpara *projpar, double *eintr, double *eproj)
void MinimizeDONLP2proj (const Interaction *Int, int j, int k, int par, angintegrationpara *projpar, const Constraint *Const, int nconst, Parameterization *P, Para *q, int maxsteps, int log, const char *logfile)
Detailed Description
using the minimization routine donlp2
(c) 2003-2006 Thomas Neff
Definition in file MinimizerDONLP2proj.h.
Function Documentation
void calcprojectedHamiltonian (const SlaterDet * Q, const Interaction * Int, int j, int k, int par, angintegrationpara * projpar, double * eintr, double * eproj)
Definition at line 179 of file MinimizerDONLP2orthogonalproj.c.
{
  SlaterDet* Qp = Work.Qp;
  SlaterDet* Qpp = Work.Qpp;
  SlaterDetAux* X = Work.X;
  int n = projpar->n;
  double alpha, beta, gamma, w;
#ifdef ORIENTED
  double alpha0, beta0, gamma0;
#endif
  complex double hme, nme, j2me;
  complex double H=0.0, N=0.0, J2=0.0;
  complex double hintr, nintr;
  copySlaterDet(Q, Qp);
#ifdef ORIENTED
  calcSlaterDetAuxod(Qp, Qp, X);
  calcOrientedOrientation(Qp, X, &alpha0, &beta0, &gamma0);
  if (orientationinverted(alpha0, beta0, gamma0, lalpha0, lbeta0, lgamma0))
    invertangles(&alpha0, &beta0, &gamma0);
  fprintf(stderr, "... (alpha, beta, gamma) = (%5.2f, %5.2f, %5.2f)\n",
          alpha0*180/M_PI, beta0*180/M_PI, gamma0*180/M_PI);
  rotateSlaterDet(Qp, -gamma0, -beta0, -alpha0);
#endif
  calcSlaterDetAuxod(Qp, Qp, X);
  nintr = X->ovlap;
  calcHamiltonianod(Int, Qp, Qp, X, &hintr);
#ifdef RANDOMIZED
  double alpharan, gammaran;
  alpharan = 0.005*2*M_PI*rand()/RAND_MAX;
  gammaran = 0.005*2*M_PI*rand()/RAND_MAX;
#endif
  int i, ip;
  for (i=0; i<n; i++) {
    copySlaterDet(Qp, Qpp);
    getangintegrationpoint(i, projpar, &alpha, &beta, &gamma, &w);
#ifdef RANDOMIZED
    alpha += alpharan;
    gamma += gammaran;
#endif
    rotateSlaterDet(Qpp, alpha, beta, gamma);
    for (ip=0; ip<=1; ip++) {
      if (ip) invertSlaterDet(Qpp);
      calcSlaterDetAuxod(Qp, Qpp, X);
      nme = X->ovlap;
      calcHamiltonianod(Int, Qp, Qpp, X, &hme);
      calcConstraintJ2od(Qp, Qpp, X, &j2me);
      H += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*Djmkstar(j,k,k,alpha,beta,gamma)*hme;
      N += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*Djmkstar(j,k,k,alpha,beta,gamma)*nme;
      J2 += w/2*(ip ? par : 1)*(j+1)/(8*M_PI2)*Djmkstar(j,k,k,alpha,beta,gamma)*j2me;
    }
  }
  fprintf(stderr, "... n: %9.7f, J2: %6.3f\n",
          creal(N/nintr),
          creal(J2/N));
  *hproj = creal(H);
  *nproj = creal(N);
}
void initWork (const SlaterDet * Q)
Definition at line 167 of file MinimizerDONLP2orthogonalproj.c.
{
  Work.Qp = malloc(sizeof(SlaterDet));
  Work.Qpp = malloc(sizeof(SlaterDet));
  Work.X = malloc(sizeof(SlaterDetAux));
  initSlaterDet(Q, Work.Qp);
  initSlaterDet(Q, Work.Qpp);
  initSlaterDetAux(Q, Work.X);
}
void MinimizeDONLP2proj (const Interaction * Int, int j, int k, int par, angintegrationpara * projpar, const Constraint * Const, int nconst, Parameterization * P, Para * q, int maxsteps, int log, const char * logfile)
Definition at line 672 of file MinimizerDONLP2proj.c.
References catchterminate(), donlp2(), env, FORTRAN, initgradSlaterDet(), initgradSlaterDetAux(), initSlaterDetAux(), and optite.
Referenced by main().
{
#ifndef MPI
  // handler for INT and TERM signals
  signal(SIGINT, catchterminate);
  signal(SIGTERM, catchterminate);
#endif
  Min.maxsteps = maxsteps;
  Min.log = log;
  Min.logfile = logfile;
  Min.Int = Int;
  Min.j = j;
  Min.k = k;
  Min.par = par;
  Min.projpar = projpar;
  Min.Const = Const;
  Min.nconst = nconst;
  Min.q = q;
  Min.P = P;
  Min.Q = malloc(sizeof(SlaterDet));
  Min.Qp = malloc(sizeof(SlaterDet));
  Min.Qpp = malloc(sizeof(SlaterDet));
  Min.X = malloc(sizeof(SlaterDetAux));
  Min.dX = malloc(sizeof(gradSlaterDetAux));
  Min.dH = malloc(sizeof(gradSlaterDet));
  Min.dN = malloc(sizeof(gradSlaterDet));
  Min.dh = malloc(sizeof(gradSlaterDet));
  Min.dn = malloc(sizeof(gradSlaterDet));
  Min.P->ParainitSlaterDet(q, Min.Q);
  Min.P->ParainitSlaterDet(q, Min.Qp);
  Min.P->ParainitSlaterDet(q, Min.Qpp);
  initSlaterDetAux(Min.Q, Min.X);
  initgradSlaterDetAux(Min.Q, Min.dX);
  initgradSlaterDet(Min.Q, Min.dH);
  initgradSlaterDet(Min.Q, Min.dN);
  initgradSlaterDet(Min.Q, Min.dh);
  initgradSlaterDet(Min.Q, Min.dn);
#ifndef MPI
  // regular program execution or catched signal ?
  if (!setjmp(env))
#endif
    FORTRAN(donlp2)();
  fprintf(stderr, "donlp2 terminated because of criterium %d\n",
          (int) FORTRAN(o8itin).optite + 11);
  copyxtopara(FORTRAN(o8xdat).x, Min.q);
}