FMD: MinimizerDONLP2multivappcm.h File Reference
MinimizerDONLP2multivappcm.h File Reference
#include "fmd/Interaction.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/Parameterization.h"
#include "fmd/Constraint.h"
#include "fmd/Projection.h"
Functions
void initWork (int nfix, const SlaterDet *Qfix, int j, int par, angintegrationpara *angpara, cmintegrationpara *cmpara, const Interaction *Int, const SlaterDet *Q)
void calcprojectedHamiltonian (int nfix, const SlaterDet *Qfix, const SlaterDet *Q, const Interaction *Int, int j, int par, int ival, angintegrationpara *angpara, cmintegrationpara *cmpara, double *eintr, double *emulti)
void MinimizeDONLP2multivapp (const Interaction *Int, int j, int par, int ival, double threshkmix, double minnormkmix, double alpha, angintegrationpara *angpara, cmintegrationpara *cmpara, const Constraint *Const, int nconst, int nfix, SlaterDet *Qfix, Parameterization *P, Para *q, int maxsteps, int log, const char *logfile)
Detailed Description
using the minimization routine donlp2
(c) 2003-2011 Thomas Neff
Definition in file MinimizerDONLP2multivappcm.h.
Function Documentation
void calcprojectedHamiltonian (int nfix, const SlaterDet * Qfix, const SlaterDet * Q, const Interaction * Int, int j, int par, int ival, angintegrationpara * angpara, cmintegrationpara * cmpara, double * eintr, double * emulti)
Definition at line 821 of file MinimizerDONLP2multivappcm.c.
References ALLOWEDJ2DEVIATION, calcHamiltonianod(), calcOrientedOrientation(), calcprojectedHamiltonianmatrix(), calcSlaterDetAuxod(), calcsubspaceoverlap(), copySlaterDet(), dim, expect(), generalizedeigensystem(), hbc, hermiteancopy(), invertangles(), kmixingstates(), multcmat(), orientationinverted(), SlaterDetAux::ovlap, rotateSlaterDet(), sorteigenstates(), THRESHMULTI, V, and X.
{
  complex double** H = Work.H;
  complex double** N = Work.N;
  complex double** J2 = Work.J2;
  complex double** V = Work.V;
  int* dim = Work.dim;
  // Q is intrinsic state to be varied
  // orient properly
  // then calculate needed matrix elements
  // solve eigenvalue problem in smaller subspace spanned by K-mixing eigenstates
  int n = nfix+1;
  SlaterDet* Qp = Work.Qp;
  SlaterDetAux* X = Work.X;
#ifdef ORIENTED
  double alpha0, beta0, gamma0;
#endif
  complex double hintr, nintr;
  copySlaterDet(Q, Qp);
#ifdef ORIENTED
  calcSlaterDetAuxod(Qp, Qp, X);
  calcOrientedOrientation(Qp, X, &alpha0, &beta0, &gamma0);
  if (orientationinverted(alpha0, beta0, gamma0, lalpha0, lbeta0, lgamma0))
    invertangles(&alpha0, &beta0, &gamma0);
  fprintf(stderr, "... (alpha, beta, gamma) = (%5.2f, %5.2f, %5.2f)\n",
          alpha0*180/M_PI, beta0*180/M_PI, gamma0*180/M_PI);
  rotateSlaterDet(Qp, -gamma0, -beta0, -alpha0);
#endif
  // intrinsic state
  calcSlaterDetAuxod(Qp, Qp, X);
  if (isnan(X->ovlap)) {
    *eintr = ENERGYPENALTY;
    *emulti = ENERGYPENALTY;
    return;
  }
  nintr = X->ovlap;
  calcHamiltonianod(Int, Qp, Qp, X, &hintr);
  // projected matrix elements, off-diagonals
  int i;
  for (i=0; i<nfix; i++) {
    calcprojectedHamiltonianmatrix(Qp, &Qfix[i], Int, j, par, angpara, cmpara,
                                   H[(n-1)+i*n], N[(n-1)+i*n], J2[(n-1)+i*n]);
    hermiteancopy(j, H[(n-1)+i*n], H[i+(n-1)*n]);
    hermiteancopy(j, N[(n-1)+i*n], N[i+(n-1)*n]);
    hermiteancopy(j, J2[(n-1)+i*n], J2[i+(n-1)*n]);
  }
  // projected matrix elements for Qp
  calcprojectedHamiltonianmatrix(Qp, Qp, Int, j, par, angpara, cmpara,
                                 H[(n-1)+(n-1)*n], N[(n-1)+(n-1)*n], J2[(n-1)+(n-1)*n]);
  // K-mixing for Qp
  double ed[j+1];
  kmixingstates(H[(n-1)+(n-1)*n], N[(n-1)+(n-1)*n], j, Min.threshkmix,
                ed, V[n-1], &dim[n-1]);
  if (!dim[n-1]) {
    fprintf(stderr, "no good eigenstate for Q !\n");
  }
  // dim[n-1] = 1;
  // ovlap of k-mixing states with intrinsic state
  complex double N2[(j+1)*(j+1)];
  multcmat(N[(n-1)+(n-1)*n], N[(n-1)+(n-1)*n], N2, j+1);
  complex double hproj[j+1], nproj[j+1], n2proj[j+1], j2proj[j+1];
  for (i=0; i<dim[n-1]; i++) {
    hproj[i] = expect(j+1, H[(n-1)+(n-1)*n], &V[n-1][i*(j+1)]);
    nproj[i] = expect(j+1, N[(n-1)+(n-1)*n], &V[n-1][i*(j+1)]);
    n2proj[i] = expect(j+1, N2, &V[n-1][i*(j+1)]);
    j2proj[i] = expect(j+1, J2[(n-1)+(n-1)*n], &V[n-1][i*(j+1)]);
  }
  for (i=0; i<dim[n-1]; i++)
    fprintf(stderr, "Q eigenstate %d: E = %8.3f MeV, n = %8.7f, J2 = %6.3f\n", i,
            hbc*creal(hproj[i]/nproj[i]), creal(n2proj[i]/(nintr*nproj[i])), creal(j2proj[i]/nproj[i]));
  // build H and N matrix in subspace from K-mixing eigenstates
  int dimsub=0;
  for (i=0; i<n; i++)
    dimsub += dim[i];
  complex double Hsub[dimsub*dimsub], Nsub[dimsub*dimsub];
  int a, b, ia, ib, idxa, idxb, k, kp;
  idxb=-1;
  for (b=0; b<n; b++)
    for (ib=0; ib<dim[b]; ib++) {
      idxb++;
      idxa=-1;
      for (a=0; a<n; a++)
        for (ia=0; ia<dim[a]; ia++) {
          idxa++;
          Hsub[idxa+idxb*dimsub] = 0.0;
          Nsub[idxa+idxb*dimsub] = 0.0;
          for (kp=0; kp<j+1; kp++)
            for (k=0; k<j+1; k++)
              Hsub[idxa+idxb*dimsub] +=
                conj(V[a][k+ia*(j+1)])*
                H[a+b*n][k+kp*(j+1)]*
                V[b][kp+ib*(j+1)];
          for (kp=0; kp<j+1; kp++)
            for (k=0; k<j+1; k++)
              Nsub[idxa+idxb*dimsub] +=
                conj(V[a][k+ia*(j+1)])*
                N[a+b*n][k+kp*(j+1)]*
                V[b][kp+ib*(j+1)];
        }
    }
  // solve eigenvalue problem in subspace
  complex double esub[dimsub];
  complex double Vsub[dimsub*dimsub];
  int dsub;
  generalizedeigensystem(Hsub, Nsub, dimsub, THRESHMULTI, esub, Vsub, &dsub);
  sorteigenstates(dimsub, esub, Vsub, dsub);
  double ovlQfix[dimsub], ovlQ[dimsub], ovlall[dimsub];
  calcsubspaceoverlap(dimsub, Nsub, Vsub, dsub, 0, dimsub-dim[n-1], ovlQfix);
  calcsubspaceoverlap(dimsub, Nsub, Vsub, dsub, dimsub-dim[n-1], dimsub, ovlQ);
  calcsubspaceoverlap(dimsub, Nsub, Vsub, dsub, 0, dimsub, ovlall);
  for (i=0; i<dsub; i++)
    fprintf(stderr, "Multiconfig eigenstate %d = %8.3f, ovlQfix: %8.7f, ovlQ: %8.7f\n",
            i, hbc*creal(esub[i]), ovlQfix[i], ovlQ[i]);
  // expectation values for optimized eigenstate
  complex double* csub = &Vsub[ival*dimsub];
  complex double hmulti, nmulti;
  hmulti = expect(dimsub, Hsub, csub);
  nmulti = expect(dimsub, Nsub, csub);
  if (dabs(j2proj[0]/nproj[0] - 0.5*j*(0.5*j+1.0)) > ALLOWEDJ2DEVIATION) {
    *eintr = ENERGYPENALTY;
    *emulti = ENERGYPENALTY;
    return;
  }
  *eintr = hintr/nintr;
  *emulti = creal(hmulti/nmulti);
}
void initWork (int nfix, const SlaterDet * Qfix, int j, int par, angintegrationpara * angpara, cmintegrationpara * cmpara, const Interaction * Int, const SlaterDet * Q)
Definition at line 730 of file MinimizerDONLP2multivappcm.c.
References calcprojectedHamiltonianmatrix(), hbc, hermiteancopy(), initgradSlaterDet(), initgradSlaterDetAux(), initSlaterDet(), initSlaterDetAux(), and kmixingstates().
{
  int n=nfix+1;
  int a,b;
  int k;
  Work.Qp = malloc(sizeof(SlaterDet));
  Work.Qpp = malloc(sizeof(SlaterDet));
  Work.X = malloc(sizeof(SlaterDetAux));
  Work.dX = malloc(sizeof(gradSlaterDetAux));
  initSlaterDet(Q, Work.Qp);
  initSlaterDet(Q, Work.Qpp);
  initSlaterDetAux(Q, Work.X);
  initgradSlaterDetAux(Q, Work.dX);
  Work.dH = malloc(n*sizeof(void*));
  Work.dN = malloc(n*sizeof(void*));
  for (b=0; b<n; b++) {
    Work.dH[b] = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
    Work.dN[b] = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
    for (k=0; k<(j+1)*(j+1); k++) {
      initgradSlaterDet(Q, &Work.dH[b][k]);
      initgradSlaterDet(Q, &Work.dN[b][k]);
    }
  }
  Work.dh = malloc(sizeof(gradSlaterDet));
  Work.dn = malloc(sizeof(gradSlaterDet));
  Work.dhmulti = malloc(sizeof(gradSlaterDet));
  Work.dnmulti = malloc(sizeof(gradSlaterDet));
  initgradSlaterDet(Q, Work.dh);
  initgradSlaterDet(Q, Work.dn);
  initgradSlaterDet(Q, Work.dhmulti);
  initgradSlaterDet(Q, Work.dnmulti);
  Work.V = malloc(n*sizeof(void*));
  for (a=0; a<n; a++)
    Work.V[a] = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.dim = malloc(n*sizeof(int));
  Work.H = malloc(n*n*sizeof(void*));
  Work.N = malloc(n*n*sizeof(void*));
  Work.J2 = malloc(n*n*sizeof(void*));
  for (b=0; b<n; b++)
    for (a=0; a<n; a++) {
      Work.H[a+b*n] = malloc((j+1)*(j+1)*sizeof(complex double));
      Work.N[a+b*n] = malloc((j+1)*(j+1)*sizeof(complex double));
      Work.J2[a+b*n] = malloc((j+1)*(j+1)*sizeof(complex double));
    }
  // calculate diagonal matrix elements for fix configs
  int ia;
  for (a=0; a<nfix; a++) {
    calcprojectedHamiltonianmatrix(&Qfix[a], &Qfix[a], Int, j, par, angpara, cmpara,
                                   Work.H[a+a*n], Work.N[a+a*n], Work.J2[a+a*n]);
    double efix[j+1];
    kmixingstates(Work.H[a+a*n], Work.N[a+a*n], j, Min.threshkmix,
                  efix, Work.V[a], &Work.dim[a]);
    for (ia=0; ia<Work.dim[a]; ia++)
      fprintf(stderr, "Qfix[%d]:  E[%d] = %8.3f MeV\n", a, ia, hbc*efix[ia]);
  }
  // calculate upper part of off-diagonal matrix elements for fix configs
  for (b=1; b<nfix; b++) {
    for (a=0; a<=b; a++) {
      calcprojectedHamiltonianmatrix(&Qfix[a], &Qfix[b], Int, j, par, angpara, cmpara,
                                     Work.H[a+b*n], Work.N[a+b*n], Work.J2[a+b*n]);
      hermiteancopy(j, Work.H[a+b*n], Work.H[b+a*n]);
      hermiteancopy(j, Work.N[a+b*n], Work.N[b+a*n]);
    }
  }
}
void MinimizeDONLP2multivapp (const Interaction * Int, int j, int par, int ival, double threshkmix, double minnormkmix, double alpha, angintegrationpara * angpara, cmintegrationpara * cmpara, const Constraint * Const, int nconst, int nfix, SlaterDet * Qfix, Parameterization * P, Para * q, int maxsteps, int log, const char * logfile)
Definition at line 1212 of file MinimizerDONLP2multivappcm.c.
References catchterminate(), donlp2(), env, FORTRAN, optite, and Parameterization::ParainitSlaterDet.
{
#ifndef MPI
  // handler for INT and TERM signals
  signal(SIGINT, catchterminate);
  signal(SIGTERM, catchterminate);
#endif
  Min.maxsteps = maxsteps;
  Min.log = log;
  Min.logfile = logfile;
  Min.Int = Int;
  Min.j = j;
  Min.par = par;
  Min.ival = ival;
  Min.threshkmix = threshkmix;
  Min.minnormkmix = minnormkmix;
  Min.alpha = alpha;
  Min.angpara = angpara;
  Min.cmpara = cmpara;
  Min.Const = Const;
  Min.nconst = nconst;
  Min.nfix = nfix;
  Min.Qfix = Qfix;
  Min.q = q;
  Min.P = P;
  Min.Q = malloc(sizeof(SlaterDet));
  P->ParainitSlaterDet(q, Min.Q);
#ifndef MPI
  // regular program execution or catched signal ?
  if (!setjmp(env))
#endif
    FORTRAN(donlp2)();
  fprintf(stderr, "donlp2 terminated because of criterium %d\n",
          (int) FORTRAN(o8itin).optite + 11);
  copyxtopara(FORTRAN(o8xdat).x, Min.q);
}