FMD: MinimizerDONLP2vappiso.h File Reference
MinimizerDONLP2vappiso.h File Reference
#include "fmd/Interaction.h"
#include "fmd/SlaterDet.h"
#include "fmd/gradSlaterDet.h"
#include "fmd/Parameterization.h"
#include "fmd/Constraint.h"
#include "fmd/Projection.h"
Functions
void initWork (int j, int par, int iso, angintegrationpara *angpara, const Interaction *Int, const SlaterDet *Q)
void calcprojectedHamiltonian (const SlaterDet *Q, const Interaction *Int, int j, int par, int iso, int ival, angintegrationpara *angpara, double *eintr, double *eproj)
void MinimizeDONLP2vappiso (const Interaction *Int, int j, int par, int iso, int ival, double alpha, angintegrationpara *projpar, const Constraint *Const, int nconst, Parameterization *P, Para *q, int maxsteps, int log, const char *logfile)
Detailed Description
using the minimization routine donlp2
(c) 2003-2006 Thomas Neff
Definition in file MinimizerDONLP2vappiso.h.
Function Documentation
void calcprojectedHamiltonian (const SlaterDet * Q, const Interaction * Int, int j, int par, int iso, int ival, angintegrationpara * angpara, double * eintr, double * eproj)
Definition at line 1006 of file MinimizerDONLP2vappiso.c.
References calcHamiltonianod(), calcOrientedOrientation(), calcprojectedHamiltonianmatrix(), calcSlaterDetAuxod(), copySlaterDet(), dim, expect(), hbc, invertangles(), kmixingstates(), multcmat(), orientationinverted(), SlaterDetAux::ovlap, rotateSlaterDet(), THRESHKMIX, V, and X.
{
  complex double* H = Work.H;
  complex double* N = Work.N;
  complex double* J2 = Work.J2;
  complex double* V = Work.V;
  int dim = Work.dim;
  // Q is intrinsic state to be varied
  // orient properly
  // then calculate needed matrix elements
  // solve eigenvalue problem in smaller subspace spanned by K-mixing eigenstates
  SlaterDet* Qp = Work.Qp;
  SlaterDetAux* X = Work.X;
#ifdef ORIENTED
  double alpha0, beta0, gamma0;
#endif
  complex double hintr, nintr;
  copySlaterDet(Q, Qp);
#ifdef ORIENTED
  calcSlaterDetAuxod(Qp, Qp, X);
  calcOrientedOrientation(Qp, X, &alpha0, &beta0, &gamma0);
  if (orientationinverted(alpha0, beta0, gamma0, lalpha0, lbeta0, lgamma0))
    invertangles(&alpha0, &beta0, &gamma0);
  fprintf(stderr, "... (alpha, beta, gamma) = (%5.2f, %5.2f, %5.2f)\n",
          alpha0*180/M_PI, beta0*180/M_PI, gamma0*180/M_PI);
  rotateSlaterDet(Qp, -gamma0, -beta0, -alpha0);
#endif
  // intrinsic state
  calcSlaterDetAuxod(Qp, Qp, X);
  if (isnan(X->ovlap)) {
    *eintr = ENERGYPENALTY;
    *eproj = ENERGYPENALTY;
    return;
  }
  nintr = X->ovlap;
  calcHamiltonianod(Int, Qp, Qp, X, &hintr);
  // projected matrix elements for Qp
  calcprojectedHamiltonianmatrix(Qp, Qp, Int, j, par, iso, angpara,
                                 H, N, J2);
  // K-mixing for Qp
  double ed[j+1];
  kmixingstates(H, N, j, THRESHKMIX, ed, V, &dim);
  if (!dim) {
    fprintf(stderr, "no good eigenstate for Q !\n");
  }
  complex double N2[(j+1)*(j+1)];
  multcmat(N, N, N2, j+1);
  complex double hproj[j+1], nproj[j+1], n2proj[j+1], j2proj[j+1];
  int i;
  for (i=0; i<dim; i++) {
    hproj[i] = expect(j+1, H, &V[i*(j+1)]);
    nproj[i] = expect(j+1, N, &V[i*(j+1)]);
    n2proj[i] = expect(j+1, N2, &V[i*(j+1)]);
    j2proj[i] = expect(j+1, J2, &V[i*(j+1)]);
  }
  for (i=0; i<dim; i++)
    fprintf(stderr, "Q eigenstate %d: E = %8.3f MeV, n = %8.7f, J2 = %6.3f\n", i,
            hbc*creal(hproj[i]/nproj[i]), creal(n2proj[i]/(nintr*nproj[i])), creal(j2proj[i]/nproj[i]));
  *eintr = hintr/nintr;
  *eproj = creal(hproj[ival]/nproj[ival]);
}
void initWork (int j, int par, int iso, angintegrationpara * angpara, const Interaction * Int, const SlaterDet * Q)
Definition at line 962 of file MinimizerDONLP2vappiso.c.
References initgradSlaterDet(), initgradSlaterDetAux(), initSlaterDet(), and initSlaterDetAux().
{
  int k;
  Work.Qp = malloc(sizeof(SlaterDet));
  Work.Qpp = malloc(sizeof(SlaterDet));
  Work.X = malloc(sizeof(SlaterDetAux));
  Work.dX = malloc(sizeof(gradSlaterDetAux));
  initSlaterDet(Q, Work.Qp);
  initSlaterDet(Q, Work.Qpp);
  initSlaterDetAux(Q, Work.X);
  initgradSlaterDetAux(Q, Work.dX);
  Work.dH = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
  Work.dN = malloc((j+1)*(j+1)*sizeof(gradSlaterDet));
  for (k=0; k<(j+1)*(j+1); k++) {
    initgradSlaterDet(Q, &Work.dH[k]);
    initgradSlaterDet(Q, &Work.dN[k]);
  }
  Work.dhproj = malloc(sizeof(gradSlaterDet));
  Work.dnproj = malloc(sizeof(gradSlaterDet));
  initgradSlaterDet(Q, Work.dhproj);
  initgradSlaterDet(Q, Work.dnproj);
  Work.V = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.H = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.N = malloc((j+1)*(j+1)*sizeof(complex double));
  Work.J2 = malloc((j+1)*(j+1)*sizeof(complex double));
}
void MinimizeDONLP2vappiso (const Interaction * Int, int j, int par, int iso, int ival, double alpha, angintegrationpara * projpar, const Constraint * Const, int nconst, Parameterization * P, Para * q, int maxsteps, int log, const char * logfile)
Definition at line 1198 of file MinimizerDONLP2vappiso.c.
References catchterminate(), donlp2(), env, FORTRAN, optite, and Parameterization::ParainitSlaterDet.
Referenced by main().
{
#ifndef MPI
  // handler for INT and TERM signals
  signal(SIGINT, catchterminate);
  signal(SIGTERM, catchterminate);
#endif
  Min.maxsteps = maxsteps;
  Min.log = log;
  Min.logfile = logfile;
  Min.Int = Int;
  Min.j = j;
  Min.par = par;
  Min.iso = iso;
  Min.ival = ival;
  Min.alpha = alpha;
  Min.projpar = projpar;
  Min.Const = Const;
  Min.nconst = nconst;
  Min.q = q;
  Min.P = P;
  Min.Q = malloc(sizeof(SlaterDet));
  P->ParainitSlaterDet(q, Min.Q);
#ifndef MPI
  // regular program execution or catched signal ?
  if (!setjmp(env))
#endif
    FORTRAN(donlp2)();
  fprintf(stderr, "donlp2 terminated because of criterium %d\n",
          (int) FORTRAN(o8itin).optite + 11);
  copyxtopara(FORTRAN(o8xdat).x, Min.q);
}