FMD: fmd/OneNucleonOvlaps.c File Reference
fmd/OneNucleonOvlaps.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <complex.h>
#include <math.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "CenterofMass.h"
#include "OneNucleonOvlaps.h"
#include "numerics/cmath.h"
#include "numerics/cmat.h"
#include "numerics/gaussquad.h"
#include "numerics/sphericalharmonics.h"
#include "numerics/clebsch.h"
#include "numerics/lapack.h"
#include "misc/utils.h"
#include "misc/physics.h"
Defines
#define SQR(x) ((x)*(x))
Functions
void initOpOneNucleonOvlaps (OneNucleonOvlapsPara *par)
void calcOneNucleonOvlapsod (OneNucleonOvlapsPara *par, const SlaterDet *QA, const SlaterDet *QB, const SlaterDetAux *dummyX, complex double *specamplitude)
void writeOneNucleonOvlaps (FILE *fp, const Projection *P, const OneNucleonOvlapsPara *p, int jfin, int pfin, int afin, int jini, int pini, int aini, void *specamplitudeme, const Eigenstates *Efin, const Eigenstates *Eini)
Variables
char * speclabel [NSPEC] = { "S12", "P12", "P32", "D32", "D52" }
int specj [NSPEC] = { 1, 1, 3, 3, 5 }
int specl [NSPEC] = { 0, 2, 2, 4, 4 }
int io [NSPEC] = { 0, 2, 4, 8, 12 }
int dimo [NSPEC] = { 2, 2, 4, 4, 6 }
ManyBodyOperator OpOneNucleonOvlap [NSPEC]
ManyBodyOperators OpOneNucleonOvlaps
Detailed Description
calculate spectroscopic amplitudes in momentum space
(c) 2004-2012 Thomas Neff
Definition in file OneNucleonOvlaps.c.
Define Documentation
#define SQR (x) ((x)*(x))
Definition at line 35 of file OneNucleonOvlaps.c.
Function Documentation
void calcOneNucleonOvlapsod (OneNucleonOvlapsPara * par, const SlaterDet * QA, const SlaterDet * QB, const SlaterDetAux * dummyX, complex double * specamplitude)
Definition at line 215 of file OneNucleonOvlaps.c.
References SlaterDet::A, boostSlaterDet(), clebsch(), copySlaterDet(), dimo, GaussLegendrePoints(), initSlaterDet(), io, j, m, mneutron, mproton, SlaterDet::N, n, OneNucleonOvlapsPara::nalpha, OneNucleonOvlapsPara::ncosb, OneNucleonOvlapsPara::npoints, OneNucleonOvlapsPara::qmax, OneNucleonOvlapsPara::recoil, ShiftedPeriodicTrapezoidalPoints(), specj, specl, SQR, Y(), and SlaterDet::Z.
Referenced by OneNucleonOvlapsSlave().
{
  double qmax = par->qmax;
  int ialpha, nalpha = par->nalpha;
  int icosb, ncosb = par->ncosb;
  int npoints = par->npoints;
  int m, ml, ms, o, i;
  int j, l;
  double alpha, beta, weight;
  double q, k[3];
  complex double sa[2];
  int gaussoverlapsdone = 0;
  // initialize workspace if necessary
  if (!QAp) {
    QAp = malloc(sizeof(SlaterDet));
    initSlaterDet(QA, QAp);
    n = malloc(SQR(QB->A)*sizeof(complex double));
    nlu = malloc(SQR(QB->A)*sizeof(complex double));
  }
  copySlaterDet(QA, QAp);
  // add single nucleon with momentum q
  // proton or neutron ?
  int iso = (QA->Z == QB->Z) ? -1 : +1;
  double massA = QA->Z*mproton+QA->N*mneutron;
  for (o=0; o<NSPEC; o++)
    for (i=0; i<dimo[o]*npoints; i++)
      specamplitude[i+io[o]*npoints] = 0.0;
  double alphal[nalpha], walphal[nalpha];
  double cosbl[ncosb], wcosbl[ncosb];
  ShiftedPeriodicTrapezoidalPoints(nalpha, 0, 2*M_PI, 0.0, alphal, walphal);
  GaussLegendrePoints(ncosb, -1, 1, cosbl, wcosbl);
  for (i=0; i<npoints; i++) {
    q = qmax* i/(npoints-1);
    for (ialpha=0; ialpha<nalpha; ialpha++)
      for (icosb=0; icosb<ncosb; icosb++) {
        alpha = alphal[ialpha];
        beta = acos(cosbl[icosb]);
        weight = walphal[ialpha]*wcosbl[icosb];
        k[0] = q*cos(alpha)*sin(beta);
        k[1] = q*sin(alpha)*sin(beta);
        k[2] = q*cos(beta);
        if (par->recoil) {
          // boost QA by -k
          double VcmA[3] = {-k[0]/massA, -k[1]/massA, -k[2]/massA};
          copySlaterDet(QA, QAp);
          boostSlaterDet(QAp, VcmA);
          gaussoverlapsdone = 0;
        }
        if (!gaussoverlapsdone) {
          calcOvlapsAB(QAp, QB, n);
          gaussoverlapsdone = 1;
        }
        calcSpecOvlaps(QAp, iso, k, QB, n, nlu, sa);
        for (ms=-1; ms<=1; ms=ms+2) {
          for (o=0; o<NSPEC; o++) {
            j = specj[o]; l = specl[o];
            for (m=-j; m<=j; m=m+2) {
              ml = m-ms;
              if (-l<=ml && ml<=l) {
                specamplitude[(-m+j)/2 + i*dimo[o] + io[o]*npoints] += weight*
                  ((j-m)%4 ? -1 : +1)*
                  clebsch(l, 1, j, ml, ms, m)* sa[(ms+1)/2]*
                  conj(Y(l,ml,beta,alpha));
              }
            }
          }
        }
    }
  }
}
void initOpOneNucleonOvlaps (OneNucleonOvlapsPara * par)
Definition at line 60 of file OneNucleonOvlaps.c.
References ManyBodyOperator::dim, ManyBodyOperators::dim, ManyBodyOperator::me, OneNucleonOvlapsPara::nalpha, ManyBodyOperator::name, ManyBodyOperators::name, OneNucleonOvlapsPara::ncosb, OneNucleonOvlapsPara::npoints, ManyBodyOperator::par, ManyBodyOperators::par, ManyBodyOperator::pi, OneNucleonOvlapsPara::qmax, ManyBodyOperator::rank, OneNucleonOvlapsPara::recoil, ManyBodyOperator::size, ManyBodyOperators::size, specj, specl, and speclabel.
Referenced by main().
{
  char* name = malloc(60);
  sprintf(name, "OneNucleonOvlaps-%05.2f-%d-%d-%d%s",
          par->qmax, par->npoints, par->nalpha, par->ncosb, par->recoil ? "-recoil" : "");
  OpOneNucleonOvlaps.name = name;
  OpOneNucleonOvlaps.dim = par->npoints;
  OpOneNucleonOvlaps.size = par->npoints;
  OpOneNucleonOvlaps.par = par;
  int i;
  for (i=0; i<NSPEC; i++) {
    char* name = malloc(60);
    sprintf(name, "OneNucleonOvlap%s-%05.2f-%d-%d-%d%s",
            speclabel[i],
            par->qmax, par->npoints, par->nalpha, par->ncosb, par->recoil ? "-recoil" : "");
    OpOneNucleonOvlap[i].name = name;
    OpOneNucleonOvlap[i].rank = specj[i];
    OpOneNucleonOvlap[i].pi = specl[i] % 4 ? 1 : 0;
    OpOneNucleonOvlap[i].dim = par->npoints;
    OpOneNucleonOvlap[i].size = par->npoints;
    OpOneNucleonOvlap[i].par = par;
    OpOneNucleonOvlap[i].me = NULL;
  }
}
void writeOneNucleonOvlaps (FILE * fp, const Projection * P, const OneNucleonOvlapsPara * p, int jfin, int pfin, int afin, int jini, int pini, int aini, void * specamplitudeme, const Eigenstates * Efin, const Eigenstates * Eini)
Definition at line 307 of file OneNucleonOvlaps.c.
References Eigenstates::index, Projection::jmax, Eigenstates::norm, OneNucleonOvlapsPara::npoints, OneNucleonOvlapsPara::qmax, and SQR.
Referenced by main().
{
  int jmax = P->jmax;
  int ipjfin = idxpij(jmax,pfin,jfin);
  int ipjini = idxpij(jmax,pini,jini);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idxfin = Efin->index[ipjfin][afin];
  int idxini = Eini->index[ipjini][aini];
  double normfin = Efin->norm[ipjfin][idxfin];
  double normini = Eini->norm[ipjini][idxini];
  complex double (****specampme)[npoints] = specamplitudeme;
  complex double *sa = specampme[ipjfin][ipjini][idxfin][idxini];
  int i;
  double q;
  complex double ml;
  // calculate spectroscopic factor
  double dq = qmax/(npoints-1);
  double S = 0.0;
  for (i=0; i<npoints; i++) {
    q = i*dq;
    S += dq*SQR(q)* (jfin+1.0)/(jini+1.0)*SQR(cabs(sa[i]))/(normfin*normini);
  }
  fprintf(stderr, "Spectroscopic factor: %6.3f\n", S);
  // write spectroscopic amplitudes
  for (i=0; i<npoints; i++) {
    q = i*dq;
    // we include factor 1/sqrt(2*Jini+1) into definiton
    // of spectroscopic amplitude
    ml = sqrt((jfin+1.0)/(jini+1.0))* sa[i]/sqrt(normfin*normini);
    fprintf(fp, "%6.3f\t%13.5g\t%13.5g\n", q, creal(ml), cimag(ml));
  }
}
Variable Documentation
int dimo[NSPEC] = { 2, 2, 4, 4, 6 }
Definition at line 42 of file OneNucleonOvlaps.c.
Referenced by calcOneNucleonOvlapsod().
int io[NSPEC] = { 0, 2, 4, 8, 12 }
Definition at line 41 of file OneNucleonOvlaps.c.
Referenced by calcOneNucleonOvlapsod(), calcprojectedMBMEs(), and calcprojectedMBMEsmpi().
ManyBodyOperator OpOneNucleonOvlap[NSPEC]
Definition at line 49 of file OneNucleonOvlaps.c.
Referenced by main().
ManyBodyOperators OpOneNucleonOvlaps
Initial value:
 {
  n : NSPEC,
  Op : OpOneNucleonOvlap,
  me : calcOneNucleonOvlapsod
}
Definition at line 52 of file OneNucleonOvlaps.c.
Referenced by main().
int specj[NSPEC] = { 1, 1, 3, 3, 5 }
Definition at line 39 of file OneNucleonOvlaps.c.
Referenced by calcOneNucleonOvlapsod(), and initOpOneNucleonOvlaps().
int specl[NSPEC] = { 0, 2, 2, 4, 4 }
Definition at line 40 of file OneNucleonOvlaps.c.
Referenced by calcOneNucleonOvlapsod(), and initOpOneNucleonOvlaps().
char* speclabel[NSPEC] = { "S12", "P12", "P32", "D32", "D52" }
Definition at line 38 of file OneNucleonOvlaps.c.
Referenced by initOpOneNucleonOvlaps(), and main().