FMD: fmdmpi/OneNucleonOvlapsSlave.h File Reference
fmdmpi/OneNucleonOvlapsSlave.h File Reference
Functions
void OneNucleonOvlapsSlave (void)
Detailed Description
MPI slave for calculating One-Nucleon Ovlap MEs
(c) 2012 Thomas Neff
Definition in file OneNucleonOvlapsSlave.h.
Function Documentation
void OneNucleonOvlapsSlave (void)
Definition at line 33 of file OneNucleonOvlapsSlave.c.
References allocateSlaterDet(), BroadcastA(), BroadcastOneNucleonOvlapsPara(), BroadcastSlaterDet(), BroadcastTask(), calcOneNucleonOvlapsod(), copySlaterDet(), dim, DIMSPEC, invertSlaterDet(), moveSlaterDet(), OneNucleonOvlapsPara::npoints, projpar, Q, Qp, Qpp, rotateSlaterDet(), TAGMEOD, TAGPROJECT6, TASKPROJECTONENUCLEONOVLAPSOD, and TASKSTART.
Referenced by main().
{
  MPI_Status status;
  OneNucleonOvlapsPara ONOpar;
  int A;
  SlaterDet Q, Qp, Qpp;
  int task;
  BroadcastTask(&task);
  if (task != TASKSTART)
    return;
  BroadcastOneNucleonOvlapsPara(&ONOpar);
  int dim = DIMSPEC* ONOpar.npoints;
  BroadcastA(&A);
  complex double specamp[2][dim];
  allocateSlaterDet(&Q, A-1);
  allocateSlaterDet(&Qp, A);
  allocateSlaterDet(&Qpp, A);
  while (1) {
    BroadcastTask(&task);
    if (task != TASKPROJECTONENUCLEONOVLAPSOD)
      return;
    double projpar[6];
    double *angle, *R;
    BroadcastSlaterDet(&Q);
    BroadcastSlaterDet(&Qp);
    while (1) {
      MPI_Recv(projpar, 6, MPI_DOUBLE, 0, TAGPROJECT6, MPI_COMM_WORLD, &status);
      if (projpar[0] < 0.0)
        break;
      angle = &projpar[0];
      R = &projpar[3];
      copySlaterDet(&Qp, &Qpp);
      moveSlaterDet(&Qpp, R);
      rotateSlaterDet(&Qpp, angle[0], angle[1], angle[2]);
      calcOneNucleonOvlapsod(&ONOpar, &Q, &Qpp, NULL, specamp[0]);
      invertSlaterDet(&Qpp);
      calcOneNucleonOvlapsod(&ONOpar, &Q, &Qpp, NULL, specamp[1]);
      MPI_Send(specamp, 2*dim*sizeof(complex double), MPI_BYTE,
               0, TAGMEOD, MPI_COMM_WORLD);
    }
  }
}