FMD: fmd/Oscillator.h File Reference
fmd/Oscillator.h File Reference
#include "SlaterDet.h"
Functions
void calcOsci2 (const SlaterDet *Q, const SlaterDetAux *X, double omega, double *hosci)
void calcOsci4 (const SlaterDet *Q, const SlaterDetAux *X, double kappa, double *hosci)
Detailed Description
external quadratic and quartic oscillator
(c) 2003 Thomas Neff
Definition in file Oscillator.h.
Function Documentation
void calcOsci2 (const SlaterDet * Q, const SlaterDetAux * X, double omega, double * hosci)
Definition at line 40 of file Oscillator.c.
References calcSlaterDetOBME(), dim, mnucleon, and par.
Referenced by main().
{
  double kosci = mnucleon*omega*omega;
  OneBodyOperator op_ob_osci2 = {dim: 1, opt: 1, par: &kosci, me: ob_osci2};
  calcSlaterDetOBME(Q, X, &op_ob_osci2, hosci);
}
void calcOsci4 (const SlaterDet * Q, const SlaterDetAux * X, double kappa, double * hosci)
Definition at line 51 of file Oscillator.c.
References calcSlaterDetOBME(), dim, mnucleon, and par.
{
  double kosci = mnucleon*kappa;
  OneBodyOperator op_ob_osci4 = {dim: 1, opt: 1, par: &kosci, me: ob_osci4};
  calcSlaterDetOBME(Q, X, &op_ob_osci4, hosci);
}