FMD: fmd/ParameterizationCluster.h File Reference
fmd/ParameterizationCluster.h File Reference
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Parameterization.h"
Functions
int Clusterread (FILE *fp, Para *q)
int Clusterwrite (FILE *fp, const Para *q)
void Clusterclone (const Para *q, Para *qp)
void ClusterinitSlaterDet (const Para *q, SlaterDet *Q)
void ClustertoSlaterDet (const Para *q, SlaterDet *Q)
void ClusterprojectgradSlaterDet (const Para *q, const gradSlaterDet *dQ, double *dq)
Variables
Parameterization ParameterizationCluster
Detailed Description
Parametrization of SlaterDet.
FMD Clusters
(c) 2004 Thomas Neff
Definition in file ParameterizationCluster.h.
Function Documentation
void Clusterclone (const Para * q, Para * qp)
Definition at line 58 of file ParameterizationCluster.c.
References Para::A, cloneSlaterDet(), ClusterInternals::cluster, ClusterInternals::clusterfmd5hash, ClusterInternals::clusterfname, Para::internals, Para::n, Para::N, Para::name, ClusterInternals::ncluster, Para::ngauss, Para::x, and Para::Z.
{
  int i;
  strcpy(qp->name, q->name);
  qp->A = q->A; qp->Z = q->Z; qp->N = q->N;
  qp->n = q->n;
  qp->x = malloc(q->n*sizeof(double));
  for (i=0; i<q->n; i++)
    qp->x[i] = q->x[i];
  qp->ngauss = q->ngauss;
  qp->internals = malloc(sizeof(ClusterInternals));
  ClusterInternals *qpint = qp->internals;
  ClusterInternals *qint = q->internals;
  qpint->ncluster = qint->ncluster;
  qpint->clusterfname = malloc(qint->ncluster*255*sizeof(char));
  qpint->clusterfmd5hash = malloc(qint->ncluster*255*sizeof(char));
  for (i=0; i<qint->ncluster; i++) {
    strcpy(qpint->clusterfname[i], qint->clusterfname[i]);
    strcpy(qpint->clusterfmd5hash[i], qint->clusterfmd5hash[i]);
  }
  qpint->cluster = malloc(qint->ncluster*sizeof(SlaterDet));
  for (i=0; i<qint->ncluster; i++)
    cloneSlaterDet(&qint->cluster[i], &qpint->cluster[i]);
}
void ClusterinitSlaterDet (const Para * q, SlaterDet * Q)
Definition at line 185 of file ParameterizationCluster.c.
References SlaterDet::A, ClusterInternals::cluster, SlaterDet::G, SlaterDet::idx, Para::internals, k, SlaterDet::N, ClusterInternals::ncluster, SlaterDet::ng, SlaterDet::ngauss, Gaussian::xi, and SlaterDet::Z.
{
  int k, ki, in;
  ClusterInternals* qint = q->internals;
  Q->A = 0; Q->Z = 0; Q->N = 0; Q->ngauss = 0;
  for (k=0; k<qint->ncluster; k++) {
    Q->A += qint->cluster[k].A;
    Q->Z += qint->cluster[k].Z;
    Q->N += qint->cluster[k].N;
    Q->ngauss += qint->cluster[k].ngauss;
  }
  // collect ngs
  Q->ng = (int*) malloc(Q->A*sizeof(int));
  in=0;
  for (k=0; k<qint->ncluster; k++) {
    for (ki=0; ki<qint->cluster[k].A; ki++) {
      Q->ng[in] = qint->cluster[k].ng[ki];
      in++;
    }
  }
  // build idx from ng
  Q->idx = (int*) malloc(Q->A*sizeof(int));
  Q->idx[0] = 0;
  for (k=1; k<Q->A; k++)
    Q->idx[k] = Q->idx[k-1]+Q->ng[k-1];
  // set xi of Gaussians
  Q->G = (Gaussian*) malloc(Q->ngauss*sizeof(Gaussian));
  in=0;
  for (k=0; k<qint->ncluster; k++) {
    for (ki=0; ki<qint->cluster[k].ngauss; ki++) {
      Q->G[in].xi = qint->cluster[k].G[ki].xi;
      in++;
    }
  }
}
void ClusterprojectgradSlaterDet (const Para * q, const gradSlaterDet * dQ, double * dq)
Definition at line 253 of file ParameterizationCluster.c.
References Gaussian::b, gradGaussian::b, gradGaussian::chi, Gaussian::chi, ClusterInternals::cluster, cm2mult(), derivrotatemat2(), derivrotatemat3(), SlaterDet::G, gradSlaterDet::gradval, Para::internals, j, k, m3mult(), ClusterInternals::ncluster, SlaterDet::ngauss, and Para::x.
{
  ClusterInternals* qint = q->internals;
  int i,j,k,ki,gk;
  double* euler;
  complex double drotmat2[3][2][2];
  double drotmat3[3][3][3];
  complex double dchidang[2];
  complex double dbdang[3];
  // gradients with respect to clusters
  gk=0;
  for (k=0; k<qint->ncluster; k++) {
    for (i=0; i<NCLUSTER; i++)
      dq[i+k*NCLUSTER] = 0.0;
    // derivatives of the rotation matrices
    euler = &q->x[3+k*NCLUSTER];
    derivrotatemat2(euler, drotmat2);
    derivrotatemat3(euler, drotmat3);
    for (ki=0; ki<qint->cluster[k].ngauss; ki++) {
      // derivatives with respect to position
      for (i=0; i<3; i++)
        dq[i+k*NCLUSTER] += 2.0*creal(dQ->gradval[gk].b[i]);
      // derivatives with respect to angles
      for (i=0; i<3; i++) {
        for (j=0; j<2; j++)
        dchidang[j] = qint->cluster[k].G[ki].chi[j];
        cm2mult(drotmat2[i], dchidang);
        for (j=0; j<2; j++)
          dq[3+i+k*NCLUSTER] += 2.0*creal(dQ->gradval[gk].chi[j]*conj(dchidang[j]));
        for (j=0; j<3; j++)
          dbdang[j] = qint->cluster[k].G[ki].b[j];
        m3mult(drotmat3[i], dbdang);
        for (j=0; j<3; j++)
          dq[3+i+k*NCLUSTER] += 2.0*creal(dQ->gradval[gk].b[j]*conj(dbdang[j]));
      }
      gk++;
    }
  }
}
int Clusterread (FILE * fp, Para * q)
Definition at line 91 of file ParameterizationCluster.c.
References BUFSIZE, ClusterInternals::cluster, ClusterInternals::clusterfmd5hash, ClusterInternals::clusterfname, Para::internals, k, md5hash(), Para::n, Para::name, ClusterInternals::ncluster, readSlaterDetfromFile(), stripstr(), and Para::x.
{
  char buf[BUFSIZE];
  int i,k;
  ClusterInternals* qint;
  qint = q->internals = malloc(sizeof(ClusterInternals));
  do
    fgets(buf, BUFSIZE, fp);
  while (strncmp(buf, "<Para ", 5) && !feof(fp));
  if (feof(fp)) {
    fprintf(stderr, "did't find <Para ...>\n");
    return -1;
  }
  char Pname[80], qname[80];
  sscanf(buf, "<Para %s %s>", Pname, qname);
  if (strcmp(Pname, "Cluster")) {
    fprintf(stderr, "not a Cluster parameter set\n");
    return -1;
  }
  strcpy(q->name, stripstr(qname, ">"));
  // read clusters
  int ncluster;
  fgets(buf, BUFSIZE, fp);
  if(sscanf(buf, "<Clusters %d>", &ncluster) != 1) {
    fprintf(stderr, "malformed line\n>>%s<<\n", stripstr(buf, "\n"));
    return -1;
  }
  qint->ncluster = ncluster;
  qint->clusterfname = malloc(ncluster*255*sizeof(char));
  qint->clusterfmd5hash = malloc(ncluster*255*sizeof(char));
  qint->cluster = malloc(ncluster*sizeof(SlaterDet));
  double clusterx[ncluster][6];
  for (i=0; i<ncluster; i++) {
    fgets(buf, BUFSIZE, fp);
    if (sscanf(buf, "<Cluster (%lf, %lf, %lf) (%lf, %lf, %lf) %s %s>",
               &clusterx[i][0], &clusterx[i][1], &clusterx[i][2],
               &clusterx[i][3], &clusterx[i][4], &clusterx[i][5],
               qint->clusterfname[i], qint->clusterfmd5hash[i]) != 8) {
      fprintf(stderr, "malformed line\n>>%s<<\n", stripstr(buf, "\n"));
      return -1;
    }
    if (strncmp(qint->clusterfmd5hash[i], md5hash(qint->clusterfname[i]), 32)) {
      fprintf(stderr, "...  SlaterDetFile does not match with existing hash\n");
      return -1;
    }
    readSlaterDetfromFile(&qint->cluster[i], qint->clusterfname[i]);
  }
  q->n = ncluster*NCLUSTER;
  q->x = (double*) malloc(q->n*sizeof(double));
  for (k=0; k<ncluster; k++)
    for (i=0; i<NCLUSTER; i++)
      q->x[i+k*NCLUSTER] = clusterx[k][i];
  fgets(buf, BUFSIZE, fp);
  if (strncmp(buf, "</Para>", 7)) {
    fprintf(stderr, "didn't find </Para>\n");
    return -1;
  }
  return 0;
}
void ClustertoSlaterDet (const Para * q, SlaterDet * Q)
Definition at line 226 of file ParameterizationCluster.c.
References ClusterInternals::cluster, SlaterDet::G, Para::internals, k, moveGaussian(), ClusterInternals::ncluster, SlaterDet::ngauss, rotateGaussian(), rotatemat2(), rotatemat3(), and Para::x.
{
  ClusterInternals* qint = q->internals;
  int i,k;
  double* euler;
  double* pos;
  complex double R2[2][2];
  double R3[3][3];
  // the clusters
  int gi = 0;
  for (k=0; k<qint->ncluster; k++) {
    pos = &q->x[0+k*NCLUSTER];
    euler = &q->x[3+k*NCLUSTER];
    rotatemat2(euler, R2);
    rotatemat3(euler, R3);
    for (i=0; i<qint->cluster[k].ngauss; i++) {
      Q->G[gi] = qint->cluster[k].G[i];
      rotateGaussian(&Q->G[gi], R3, R2);
      moveGaussian(&Q->G[gi], pos);
      gi++;
    }
  }
}
int Clusterwrite (FILE * fp, const Para * q)
Definition at line 163 of file ParameterizationCluster.c.
References ClusterInternals::clusterfmd5hash, ClusterInternals::clusterfname, Para::internals, k, Para::name, NCLUSTER, ClusterInternals::ncluster, and Para::x.
{
  int k, ki, i;
  ClusterInternals* qint = q->internals;
  fprintf(fp, "<Para Cluster %s>\n", q->name);
  fprintf(fp, "<Clusters %d>\n", qint->ncluster);
  for (k=0; k<qint->ncluster; k++) {
    fprintf(fp, "<Cluster (%12.8f, %12.8f, %12.8f) (%12.8f, %12.8f, %12.8f) %s %s\n",
            q->x[0+k*NCLUSTER], q->x[1+k*NCLUSTER], q->x[2+k*NCLUSTER],
            q->x[3+k*NCLUSTER], q->x[4+k*NCLUSTER], q->x[5+k*NCLUSTER],
            qint->clusterfname[k], qint->clusterfmd5hash[k]);
  }
  fprintf(fp, "</Para>\n");
  return 0;
}
Variable Documentation
Parameterization ParameterizationCluster
Definition at line 43 of file ParameterizationCluster.c.
Referenced by readParafromFile().