FMD: fmd/Parameterization.c File Reference
fmd/Parameterization.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SlaterDet.h"
#include "gradSlaterDet.h"
#include "Parameterization.h"
#include "ParameterizationFMD.h"
#include "ParameterizationFMDr.h"
#include "ParameterizationFMDS.h"
#include "ParameterizationFMDreal.h"
#include "ParameterizationAMD.h"
#include "ParameterizationAMDd.h"
#include "ParameterizationAMDS.h"
#include "ParameterizationAMDA.h"
#include "ParameterizationAMDAS.h"
#include "ParameterizationAlpha.h"
#include "ParameterizationAlphaA.h"
#include "ParameterizationAlphaC.h"
#include "ParameterizationCluster.h"
#include "ParameterizationCoreFMD.h"
#include "ParameterizationClusterFMD.h"
#include "ParameterizationClustersFMD.h"
#include "ParameterizationFMDd3h.h"
#include "ParameterizationFMDvxz.h"
#include "misc/utils.h"
Defines
#define BUFSIZE 255
Functions
void shakePara (Para *q, double magnitude)
int readParafromFile (Parameterization *P, Para *q, const char *fname)
Detailed Description
Parametrizations of Slater determinants
(c) 2003 Thomas Neff
Definition in file Parameterization.c.
Define Documentation
#define BUFSIZE 255
Definition at line 60 of file Parameterization.c.
Referenced by readParafromFile().
Function Documentation
int readParafromFile (Parameterization * P, Para * q, const char * fname)
Definition at line 62 of file Parameterization.c.
References BUFSIZE, ParameterizationAlpha, ParameterizationAlphaA, ParameterizationAlphaC, ParameterizationAMD, ParameterizationAMDA, ParameterizationAMDAS, ParameterizationAMDd, ParameterizationAMDS, ParameterizationCluster, ParameterizationClusterFMD, ParameterizationClustersFMD, ParameterizationCoreFMD, ParameterizationFMD, ParameterizationFMDd3h, ParameterizationFMDr, ParameterizationFMDreal, ParameterizationFMDS, ParameterizationFMDvxz, Parameterization::Pararead, and stripstr().
Referenced by main().
{
  FILE* fp;
  if (!(fp = fopen(fname, "r"))) {
    fprintf(stderr, "couldn't open %s for reading\n", fname);
    return -1;
  }
  fprintf(stderr, "... reading Parameters from file %s\n", fname);
  char buf[BUFSIZE];
  do
    fgets(buf, BUFSIZE, fp);
  while (strncmp(buf, "<Parameterization", 16) && !feof(fp));
  if (feof(fp)) {
    fprintf(stderr, "did't find <Parameterization ...>\n");
    return -1;
  }
  char Pname[80];
  sscanf(buf, "<Parameterization %s>", Pname);
  stripstr(Pname, ">");
  if (!strcmp(Pname, "FMD"))
    *P = ParameterizationFMD;
  else if (!strcmp(Pname, "FMDr"))
    *P = ParameterizationFMDr;
  else if (!strcmp(Pname, "FMDS"))
    *P = ParameterizationFMDS;
  else if (!strcmp(Pname, "FMDreal"))
    *P = ParameterizationFMDreal;
  else if (!strcmp(Pname, "AMD"))
    *P = ParameterizationAMD;
  else if (!strcmp(Pname, "AMDd"))
    *P = ParameterizationAMDd;
  else if (!strcmp(Pname, "AMDS"))
    *P = ParameterizationAMDS;
  else if (!strcmp(Pname, "AMDA"))
    *P = ParameterizationAMDA;
  else if (!strcmp(Pname, "AMDAS"))
    *P = ParameterizationAMDAS;
  else if (!strcmp(Pname, "Alpha"))
    *P = ParameterizationAlpha;
  else if (!strcmp(Pname, "AlphaA"))
    *P = ParameterizationAlphaA;
  else if (!strcmp(Pname, "AlphaC"))
    *P = ParameterizationAlphaC;
  else if (!strcmp(Pname, "Cluster"))
    *P = ParameterizationCluster;
  else if (!strcmp(Pname, "CoreFMD"))
    *P = ParameterizationCoreFMD;
  else if (!strcmp(Pname, "ClusterFMD"))
    *P = ParameterizationClusterFMD;
  else if (!strcmp(Pname, "ClustersFMD"))
    *P = ParameterizationClustersFMD;
  else if (!strcmp(Pname, "FMDd3h"))
    *P = ParameterizationFMDd3h;
  else if (!strcmp(Pname, "FMDvxz"))
    *P = ParameterizationFMDvxz;
  else {
    fprintf(stderr, "Parameterization %s not implemented\n", Pname);
    return -1;
  }
  return P->Pararead(fp, q);
}
void shakePara (Para * q, double magnitude)
Definition at line 51 of file Parameterization.c.
References Para::n, and Para::x.
Referenced by main().
{
  int i;
  for (i=0; i<q->n; i++)
    q->x[i] = q->x[i]*(1+ranmag(magnitude)) + ranmag(magnitude);
}