FMD: fmd/Parity.c File Reference
fmd/Parity.c File Reference
#include <complex.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "Parity.h"
Functions
void ob_parity (void *par, const Gaussian *G1, const Gaussian *G2, const GaussianAux *X, complex double *pi)
void calcParity (const SlaterDet *Q, const SlaterDetAux *X, double *pi)
void calcParityod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *pi)
void calcparHF (const SlaterDet *Q, const SlaterDetAux *X, void *mes)
Detailed Description
calculate parity
(c) 2003 Thomas Neff
Definition in file Parity.c.
Function Documentation
void calcparHF (const SlaterDet * Q, const SlaterDetAux * X, void * mes)
Definition at line 79 of file Parity.c.
References calcSlaterDetOBHFMEs(), dim, ob_parity(), and par.
Referenced by main().
{
  OneBodyOperator op_ob_par = {dim: 1, opt: 1, par: NULL, me: ob_parity};
  calcSlaterDetOBHFMEs(Q, X, &op_ob_par, mes);
}
void calcParity (const SlaterDet * Q, const SlaterDetAux * X, double * pi)
Definition at line 39 of file Parity.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), initSlaterDet(), initSlaterDetAux(), invertSlaterDet(), and SlaterDetAux::ovlap.
Referenced by calcObservables().
{
  // do we have to initialize the workspace first ?
  if (Qpp.A == 0) {
    initSlaterDet(Q, &Qpp);
    initSlaterDetAux(&Qpp, &Xpp);
  }
  copySlaterDet(Q, &Qpp);
  calcSlaterDetAuxod(Q, &Qpp, &Xpp);
  double norm = Xpp.ovlap;
  invertSlaterDet(&Qpp);
  calcSlaterDetAuxod(Q, &Qpp, &Xpp);
  *pi = Xpp.ovlap/norm;
}
void calcParityod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * pi)
Definition at line 60 of file Parity.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), initSlaterDet(), initSlaterDetAux(), invertSlaterDet(), and SlaterDetAux::ovlap.
Referenced by calcObservablesod().
{
  // do we have to initialize the workspace first ?
  if (Qpp.A == 0) {
    initSlaterDet(Qp, &Qpp);
    initSlaterDetAux(&Qpp, &Xpp);
  }
  copySlaterDet(Qp, &Qpp);
  invertSlaterDet(&Qpp);
  calcSlaterDetAuxod(Q, &Qpp, &Xpp);
  *pi = Xpp.ovlap;
}
void ob_parity (void * par, const Gaussian * G1, const Gaussian * G2, const GaussianAux * X, complex double * pi)
Definition at line 25 of file Parity.c.
References calcGaussianAux(), invertGaussian(), GaussianAux::Q, and Xp.
Referenced by calcparHF().
{
  Gaussian G2p = *G2;
  GaussianAux Xp;
  invertGaussian(&G2p);
  calcGaussianAux(G1, &G2p, &Xp);
  *pi += Xp.Q;
}