FMD: fmd/Potential.h File Reference
fmd/Potential.h File Reference
#include <complex.h>
#include "SlaterDet.h"
#include "Interaction.h"
Functions
void calcPotential (const Interaction *Int, const SlaterDet *Q, const SlaterDetAux *X, double v[])
void calcPotentialrowcol (const Interaction *Int, const SlaterDet *Q, const SlaterDetAux *X, double v[], int k, int l)
void calcPotentialod (const Interaction *Int, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double v[])
void calcPotentialodrowcol (const Interaction *Int, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double v[], int k, int l)
void calcPotentialsHF (const Interaction *Int, const SlaterDet *Q, const SlaterDetAux *X, void *mes)
void calcPotentialHF (const Interaction *Int, const SlaterDet *Q, const SlaterDetAux *X, complex double *mes)
Detailed Description
calculate matrix element of Interaction
(c) 2003 Thomas Neff
Definition in file Potential.h.
Function Documentation
void calcPotential (const Interaction * Int, const SlaterDet * Q, const SlaterDetAux * X, double v[])
Definition at line 394 of file Potential.c.
References calcSlaterDetTBME(), dim, Interaction::n, and par.
Referenced by calcHamiltonian(), and calcObservables().
{
  int i;
  TwoBodyOperator op_tb_pot = {dim: P->n, opt: 0, par: P, me: tb_pot};
  calcSlaterDetTBME(Q, X, &op_tb_pot, v);
  v[0] = 0.0;
  for (i=1; i<P->n; i++)
    v[0] += v[i];
}
void calcPotentialHF (const Interaction * Int, const SlaterDet * Q, const SlaterDetAux * X, complex double * mes)
Definition at line 475 of file Potential.c.
References SlaterDet::A, calcPotentialsHF(), k, m, and Interaction::n.
Referenced by calcHamiltonianHF(), and main().
{
  int A=Q->A;
  complex double v[A*A][Int->n];
  calcPotentialsHF(Int, Q, X, v);
  int k,m;
  for (m=0; m<A; m++)
    for (k=0; k<A; k++)
      vhf[k+m*A] = v[k+m*A][0];
}
void calcPotentialod (const Interaction * Int, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double v[])
Definition at line 423 of file Potential.c.
References calcSlaterDetTBMEod(), dim, Interaction::n, and par.
Referenced by calcHamiltonianod(), and calcObservablesod().
{
  int i;
  TwoBodyOperator op_tb_pot = {dim: P->n, opt: 0, par: P, me: tb_pot};
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_pot, v);
  v[0] = 0.0;
  for (i=1; i<P->n; i++)
    v[0] += v[i];
}
void calcPotentialodrowcol (const Interaction * Int, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double v[], int k, int l)
Definition at line 439 of file Potential.c.
References calcSlaterDetTBMEodrowcol(), dim, Interaction::n, and par.
Referenced by MinimizerSlaveod().
{
  int i;
  TwoBodyOperator op_tb_pot = {dim: P->n, opt: 0, par: P, me: tb_pot};
  calcSlaterDetTBMEodrowcol(Q, Qp, X, &op_tb_pot, v, k, l);
  v[0] = 0.0;
  for (i=1; i<P->n; i++)
    v[0] += v[i];
}
void calcPotentialrowcol (const Interaction * Int, const SlaterDet * Q, const SlaterDetAux * X, double v[], int k, int l)
Definition at line 408 of file Potential.c.
References calcSlaterDetTBMErowcol(), dim, Interaction::n, and par.
Referenced by MinimizerSlave().
{
  int i;
  TwoBodyOperator op_tb_pot = {dim: P->n, opt: 0, par: P, me: tb_pot};
  calcSlaterDetTBMErowcol(Q, X, &op_tb_pot, v, k, l);
  v[0] = 0.0;
  for (i=1; i<P->n; i++)
    v[0] += v[i];
}
void calcPotentialsHF (const Interaction * Int, const SlaterDet * Q, const SlaterDetAux * X, void * mes)
Definition at line 455 of file Potential.c.
References SlaterDet::A, calcSlaterDetTBHFMEs(), dim, k, m, Interaction::n, and par.
Referenced by calcPotentialHF().
{
  TwoBodyOperator op_tb_pot = {dim: Int->n, opt: 0, par: Int, me: tb_pot};
  calcSlaterDetTBHFMEs(Q, X, &op_tb_pot, mes);
  int A=Q->A;
  complex double (*v)[Int->n] = mes;
  int k,m,i;
  for (m=0; m<A; m++)
    for (k=0; k<A; k++) {
      v[k+m*A][0] = 0.0;
      for (i=1; i<Int->n; i++)
       v[k+m*A][0] += v[k+m*A][i];
    }
}