FMD: fmd/ProjectedObservables.h File Reference
fmd/ProjectedObservables.h File Reference
#include "SlaterDet.h"
#include "Observables.h"
#include "Projection.h"
#include "Symmetry.h"
Functions
void initOpObservables (const Interaction *Int)
void scaleprojectedObservablesMBME (const Projection *P, const Interaction *Int, Observablesod **obsme)
void showprojectedObservables (FILE *fp, const Projection *P, const Interaction *Int, const SlaterDet *Q, const Observablesod *obs, const Eigenstates *E, const Amplitudes *A, const char *pre)
void showSpectrum (FILE *fp, const Projection *P, const Observablesod **obs, const Eigenstates *E)
Variables
ManyBodyOperator OpObservables
Detailed Description
read or calculate/write projected Observables matrix elements
(c) 2003 Thomas Neff
Definition in file ProjectedObservables.h.
Function Documentation
void initOpObservables (const Interaction * Int)
Definition at line 42 of file ProjectedObservables.c.
References ManyBodyOperator::dim, MAXINTERACTIONS, Interaction::n, ManyBodyOperator::name, Interaction::name, ManyBodyOperator::par, and ManyBodyOperator::size.
Referenced by main().
{
  char* obsintname = malloc(13+strlen(Int->name));
  sprintf(obsintname, "Observables-%s", Int->name);
  OpObservables.name = obsintname;
  OpObservables.dim = sizeof(Observablesod)/sizeof(double complex) - (MAXINTERACTIONS+1) + Int->n ;
  OpObservables.size = sizeof(Observablesod)/sizeof(double complex);
  OpObservables.par = Int;
}
void scaleprojectedObservablesMBME (const Projection * P, const Interaction * Int, Observablesod ** obsme)
Definition at line 53 of file ProjectedObservables.c.
References j, Projection::jmax, k, m, Projection::odd, and scaleObservablesod().
Referenced by main(), and readorcalcandwriteprojectedMBMEfromtoFile().
{
  int odd=P->odd;
  int jmax=P->jmax;
  int p,j,m,k;
  for (p=0; p<=1; p++)
    for (j=odd; j<jmax; j=j+2)
      for (m=-j; m<=j; m=m+2)
        for (k=-j; k<=j; k=k+2)
          scaleObservablesod(Int, &obsme[idxpij(jmax,p,j)][idxjmk(j,m,k)]);
}
void showprojectedObservables (FILE * fp, const Projection * P, const Interaction * Int, const SlaterDet * Q, const Observablesod * obs, const Eigenstates * E, const Amplitudes * A, const char * pre)
void showSpectrum (FILE * fp, const Projection * P, const Observablesod ** obs, const Eigenstates * E)
Definition at line 186 of file ProjectedObservables.c.
References Level::en, hbc, Level::i, Eigenstates::index, j, Level::j2, Projection::jmax, Level::l2, n, Eigenstates::ngood, Projection::odd, Level::s2, Level::t2, and Level::tcm.
Referenced by main().
{
  int odd=P->odd;
  int jmax=P->jmax;
  int p,j,ipj,i;
  char spin[6];
  Observablesod* o;
  int* idx;
  // how many levels ?
  int nlevels = 0;
  for (p=0; p<=1; p++)
    for (j=odd; j<jmax; j=j+2)
      nlevels += E->ngood[idxpij(jmax,p,j)];
  Level level[nlevels];
  // collect level data
  int ilevel = -1;
  for (p=0; p<=1; p++)
    for (j=odd; j<jmax; j=j+2) {
      ipj = idxpij(jmax,p,j);
      if(odd) sprintf(spin, "%d/2%c", j, p ? '-' : '+');
      else    sprintf(spin, "%d%c", j/2, p ? '-' : '+');
      o = obs[ipj];
      idx = E->index[ipj];
      for (i=0; i<E->ngood[ipj]; i++) {
        ilevel++;
        level[ilevel].en = hbc*creal(o[idx[i]].h/o[idx[i]].n);
        strncpy(level[ilevel].spin, spin, 6);
        level[ilevel].i = i;
        level[ilevel].j2 = creal(o[idx[i]].j2/o[idx[i]].n);
        level[ilevel].l2 = creal(o[idx[i]].l2/o[idx[i]].n);
        level[ilevel].s2 = creal(o[idx[i]].s2/o[idx[i]].n);
        level[ilevel].t2 = creal(o[idx[i]].t2/o[idx[i]].n);
        level[ilevel].tcm = hbc*creal(o[idx[i]].tcm/o[idx[i]].n);
      }
    }
  // sort levels according to energy
  qsort(level, nlevels, sizeof(Level), cmplevels);
  double e0 = level[0].en;
  // write level data
  fprintf(fp, "\n# E0 = %8.3f MeV\n", e0);
  fprintf(fp, "# Energy\t  Spin   #\t L2\t S2\t T2\t\t J2\t Tcm\n\n");
  for (i=0; i<nlevels; i++) {
    fprintf(fp, "%8.3f\t%6s  %2d\t%6.3f\t%6.3f\t%6.3f\t\t%6.3f\t%7.3f\n",
            level[i].en - e0, level[i].spin, level[i].i, level[i].l2, level[i].s2, level[i].t2,
            level[i].j2, level[i].tcm);
  }
}
Variable Documentation
ManyBodyOperator OpObservables
Definition at line 31 of file ProjectedObservables.c.
Referenced by main().