FMD: fmd/Quadrupole.c File Reference
fmd/Quadrupole.c File Reference
#include <math.h>
#include <complex.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "Quadrupole.h"
#include "Radii.h"
#include "numerics/cmath.h"
Defines
#define SQR(x) (x)*(x)
Functions
void calcQuadrupole (const SlaterDet *Q, const SlaterDetAux *X, double beta[3], double gamma[3])
void calcQuadrupolePrime (const SlaterDet *Q, const SlaterDetAux *X, double beta[3])
Detailed Description
calculate quadrupole parameters beta and gamma
(c) 2003 Thomas Neff
calculate quadrupole parameters beta and gamma for nucleons, protons and neutrons
(c) 2003, 2005 Thomas Neff
Definition in file Quadrupole.c.
Define Documentation
#define SQR (x) (x)*(x)
Definition at line 73 of file Quadrupole.c.
Function Documentation
void calcQuadrupole (const SlaterDet * Q, const SlaterDetAux * X, double beta[3], double gamma[3])
Definition at line 83 of file Quadrupole.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), dim, par, and SQR.
Referenced by main().
{
  double qone[9][3], qtwo[9][3], q[9], qsq, detq;
  int i,j;
  OneBodyOperator op_ob_quadrupole = {dim: 27, opt: 1, par: Q, me: ob_quadrupole};
  TwoBodyOperator op_tb_quadrupole = {dim: 27, opt: 1, par: Q, me: tb_quadrupole};
  calcSlaterDetOBME(Q, X, &op_ob_quadrupole, qone);
  calcSlaterDetTBME(Q, X, &op_tb_quadrupole, qtwo);
  for (j=0; j<3; j++) {
    qsq = 0.0;
    for (i=0; i<9; i++) {
      q[i] = qone[i][j] + qtwo[i][j];
      // q[i] = qone[i][j];
      qsq += SQR(q[i]);
    }
    detq = det(q);
    beta[j] = sqrt(5/(24*M_PI)*qsq);
    gamma[j] = 60/M_PI*acos(5*sqrt(5)/(16*pow(M_PI,1.5))*detq/pow(beta[j],3));
  }
}
void calcQuadrupolePrime (const SlaterDet * Q, const SlaterDetAux * X, double beta[3])
Definition at line 110 of file Quadrupole.c.
References SlaterDet::A, calcRadii2(), calcSlaterDetOBME(), calcSlaterDetTBME(), dim, SlaterDet::N, par, SQR, and SlaterDet::Z.
Referenced by main().
{
  double qone[9][3], qtwo[9][3], q[9], qsq, detq;
  double r2[3];
  int i,j;
  calcRadii2(Q, X, &r2[0], &r2[1], &r2[2]);
  OneBodyOperator op_ob_quadrupole = {dim: 27, opt: 1, par: Q, me: ob_quadrupole};
  TwoBodyOperator op_tb_quadrupole = {dim: 27, opt: 1, par: Q, me: tb_quadrupole};
  calcSlaterDetOBME(Q, X, &op_ob_quadrupole, qone);
  calcSlaterDetTBME(Q, X, &op_tb_quadrupole, qtwo);
  for (j=0; j<3; j++) {
    qsq = 0.0;
    for (i=0; i<9; i++) {
      q[i] = qone[i][j] + qtwo[i][j];
      // q[i] = qone[i][j];
      qsq += SQR(q[i]);
    }
    detq = det(q);
    beta[j] = sqrt(2*M_PI/15*qsq)/r2[j];
  }
  beta[0] /= Q->A;
  beta[1] /= Q->Z;
  beta[2] /= Q->N;
}