FMD: fmd/Radii.h File Reference
fmd/Radii.h File Reference
#include "SlaterDet.h"
Functions
void calcRadii2 (const SlaterDet *Q, const SlaterDetAux *X, double *r2mass, double *r2proton, double *r2neutron)
void calcRadii2od (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *r2mass, complex double *r2proton, complex double *r2neutron)
Detailed Description
calculate radii
(c) 2003 Thomas Neff
Definition in file Radii.h.
Function Documentation
void calcRadii2 (const SlaterDet * Q, const SlaterDetAux * X, double * r2mass, double * r2proton, double * r2neutron)
Definition at line 55 of file Radii.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), dim, and par.
Referenced by calcObservables(), and calcQuadrupolePrime().
{
  double r2one[3], r2two[3];
  OneBodyOperator op_ob_radii2 = {dim: 3, opt: 1, par: Q, me: ob_radii2};
  TwoBodyOperator op_tb_radii2 = {dim: 3, opt: 1, par: Q, me: tb_radii2};
  calcSlaterDetOBME(Q, X, &op_ob_radii2, r2one);
  calcSlaterDetTBME(Q, X, &op_tb_radii2, r2two);
  *r2mass = r2one[0] + r2two[0];
  *r2proton = r2one[1] + r2two[1];
  *r2neutron = r2one[2] + r2two[2];
}
void calcRadii2od (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * r2mass, complex double * r2proton, complex double * r2neutron)
Definition at line 72 of file Radii.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), dim, and par.
Referenced by calcObservablesod().
{
  complex double r2one[3], r2two[3];
  OneBodyOperator op_ob_radii2 = {dim: 3, opt: 1, par: Q, me: ob_radii2};
  TwoBodyOperator op_tb_radii2 = {dim: 3, opt: 1, par: Q, me: tb_radii2};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_radii2, r2one);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_radii2, r2two);
  *r2mass = r2one[0] + r2two[0];
  *r2proton = r2one[1] + r2two[1];
  *r2neutron = r2one[2] + r2two[2];
}