FMD: fmd/RadiiLS.c File Reference
fmd/RadiiLS.c File Reference
#include <math.h>
#include <complex.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "Projection.h"
#include "RadiiLS.h"
#include "misc/physics.h"
#include "numerics/cmath.h"
Functions
void calcRadii2LS (const SlaterDet *Q, const SlaterDetAux *X, RadiiLS *R2ls)
void calcRadii2LSod (void *par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, RadiiLSod *R2ls)
void writeprojectedRadiiLS (FILE *fp, const SlaterDet *Q, const Projection *P, const RadiiLSod **radiils, const Eigenstates *E)
Variables
ManyBodyOperator OpRadiiLS
Detailed Description
calculate spin-orbit contribution to nuclear charge radius
(c) 2011 Thomas Neff
Definition in file RadiiLS.c.
Function Documentation
void calcRadii2LS (const SlaterDet * Q, const SlaterDetAux * X, RadiiLS * R2ls)
Definition at line 47 of file RadiiLS.c.
References calcSlaterDetOBME(), dim, RadiiLS::r2lsn, and RadiiLS::r2lsp.
{
  double r2ls[2];
  OneBodyOperator op_ob_radii2ls = {dim: 2, opt: 0, par: NULL, me: ob_radii2ls};
  calcSlaterDetOBME(Q, X, &op_ob_radii2ls, r2ls);
  R2ls->r2lsp = r2ls[0];
  R2ls->r2lsn = r2ls[1];
}
void calcRadii2LSod (void * par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, RadiiLSod * R2ls)
Definition at line 60 of file RadiiLS.c.
References calcSlaterDetOBMEod(), dim, RadiiLSod::r2lsn, and RadiiLSod::r2lsp.
{
  complex double r2ls[2];
  OneBodyOperator op_ob_radii2ls = {dim: 2, opt: 0, par: NULL, me: ob_radii2ls};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_radii2ls, r2ls);
  R2ls->r2lsp = r2ls[0];
  R2ls->r2lsn = r2ls[1];
}
void writeprojectedRadiiLS (FILE * fp, const SlaterDet * Q, const Projection * P, const RadiiLSod ** radiils, const Eigenstates * E)
Definition at line 75 of file RadiiLS.c.
References hbc, Eigenstates::index, j, Projection::jmax, n, Eigenstates::ngood, Eigenstates::norm, Projection::odd, and Eigenstates::v.
Referenced by main().
{
  int odd=P->odd;
  int jmax=P->jmax;
  int p,j,i,n;
  char prefix[8];
  RadiiLSod* r;
  int* idx;
  int ngood;
  complex double *norm, *H;
  for (p=0; p<=1; p++)
    for (j=odd; j<jmax; j=j+2) {
      ngood = E->ngood[idxpij(jmax,p,j)];
      if (ngood) {
        if(odd) sprintf(prefix, "[%d/2%c]", j, p ? '-' : '+');
        else    sprintf(prefix, "[%d%c]", j/2, p ? '-' : '+');
        idx = E->index[idxpij(jmax,p,j)];
        norm = E->norm[idxpij(jmax,p,j)];
        H = E->v[idxpij(jmax,p,j)];
        r = radiils[idxpij(jmax,p,j)];
        fprintf(fp, "\n%s  N      = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.5f", creal(norm[idx[i]]));
        fprintf(fp, "\n%s  H      = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", hbc*creal(H[idx[i]]));
        fprintf(fp, "\n%s  R2lsp  = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", 0.5*creal(r[idx[i]].r2lsp/norm[idx[i]]));
        fprintf(fp, "\n%s  R2lsn  = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", 0.5*creal(r[idx[i]].r2lsn/norm[idx[i]]));
       fprintf(fp, "\n");
      }
    }
}
Variable Documentation
ManyBodyOperator OpRadiiLS
Initial value:
 {
 name : "RadiiLS",
 rank : 0,
 pi : 0,
 dim : 2,
 size : 2,
 par : NULL,
 me : calcRadii2LSod
}
Definition at line 24 of file RadiiLS.c.
Referenced by main().