FMD: fmd/RadiiAll.h File Reference
fmd/RadiiAll.h File Reference
#include <complex.h>
#include "SlaterDet.h"
#include "Projection.h"
Data Structures
struct RadiiAll
struct RadiiAllod
Functions
void calcRadii2all (const SlaterDet *Q, const SlaterDetAux *X, RadiiAll *r2)
void calcRadii2allod (void *par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, RadiiAllod *r2)
void writeprojectedRadiiAll (FILE *fp, const SlaterDet *Q, const Projection *P, RadiiAllod **radiiall, const Eigenstates *E)
Variables
ManyBodyOperator OpRadiiAll
Detailed Description
calculate radii
(c) 2009 Thomas Neff
Definition in file RadiiAll.h.
Function Documentation
void calcRadii2all (const SlaterDet * Q, const SlaterDetAux * X, RadiiAll * r2)
Definition at line 73 of file RadiiAll.c.
References calcSlaterDetOBME(), calcSlaterDetTBME(), dim, par, RadiiAll::r2m, RadiiAll::r2n, RadiiAll::r2nn, RadiiAll::r2p, and RadiiAll::r2pp.
{
  double r2one[5], r2two[5];
  OneBodyOperator op_ob_radii2 = {dim: 5, opt: 1, par: Q, me: ob_radii2all};
  TwoBodyOperator op_tb_radii2 = {dim: 5, opt: 1, par: Q, me: tb_radii2all};
  calcSlaterDetOBME(Q, X, &op_ob_radii2, r2one);
  calcSlaterDetTBME(Q, X, &op_tb_radii2, r2two);
  r2->r2m = r2one[0] + r2two[0];
  r2->r2p = r2one[1] + r2two[1];
  r2->r2n = r2one[2] + r2two[2];
  r2->r2pp = r2one[3] + r2two[3];
  r2->r2nn = r2one[4] + r2two[4];
}
void calcRadii2allod (void * par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, RadiiAllod * r2)
Definition at line 92 of file RadiiAll.c.
References calcSlaterDetOBMEod(), calcSlaterDetTBMEod(), dim, RadiiAllod::r2m, RadiiAllod::r2n, RadiiAllod::r2nn, RadiiAllod::r2p, and RadiiAllod::r2pp.
{
  complex double r2one[5], r2two[5];
  OneBodyOperator op_ob_radii2 = {dim: 5, opt: 1, par: Q, me: ob_radii2all};
  TwoBodyOperator op_tb_radii2 = {dim: 5, opt: 1, par: Q, me: tb_radii2all};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_radii2, r2one);
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_radii2, r2two);
  r2->r2m = r2one[0] + r2two[0];
  r2->r2p = r2one[1] + r2two[1];
  r2->r2n = r2one[2] + r2two[2];
  r2->r2pp = r2one[3] + r2two[3];
  r2->r2nn = r2one[4] + r2two[4];
}
void writeprojectedRadiiAll (FILE * fp, const SlaterDet * Q, const Projection * P, RadiiAllod ** radiiall, const Eigenstates * E)
Definition at line 113 of file RadiiAll.c.
References hbc, Eigenstates::index, j, Projection::jmax, SlaterDet::N, n, Eigenstates::ngood, Eigenstates::norm, Projection::odd, r2charge(), Eigenstates::v, and SlaterDet::Z.
Referenced by main().
{
  int odd=P->odd;
  int jmax=P->jmax;
  int p,j,i,n;
  char prefix[8];
  RadiiAllod* r;
  int* idx;
  int ngood;
  complex double *norm, *H;
  for (p=0; p<=1; p++)
    for (j=odd; j<jmax; j=j+2) {
      ngood = E->ngood[idxpij(jmax,p,j)];
      if (ngood) {
        if(odd) sprintf(prefix, "[%d/2%c]", j, p ? '-' : '+');
        else    sprintf(prefix, "[%d%c]", j/2, p ? '-' : '+');
        idx = E->index[idxpij(jmax,p,j)];
        norm = E->norm[idxpij(jmax,p,j)];
        H = E->v[idxpij(jmax,p,j)];
        r = radiiall[idxpij(jmax,p,j)];
        fprintf(fp, "\n%s  N      = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.5f", creal(norm[idx[i]]));
        fprintf(fp, "\n%s  H      = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", hbc*creal(H[idx[i]]));
        fprintf(fp, "\n%s  Rm     = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", sqrt(creal(r[idx[i]].r2m/norm[idx[i]])));
        fprintf(fp, "\n%s  Rp     = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", sqrt(creal(r[idx[i]].r2p/norm[idx[i]])));
        fprintf(fp, "\n%s  Rn     = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", sqrt(creal(r[idx[i]].r2n/norm[idx[i]])));
        fprintf(fp, "\n%s  Rch    = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", sqrt(r2charge(creal(r[idx[i]].r2p/norm[idx[i]]), Q->N, Q->Z)));
        fprintf(fp, "\n%s  Rpp    = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", sqrt(creal(r[idx[i]].r2pp/norm[idx[i]])));
        fprintf(fp, "\n%s  Rnn    = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", sqrt(creal(r[idx[i]].r2nn/norm[idx[i]])));
       fprintf(fp, "\n");
      }
    }
}
Variable Documentation
ManyBodyOperator OpRadiiAll
Definition at line 24 of file RadiiAll.c.
Referenced by main().