FMD: numerics/rotationmatrices.c File Reference
numerics/rotationmatrices.c File Reference
#include <math.h>
#include <complex.h>
#include "rotationmatrices.h"
Functions
void m3mult (const double A[3][3], complex double x[3])
multiply complex 3-vector with real 3x3-matrix
void cm2mult (const complex double A[2][2], complex double x[2])
multiply complex 2-vector with complex 2x2-matrix
void rotatemat2 (const double euler[3], complex double rmat2[2][2])
spinor rotation matrix
void derivrotatemat2 (const double euler[3], complex double drmat2[3][2][2])
derivatives of spinor rotation matrix
void rotatemat3 (const double euler[3], double rmat3[3][3])
vector rotation matrix
void derivrotatemat3 (const double euler[3], double drmat3[3][3][3])
derivatives of vector rotation matrix
Detailed Description
Rotation matrices in Spinor and Coordinate space and derivatives of rotation matrices with respect to Euler angles.
(c) 2004 Thomas Neff
Definition in file rotationmatrices.c.
Function Documentation
void cm2mult (const complex double A[2][2], complex double x[2])
multiply complex 2-vector with complex 2x2-matrix
Definition at line 35 of file rotationmatrices.c.
References j.
Referenced by ClusterFMDprojectgradSlaterDet(), ClusterprojectgradSlaterDet(), ClustersFMDprojectgradSlaterDet(), and rotateGaussian().
{
  complex double y[2];
  int i,j;
  for (i=0; i<2; i++) {
    y[i] = 0.0;
    for (j=0; j<2; j++)
      y[i] += A[i][j]*x[j];
  }
  for (i=0; i<2; i++)
    x[i] = y[i];
}
void derivrotatemat2 (const double euler[3], complex double drmat2[3][2][2])
derivatives of spinor rotation matrix
Definition at line 60 of file rotationmatrices.c.
References I.
Referenced by ClusterFMDprojectgradSlaterDet(), ClusterprojectgradSlaterDet(), and ClustersFMDprojectgradSlaterDet().
{
  double a = euler[0]; double b = euler[1]; double g = euler[2];
  // derivative with respect to a
  drmat2[0][0][0] = -0.5*I*cos(0.5*b)*cexp(-I*0.5*(a+g));
  drmat2[0][0][1] = +0.5*I*sin(0.5*b)*cexp(-I*0.5*(a-g));
  drmat2[0][1][0] = +0.5*I*sin(0.5*b)*cexp(I*0.5*(a-g));
  drmat2[0][1][1] = +0.5*I*cos(0.5*b)*cexp(I*0.5*(a+g));
  // derivative with respect to b
  drmat2[1][0][0] = -0.5*sin(0.5*b)*cexp(-I*0.5*(a+g));
  drmat2[1][0][1] = -0.5*cos(0.5*b)*cexp(-I*0.5*(a-g));
  drmat2[1][1][0] = +0.5*cos(0.5*b)*cexp(I*0.5*(a-g));
  drmat2[1][1][1] = -0.5*sin(0.5*b)*cexp(I*0.5*(a+g));
  // derivative with respect to g
  drmat2[2][0][0] = -0.5*I*cos(0.5*b)*cexp(-I*0.5*(a+g));
  drmat2[2][0][1] = -0.5*I*sin(0.5*b)*cexp(-I*0.5*(a-g));
  drmat2[2][1][0] = -0.5*I*sin(0.5*b)*cexp(I*0.5*(a-g));
  drmat2[2][1][1] = +0.5*I*cos(0.5*b)*cexp(I*0.5*(a+g));
}
void derivrotatemat3 (const double euler[3], double drmat3[3][3][3])
derivatives of vector rotation matrix
Definition at line 100 of file rotationmatrices.c.
Referenced by ClusterFMDprojectgradSlaterDet(), ClusterprojectgradSlaterDet(), and ClustersFMDprojectgradSlaterDet().
{
  double a = euler[0]; double b = euler[1]; double g = euler[2];
  // derivative with respect to a
  drmat3[0][0][0] = -cos(g)*cos(b)*sin(a)-sin(g)*cos(a);
  drmat3[0][0][1] = sin(g)*cos(b)*sin(a)-cos(g)*cos(a);
  drmat3[0][0][2] = -sin(b)*sin(a);
  drmat3[0][1][0] = cos(g)*cos(b)*cos(a)-sin(g)*sin(a);
  drmat3[0][1][1] = -sin(g)*cos(b)*cos(a)-cos(g)*sin(a);
  drmat3[0][1][2] = sin(b)*cos(a);
  drmat3[0][2][0] = 0.0;
  drmat3[0][2][1] = 0.0;
  drmat3[0][2][2] = 0.0;
  // derivative with respect to b
  drmat3[1][0][0] = -cos(g)*sin(b)*cos(a);
  drmat3[1][0][1] = sin(g)*sin(b)*cos(a);
  drmat3[1][0][2] = cos(b)*cos(a);
  drmat3[1][1][0] = -cos(g)*sin(b)*sin(a);
  drmat3[1][1][1] = sin(g)*sin(b)*sin(a);
  drmat3[1][1][2] = cos(b)*sin(a);
  drmat3[1][2][0] = -cos(g)*cos(b);
  drmat3[1][2][1] =  sin(g)*cos(b);
  drmat3[1][2][2] = -sin(b);
  // derivative with respect to g
  drmat3[2][0][0] = -sin(g)*cos(b)*cos(a)-cos(g)*sin(a);
  drmat3[2][0][1] = -cos(g)*cos(b)*cos(a)+sin(g)*sin(a);
  drmat3[2][0][2] = 0.0;
  drmat3[2][1][0] = -sin(g)*cos(b)*sin(a)+cos(g)*cos(a);
  drmat3[2][1][1] = -cos(g)*cos(b)*sin(a)-sin(g)*cos(a);
  drmat3[2][1][2] = 0.0;
  drmat3[2][2][0] = sin(g)*sin(b);
  drmat3[2][2][1] = cos(g)*sin(b);
  drmat3[2][2][2] = 0.0;
}
void m3mult (const double A[3][3], complex double x[3])
multiply complex 3-vector with real 3x3-matrix
Definition at line 20 of file rotationmatrices.c.
References j.
Referenced by ClusterFMDprojectgradSlaterDet(), ClusterprojectgradSlaterDet(), ClustersFMDprojectgradSlaterDet(), and rotateGaussian().
{
  complex double y[3];
  int i,j;
  for (i=0; i<3; i++) {
    y[i] = 0.0;
    for (j=0; j<3; j++)
      y[i] += A[i][j]*x[j];
  }
  for (i=0; i<3; i++)
    x[i] = y[i];
}
void rotatemat2 (const double euler[3], complex double rmat2[2][2])
spinor rotation matrix
Definition at line 50 of file rotationmatrices.c.
References I.
Referenced by ClusterFMDtoSlaterDet(), ClustersFMDprojectgradSlaterDet(), ClustersFMDtoSlaterDet(), ClustertoSlaterDet(), rotategradSlaterDet(), and rotateSlaterDet().
{
  double a = euler[0]; double b = euler[1]; double g = euler[2];
  rmat2[0][0] = cos(0.5*b)*cexp(-I*0.5*(a+g));
  rmat2[0][1] = -sin(0.5*b)*cexp(-I*0.5*(a-g));
  rmat2[1][0] = sin(0.5*b)*cexp(I*0.5*(a-g));
  rmat2[1][1] = cos(0.5*b)*cexp(I*0.5*(a+g));
}
void rotatemat3 (const double euler[3], double rmat3[3][3])
vector rotation matrix
Definition at line 84 of file rotationmatrices.c.
Referenced by ClusterFMDtoSlaterDet(), ClustersFMDprojectgradSlaterDet(), ClustersFMDtoSlaterDet(), ClustertoSlaterDet(), rotategradSlaterDet(), and rotateSlaterDet().
{
  double a = euler[0]; double b = euler[1]; double g = euler[2];
  rmat3[0][0] = cos(g)*cos(b)*cos(a)-sin(g)*sin(a);
  rmat3[0][1] = -sin(g)*cos(b)*cos(a)-cos(g)*sin(a);
  rmat3[0][2] = sin(b)*cos(a);
  rmat3[1][0] = cos(g)*cos(b)*sin(a)+sin(g)*cos(a);
  rmat3[1][1] = -sin(g)*cos(b)*sin(a)+cos(g)*cos(a);
  rmat3[1][2] = sin(b)*sin(a);
  rmat3[2][0] = -cos(g)*sin(b);
  rmat3[2][1] =  sin(g)*sin(b);
  rmat3[2][2] = cos(b);
}