FMD: fmd/SDRadii.c File Reference
fmd/SDRadii.c File Reference
#include <math.h>
#include <complex.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "Projection.h"
#include "SDRadii.h"
#include "misc/physics.h"
#include "numerics/cmath.h"
Functions
void calcSDRadii2 (const SlaterDet *Q, const SlaterDetAux *X, SDRadii *r2)
void calcSDRadii2od (void *par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, SDRadiiod *r2)
void writeprojectedSDRadii (FILE *fp, const SlaterDet *Q, const Projection *P, SDRadiiod **sdradii, const Eigenstates *E)
Variables
ManyBodyOperator OpSDRadii
Function Documentation
void calcSDRadii2 (const SlaterDet * Q, const SlaterDetAux * X, SDRadii * r2)
Definition at line 51 of file SDRadii.c.
References calcSlaterDetOBME(), dim, par, SDRadii::r2m, SDRadii::r2n, and SDRadii::r2p.
{
  double r2sd[3];
  OneBodyOperator op_ob_radii2sd = {dim: 3, opt: 1, par: Q, me: ob_radii2sd};
  calcSlaterDetOBME(Q, X, &op_ob_radii2sd, r2sd);
  r2->r2m = r2sd[0];
  r2->r2p = r2sd[1];
  r2->r2n = r2sd[2];
}
void calcSDRadii2od (void * par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, SDRadiiod * r2)
Definition at line 66 of file SDRadii.c.
References calcSlaterDetOBMEod(), dim, SDRadiiod::r2m, SDRadiiod::r2n, and SDRadiiod::r2p.
{
  complex double r2sd[3];
  OneBodyOperator op_ob_radii2sd = {dim: 3, opt: 1, par: Q, me: ob_radii2sd};
  calcSlaterDetOBMEod(Q, Qp, X, &op_ob_radii2sd, r2sd);
  r2->r2m = r2sd[0];
  r2->r2p = r2sd[1];
  r2->r2n = r2sd[2];
}
void writeprojectedSDRadii (FILE * fp, const SlaterDet * Q, const Projection * P, SDRadiiod ** sdradii, const Eigenstates * E)
Definition at line 82 of file SDRadii.c.
References hbc, Eigenstates::index, j, Projection::jmax, SlaterDet::N, n, Eigenstates::ngood, Eigenstates::norm, Projection::odd, r2charge(), Eigenstates::v, and SlaterDet::Z.
Referenced by main().
{
  int odd=P->odd;
  int jmax=P->jmax;
  int p,j,i,n;
  char prefix[8];
  SDRadiiod* r;
  int* idx;
  int ngood;
  complex double *norm, *H;
  for (p=0; p<=1; p++)
    for (j=odd; j<jmax; j=j+2) {
      ngood = E->ngood[idxpij(jmax,p,j)];
      if (ngood) {
        if(odd) sprintf(prefix, "[%d/2%c]", j, p ? '-' : '+');
        else    sprintf(prefix, "[%d%c]", j/2, p ? '-' : '+');
        idx = E->index[idxpij(jmax,p,j)];
        norm = E->norm[idxpij(jmax,p,j)];
        H = E->v[idxpij(jmax,p,j)];
        r = sdradii[idxpij(jmax,p,j)];
        fprintf(fp, "\n%s  N      = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.5f", creal(norm[idx[i]]));
        fprintf(fp, "\n%s  H      = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", hbc*creal(H[idx[i]]));
        fprintf(fp, "\n%s  Rm     = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", sqrt(creal(r[idx[i]].r2m/norm[idx[i]])));
        fprintf(fp, "\n%s  Rp     = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", sqrt(creal(r[idx[i]].r2p/norm[idx[i]])));
        fprintf(fp, "\n%s  Rn     = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", sqrt(creal(r[idx[i]].r2n/norm[idx[i]])));
        fprintf(fp, "\n%s  Rch    = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", sqrt(r2charge(creal(r[idx[i]].r2p/norm[idx[i]]), Q->N, Q->Z)));
       fprintf(fp, "\n");
      }
    }
}
Variable Documentation
ManyBodyOperator OpSDRadii
Initial value:
 {
 name : "SDRadii",
 rank : 0,
 pi : 0,
 dim : 3,
 size : 3,
 par : NULL,
 me : calcSDRadii2od
}
Definition at line 24 of file SDRadii.c.
Referenced by main().