FMD: fmd/SimpleSlaterDet.h File Reference
fmd/SimpleSlaterDet.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "SlaterDet.h"
#include "Symmetry.h"
#include "MultiSlaterDet.h"
Functions
Symmetry SimpleSlaterDetSymmetry (const MultiSlaterDet *MB, int iM)
complex double SimpleSlaterDetWeight (const MultiSlaterDet *MB, int iM, int i)
void SimpleSlaterDetGet (const MultiSlaterDet *MB, int i, SlaterDet *Q)
int SimpleSlaterDetRead (FILE *fp, MultiSlaterDet *MB)
Variables
MultiSlaterDet SimpleSlaterDet
some fields have to be initialized later
Detailed Description
implement SimpleSlaterDet as MultiSlaterDet
(c) 2005
Definition in file SimpleSlaterDet.h.
Function Documentation
void SimpleSlaterDetGet (const MultiSlaterDet * MB, int i, SlaterDet * Q)
Definition at line 54 of file SimpleSlaterDet.c.
References copySlaterDet(), _MSD_::internals, and SimpleSlaterDetInternals::Q.
{
  SimpleSlaterDetInternals* internals = MB->internals;
  copySlaterDet(internals->Q, Q);
}
int SimpleSlaterDetRead (FILE * fp, MultiSlaterDet * MB)
Definition at line 63 of file SimpleSlaterDet.c.
References SlaterDet::A, _MSD_::A, _MSD_::internals, SimpleSlaterDetInternals::Q, and readSlaterDet().
Referenced by readMultiSlaterDetfromFile().
{
  *MB = SimpleSlaterDet;
  SimpleSlaterDetInternals* internals =
    malloc(sizeof(SimpleSlaterDetInternals));
  internals->Q = malloc(sizeof(SlaterDet));
  MB->internals = internals;
  int ret;
  ret = readSlaterDet(fp, internals->Q);
  MB->A = internals->Q->A;
  return ret;
}
Symmetry SimpleSlaterDetSymmetry (const MultiSlaterDet * MB, int iM)
Definition at line 42 of file SimpleSlaterDet.c.
{
  return 0;
}
complex double SimpleSlaterDetWeight (const MultiSlaterDet * MB, int iM, int i)
Definition at line 48 of file SimpleSlaterDet.c.
{
  return 1.0;
}
Variable Documentation
MultiSlaterDet SimpleSlaterDet
some fields have to be initialized later
Definition at line 31 of file SimpleSlaterDet.c.