FMD: fmd/SlaterDet.h File Reference
fmd/SlaterDet.h File Reference
#include <stdio.h>
#include <complex.h>
#include "Gaussian.h"
Data Structures
struct SlaterDet
Slater Determinant.
struct SlaterDetAux
Defines
#define MAXNG 3
Functions
void allocateSlaterDet (SlaterDet *Q, int A)
allocate memory for SlaterDet
void initSlaterDet (const SlaterDet *Q, SlaterDet *Qp)
void freeSlaterDet (SlaterDet *Q)
free memory used by Slater determinant Q
void writeSlaterDet (FILE *fp, const SlaterDet *Q)
write parameters of Slater determinant Q in file
int readSlaterDet (FILE *fp, SlaterDet *Q)
int readSlaterDetfromFile (SlaterDet *Q, const char *fname)
void copySlaterDet (const SlaterDet *Q, SlaterDet *Qp)
void cloneSlaterDet (const SlaterDet *Q, SlaterDet *Qp)
void joinSlaterDets (const SlaterDet *Qa, const SlaterDet *Qb, SlaterDet *Q)
void normalizeSlaterDet (SlaterDet *Q, SlaterDetAux *X)
normalize SlaterDet
void moveSlaterDet (SlaterDet *Q, double d[3])
move Slater determinant by vector d
void boostSlaterDet (SlaterDet *Q, double v[3])
boost Slater determinant with speed v
void rotateSlaterDet (SlaterDet *Q, double alpha, double beta, double gamma)
rotate Slater determinant by euler angles
void moveboostSlaterDet (SlaterDet *Q, SlaterDetAux *X)
move and boost center of mass to origin
void moveboostorientSlaterDet (SlaterDet *Q, SlaterDetAux *X)
move and boost center of mass to origin, orient main axes
void orientSlaterDet (SlaterDet *Q, SlaterDetAux *X)
orient main axes
void invertSlaterDet (SlaterDet *Q)
invert Slater determinant in origin
void invertcmSlaterDet (SlaterDet *Q, SlaterDetAux *X)
invert Slater determinant with respect to cm position and velocity
void timerevertSlaterDet (SlaterDet *Q)
time revert Slater determinant
void scaleSlaterDet (SlaterDet *Q, double kappa)
scale Slater determinant
void allocateSlaterDetAux (SlaterDetAux *X, int A)
allocate memory for SlaterDetAux
void initSlaterDetAux (const SlaterDet *Q, SlaterDetAux *X)
init SlaterDetAux X
void freeSlaterDetAux (SlaterDetAux *X)
free memory used by SlaterDetAux X
void calcSlaterDetAux (const SlaterDet *Q, SlaterDetAux *X)
void calcSlaterDetAuxod (const SlaterDet *Q, const SlaterDet *Qp, SlaterDetAux *X)
void calcSlaterDetAuxodsingular (const SlaterDet *Q, const SlaterDet *Qp, SlaterDetAux *X)
void calcSlaterDetOBME (const SlaterDet *Q, const SlaterDetAux *X, const OneBodyOperator *op, double val[])
void calcSlaterDetTBME (const SlaterDet *Q, const SlaterDetAux *X, const TwoBodyOperator *op, double val[])
void calcSlaterDetTBMErowcol (const SlaterDet *Q, const SlaterDetAux *X, const TwoBodyOperator *op, double val[], int k, int l)
void calcSlaterDetOBMEod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const OneBodyOperator *op, complex double val[])
void calcSlaterDetTBMEod (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const TwoBodyOperator *op, complex double val[])
void calcSlaterDetTBMEodrowcol (const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const TwoBodyOperator *op, complex double val[], int k, int l)
void calcSlaterDetOBHFMEs (const SlaterDet *Q, const SlaterDetAux *X, const OneBodyOperator *op, void *val)
calculate Hartree-Fock matrix elements for one-body operator
void calcSlaterDetTBHFMEs (const SlaterDet *Q, const SlaterDetAux *X, const TwoBodyOperator *op, void *val)
calculate Hartree-Fock matrix elements for two-body operator
Detailed Description
Slater determinant build of Gaussians
(c) 2003 Thomas Neff
Definition in file SlaterDet.h.
Define Documentation
#define MAXNG 3
Definition at line 24 of file SlaterDet.h.
Function Documentation
void allocateSlaterDet (SlaterDet * Q, int A)
allocate memory for SlaterDet
Definition at line 32 of file SlaterDet.c.
References SlaterDet::A, SlaterDet::G, SlaterDet::idx, MAXNG, and SlaterDet::ng.
Referenced by calcprojectedMultiMBME(), calcprojectedMultiMBMEmpi(), DiagonalDensityHOSlave(), DiClusterMulticonfigGet(), DiClusterMultiProjSlaterDetGet(), DiClusterProjSlaterDetGet(), FormfactorSlave(), main(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
{
  Q->A = A;
  Q->idx = malloc(A*sizeof(int));
  Q->ng = malloc(A*sizeof(int));
  Q->G = malloc(MAXNG*A*sizeof(Gaussian));
}
void allocateSlaterDetAux (SlaterDetAux * X, int A)
allocate memory for SlaterDetAux
Definition at line 405 of file SlaterDet.c.
References SlaterDetAux::Gaux, initcmat(), MAXNG, SlaterDetAux::n, SlaterDetAux::o, and SQR.
Referenced by calcprojectedMultiMBME(), calcprojectedMultiMBMEmpi(), DiagonalDensityHOSlave(), FormfactorSlave(), MinimizerprojSlave(), MinimizerSlave(), MinimizerSlaveod(), and ProjectionSlave().
{
  X->Gaux = malloc(SQR(MAXNG*A)*sizeof(GaussianAux));
  X->n = initcmat(A);
  X->o = initcmat(A);
}
void boostSlaterDet (SlaterDet * Q, double v[3])
boost Slater determinant with speed v
Definition at line 264 of file SlaterDet.c.
References boostGaussian(), SlaterDet::G, and SlaterDet::ngauss.
Referenced by calcFormfactorod(), calcOneNucleonOvlapsod(), calcTwoNucleonOvlapsTod(), calcTwoNucleonOvlapsYod(), invertcmSlaterDet(), main(), moveboostorientSlaterDet(), and moveboostSlaterDet().
{
  int i;
  for (i=0; i<Q->ngauss; i++)
    boostGaussian(&Q->G[i], v);
}
void calcSlaterDetAux (const SlaterDet * Q, SlaterDetAux * X)
calculate SlaterDetAux for SlaterDet Q. hermiticity not exploited yet
Definition at line 432 of file SlaterDet.c.
References SlaterDet::A, calcGaussianAux(), copycmat(), FORTRAN, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, k, l, mirrorcmat(), SlaterDetAux::n, SlaterDet::ng, ng, SlaterDet::ngauss, SlaterDetAux::o, zpotrf(), and zpotri().
Referenced by _estimateacm(), calcDensitiesCoordinate(), calcDensitiesMomentum(), calcgradprojectedHamiltonian(), calcObservables(), calcRadialDensitiesCoordinate(), calcRadialDensitiesMomentum(), calcShellOccupationsod(), ef(), egradf(), egradh(), eh(), invertcmSlaterDet(), main(), MinimizerSlave(), moveboostorientSlaterDet(), moveboostSlaterDet(), and orientSlaterDet().
{
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* ng=Q->ng;
  Gaussian* G=Q->G;
  GaussianAux* Gaux=X->Gaux;
  int k,l,ki,li;
  for (l=0; l<A; l++)
    for (li=0; li<ng[l]; li++)
      for (k=0; k<A; k++)
        for (ki=0; ki<ng[k]; ki++)
          calcGaussianAux(&G[idx[k]+ki], &G[idx[l]+li],
                          &Gaux[(idx[k]+ki)+(idx[l]+li)*ngauss]);
  for (l=0; l<A; l++)
    for (k=0; k<A; k++) {
      X->n[k+l*A] = 0.0;
      for (li=0; li<ng[l]; li++)
        for (ki=0; ki<ng[k]; ki++)
          X->n[k+l*A] += Gaux[(idx[k]+ki)+(idx[l]+li)*ngauss].Q;
    }
  char UPLO='U';
  int info;
  copycmat(A, X->n, X->o);
  FORTRAN(zpotrf)(&UPLO, &A, X->o, &A, &info);
  FORTRAN(zpotri)(&UPLO, &A, X->o, &A, &info);
  mirrorcmat(A, X->o);
}
void calcSlaterDetAuxod (const SlaterDet * Q, const SlaterDet * Qp, SlaterDetAux * X)
calculate SlaterDetAux for SlaterDet's Q and Qp. inversion by LU decomposition does not work for singular overlap matrix
Definition at line 468 of file SlaterDet.c.
References SlaterDet::A, calcGaussianAux(), copycmat(), FORTRAN, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, k, l, SlaterDetAux::n, n, SlaterDet::N, SlaterDet::ng, ng, SlaterDet::ngauss, SlaterDetAux::o, SlaterDetAux::ovlap, SlaterDet::Z, zdet(), zgetrf(), and zgetri().
Referenced by _estimateangkappa(), calcConstraintD3H(), calcConstraintParCh(), calcConstraintParN(), calcConstraintParP(), calcConstraintSxz(), calcConstraintSyz(), calcDensitiesCoordinateParity(), calcDensityMatrixHO(), calcFormfactorod(), calcgradConstraintD3H(), calcgradConstraintParCh(), calcgradConstraintParN(), calcgradConstraintParP(), calcgradConstraintSxz(), calcgradConstraintSyz(), calcgradorthprojectedHamiltonian(), calcgradprojectedHamiltonian(), calcgradprojectedHamiltonianmatrix(), calcObservablesParity(), calcorthprojectedHamiltonian(), calcParity(), calcParityod(), calcprojectedHamiltonian(), calcprojectedHamiltonianmatrix(), calcprojectedMBME(), calcprojectedMBMEmpi(), calcprojectedMBMEs(), calcprojectedMBMEsmpi(), calcprojectedMultiMBME(), calcprojectedMultiMBMEmpi(), calcTimeReversal(), calcTimeReversalod(), DiagonalDensityHOSlave(), ef(), egradf(), egradh(), eh(), FormfactorSlave(), main(), MinimizerprojSlave(), MinimizerSlaveod(), normalizeSlaterDet(), and ProjectionSlave().
{
  assert(Q->A == Qp->A && Q->Z == Qp->Z && Q->N == Qp->N);
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* idxp=Qp->idx;
  int* ng=Q->ng; int* ngp=Qp->ng;
  Gaussian* G=Q->G; Gaussian* Gp=Qp->G;
  GaussianAux* Gaux=X->Gaux;
  complex double* n=X->n;
  int k,l,ki,li;
  for (l=0; l<A; l++)
    for (li=0; li<ngp[l]; li++)
      for (k=0; k<A; k++)
        for (ki=0; ki<ng[k]; ki++)
          calcGaussianAux(&G[idx[k]+ki], &Gp[idxp[l]+li],
                          &Gaux[(idx[k]+ki)+(idxp[l]+li)*ngauss]);
  for (l=0; l<A; l++)
    for (k=0; k<A; k++) {
      n[k+l*A] = 0.0;
      for (li=0; li<ngp[l]; li++)
        for (ki=0; ki<ng[k]; ki++)
          n[k+l*A] += Gaux[(idx[k]+ki)+(idxp[l]+li)*ngauss].Q;
    }
  int ipiv[A];
  int lwork=A*A;
  complex double work[lwork];
  int info;
  copycmat(A, X->n, X->o);
  FORTRAN(zgetrf)(&A, &A, X->o, &A, ipiv, &info);
  FORTRAN(zdet)(X->o, &A, &A, ipiv, &X->ovlap);
  FORTRAN(zgetri)(&A, X->o, &A, ipiv, work, &lwork, &info);
  if (info)
    fprintf(stderr, "calcSlaterDetAuxod: overlap matrix singular !\n");
}
void calcSlaterDetAuxodsingular (const SlaterDet * Q, const SlaterDet * Qp, SlaterDetAux * X)
calculate SlaterDetAux for SlaterDet's Q and Qp. inversion by SVD decomposition rank A-1 of overlap matrix assumed, ovlap set to 1.0 can only be used with One-Body Operators (GT)
Definition at line 520 of file SlaterDet.c.
References SlaterDet::A, calcGaussianAux(), FORTRAN, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, j, k, l, multcmat(), SlaterDetAux::n, n, SlaterDet::ng, ng, SlaterDet::ngauss, SlaterDetAux::o, SlaterDetAux::ovlap, zdet(), zgesvd(), and zgetrf().
Referenced by calcprojectedMBME(), and calcprojectedMBMEs().
{
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* idxp=Qp->idx;
  int* ng=Q->ng; int* ngp=Qp->ng;
  Gaussian* G=Q->G; Gaussian* Gp=Qp->G;
  GaussianAux* Gaux=X->Gaux;
  complex double* n=X->n;
  complex double* o=X->o;
  int k,l,ki,li;
  for (l=0; l<A; l++)
    for (li=0; li<ngp[l]; li++)
      for (k=0; k<A; k++)
        for (ki=0; ki<ng[k]; ki++)
          calcGaussianAux(&G[idx[k]+ki], &Gp[idxp[l]+li],
                          &Gaux[(idx[k]+ki)+(idxp[l]+li)*ngauss]);
  for (l=0; l<A; l++)
    for (k=0; k<A; k++) {
      n[k+l*A] = 0.0;
      for (li=0; li<ngp[l]; li++)
        for (ki=0; ki<ng[k]; ki++)
          n[k+l*A] += Gaux[(idx[k]+ki)+(idxp[l]+li)*ngauss].Q;
    }
  // calculate SVD of overlap matrix
  complex double U[A*A];
  complex double Vh[A*A];
  double S[A];
  {
    const char jobu='A', jobvt='A';
    const int lwork=5*A;
    complex double work[lwork];
    double rwork[lwork];
    int info;
    FORTRAN(zgesvd)(&jobu, &jobvt, &A, &A, n, &A, S,
                    U, &A, Vh, &A, work, &lwork, rwork, &info);
  }
  // calculate phase detVhU using LU decomposition
  complex double detVhU;
  {
    complex double VhU[A*A];
    int ipiv[A];
    int info;
    multcmat(Vh, U, VhU, A);
    FORTRAN(zgetrf)(&A, &A, VhU, &A, ipiv, &info);
    FORTRAN(zdet)(VhU, &A, &A, ipiv, &detVhU);
  }
  int i,j;
  double prodS;
  prodS = 1.0;
  for (j=0; j<A-1; j++)
    prodS *= S[j];
  for (l=0; l<A; l++)
    for (k=0; k<A; k++)
      o[k+l*A] = conj(Vh[A-1+k*A])*prodS*conj(U[l+(A-1)*A])*detVhU;
  X->ovlap = 1.0;
}
void calcSlaterDetOBHFMEs (const SlaterDet * Q, const SlaterDetAux * X, const OneBodyOperator * op, void * val)
calculate Hartree-Fock matrix elements for one-body operator
Definition at line 879 of file SlaterDet.c.
References SlaterDet::A, OneBodyOperator::dim, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, k, l, OneBodyOperator::me, SlaterDet::ng, ng, SlaterDet::ngauss, OneBodyOperator::opt, OneBodyOperator::par, and GaussianAux::T.
Referenced by calcDensitiesCoordinateHF(), calcDensitiesMomentumHF(), calcHOsciHF(), calcj2HF(), calcl2HF(), calcparHF(), calct3HF(), calcTCMHF(), and calcTHF().
{
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* ng=Q->ng;
  Gaussian* G=Q->G;
  GaussianAux* Gaux=X->Gaux;
  complex double (*mes)[op->dim] = val;
  int k,l,ki,li;
  int i;
  complex double gval[op->dim];
  for (l=0; l<A; l++)
    for (k=0; k<A; k++)
      for (i=0; i<op->dim; i++)
        mes[k+l*A][i] = 0.0;
  for (l=0; l<A; l++) {
    for (k=0; k<A; k++)
      if (!op->opt || Gaux[idx[k]+idx[l]*ngauss].T) {
      for (i=0; i<op->dim; i++)
        gval[i] = 0.0;
      for (li=0; li<ng[l]; li++)
        for (ki=0; ki<ng[k]; ki++)
          op->me(op->par,
                 &G[idx[k]+ki], &G[idx[l]+li],
                 &Gaux[(idx[k]+ki)+(idx[l]+li)*ngauss],
                 gval);
      for (i=0; i<op->dim; i++)
        mes[k+l*A][i] += gval[i];
    }
  }
}
void calcSlaterDetOBME (const SlaterDet * Q, const SlaterDetAux * X, const OneBodyOperator * op, double val[])
calculate matrix element with SaterDet Q for one-body operator op defined for Gaussians val will be overwritten
Definition at line 591 of file SlaterDet.c.
References SlaterDet::A, OneBodyOperator::dim, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, k, l, OneBodyOperator::me, SlaterDet::ng, ng, SlaterDet::ngauss, SlaterDetAux::o, OneBodyOperator::opt, OneBodyOperator::par, and GaussianAux::T.
Referenced by calcAngularMomenta(), calcCMPosition(), calcCMVelocity(), calcConstraintCM(), calcConstraintDetQ(), calcConstraintED2(), calcConstraintEO2(), calcConstraintEQ2(), calcConstraintER2(), calcConstraintJ(), calcConstraintJ2(), calcConstraintJ2(), calcConstraintl2(), calcConstraintls(), calcConstraintLS(), calcConstraintMainAxes(), calcConstraintNNOsci(), calcConstraintNO2(), calcConstraintNOsci(), calcConstraintNQ2(), calcConstraintNR2(), calcConstraintNS2(), calcConstraintNT2(), calcConstraintO2(), calcConstraintPNOsci(), calcConstraintPS2(), calcConstraintPT2(), calcConstraintPX(), calcConstraintPY(), calcConstraintPZ(), calcConstraintQ2(), calcConstraintQ2offdiagonal(), calcConstraintQbeta2(), calcConstraintR2(), calcConstraintS2(), calcConstraintT2(), calcConstraintX(), calcConstraintY(), calcConstraintZ(), calcDensitiesCoordinate(), calcDensitiesCoordinate3d(), calcDensitiesMomentum(), calcDensitiesMomentum3d(), calcgradCMSlaterDetOBME(), calcgradConstraintCM(), calcgradConstraintDetQ(), calcgradConstraintED2(), calcgradConstraintEO2(), calcgradConstraintEQ2(), calcgradConstraintMainAxes(), calcgradConstraintNNOsci(), calcgradConstraintNO2(), calcgradConstraintNOsci(), calcgradConstraintNQ2(), calcgradConstraintO2(), calcgradConstraintPNOsci(), calcgradConstraintQ2(), calcgradConstraintQ2offdiagonal(), calcgradConstraintQbeta2(), calcInertiaTensor(), calcIsospin(), calcJ(), calcJ2(), calcL(), calcOctupoleTensor(), calcOsci2(), calcOsci4(), calcQuadrupole(), calcQuadrupolePrime(), calcRadialDensitiesCoordinate(), calcRadialDensitiesMomentum(), calcRadii2(), calcRadii2all(), calcRadii2LS(), calcS(), calcSDRadii2(), calcSpinDensitiesCoordinate(), calcSpinDensitiesMomentum(), calcT(), and calcTCM().
{
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* ng=Q->ng;
  Gaussian* G=Q->G;
  GaussianAux* Gaux=X->Gaux;
  complex double* o=X->o;
  int k,l,ki,li;
  int i;
  complex double *gval = malloc(op->dim*sizeof(complex double));
  for (i=0; i<op->dim; i++)
    val[i] = 0.0;
  for (l=0; l<A; l++) {
    for (k=0; k<l; k++)
      if (!op->opt || Gaux[idx[k]+idx[l]*ngauss].T) {
      for (i=0; i<op->dim; i++)
        gval[i] = 0.0;
      for (li=0; li<ng[l]; li++)
        for (ki=0; ki<ng[k]; ki++)
          op->me(op->par,
                 &G[idx[k]+ki], &G[idx[l]+li],
                 &Gaux[(idx[k]+ki)+(idx[l]+li)*ngauss],
                 gval);
      for (i=0; i<op->dim; i++)
        val[i] += 2.0*gval[i]*o[l+k*A];
    }
    for (i=0; i<op->dim; i++)
      gval[i] = 0.0;
    for (li=0; li<ng[l]; li++)
      for (ki=0; ki<ng[l]; ki++)
        op->me(op->par,
               &G[idx[l]+ki], &G[idx[l]+li],
               &Gaux[(idx[l]+ki)+(idx[l]+li)*ngauss],
               gval);
    for (i=0; i<op->dim; i++)
      val[i] += creal(gval[i])*creal(o[k+l*A]);
  }
  free(gval);
}
void calcSlaterDetOBMEod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const OneBodyOperator * op, complex double val[])
calculate off-diagonal matrix element with SaterDets Q and Qp for one-body operator op defined for Gaussians val will be overwritten
Definition at line 736 of file SlaterDet.c.
References SlaterDet::A, OneBodyOperator::dim, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, k, l, OneBodyOperator::me, SlaterDet::ng, ng, SlaterDet::ngauss, SlaterDetAux::o, OneBodyOperator::opt, SlaterDetAux::ovlap, OneBodyOperator::par, and GaussianAux::T.
Referenced by calcAngularMomentaod(), calcConstraintEQ2od(), calcConstraintER2od(), calcConstraintJ2od(), calcConstraintLSod(), calcConstraintNQ2od(), calcConstraintNR2od(), calcConstraintQ2od(), calcConstraintR2od(), calcConstraintS2od(), calcConstraintT2od(), calcDensitiesCoordinateParity(), calcDensityMatrixHO(), calcEDipoleod(), calcEMonopoleod(), calcEQuadrupoleod(), calcFormfactorod(), calcGTminusod(), calcGTplusod(), calcIsospinod(), calcJ2od(), calcJod(), calcLod(), calcMDipoleod(), calcMeanOsciQuantaod(), calcNOsciod(), calcRadii2allod(), calcRadii2LSod(), calcRadii2od(), calcSDRadii2od(), calcSod(), calcTCMod(), and calcTod().
{
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* idxp=Qp->idx;
  int* ng=Q->ng; int* ngp=Qp->ng;
  Gaussian* G=Q->G; Gaussian* Gp=Qp->G;
  GaussianAux* Gaux=X->Gaux;
  complex double* o=X->o;
  complex double ovl = X->ovlap;
  int k,l, ki,li;
  int i;
  complex double *gval = malloc(op->dim*sizeof(complex double));
  for (i=0; i<op->dim; i++)
    val[i] = 0.0;
  for (l=0; l<A; l++)
    for (k=0; k<A; k++)
      if (!op->opt || Gaux[idx[k]+idxp[l]*ngauss].T) {
        for (i=0; i<op->dim; i++)
          gval[i] = 0.0;
        for (li=0; li<ngp[l]; li++)
          for (ki=0; ki<ng[k]; ki++)
            op->me(op->par,
                   &G[idx[k]+ki], &Gp[idxp[l]+li],
                   &Gaux[(idx[k]+ki)+(idxp[l]+li)*ngauss],
                   gval);
        for (i=0; i<op->dim; i++)
          val[i] += gval[i]*o[l+k*A]*ovl;
      }
  free(gval);
}
void calcSlaterDetTBHFMEs (const SlaterDet * Q, const SlaterDetAux * X, const TwoBodyOperator * op, void * val)
calculate Hartree-Fock matrix elements for two-body operator
Definition at line 917 of file SlaterDet.c.
References SlaterDet::A, TwoBodyOperator::dim, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, k, l, m, TwoBodyOperator::me, n, SlaterDet::ng, ng, SlaterDet::ngauss, SlaterDetAux::o, TwoBodyOperator::opt, TwoBodyOperator::par, and GaussianAux::T.
Referenced by calcPotentialsHF(), and calcTCMHF().
{
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* ng=Q->ng;
  Gaussian* G=Q->G;
  GaussianAux* Gaux=X->Gaux;
  complex double* o=X->o;
  complex double (*mes)[op->dim] = val;
  int k,l,m,n, ki,li,mi,ni;
  int i;
  complex double gval[op->dim];
  for (m=0; m<A; m++)
    for (k=0; k<A; k++)
      for (i=0; i<op->dim; i++)
        mes[k+m*A][i] = 0.0;
  for (n=0; n<A; n++)
    for (l=0; l<A; l++)
      if (!op->opt || Gaux[idx[l]+idx[n]*ngauss].T) {
        for (m=0; m<A; m++)
          for (k=0; k<A; k++)
            if (!op->opt || Gaux[idx[k]+idx[m]*ngauss].T) {
              for (i=0; i<op->dim; i++)
                gval[i] = 0.0;
              for (ni=0; ni<ng[n]; ni++)
                for (li=0; li<ng[l]; li++)
                  for (mi=0; mi<ng[m]; mi++)
                    for (ki=0; ki<ng[k]; ki++)
                      op->me(op->par,
                             &G[idx[k]+ki], &G[idx[l]+li],
                             &G[idx[m]+mi], &G[idx[n]+ni],
                             &Gaux[(idx[k]+ki)+(idx[m]+mi)*ngauss],
                             &Gaux[(idx[l]+li)+(idx[n]+ni)*ngauss],
                             gval);
              for (i=0; i<op->dim; i++) {
                mes[k+m*A][i] += gval[i]*o[n+l*A];
                mes[k+n*A][i] -= gval[i]*o[m+l*A];
              }
            }
      }
}
void calcSlaterDetTBME (const SlaterDet * Q, const SlaterDetAux * X, const TwoBodyOperator * op, double val[])
calculate matrix element with SaterDet Q for two-body operator op defined for Gaussians val will be overwritten
Definition at line 641 of file SlaterDet.c.
References SlaterDet::A, TwoBodyOperator::dim, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, k, l, m, TwoBodyOperator::me, n, SlaterDet::ng, ng, SlaterDet::ngauss, SlaterDetAux::o, TwoBodyOperator::opt, TwoBodyOperator::par, and GaussianAux::T.
Referenced by calcAngularMomenta(), calcConstraintER2(), calcConstraintJ2(), calcConstraintLS(), calcConstraintMainAxes(), calcConstraintNR2(), calcConstraintNS2(), calcConstraintNT2(), calcConstraintPS2(), calcConstraintPT2(), calcConstraintQbeta2(), calcConstraintR2(), calcConstraintS2(), calcConstraintT2(), calcgradCMSlaterDetTBME(), calcgradConstraintMainAxes(), calcgradConstraintQbeta2(), calcIsospin(), calcJ2(), calcPairs(), calcPotential(), calcQuadrupole(), calcQuadrupolePrime(), calcRadii2(), calcRadii2all(), and calcTCM().
{
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* ng=Q->ng;
  Gaussian* G=Q->G;
  GaussianAux* Gaux=X->Gaux;
  complex double* o=X->o;
  int k,l,m,n, ki,li,mi,ni;
  int i;
  complex double *gval = malloc(op->dim*sizeof(complex double));
  for (i=0; i<op->dim; i++)
    val[i] = 0.0;
  for (n=0; n<A; n++)
    for (l=0; l<A; l++)
      if (!op->opt || Gaux[idx[l]+idx[n]*ngauss].T) {
        for (m=0; m<A; m++)
          for (k=0; k<l; k++)
            if (!op->opt || Gaux[idx[k]+idx[m]*ngauss].T) {
              for (i=0; i<op->dim; i++)
                gval[i] = 0.0;
              for (ni=0; ni<ng[n]; ni++)
                for (li=0; li<ng[l]; li++)
                  for (mi=0; mi<ng[m]; mi++)
                    for (ki=0; ki<ng[k]; ki++)
                      op->me(op->par,
                             &G[idx[k]+ki], &G[idx[l]+li],
                             &G[idx[m]+mi], &G[idx[n]+ni],
                             &Gaux[(idx[k]+ki)+(idx[m]+mi)*ngauss],
                             &Gaux[(idx[l]+li)+(idx[n]+ni)*ngauss],
                             gval);
              for (i=0; i<op->dim; i++)
                val[i] += gval[i]*
                  (o[m+k*A]*o[n+l*A]-o[n+k*A]*o[m+l*A]);
            }
      }
  free(gval);
}
void calcSlaterDetTBMEod (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const TwoBodyOperator * op, complex double val[])
calculate off-diagonal matrix element with SaterDets Q and Qp for two-body operator op defined for Gaussians val will be overwritten
Definition at line 777 of file SlaterDet.c.
References SlaterDet::A, TwoBodyOperator::dim, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, k, l, m, TwoBodyOperator::me, n, SlaterDet::ng, ng, SlaterDet::ngauss, SlaterDetAux::o, TwoBodyOperator::opt, SlaterDetAux::ovlap, TwoBodyOperator::par, and GaussianAux::T.
Referenced by calcAngularMomentaod(), calcConstraintER2od(), calcConstraintJ2od(), calcConstraintLSod(), calcConstraintNR2od(), calcConstraintR2od(), calcConstraintS2od(), calcConstraintT2od(), calcEMonopoleod(), calcEQuadrupoleod(), calcIsospinod(), calcJ2od(), calcMDipoleod(), calcPairsod(), calcPotentialod(), calcRadii2allod(), calcRadii2od(), calcTBDensQLod(), calcTBDensQod(), calcTBDensRLod(), calcTBDensRod(), and calcTCMod().
{
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* idxp=Qp->idx;
  int* ng=Q->ng; int* ngp=Qp->ng;
  Gaussian* G=Q->G; Gaussian* Gp=Qp->G;
  GaussianAux* Gaux=X->Gaux;
  complex double* o=X->o;
  complex double ovl=X->ovlap;
  int k,l,m,n, ki,li,mi,ni;
  int i;
  complex double *gval = malloc(op->dim*sizeof(complex double));
  for (i=0; i<op->dim; i++)
    val[i] = 0.0;
  for (n=0; n<A; n++)
    for (l=0; l<A; l++)
      if (!op->opt || Gaux[idx[l]+idxp[n]*ngauss].T) {
        for (m=0; m<A; m++)
          for (k=0; k<A; k++)
            if (!op->opt || Gaux[idx[k]+idxp[m]*ngauss].T) {
              for (i=0; i<op->dim; i++)
                gval[i] = 0.0;
              for (ni=0; ni<ngp[n]; ni++)
                for (li=0; li<ng[l]; li++)
                  for (mi=0; mi<ngp[m]; mi++)
                    for (ki=0; ki<ng[k]; ki++)
                      op->me(op->par,
                             &G[idx[k]+ki], &G[idx[l]+li],
                             &Gp[idxp[m]+mi], &Gp[idxp[n]+ni],
                             &Gaux[(idx[k]+ki)+(idxp[m]+mi)*ngauss],
                             &Gaux[(idx[l]+li)+(idxp[n]+ni)*ngauss],
                             gval);
              for (i=0; i<op->dim; i++)
                val[i] += 0.5*gval[i]*
                  (o[m+k*A]*o[n+l*A]-o[n+k*A]*o[m+l*A])*ovl;
            }
      }
  free(gval);
}
void calcSlaterDetTBMEodrowcol (const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, const TwoBodyOperator * op, complex double val[], int k, int l)
Definition at line 827 of file SlaterDet.c.
References SlaterDet::A, TwoBodyOperator::dim, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, m, TwoBodyOperator::me, n, SlaterDet::ng, ng, SlaterDet::ngauss, SlaterDetAux::o, TwoBodyOperator::opt, SlaterDetAux::ovlap, TwoBodyOperator::par, and GaussianAux::T.
Referenced by calcPotentialodrowcol().
{
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* idxp=Qp->idx;
  int* ng=Q->ng; int* ngp=Qp->ng;
  Gaussian* G=Q->G; Gaussian* Gp=Qp->G;
  GaussianAux* Gaux=X->Gaux;
  complex double* o=X->o;
  complex double ovl=X->ovlap;
  int m,n, ki,li,mi,ni;
  int i;
  complex double *gval = malloc(op->dim*sizeof(complex double));
  for (i=0; i<op->dim; i++)
    val[i] = 0.0;
  for (n=0; n<A; n++)
    // for (l=0; l<A; l++)
      if (!op->opt || Gaux[idx[l]+idxp[n]*ngauss].T) {
        for (m=0; m<A; m++)
          // for (k=0; k<A; k++)
            if (!op->opt || Gaux[idx[k]+idxp[m]*ngauss].T) {
              for (i=0; i<op->dim; i++)
                gval[i] = 0.0;
              for (ni=0; ni<ngp[n]; ni++)
                for (li=0; li<ng[l]; li++)
                  for (mi=0; mi<ngp[m]; mi++)
                    for (ki=0; ki<ng[k]; ki++)
                      op->me(op->par,
                             &G[idx[k]+ki], &G[idx[l]+li],
                             &Gp[idxp[m]+mi], &Gp[idxp[n]+ni],
                             &Gaux[(idx[k]+ki)+(idxp[m]+mi)*ngauss],
                             &Gaux[(idx[l]+li)+(idxp[n]+ni)*ngauss],
                             gval);
              for (i=0; i<op->dim; i++)
                val[i] += gval[i]*
                  (o[m+k*A]*o[n+l*A]-o[n+k*A]*o[m+l*A])*ovl;
            }
      }
  free(gval);
}
void calcSlaterDetTBMErowcol (const SlaterDet * Q, const SlaterDetAux * X, const TwoBodyOperator * op, double val[], int k, int l)
Definition at line 688 of file SlaterDet.c.
References SlaterDet::A, TwoBodyOperator::dim, SlaterDet::G, G, SlaterDetAux::Gaux, SlaterDet::idx, m, TwoBodyOperator::me, n, SlaterDet::ng, ng, SlaterDet::ngauss, SlaterDetAux::o, TwoBodyOperator::opt, TwoBodyOperator::par, and GaussianAux::T.
Referenced by calcPotentialrowcol().
{
  int A=Q->A; int ngauss=Q->ngauss;
  int* idx=Q->idx; int* ng=Q->ng;
  Gaussian* G=Q->G;
  GaussianAux* Gaux=X->Gaux;
  complex double* o=X->o;
  int m,n, ki,li,mi,ni;
  int i;
  complex double *gval = malloc(op->dim*sizeof(complex double));
  for (i=0; i<op->dim; i++)
    val[i] = 0.0;
  for (n=0; n<A; n++)
    // for (l=0; l<A; l++)
      if (!op->opt || Gaux[idx[l]+idx[n]*ngauss].T) {
        for (m=0; m<A; m++)
          // for (k=0; k<l; k++)
            if (!op->opt || Gaux[idx[k]+idx[m]*ngauss].T) {
              for (i=0; i<op->dim; i++)
                gval[i] = 0.0;
              for (ni=0; ni<ng[n]; ni++)
                for (li=0; li<ng[l]; li++)
                  for (mi=0; mi<ng[m]; mi++)
                    for (ki=0; ki<ng[k]; ki++)
                      op->me(op->par,
                             &G[idx[k]+ki], &G[idx[l]+li],
                             &G[idx[m]+mi], &G[idx[n]+ni],
                             &Gaux[(idx[k]+ki)+(idx[m]+mi)*ngauss],
                             &Gaux[(idx[l]+li)+(idx[n]+ni)*ngauss],
                             gval);
              for (i=0; i<op->dim; i++)
                val[i] += gval[i]*
                  (o[m+k*A]*o[n+l*A]-o[n+k*A]*o[m+l*A]);
            }
      }
  free(gval);
}
void cloneSlaterDet (const SlaterDet * Q, SlaterDet * Qp)
copy Slater determinant Q into Qp Qp will be initialized
Definition at line 198 of file SlaterDet.c.
References SlaterDet::A, copySlaterDet(), SlaterDet::G, SlaterDet::idx, MAXNG, SlaterDet::ng, and SlaterDet::ngauss.
Referenced by calcObservablesParity(), Clusterclone(), ClusterFMDclone(), ClustersFMDclone(), CoreFMDclone(), DiClusterMulticonfigRead(), DiClusterMultiProjSlaterDetRead(), and DiClusterProjSlaterDetRead().
{
  Qp->A = Q->A;
  Qp->ngauss = Q->ngauss;
  Qp->idx = malloc(Qp->A*sizeof(int));
  Qp->ng = malloc(Qp->A*sizeof(int));
  Qp->G = malloc(MAXNG*Qp->A*sizeof(Gaussian));
  copySlaterDet(Q, Qp);
}
void copySlaterDet (const SlaterDet * Q, SlaterDet * Qp)
copy Slater determinant Q into Qp Qp must have been initialized already
Definition at line 180 of file SlaterDet.c.
References SlaterDet::A, SlaterDet::G, SlaterDet::idx, SlaterDet::N, SlaterDet::ng, SlaterDet::ngauss, and SlaterDet::Z.
Referenced by _estimateangkappa(), calcConstraintD3H(), calcConstraintParCh(), calcConstraintParN(), calcConstraintParP(), calcConstraintSxz(), calcConstraintSyz(), calcDensitiesCoordinateParity(), calcFormfactorod(), calcgradConstraintD3H(), calcgradConstraintParCh(), calcgradConstraintParN(), calcgradConstraintParP(), calcgradConstraintSxz(), calcgradConstraintSyz(), calcgradorthprojectedHamiltonian(), calcgradprojectedHamiltonian(), calcgradprojectedHamiltonianmatrix(), calcOneNucleonOvlapsod(), calcorthprojectedHamiltonian(), calcParity(), calcParityod(), calcprojectedHamiltonian(), calcprojectedHamiltonianmatrix(), calcprojectedMBME(), calcprojectedMBMEs(), calcprojectedMultiMBME(), calcTimeReversal(), calcTimeReversalod(), calcTwoNucleonOvlapsTod(), calcTwoNucleonOvlapsYod(), cloneSlaterDet(), DiagonalDensityHOSlave(), DiClusterMulticonfigGet(), DiClusterMultiProjSlaterDetGet(), DiClusterProjSlaterDetGet(), ef(), egradf(), egradh(), eh(), FormfactorSlave(), main(), MinimizerprojSlave(), OneNucleonOvlapsSlave(), ProjectionSlave(), SimpleSlaterDetGet(), SymmetricMultiSlaterDetGet(), SymmetricSlaterDetGet(), and TwoNucleonOvlapsSlave().
{
  int i;
  assert(Qp->A >= Q->A);
  Qp->A = Q->A;
  Qp->Z = Q->Z; Qp->N = Q->N;
  Qp->ngauss = Q->ngauss;
  for (i=0; i<Q->A; i++) {
    Qp->idx[i] = Q->idx[i];
    Qp->ng[i] = Q->ng[i];
  }
  for (i=0; i<Q->ngauss; i++)
    Qp->G[i] = Q->G[i];
}
void freeSlaterDet (SlaterDet * Q)
free memory used by Slater determinant Q
Definition at line 53 of file SlaterDet.c.
References SlaterDet::G, SlaterDet::idx, and SlaterDet::ng.
Referenced by calcDensitiesCoordinateParity(), calcObservablesParity(), calcprojectedMBME(), and calcprojectedMBMEs().
{
  free(Q->idx);
  free(Q->ng);
  free(Q->G);
}
void freeSlaterDetAux (SlaterDetAux * X)
free memory used by SlaterDetAux X
Definition at line 423 of file SlaterDet.c.
References SlaterDetAux::Gaux, SlaterDetAux::n, and SlaterDetAux::o.
Referenced by _estimateacm(), calcDensitiesCoordinate(), calcDensitiesCoordinateParity(), calcDensitiesMomentum(), calcObservables(), calcObservablesParity(), calcprojectedMBME(), calcprojectedMBMEs(), calcRadialDensitiesCoordinate(), calcRadialDensitiesMomentum(), and calcShellOccupationsod().
{
  free(X->Gaux);
  free(X->n);
  free(X->o);
}
void initSlaterDet (const SlaterDet * Q, SlaterDet * Qp)
initialize Slater determinant Qp with Q
Definition at line 41 of file SlaterDet.c.
References SlaterDet::A, SlaterDet::G, SlaterDet::idx, MAXNG, SlaterDet::ng, and SlaterDet::ngauss.
Referenced by _estimateangkappa(), calcDensitiesCoordinateParity(), calcFormfactorod(), calcOneNucleonOvlapsod(), calcParity(), calcParityod(), calcprojectedMBME(), calcprojectedMBMEs(), calcTimeReversal(), calcTimeReversalod(), calcTwoNucleonOvlapsTod(), calcTwoNucleonOvlapsYod(), initWork(), and main().
{
  assert(Q->ngauss <= MAXNG*Q->A);
  Qp->A = Q->A;
  Qp->ngauss = Q->ngauss;
  Qp->idx = malloc(Qp->A*sizeof(int));
  Qp->ng = malloc(Qp->A*sizeof(int));
  Qp->G = malloc(MAXNG*Qp->A*sizeof(Gaussian));
}
void initSlaterDetAux (const SlaterDet * Q, SlaterDetAux * X)
init SlaterDetAux X
Definition at line 414 of file SlaterDet.c.
References SlaterDet::A, SlaterDetAux::Gaux, initcmat(), MAXNG, SlaterDetAux::n, SlaterDet::ngauss, SlaterDetAux::o, and SQR.
Referenced by _estimateacm(), _estimateangkappa(), calcDensitiesCoordinate(), calcDensitiesCoordinateParity(), calcDensitiesMomentum(), calcFormfactorod(), calcObservables(), calcObservablesParity(), calcParity(), calcParityod(), calcprojectedMBME(), calcprojectedMBMEmpi(), calcprojectedMBMEs(), calcprojectedMBMEsmpi(), calcRadialDensitiesCoordinate(), calcRadialDensitiesMomentum(), calcShellOccupationsod(), calcTimeReversal(), calcTimeReversalod(), initWork(), main(), MinimizeDONLP2(), MinimizeDONLP2orthproj(), MinimizeDONLP2p(), MinimizeDONLP2par(), MinimizeDONLP2proj(), and MinimizeDONLP2vap().
{
  assert(Q->ngauss <= MAXNG*Q->A);
  X->Gaux = malloc(SQR(MAXNG*Q->A)*sizeof(GaussianAux));
  X->n = initcmat(Q->A);
  X->o = initcmat(Q->A);
}
void invertcmSlaterDet (SlaterDet * Q, SlaterDetAux * X)
invert Slater determinant with respect to cm position and velocity
Definition at line 359 of file SlaterDet.c.
References boostSlaterDet(), calcCMPosition(), calcCMVelocity(), calcSlaterDetAux(), invertSlaterDet(), and moveSlaterDet().
Referenced by main().
{
  double Xcm[3], Vcm[3];
  int i;
  calcSlaterDetAux(Q, X);
  calcCMPosition(Q, X, Xcm);
  calcCMVelocity(Q, X, Vcm);
  for (i=0; i<3; i++) {
    Xcm[i] *= -1;
    Vcm[i] *= -1;
  }
  boostSlaterDet(Q, Vcm);
  moveSlaterDet(Q, Xcm);
  invertSlaterDet(Q);
  for (i=0; i<3; i++) {
    Xcm[i] *= -1;
    Vcm[i] *= -1;
  }
  moveSlaterDet(Q, Xcm);
  boostSlaterDet(Q, Vcm);
}
void invertSlaterDet (SlaterDet * Q)
invert Slater determinant in origin
Definition at line 350 of file SlaterDet.c.
References SlaterDet::G, invertGaussian(), and SlaterDet::ngauss.
Referenced by calcConstraintParCh(), calcConstraintParN(), calcConstraintParP(), calcConstraintSxz(), calcConstraintSyz(), calcDensitiesCoordinateParity(), calcgradConstraintParCh(), calcgradConstraintParN(), calcgradConstraintParP(), calcgradConstraintSxz(), calcgradConstraintSyz(), calcgradorthprojectedHamiltonian(), calcgradprojectedHamiltonian(), calcgradprojectedHamiltonianmatrix(), calcObservablesParity(), calcorthprojectedHamiltonian(), calcParity(), calcParityod(), calcprojectedHamiltonian(), calcprojectedHamiltonianmatrix(), calcprojectedMBME(), calcprojectedMBMEs(), calcprojectedMultiMBME(), DiagonalDensityHOSlave(), DiClusterMulticonfigGet(), DiClusterMultiProjSlaterDetGet(), DiClusterProjSlaterDetGet(), ef(), egradf(), egradh(), eh(), FormfactorSlave(), invertcmSlaterDet(), main(), MinimizerprojSlave(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
{
  int i;
  for (i=0; i<Q->ngauss; i++)
    invertGaussian(&Q->G[i]);
}
void joinSlaterDets (const SlaterDet * Qa, const SlaterDet * Qb, SlaterDet * Q)
join Slater determinants Qa and Qb into Q Q will be initialized
Definition at line 211 of file SlaterDet.c.
References SlaterDet::A, SlaterDet::G, SlaterDet::idx, MAXNG, SlaterDet::N, SlaterDet::ng, SlaterDet::ngauss, and SlaterDet::Z.
Referenced by main().
{
  Q->A = Qa->A+Qb->A;
  Q->Z = Qa->Z+Qb->Z;
  Q->N = Qa->N+Qb->N;
  Q->ngauss = Qa->ngauss+Qb->ngauss;
  Q->idx = malloc(Q->A*sizeof(int));
  Q->ng = malloc(Q->A*sizeof(int));
  Q->G = malloc(MAXNG*Q->A*sizeof(Gaussian));
  int i;
  // copy Qa
  for (i=0; i<Qa->A; i++) {
    Q->idx[i] = Qa->idx[i];
    Q->ng[i] = Qa->ng[i];
  }
  for (i=0; i<Qa->ngauss; i++)
    Q->G[i] = Qa->G[i];
  // copy Qb
  for (i=0; i<Qb->A; i++) {
    Q->idx[i+Qa->A] = Qb->idx[i]+Qa->ngauss;
    Q->ng[i+Qa->A] = Qb->ng[i];
  }
  for (i=0; i<Qb->ngauss; i++)
    Q->G[i+Qa->ngauss] = Qb->G[i];
}
void moveboostorientSlaterDet (SlaterDet * Q, SlaterDetAux * X)
move and boost center of mass to origin, orient main axes
Definition at line 310 of file SlaterDet.c.
References alpha, boostSlaterDet(), calcCMPosition(), calcCMVelocity(), calcOrientedOrientation(), calcSlaterDetAux(), moveSlaterDet(), and rotateSlaterDet().
Referenced by main().
{
  int i;
  // move SlaterDet to origin in phase space
  // orient so that min moment of inertia around the z-axes
  double Xcm[3], Vcm[3];
  calcSlaterDetAux(Q, X);
  calcCMPosition(Q, X, Xcm);
  calcCMVelocity(Q, X, Vcm);
  for (i=0; i<3; i++)
    Vcm[i] *= -1;
  for (i=0; i<3; i++)
    Xcm[i] *= -1;
  boostSlaterDet(Q, Vcm);
  moveSlaterDet(Q, Xcm);
  // orient the nucleus along the main axes
  double alpha, beta, gamma;
  calcSlaterDetAux(Q, X);
  calcOrientedOrientation(Q, X, &alpha, &beta, &gamma);
  rotateSlaterDet(Q, -gamma, -beta, -alpha);
}
void moveboostSlaterDet (SlaterDet * Q, SlaterDetAux * X)
move and boost center of mass to origin
Definition at line 273 of file SlaterDet.c.
References boostSlaterDet(), calcCMPosition(), calcCMVelocity(), calcSlaterDetAux(), and moveSlaterDet().
Referenced by ef(), egradf(), egradh(), and eh().
{
  int i;
  // move SlaterDet to origin in phase space
  double Xcm[3], Vcm[3];
  calcSlaterDetAux(Q, X);
  calcCMPosition(Q, X, Xcm);
  calcCMVelocity(Q, X, Vcm);
  for (i=0; i<3; i++)
    Vcm[i] *= -1;
  for (i=0; i<3; i++)
    Xcm[i] *= -1;
  boostSlaterDet(Q, Vcm);
  moveSlaterDet(Q, Xcm);
}
void moveSlaterDet (SlaterDet * Q, double d[3])
move Slater determinant by vector d
Definition at line 255 of file SlaterDet.c.
References SlaterDet::G, moveGaussian(), and SlaterDet::ngauss.
Referenced by calcgradprojectedHamiltonianmatrix(), calcprojectedHamiltonianmatrix(), calcprojectedMBME(), calcprojectedMBMEs(), calcprojectedMultiMBME(), DiagonalDensityHOSlave(), DiClusterMulticonfigGet(), DiClusterMultiProjSlaterDetGet(), DiClusterProjSlaterDetGet(), FormfactorSlave(), invertcmSlaterDet(), main(), MinimizerprojSlave(), moveboostorientSlaterDet(), moveboostSlaterDet(), OneNucleonOvlapsSlave(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
{
  int i;
  for (i=0; i<Q->ngauss; i++)
    moveGaussian(&Q->G[i], d);
}
void normalizeSlaterDet (SlaterDet * Q, SlaterDetAux * X)
normalize SlaterDet
Definition at line 241 of file SlaterDet.c.
References SlaterDet::A, calcSlaterDetAuxod(), Gaussian::chi, SlaterDet::G, SlaterDet::ngauss, and SlaterDetAux::ovlap.
Referenced by main().
{
  calcSlaterDetAuxod(Q, Q, X);
  double norm = sqrt(creal(X->ovlap));
  double normsp = pow(norm, 1.0/Q->A);
  int i;
  for (i=0; i<Q->ngauss; i++) {
    Q->G[i].chi[0] /= normsp;
    Q->G[i].chi[1] /= normsp;
  }
}
void orientSlaterDet (SlaterDet * Q, SlaterDetAux * X)
orient main axes
Definition at line 339 of file SlaterDet.c.
References alpha, calcOrientedOrientation(), calcSlaterDetAux(), and rotateSlaterDet().
Referenced by main().
{
  // orient the nucleus along the main axes
  double alpha, beta, gamma;
  calcSlaterDetAux(Q, X);
  calcOrientedOrientation(Q, X, &alpha, &beta, &gamma);
  rotateSlaterDet(Q, -gamma, -beta, -alpha);
}
int readSlaterDet (FILE * fp, SlaterDet * Q)
read parameters of Slater determinant Q from file Q will be initialized
Definition at line 88 of file SlaterDet.c.
References Gaussian::a, SlaterDet::A, Gaussian::b, BUFSIZE, Gaussian::chi, SlaterDet::G, I, SlaterDet::idx, k, MAXNG, SlaterDet::N, SlaterDet::ng, SlaterDet::ngauss, stripstr(), Gaussian::xi, and SlaterDet::Z.
Referenced by readSlaterDetfromFile(), SimpleSlaterDetRead(), SymmetricMultiSlaterDetRead(), and SymmetricSlaterDetRead().
{
  char buf[BUFSIZE];
  int i;
  do
    fgets(buf, BUFSIZE, fp);
  while (strncmp(buf, "<SlaterDet>", 11) && !feof(fp));
  if (feof(fp)) {
    fprintf(stderr, "did't find <SlaterDet>\n");
    return -1;
  }
  fgets(buf, BUFSIZE, fp);
  if (sscanf(buf, "%d %d %d", &Q->A, &Q->Z, &Q->N) != 3) {
    fprintf(stderr, "malformed line\n>>%s<<\n", stripstr(buf, "\n"));
    return -1;
  }
  if (Q->A != Q->Z+Q->N) {
    fprintf(stderr, "proton and neutron number don't sum up in line\n>>%s<<\n",
            stripstr(buf, "\n"));
    return -1;
  }
  fgets(buf, BUFSIZE, fp);
  if (sscanf(buf, "%d", &Q->ngauss) != 1) {
    fprintf(stderr, "malformed line\n>>%s<<\n", stripstr(buf, "\n"));
    return -1;
  }
  Q->idx = malloc(Q->A*sizeof(int));
  Q->ng = malloc(Q->A*sizeof(int));
  for (i=0; i<Q->A; i++) {
    Q->idx[i] = 0;
    Q->ng[i] = 0;
  }
  Q->G = malloc(MAXNG*Q->A*sizeof(Gaussian));
  int k, xi;
  double chi0re, chi0im, chi1re, chi1im;
  double are, aim, b0re, b0im, b1re, b1im, b2re, b2im;
  for (i=0; i<Q->ngauss; i++) {
    fgets(buf, BUFSIZE, fp);
    if (sscanf(buf, "%d %d "
               "(%lf,%lf) (%lf,%lf) (%lf,%lf) (%lf,%lf) (%lf,%lf) (%lf,%lf)",
               &k, &xi, &chi0re, &chi0im, &chi1re, &chi1im,
               &are, &aim, &b0re, &b0im, &b1re, &b1im, &b2re, &b2im) != 14) {
      fprintf(stderr, "malformed line\n>>%s<<\n",
              stripstr(buf,"\n"));
      return -1;
    }
    Q->ng[k]++;
    Q->G[i].xi = xi;
    Q->G[i].chi[0] = chi0re + I*chi0im;
    Q->G[i].chi[1] = chi1re + I*chi1im;
    Q->G[i].a = are + I*aim;
    Q->G[i].b[0] = b0re + I*b0im;
    Q->G[i].b[1] = b1re + I*b1im;
    Q->G[i].b[2] = b2re + I*b2im;
  }
  for (k=1; k<Q->A; k++)
    Q->idx[k] = Q->idx[k-1]+Q->ng[k-1];
  fgets(buf, BUFSIZE, fp);
  if (strncmp(buf, "</SlaterDet>", 12)) {
    fprintf(stderr, "did't find </SlaterDet>\n");
    return -1;
  }
  return 0;
}
int readSlaterDetfromFile (SlaterDet * Q, const char * fname)
read Slater determinant Q from file Q will be initialized
Definition at line 162 of file SlaterDet.c.
References readSlaterDet().
Referenced by ClusterFMDread(), Clusterread(), ClustersFMDread(), CoreFMDread(), DiClusterMulticonfigRead(), DiClusterMultiProjSlaterDetRead(), DiClusterProjSlaterDetRead(), main(), and readMulticonfigfile().
{
  FILE* fp;
  if (!(fp = fopen(fname, "r"))) {
    fprintf(stderr, "couldn't open %s for reading\n", fname);
    return -1;
  }
  fprintf(stderr, "... reading SlaterDet from file %s\n", fname);
  int err = readSlaterDet(fp, Q);
  fclose(fp);
  return err;
}
void rotateSlaterDet (SlaterDet * Q, double alpha, double beta, double gamma)
rotate Slater determinant by euler angles
Definition at line 294 of file SlaterDet.c.
References SlaterDet::G, SlaterDet::ngauss, rotateGaussian(), rotatemat2(), and rotatemat3().
Referenced by _estimateangkappa(), calcConstraintD3H(), calcConstraintSxz(), calcConstraintSyz(), calcgradConstraintD3H(), calcgradConstraintSxz(), calcgradConstraintSyz(), calcgradorthprojectedHamiltonian(), calcgradprojectedHamiltonian(), calcgradprojectedHamiltonianmatrix(), calcorthprojectedHamiltonian(), calcprojectedHamiltonian(), calcprojectedHamiltonianmatrix(), calcprojectedMBME(), calcprojectedMBMEs(), calcprojectedMultiMBME(), DiagonalDensityHOSlave(), DiClusterMulticonfigGet(), DiClusterMultiProjSlaterDetGet(), DiClusterProjSlaterDetGet(), FormfactorSlave(), main(), MinimizerprojSlave(), moveboostorientSlaterDet(), OneNucleonOvlapsSlave(), orientSlaterDet(), ProjectionSlave(), and TwoNucleonOvlapsSlave().
{
  double euler[3] = { a, b, g };
  complex double R2[2][2];
  rotatemat2(euler, R2);
  double R3[3][3];
  rotatemat3(euler, R3);
  int i;
  for (i=0; i<Q->ngauss; i++)
    rotateGaussian(&Q->G[i], R3, R2);
}
void scaleSlaterDet (SlaterDet * Q, double kappa)
scale Slater determinant
Definition at line 396 of file SlaterDet.c.
References SlaterDet::G, SlaterDet::ngauss, and scaleGaussian().
Referenced by main().
{
  int i;
  for (i=0; i<Q->ngauss; i++)
    scaleGaussian(&Q->G[i], kappa);
}
void timerevertSlaterDet (SlaterDet * Q)
time revert Slater determinant
Definition at line 387 of file SlaterDet.c.
References SlaterDet::G, SlaterDet::ngauss, and timerevertGaussian().
Referenced by calcTimeReversal(), calcTimeReversalod(), and main().
{
  int i;
  for (i=0; i<Q->ngauss; i++)
    timerevertGaussian(&Q->G[i]);
}
void writeSlaterDet (FILE * fp, const SlaterDet * Q)
write parameters of Slater determinant Q in file
Definition at line 61 of file SlaterDet.c.
References Gaussian::a, SlaterDet::A, Gaussian::b, Gaussian::chi, SlaterDet::G, SlaterDet::idx, k, SlaterDet::N, SlaterDet::ng, SlaterDet::ngauss, Gaussian::xi, and SlaterDet::Z.
Referenced by egradf(), and main().
{
  int k, i, idx;
  fprintf(fp, "<SlaterDet>\n");
  fprintf(fp, "%d %d %d\n", Q->A, Q->Z, Q->N);
  fprintf(fp, "%d\n", Q->ngauss);
  for (k=0; k<Q->A; k++)
    for (i=0; i<Q->ng[k]; i++) {
      idx = Q->idx[k]+i;
      fprintf(fp,
              "%2d  %+2d  (%12.8f,%12.8f)(%12.8f,%12.8f)  (%12.8f,%12.8f)  (%12.8f,%12.8f)(%12.8f,%12.8f)(%12.8f,%12.8f)\n",
            k, Q->G[idx].xi,
            creal(Q->G[idx].chi[0]), cimag(Q->G[idx].chi[0]),
            creal(Q->G[idx].chi[1]), cimag(Q->G[idx].chi[1]),
            creal(Q->G[idx].a), cimag(Q->G[idx].a),
            creal(Q->G[idx].b[0]), cimag(Q->G[idx].b[0]),
            creal(Q->G[idx].b[1]), cimag(Q->G[idx].b[1]),
            creal(Q->G[idx].b[2]), cimag(Q->G[idx].b[2]));
  }
  fprintf(fp, "</SlaterDet>\n");
}