FMD: fmd/SpatialOrientation.c File Reference
fmd/SpatialOrientation.c File Reference
#include <math.h>
#include <complex.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "CenterofMass.h"
#include "AngularMomenta.h"
#include "SpatialOrientation.h"
#include "numerics/cmath.h"
#include "numerics/lapack.h"
Functions
void calcInertiaTensor (const SlaterDet *Q, const SlaterDetAux *X, double T[9])
calculate mass inertia tensor
void calcOctupoleTensor (const SlaterDet *Q, const SlaterDetAux *X, double O[27])
void calcSpatialOrientation (const SlaterDet *Q, const SlaterDetAux *X, double *alpha, double *beta, double *gamma)
void calcOrientedOrientation (const SlaterDet *Q, const SlaterDetAux *X, double *alpha, double *beta, double *gamma)
void calcSpinOrientation (const SlaterDet *Q, const SlaterDetAux *X, double *alpha, double *beta, double *gamma)
spin orientation with respect to z-axis
Detailed Description
determine euler angles of spatial orientation by diagonalizing the inertia tensor
determine euler angles of intrinsic coordinate system by diagonalizing the < Ji Jj > tensor
(c) 2003 Thomas Neff
Definition in file SpatialOrientation.c.
Function Documentation
void calcInertiaTensor (const SlaterDet * Q, const SlaterDetAux * X, double T[9])
calculate mass inertia tensor
Definition at line 49 of file SpatialOrientation.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, and par.
Referenced by calcOrientedOrientation(), calcSpatialOrientation(), and main().
{
  double Xcm[3];
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_inertia = { dim: 9, opt: 1, par: Xcm, me: ob_inertia};
  calcSlaterDetOBME(Q, X, &op_ob_inertia, T);
}
void calcOctupoleTensor (const SlaterDet * Q, const SlaterDetAux * X, double O[27])
Definition at line 86 of file SpatialOrientation.c.
References calcCMPosition(), calcSlaterDetOBME(), dim, and par.
Referenced by calcOrientedOrientation().
{
  double Xcm[3];
  calcCMPosition(Q, X, Xcm);
  OneBodyOperator op_ob_octupole = {dim: 27, opt: 1, par: Xcm, me: ob_octupole};
  calcSlaterDetOBME(Q, X, &op_ob_octupole, O);
}
void calcOrientedOrientation (const SlaterDet * Q, const SlaterDetAux * X, double * alpha, double * beta, double * gamma)
Definition at line 198 of file SpatialOrientation.c.
References calcInertiaTensor(), calcOctupoleTensor(), dsyev(), FORTRAN, and N.
Referenced by calcgradorthprojectedHamiltonian(), calcgradprojectedHamiltonian(), calcorthprojectedHamiltonian(), calcprojectedHamiltonian(), main(), moveboostorientSlaterDet(), and orientSlaterDet().
{
  double T[3][3];
  double O[3][3][3];
  int i,j,k;
  calcInertiaTensor(Q, X, T);
  calcOctupoleTensor(Q, X, O);
  char JOBZ='V';
  char UPLO='U';
  int N=3;
  double W[3];
  double WORK[15];
  int LWORK=15;
  int INFO;
  FORTRAN(dsyev)(&JOBZ, &UPLO, &N, (double*)T, &N, W, WORK, &LWORK, &INFO);
  // axis with smallest eigenvalue to become z axis
  int imin=0;
  double minw=fabs(W[0]);
  for (i=1; i<3; i++)
    if (fabs(W[i]) < minw) {
      imin = i;
      minw = fabs(W[i]);
    }
  // align z-axis with symmetry axis
  double dummy;
  for (i=0; i<3; i++) {
    dummy = T[2][i];
    T[2][i] = T[imin][i];
    T[imin][i] = dummy;
  }
  // we want a pure rotation
  if (det(T) < 0.0)
    for (i=0; i<3; i++)
      T[0][i] *= -1;
  // inertia tensor is invariant under Ry(180deg)
  // use sign of octupole moment to select orientation
  double Ozzz = 0.0;
  for (i=0; i<3; i++)
    for (j=0; j<3; j++)
      for (k=0; k<3; k++)
        Ozzz += T[2][i]*T[2][j]*T[2][k]*O[i][j][k];
  fprintf(stderr, "... Ozzz: %8.5f\n", Ozzz);
  // Ry(180deg)
  if (Ozzz < 0.0) {
    for (i=0; i<3; i++) {
      T[0][i] *= -1;
      T[2][i] *= -1;
    }
  }
  RotationMatrixToEulerAngles(T, alpha, beta, gamma);
}
void calcSpatialOrientation (const SlaterDet * Q, const SlaterDetAux * X, double * alpha, double * beta, double * gamma)
calculate euler angles to describe orientation of mass distribution Slater determinant center of mass should be in origin
Definition at line 145 of file SpatialOrientation.c.
References calcInertiaTensor(), dsyev(), FORTRAN, and N.
Referenced by main().
{
  double T[3][3];
  calcInertiaTensor(Q, X, T);
  char JOBZ='V';
  char UPLO='U';
  int N=3;
  double W[3];
  double WORK[15];
  int LWORK=15;
  int INFO;
  FORTRAN(dsyev)(&JOBZ, &UPLO, &N, (double*)T, &N, W, WORK, &LWORK, &INFO);
  // align supposed symmetry axis with z axis
  int i;
  double maxe=0.0;
  for (i=0; i<3; i++)
    maxe = fmax(maxe, fabs(W[i]));
  double dif[3], mindif = 1.0;
  int imin=-1;
  for (i=0; i<3; i++) {
    dif[i] = fabs(W[(i+1)%3]-W[(i+2)%3])/maxe;
    if (dif[i] < mindif) {
      mindif = dif[i];
      imin = i;
    }
  }
  // align z-axis with symmetry axis
  double dummy;
  for (i=0; i<3; i++) {
    dummy = T[2][i];
    T[2][i] = T[imin][i];
    T[imin][i] = dummy;
  }
  if (det(T) < 0.0)
    for (i=0; i<3; i++)
      T[0][i] *= -1;
  RotationMatrixToEulerAngles(T, alpha, beta, gamma);
}
void calcSpinOrientation (const SlaterDet * Q, const SlaterDetAux * X, double * alpha, double * beta, double * gamma)
spin orientation with respect to z-axis
Definition at line 266 of file SpatialOrientation.c.
References calcJ(), and J2.
Referenced by main().
{
  double J[3];
  calcJ(Q, X, J);
  double Jxy=sqrt(J[0]*J[0]+J[1]*J[1]);
  double J2=sqrt(J[0]*J[0]+J[1]*J[1]+J[2]*J[2]);
  *alpha = (J[1] > 0.0 ? +1 : -1)* acos(J[0]/Jxy);
  *beta = acos(J[2]/J2);
  *gamma = 0.0;
}