FMD: numerics/sphericalbessel.h File Reference
numerics/sphericalbessel.h File Reference
#include <complex.h>
Functions
double besselj0 (double x)
complex double cbesselj0 (complex double x)
void besseljs (int lmax, double x, double *jl)
void cbesseljs (int lmax, complex double x, complex double *jl)
double besseli0 (double x)
complex double cbesseli0 (complex double x)
void besselis (int lmax, double x, double *il)
void cbesselis (int lmax, complex double x, complex double *il)
Detailed Description
Spherical Bessel Functions j_l(x) and i_l(x) = i^(-l) j_l(i x)
(c) 2012 Thomas Neff
Definition in file sphericalbessel.h.
Function Documentation
double besseli0 (double x)
Definition at line 120 of file sphericalbessel.c.
References SQR.
{
  const double EPSILON = 1E-8;
  if (fabs(x) < EPSILON)
    return(1.0 + SQR(x)/6.0);
  else
    return sinh(x)/x;
}
void besselis (int lmax, double x, double * il)
Definition at line 147 of file sphericalbessel.c.
References l, and SQR.
{
  const double EPSILON = 0.5;
  double x2 = SQR(x);
  // Taylor expansion for small x
  if (fabs(x) < EPSILON) {
    il[0] = 1.0 + x2/6.0* (1.0+x2/20.0);
    for (int l=1; l<=lmax; l++)
      il[l] = il[l-1]*x/(2*l+1)*(1.0-x2/((2l+1)*(2l+3))*(1.0-x2/((2l+1)*(2l+5))));
  } else {
    il[0] = sinh(x)/x;
    if (lmax==0) return;
    il[1] = -(sinh(x)-x*cosh(x))/x2;
    for (int l=2; l<=lmax; l++)
      il[l] = -(2*l-1)*il[l-1]/x+il[l-2];
  }
}
double besselj0 (double x)
Definition at line 27 of file sphericalbessel.c.
References SQR.
Referenced by writeChargeDensities(), writeMatterDensities(), writePointDensities(), writeTransitionChargeDensities(), and writeTransitionPointDensities().
{
  const double EPSILON = 1E-8;
  if (fabs(x) < EPSILON)
    return (1.0 - SQR(x)/6.0);
  else
    return sin(x)/x;
}
void besseljs (int lmax, double x, double * jl)
Definition at line 53 of file sphericalbessel.c.
References l, and SQR.
{
  const double EPSILON = 0.5;
  double x2 = SQR(x);
  // low order Taylor for small x
  if (fabs(x) < EPSILON) {
    jl[0] = 1.0 - x2/6.0* (1.0+x2/20.0);
    for (int l=1; l<=lmax; l++)
      jl[l] = jl[l-1]*x/(2*l+1) *(1.0+x2/((2l+1)*(2l+3))* (1.0+x2/((2l+1)*(2l+5))));
  } else {
    jl[0] = sin(x)/x;
    if (lmax==0) return;
    jl[1] = (sin(x)-x*cos(x))/SQR(x);
    for (int l=2; l<=lmax; l++)
      jl[l] = (2*l-1)*jl[l-1]/x-jl[l-2];
  }
}
complex double cbesseli0 (complex double x)
Definition at line 131 of file sphericalbessel.c.
References SQR.
{
  const double EPSILON = 1E-8;
  if (cabs(x) < EPSILON)
    return(1.0 + SQR(x)/6.0);
  else
    return csinh(x)/x;
}
void cbesselis (int lmax, complex double x, complex double * il)
Definition at line 167 of file sphericalbessel.c.
References l, and SQR.
{
  const double EPSILON = 0.5;
  complex double x2 = SQR(x);
  // Taylor expansion for small x
  if (cabs(x) < EPSILON) {
    il[0] = 1.0 + x2/6.0* (1.0+x2/20.0);
    for (int l=1; l<=lmax; l++)
      il[l] = il[l-1]*x/(2*l+1)*(1.0-x2/((2l+1)*(2l+3))*(1.0-x2/((2l+1)*(2l+5))));
  } else {
    il[0] = csinh(x)/x;
    if (lmax==0) return;
    il[1] = -(csinh(x)-x*ccosh(x))/x2;
    for (int l=2; l<=lmax; l++)
      il[l] = -(2*l-1)*il[l-1]/x+il[l-2];
  }
}
complex double cbesselj0 (complex double x)
Definition at line 38 of file sphericalbessel.c.
References SQR.
{
  const double EPSILON = 1E-8;
  if (cabs(x) < EPSILON)
    return (1.0 - SQR(x)/6.0);
  else
    return csin(x)/x;
}
void cbesseljs (int lmax, complex double x, complex double * jl)
Definition at line 73 of file sphericalbessel.c.
References l, and SQR.
{
  const double EPSILON = 0.5;
  complex double x2 = SQR(x);
  // low order Taylor for small x
  if (cabs(x) < EPSILON) {
    jl[0] = 1.0 - x2/6.0* (1.0+x2/20.0);
    for (int l=1; l<=lmax; l++)
      jl[l] = jl[l-1]*x/(2*l+1) *(1.0+x2/((2l+1)*(2l+3))* (1.0+x2/((2l+1)*(2l+5))));
  } else {
    jl[0] = csin(x)/x;
    if (lmax==0) return;
    jl[1] = (csin(x)-x*ccos(x))/SQR(x);
    for (int l=2; l<=lmax; l++)
      jl[l] = (2*l-1)*jl[l-1]/x-jl[l-2];
  }
}