FMD: fmd/SpinDensities.h File Reference
fmd/SpinDensities.h File Reference
Functions
void calcSpinDensitiesCoordinate (const SlaterDet *Q, const SlaterDetAux *X, int v, int n, double x, double *dens)
void calcSpinDensitiesMomentum (const SlaterDet *Q, const SlaterDetAux *X, int v, int n, double p, double *dens)
Detailed Description
calculate one-body spin densities in coordinate and momentum space
(c) 2003 Thomas Neff
Definition in file SpinDensities.h.
Function Documentation
void calcSpinDensitiesCoordinate (const SlaterDet * Q, const SlaterDetAux * X, int v, int n, double x, double * dens)
Definition at line 110 of file SpinDensities.c.
References calcSlaterDetOBME(), dim, and P.
Referenced by main().
{
  densparameters P = { normal: v, npoints: n, range: x };
  OneBodyOperator op_ob_dens = {dim: 3*n*n, opt: 1, par: &P, me: ob_spindensx};
  calcSlaterDetOBME(Q, X, &op_ob_dens, dens);
}
void calcSpinDensitiesMomentum (const SlaterDet * Q, const SlaterDetAux * X, int v, int n, double p, double * dens)
Definition at line 120 of file SpinDensities.c.
References calcSlaterDetOBME(), dim, and P.
Referenced by main().
{
  densparameters P = { normal: v, npoints: n, range: p };
  OneBodyOperator op_ob_dens = {dim: 3*n*n, opt: 1, par: &P, me: ob_spindensp};
  calcSlaterDetOBME(Q, X, &op_ob_dens, dens);
}