FMD: Constraintod Struct Reference
Constraintod Struct Reference
#include <Constraint.h>
Data Fields
double val
char * label
int dim
int gradneedsme
void(* me)(const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *mes)
void(* gradme)(const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *mes, gradSlaterDet *dval)
double(* output)(double val)
Detailed Description
Definition at line 30 of file Constraint.h.
Field Documentation
int Constraintod::dim
Definition at line 33 of file Constraint.h.
Referenced by egradh(), and eh().
void(* Constraintod::gradme)(const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, const gradSlaterDetAux *dX, const double *mes, gradSlaterDet *dval)
Definition at line 37 of file Constraint.h.
Referenced by egradh().
int Constraintod::gradneedsme
Definition at line 34 of file Constraint.h.
Referenced by egradh().
char* Constraintod::label
Definition at line 32 of file Constraint.h.
Referenced by egradh().
void(* Constraintod::me)(const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *mes)
Definition at line 35 of file Constraint.h.
Referenced by egradh(), and eh().
double(* Constraintod::output)(double val)
Definition at line 42 of file Constraint.h.
Referenced by egradh().
double Constraintod::val
Definition at line 31 of file Constraint.h.
Referenced by eh(), and main().
The documentation for this struct was generated from the following file:
fmd/Constraint.h