FMD: Constraint Struct Reference
Constraint Struct Reference
#include <Constraint.h>
Data Fields
double val
char * label
void(* me)(const SlaterDet *Q, const SlaterDetAux *X, double *val)
void(* gradme)(const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dval)
double(* output)(double val)
Detailed Description
Definition at line 20 of file Constraint.h.
Field Documentation
void(* Constraint::gradme)(const SlaterDet *Q, const SlaterDetAux *X, const gradSlaterDetAux *dX, gradSlaterDet *dval)
Definition at line 24 of file Constraint.h.
Referenced by egradh().
char* Constraint::label
Definition at line 22 of file Constraint.h.
Referenced by egradh().
void(* Constraint::me)(const SlaterDet *Q, const SlaterDetAux *X, double *val)
Definition at line 23 of file Constraint.h.
Referenced by eh().
double(* Constraint::output)(double val)
Definition at line 26 of file Constraint.h.
Referenced by egradh().
double Constraint::val
Definition at line 21 of file Constraint.h.
Referenced by main().
The documentation for this struct was generated from the following file:
fmd/Constraint.h