FMD: ClusterInternals Struct Reference
ClusterInternals Struct Reference
Data Fields
int ncluster
char(* clusterfname)[255]
char(* clusterfmd5hash)[255]
SlaterDet * cluster
Detailed Description
Definition at line 35 of file ParameterizationCluster.c.
Field Documentation
SlaterDet* ClusterInternals::cluster
Definition at line 39 of file ParameterizationCluster.c.
Referenced by Clusterclone(), ClusterinitSlaterDet(), ClusterprojectgradSlaterDet(), Clusterread(), and ClustertoSlaterDet().
char(* ClusterInternals::clusterfmd5hash)[255]
Definition at line 38 of file ParameterizationCluster.c.
Referenced by Clusterclone(), Clusterread(), and Clusterwrite().
char(* ClusterInternals::clusterfname)[255]
Definition at line 37 of file ParameterizationCluster.c.
Referenced by Clusterclone(), Clusterread(), and Clusterwrite().
int ClusterInternals::ncluster
Definition at line 36 of file ParameterizationCluster.c.
Referenced by Clusterclone(), ClusterinitSlaterDet(), ClusterprojectgradSlaterDet(), Clusterread(), ClustertoSlaterDet(), and Clusterwrite().
The documentation for this struct was generated from the following file:
fmd/ParameterizationCluster.c