FMD: Parameterization Struct Reference
Parameterization Struct Reference
(virtual) Parameterization of a Slater determinant.
#include <Parameterization.h>
Data Fields
char * name
its name
int(* Pararead)(FILE *fp, Para *q)
read parameters from file
int(* Parawrite)(FILE *fp, const Para *q)
write parameters to file
void(* Paraclone)(const Para *q, Para *qp)
clone parameters
void(* ParainitSlaterDet)(const Para *q, SlaterDet *Q)
init Slater determinant with the parameters
void(* ParatoSlaterDet)(const Para *q, SlaterDet *Q)
convert paramaters to Slater determinant
void(* ParaprojectgradSlaterDet)(const Para *q, const gradSlaterDet *dQ, double *dq)
project Slater determinant gradient to paramater gradient
Detailed Description
(virtual) Parameterization of a Slater determinant.
Definition at line 38 of file Parameterization.h.
Field Documentation
char* Parameterization::name
its name
Definition at line 39 of file Parameterization.h.
Referenced by main().
void(* Parameterization::Paraclone)(const Para *q, Para *qp)
clone parameters
Definition at line 47 of file Parameterization.h.
Referenced by main().
void(* Parameterization::ParainitSlaterDet)(const Para *q, SlaterDet *Q)
init Slater determinant with the parameters
Definition at line 50 of file Parameterization.h.
Referenced by main(), MinimizeDONLP2multivapp(), MinimizeDONLP2orthogonalvapp(), MinimizeDONLP2vapp(), and MinimizeDONLP2vappiso().
void(* Parameterization::ParaprojectgradSlaterDet)(const Para *q, const gradSlaterDet *dQ, double *dq)
project Slater determinant gradient to paramater gradient
Definition at line 54 of file Parameterization.h.
Referenced by main().
int(* Parameterization::Pararead)(FILE *fp, Para *q)
read parameters from file
Definition at line 42 of file Parameterization.h.
Referenced by readParafromFile().
void(* Parameterization::ParatoSlaterDet)(const Para *q, SlaterDet *Q)
convert paramaters to Slater determinant
Definition at line 52 of file Parameterization.h.
Referenced by main().
int(* Parameterization::Parawrite)(FILE *fp, const Para *q)
write parameters to file
Definition at line 44 of file Parameterization.h.
Referenced by main().
The documentation for this struct was generated from the following file:
fmd/Parameterization.h