FMD: fmd/Symmetry.h File Reference
fmd/Symmetry.h File Reference
Typedefs
typedef unsigned int Symmetry
Enumerations
enum {
parity0 = 0, parity1, spherical, axial = 3,
axial0 = 4, axial1, axial2, axial3,
axial4, axial5, axial6, axial7,
axial8, axial9, rotatez2 = 16, rotatez3,
rotatey1 = 20, reflectxy = 24, reflectxz
}
encode the symmetries as bits in an integer
Functions
int SymmetryAllowed (Symmetry S, int pi, int j, int k)
quantum numbers J^pi,K allowed by symmetry ?
void extractSymmetryfromString (char **str, Symmetry *S)
char * SymmetrytoStr (Symmetry S)
get String with Symmetry
Detailed Description
Symmetries and Selection Rules for intrinsic states
(c) 2005 Thomas Neff
Definition in file Symmetry.h.
Typedef Documentation
typedef unsigned int Symmetry
Definition at line 28 of file Symmetry.h.
Enumeration Type Documentation
anonymous enum
encode the symmetries as bits in an integer
Enumerator:
parity0
parity1
spherical
axial
axial0
axial1
axial2
axial3
axial4
axial5
axial6
axial7
axial8
axial9
rotatez2
rotatez3
rotatey1
reflectxy
reflectxz
Definition at line 19 of file Symmetry.h.
     { parity0=0, parity1, spherical,
       axial=3,                                   // indicates any of axialx
       axial0=4, axial1, axial2, axial3, axial4,
       axial5, axial6, axial7, axial8, axial9,
       rotatez2=16, rotatez3,
       rotatey1=20,
       reflectxy=24,
       reflectxz };
Function Documentation
void extractSymmetryfromString (char ** str, Symmetry * S)
get Symmetry from string 'SYMMETRY:FILENAME' return pointer to FILENAME
Definition at line 41 of file Symmetry.c.
References axial0, axial1, axial2, axial3, axial4, parity0, parity1, reflectxy, reflectxz, rotatey1, rotatez2, rotatez3, and spherical.
Referenced by main(), SymmetricMultiSlaterDetRead(), and SymmetricSlaterDetRead().
{
  *S = 0;
  char *c, *s = *str;
  while (1) {
    c = strtok(s, ": >");
    if (c == NULL) {
      *str = c;
      return;
    }
    if (!strcmp(c, "parity0")) setSymmetry(S, parity0);
    else if (!strcmp(c, "parity1")) setSymmetry(S, parity1);
    else if (!strcmp(c, "spherical")) setSymmetry(S, spherical);
    else if (!strcmp(c, "axial0")) setSymmetry(S, axial0);
    else if (!strcmp(c, "axial1")) setSymmetry(S, axial1);
    else if (!strcmp(c, "axial2")) setSymmetry(S, axial2);
    else if (!strcmp(c, "axial3")) setSymmetry(S, axial3);
    else if (!strcmp(c, "axial4")) setSymmetry(S, axial4);
    else if (!strcmp(c, "rotatez2")) setSymmetry(S, rotatez2);
    else if (!strcmp(c, "rotatez3")) setSymmetry(S, rotatez3);
    else if (!strcmp(c, "rotatey1")) setSymmetry(S, rotatey1);
    else if (!strcmp(c, "reflectxz")) setSymmetry(S, reflectxz);
    else if (!strcmp(c, "reflectxy")) setSymmetry(S, reflectxy);
    else {
      *str = c;
      return;
    }
    s = NULL;
  }
}
int SymmetryAllowed (Symmetry S, int pi, int j, int k)
quantum numbers J^pi,K allowed by symmetry ?
Definition at line 19 of file Symmetry.c.
References axial0, axial1, axial2, axial3, axial4, parity0, parity1, rotatez2, rotatez3, and spherical.
Referenced by calcexpectprojectedMBME(), calcexpectprojectedMBMEipj(), calcexpectprojectedMultiMBME(), calcprojectedMBME(), calcprojectedMBMEmpi(), calcprojectedMBMEs(), calcprojectedMBMEsmpi(), calcprojectedMultiMBME(), calcprojectedMultiMBMEmpi(), calctransitionprojectedMBME(), calctransitionprojectedMBMEipj(), calctransitionprojectedMultiMBME(), readprojectedMBME(), and writeprojectedMBME().
{
  if (sym==0) return 1;
  if (hasSymmetry(sym, spherical) && (j!=0 || pi==1)) return 0;
  if (hasSymmetry(sym, parity0) && pi==1) return 0;
  if (hasSymmetry(sym, parity1) && pi==0) return 0;
  if (hasSymmetry(sym, axial0) && k!=0) return 0;
  if (hasSymmetry(sym, axial1) && k!=1) return 0;
  if (hasSymmetry(sym, axial2) && k!=2) return 0;
  if (hasSymmetry(sym, axial3) && k!=3) return 0;
  if (hasSymmetry(sym, axial4) && k!=4) return 0;
  if (hasSymmetry(sym, rotatez2) && k%4) return 0;
  if (hasSymmetry(sym, rotatez3) && k%6) return 0;
  // if (hasSymmetry(sym, rotatey1 && ) return 0;
  // if (hasSymmetry(sym, reflectxz) && k==0 &&
  //    (j%4 && pi==0 || !(j%4) && pi==1)) return 0;
  return 1;
}
char* SymmetrytoStr (Symmetry S)
get String with Symmetry
Definition at line 76 of file Symmetry.c.
References axial, axial0, axial1, axial2, axial3, axial4, parity0, parity1, reflectxy, reflectxz, rotatez2, rotatez3, and spherical.
Referenced by calcprojectedMultiMBME(), calcprojectedMultiMBMEmpi(), main(), readprojectedMBMEfromFile(), and writeprojectedMBMEtoFile().
{
  char* str;
  str = malloc(40*sizeof(char));
  if (S==0) sprintf(str, "%s", "none");
  if (hasSymmetry(S, parity0))   sprintf(str, "%s", "parity0");
  if (hasSymmetry(S, parity1))   sprintf(str, "%s", "parity1");
  if (hasSymmetry(S, spherical)) sprintf(str, "%s", "spherical");
  if (hasSymmetry(S, axial))     sprintf(str, "%s", "axial");
  if (hasSymmetry(S, axial0))    sprintf(str, "%s", "axial0");
  if (hasSymmetry(S, axial1))    sprintf(str, "%s", "axial1");
  if (hasSymmetry(S, axial2))    sprintf(str, "%s", "axial2");
  if (hasSymmetry(S, axial3))    sprintf(str, "%s", "axial3");
  if (hasSymmetry(S, axial4))    sprintf(str, "%s", "axial4");
  if (hasSymmetry(S, rotatez2))  sprintf(str, "%s", "rotatez2");
  if (hasSymmetry(S, rotatez3))  sprintf(str, "%s", "rotatez3");
  if (hasSymmetry(S, reflectxz)) sprintf(str, "%s", "reflectxy");
  if (hasSymmetry(S, reflectxy)) sprintf(str, "%s", "reflectxz");
  return str;
}