FMD: fmd/SymmetricMultiSlaterDet.c File Reference
fmd/SymmetricMultiSlaterDet.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <complex.h>
#include <math.h>
#include "SlaterDet.h"
#include "Symmetry.h"
#include "MultiSlaterDet.h"
#include "SymmetricMultiSlaterDet.h"
#include "misc/utils.h"
Data Structures
struct SymmetricMultiSlaterDetInternals
Functions
Symmetry SymmetricMultiSlaterDetSymmetry (const MultiSlaterDet *MB, int iM)
complex double SymmetricMultiSlaterDetWeight (const MultiSlaterDet *MB, int iM, int i)
void SymmetricMultiSlaterDetGet (const MultiSlaterDet *MB, int i, SlaterDet *Q)
int SymmetricMultiSlaterDetRead (FILE *fp, MultiSlaterDet *MB)
Variables
MultiSlaterDet SymmetricMultiSlaterDet
some fields have to be initialized later
Detailed Description
implement multiconfig state as MultiSlaterDet
(c) 2006 Thomas Neff
Definition in file SymmetricMultiSlaterDet.c.
Function Documentation
void SymmetricMultiSlaterDetGet (const MultiSlaterDet * MB, int i, SlaterDet * Q)
Definition at line 64 of file SymmetricMultiSlaterDet.c.
References copySlaterDet(), _MSD_::internals, and SymmetricMultiSlaterDetInternals::Q.
{
  SymmetricMultiSlaterDetInternals* internals = MB->internals;
  copySlaterDet(&internals->Q[i], Q);
}
int SymmetricMultiSlaterDetRead (FILE * fp, MultiSlaterDet * MB)
Definition at line 72 of file SymmetricMultiSlaterDet.c.
References SlaterDet::A, _MSD_::A, extractSymmetryfromString(), I, _MSD_::internals, _MSD_::n, n, SymmetricMultiSlaterDetInternals::Q, readSlaterDet(), SymmetricMultiSlaterDetInternals::S, and SymmetricMultiSlaterDetInternals::w.
Referenced by readMultiSlaterDetfromFile().
{
  *MB = SymmetricMultiSlaterDet;
  SymmetricMultiSlaterDetInternals* internals =
    malloc(sizeof(SymmetricMultiSlaterDetInternals));
  char buf[1024];
  fgets(buf, 1024, fp);
  int n;
  char sym[255]; char* s=sym;
  sscanf(buf, "<SymmetricMultiSlaterDet n=%d Sym=%s>", &n, sym);
  extractSymmetryfromString(&s, &internals->S);
  MB->n = n;
  internals->Q = malloc(n*sizeof(SlaterDet));
  internals->w = malloc(n*sizeof(complex double));
  do
    fgets(buf, 1024, fp);
  while (strncmp(buf, "<Weights", 8));
  int i;
  double wre, wim;
  char* c = strtok(buf+8, ", ()");
  for (i=0; i<n; i++) {
    wre=atof(c); c=strtok(NULL, " ,()");
    wim=atof(c); c=strtok(NULL, " ,()");
    internals->w[i] = wre+I*wim;
  }
  int ret=0;
  for (i=0; i<n; i++)
    ret |= readSlaterDet(fp, &internals->Q[i]);
  MB->A = internals->Q[0].A;
  MB->internals = internals;
  return ret;
}
Symmetry SymmetricMultiSlaterDetSymmetry (const MultiSlaterDet * MB, int iM)
Definition at line 48 of file SymmetricMultiSlaterDet.c.
References _MSD_::internals, and SymmetricMultiSlaterDetInternals::S.
{
  SymmetricMultiSlaterDetInternals* internals = MB->internals;
  return internals->S;
}
complex double SymmetricMultiSlaterDetWeight (const MultiSlaterDet * MB, int iM, int i)
Definition at line 56 of file SymmetricMultiSlaterDet.c.
References _MSD_::internals, and SymmetricMultiSlaterDetInternals::w.
{
  SymmetricMultiSlaterDetInternals* internals = MB->internals;
  return internals->w[i];
}
Variable Documentation
MultiSlaterDet SymmetricMultiSlaterDet
Initial value:
 {
  A : 0,
  N : 1,
  n : 0,
  symmetry : SymmetricMultiSlaterDetSymmetry,
  weight : SymmetricMultiSlaterDetWeight,
  get : SymmetricMultiSlaterDetGet,
  internals : NULL
}
some fields have to be initialized later
Definition at line 37 of file SymmetricMultiSlaterDet.c.