FMD: fmd/SymmetricSlaterDet.c File Reference
fmd/SymmetricSlaterDet.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "SlaterDet.h"
#include "Symmetry.h"
#include "MultiSlaterDet.h"
#include "SymmetricSlaterDet.h"
#include "misc/utils.h"
Data Structures
struct SymmetricSlaterDetInternals
Functions
Symmetry SymmetricSlaterDetSymmetry (const MultiSlaterDet *MB, int iM)
complex double SymmetricSlaterDetWeight (const MultiSlaterDet *MB, int iM, int i)
void SymmetricSlaterDetGet (const MultiSlaterDet *MB, int i, SlaterDet *Q)
int SymmetricSlaterDetRead (FILE *fp, MultiSlaterDet *MB)
Variables
MultiSlaterDet SymmetricSlaterDet
some fields have to be initialized later
Detailed Description
implement SymmetricSlaterDet as MultiSlaterDet
only parity for the start
(c) 2005
Definition in file SymmetricSlaterDet.c.
Function Documentation
void SymmetricSlaterDetGet (const MultiSlaterDet * MB, int i, SlaterDet * Q)
Definition at line 61 of file SymmetricSlaterDet.c.
References copySlaterDet(), _MSD_::internals, and SymmetricSlaterDetInternals::Q.
{
  SymmetricSlaterDetInternals* internals = MB->internals;
  copySlaterDet(internals->Q, Q);
}
int SymmetricSlaterDetRead (FILE * fp, MultiSlaterDet * MB)
Definition at line 69 of file SymmetricSlaterDet.c.
References SlaterDet::A, _MSD_::A, extractSymmetryfromString(), _MSD_::internals, SymmetricSlaterDetInternals::Q, readSlaterDet(), and SymmetricSlaterDetInternals::S.
Referenced by readMultiSlaterDetfromFile().
{
  *MB = SymmetricSlaterDet;
  SymmetricSlaterDetInternals* internals =
    malloc(sizeof(SymmetricSlaterDetInternals));
  internals->Q = malloc(sizeof(SlaterDet));
  char buf[1024];
  fgets(buf, 1024, fp);
  char sym[255]; char* s=sym;
  sscanf(buf, "<SymmetricSlaterDet Sym=%s>", sym);
  extractSymmetryfromString(&s, &internals->S);
  int ret;
  ret = readSlaterDet(fp, internals->Q);
  MB->A = internals->Q->A;
  MB->internals = internals;
  return ret;
}
Symmetry SymmetricSlaterDetSymmetry (const MultiSlaterDet * MB, int iM)
Definition at line 47 of file SymmetricSlaterDet.c.
References _MSD_::internals, and SymmetricSlaterDetInternals::S.
{
  SymmetricSlaterDetInternals* internals = MB->internals;
  return internals->S;
}
complex double SymmetricSlaterDetWeight (const MultiSlaterDet * MB, int iM, int i)
Definition at line 55 of file SymmetricSlaterDet.c.
{
  return 1.0;
}
Variable Documentation
MultiSlaterDet SymmetricSlaterDet
Initial value:
 {
  A : 0,
  N : 1,
  n : 1,
  symmetry : SymmetricSlaterDetSymmetry,
  weight : SymmetricSlaterDetWeight,
  get : SymmetricSlaterDetGet,
  internals : NULL
}
some fields have to be initialized later
Definition at line 36 of file SymmetricSlaterDet.c.