FMD: fmd/TimeReversal.h File Reference
fmd/TimeReversal.h File Reference
#include "SlaterDet.h"
#include "Projection.h"
Functions
void calcTimeReversal (const SlaterDet *Q, const SlaterDetAux *X, complex double *t)
void calcTimeReversalod (void *dummy, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *t)
void showprojectedTimeReversal (FILE *fp, const Projection *P, complex double **tr, const Eigenstates *E)
Variables
ManyBodyOperator OpTimeReversal
Detailed Description
calculate TimeReversal
(c) 2007 Thomas Neff
Definition in file TimeReversal.h.
Function Documentation
void calcTimeReversal (const SlaterDet * Q, const SlaterDetAux * X, complex double * t)
Definition at line 41 of file TimeReversal.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), initSlaterDet(), initSlaterDetAux(), SlaterDetAux::ovlap, and timerevertSlaterDet().
{
  // do we have to initialize the workspace first ?
  if (Qpp.A == 0) {
    initSlaterDet(Q, &Qpp);
    initSlaterDetAux(&Qpp, &Xpp);
  }
  copySlaterDet(Q, &Qpp);
  calcSlaterDetAuxod(Q, &Qpp, &Xpp);
  double norm = Xpp.ovlap;
  timerevertSlaterDet(&Qpp);
  calcSlaterDetAuxod(Q, &Qpp, &Xpp);
  *t = Xpp.ovlap/norm;
}
void calcTimeReversalod (void * dummy, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * t)
Definition at line 62 of file TimeReversal.c.
References SlaterDet::A, calcSlaterDetAuxod(), copySlaterDet(), initSlaterDet(), initSlaterDetAux(), SlaterDetAux::ovlap, and timerevertSlaterDet().
{
  // do we have to initialize the workspace first ?
  if (Qpp.A == 0) {
    initSlaterDet(Qp, &Qpp);
    initSlaterDetAux(&Qpp, &Xpp);
  }
  copySlaterDet(Qp, &Qpp);
  timerevertSlaterDet(&Qpp);
  calcSlaterDetAuxod(Q, &Qpp, &Xpp);
  *t = Xpp.ovlap;
}
void showprojectedTimeReversal (FILE * fp, const Projection * P, complex double ** tr, const Eigenstates * E)
Definition at line 83 of file TimeReversal.c.
References hbc, Eigenstates::index, j, Projection::jmax, Eigenstates::ngood, Eigenstates::norm, Projection::odd, and Eigenstates::v.
Referenced by main().
{
  int odd=P->odd;
  int jmax=P->jmax;
  int p,j,ipj,i;
  char prefix[20];
  complex double* norm;
  complex double* H;
  complex double* TR;
  int* idx;
  int ngood;
  for (p=0; p<=1; p++)
    for (j=odd; j<jmax; j=j+2) {
      ipj = idxpij(jmax,p,j);
      ngood = E->ngood[ipj];
      if (ngood) {
        if(odd) sprintf(prefix, "[%d/2%c]", j, p ? '-' : '+');
        else    sprintf(prefix, "[%d%c]", j/2, p ? '-' : '+');
        idx = E->index[idxpij(jmax,p,j)];
        norm = E->norm[idxpij(jmax,p,j)];
        H = E->v[idxpij(jmax,p,j)];
        TR = tr[idxpij(jmax,p,j)];
        fprintf(fp, "\n%s N     = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.5f", creal(norm[idx[i]]));
        fprintf(fp, "\n%s H     = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", hbc*creal(H[idx[i]]));
        fprintf(fp, "\n%s TR    = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   (%8.3f, %8.3f)",
                  creal(TR[idx[i]]/norm[idx[i]]),
                  cimag(TR[idx[i]]/norm[idx[i]]));
        fprintf(fp, "\n");
      }
    }
}
Variable Documentation
ManyBodyOperator OpTimeReversal
Definition at line 23 of file TimeReversal.c.
Referenced by main().