FMD: fmd/TwoBodyDensity.c File Reference
fmd/TwoBodyDensity.c File Reference
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include "Gaussian.h"
#include "SlaterDet.h"
#include "TwoBodyDensity.h"
#include "numerics/cmath.h"
#include "numerics/sphericalbessel.h"
#include "numerics/legendrep.h"
#include "numerics/clebsch.h"
#include "misc/physics.h"
Defines
#define MAX(x, y) ((x) > (y) ? (x) : (y))
Functions
double sqr (double x)
void initOpTwoBodyDensityR (TBDensRPara *par)
void initOpTwoBodyDensityQ (TBDensQPara *par)
void initOpTwoBodyDensityRL (TBDensRLPara *par)
void initOpTwoBodyDensityQL (TBDensQLPara *par)
void initcg2 (int lmax, int lambdamax)
void calcPairs (const SlaterDet *Q, const SlaterDetAux *X, double pairs[4])
void calcPairsod (void *Par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double pairs[4])
void writeprojectedPairs (FILE *fp, const Projection *P, const complex double(**pairsexp)[4], const Eigenstates *E)
void calcTBDensRod (TBDensRPara *par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *densr)
void writeTBDensR (FILE *fp, const Projection *P, const TBDensRPara *p, int j, int pi, int a, void *tbdensme, const Eigenstates *E)
void calcTBDensQod (TBDensQPara *par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *densq)
void writeTBDensQ (FILE *fp, const Projection *P, const TBDensQPara *p, int j, int pi, int a, void *tbdensme, const Eigenstates *E)
void calcTBDensRLod (TBDensRLPara *par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *densr)
void writeTBDensRL (FILE *fp, const Projection *P, const TBDensRLPara *p, int j, int pi, int a, void *tbdensme, const Eigenstates *E)
void calcTBDensQLod (TBDensQLPara *par, const SlaterDet *Q, const SlaterDet *Qp, const SlaterDetAux *X, complex double *densq)
void writeTBDensQL (FILE *fp, const Projection *P, const TBDensQLPara *p, int j, int pi, int a, void *tbdensme, const Eigenstates *E)
Variables
ManyBodyOperator OpPairs
ManyBodyOperator OpTwoBodyDensityR
ManyBodyOperator OpTwoBodyDensityQ
ManyBodyOperator OpTwoBodyDensityRL
ManyBodyOperator OpTwoBodyDensityQL
double * cg2tab = NULL
Detailed Description
calculate matrix elements of two-body density operators
(c) 2010 Thomas Neff
Definition in file TwoBodyDensity.c.
Define Documentation
#define MAX (x, y) ((x) > (y) ? (x) : (y))
Definition at line 28 of file TwoBodyDensity.c.
Function Documentation
void calcPairs (const SlaterDet * Q, const SlaterDetAux * X, double pairs[4])
Definition at line 667 of file TwoBodyDensity.c.
References calcSlaterDetTBME(), and dim.
{
  TwoBodyOperator op_tb_pairs = {dim: 4, opt: 0, par: NULL, me: tb_pairs};
  calcSlaterDetTBME(Q, X, &op_tb_pairs, pairs);
}
void calcPairsod (void * Par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double pairs[4])
Definition at line 675 of file TwoBodyDensity.c.
References calcSlaterDetTBMEod(), and dim.
{
  TwoBodyOperator op_tb_pairs = {dim: 4, opt: 0, par: NULL, me: tb_pairs};
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_pairs, pairs);
}
void calcTBDensQLod (TBDensQLPara * par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * densq)
Definition at line 874 of file TwoBodyDensity.c.
References calcSlaterDetTBMEod(), dim, TBDensQLPara::lmax, and TBDensQLPara::npoints.
{
  int npoints=par->npoints;
  int dim=2*par->lmax+6;
  TwoBodyOperator op_tb_densql = {dim: dim*npoints, opt: 0, par: par, me: tb_densql};
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_densql, densq);
}
void calcTBDensQod (TBDensQPara * par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * densq)
Definition at line 786 of file TwoBodyDensity.c.
References calcSlaterDetTBMEod(), dim, and TBDensQPara::npoints.
{
  int npoints=par->npoints;
  TwoBodyOperator op_tb_densq = {dim: 4*npoints, opt: 0, par: par, me: tb_densq};
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_densq, densq);
}
void calcTBDensRLod (TBDensRLPara * par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * densr)
Definition at line 829 of file TwoBodyDensity.c.
References calcSlaterDetTBMEod(), dim, TBDensRLPara::lmax, and TBDensRLPara::npoints.
{
  int npoints=par->npoints;
  int dim=2*par->lmax+6;
  TwoBodyOperator op_tb_densrl = {dim: dim*npoints, opt: 0, par: par, me: tb_densrl};
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_densrl, densr);
}
void calcTBDensRod (TBDensRPara * par, const SlaterDet * Q, const SlaterDet * Qp, const SlaterDetAux * X, complex double * densr)
Definition at line 743 of file TwoBodyDensity.c.
References calcSlaterDetTBMEod(), dim, and TBDensRPara::npoints.
{
  int npoints=par->npoints;
  TwoBodyOperator op_tb_densr = {dim: 4*npoints, opt: 0, par: par, me: tb_densr};
  calcSlaterDetTBMEod(Q, Qp, X, &op_tb_densr, densr);
}
void initcg2 (int lmax, int lambdamax)
Definition at line 398 of file TwoBodyDensity.c.
References clebsch(), l, and sqr().
{
  if (cg2tab) return;
  cg2tab = malloc((lmax+1)*(lambdamax+1)*(lmax+lambdamax+1)*sizeof(double));
  double (*cg2)[lambdamax+1][lmax+lambdamax+1] = cg2tab;
  int l, lambda, lp;
  for (l=0; l<=lmax; l++)
    for (lambda=0; lambda<=lambdamax; lambda++)
      for (lp=abs(l-lambda); lp<=l+lambda; lp++)
        cg2[l][lambda][lp] = sqr(clebsch(2*l,2*lp,2*lambda,0,0,0));
}
void initOpTwoBodyDensityQ (TBDensQPara * par)
Definition at line 107 of file TwoBodyDensity.c.
References ManyBodyOperator::dim, ManyBodyOperator::name, TBDensQPara::npoints, ManyBodyOperator::par, TBDensQPara::qmax, and ManyBodyOperator::size.
Referenced by main().
{
  char* name = malloc(60);
  sprintf(name, "TwoBodyDensityQ-%05.2f-%d", par->qmax, par->npoints);
  OpTwoBodyDensityQ.name = name;
  OpTwoBodyDensityQ.dim = 4*par->npoints;
  OpTwoBodyDensityQ.size = 4*par->npoints;
  OpTwoBodyDensityQ.par = par;
}
void initOpTwoBodyDensityQL (TBDensQLPara * par)
Definition at line 130 of file TwoBodyDensity.c.
References ManyBodyOperator::dim, TBDensQLPara::lambdamax, TBDensQLPara::lmax, ManyBodyOperator::name, TBDensQLPara::npoints, ManyBodyOperator::par, TBDensQLPara::qmax, and ManyBodyOperator::size.
Referenced by main().
{
  char* name = malloc(60);
  sprintf(name, "TwoBodyDensityQL-%d-%d-%05.2f-%d",
          par->lmax, par->lambdamax, par->qmax, par->npoints);
  OpTwoBodyDensityQL.name = name;
  OpTwoBodyDensityQL.dim = (2*par->lmax+6)*par->npoints;
  OpTwoBodyDensityQL.size = (2*par->lmax+6)*par->npoints;
  OpTwoBodyDensityQL.par = par;
}
void initOpTwoBodyDensityR (TBDensRPara * par)
Definition at line 95 of file TwoBodyDensity.c.
References ManyBodyOperator::dim, ManyBodyOperator::name, TBDensRPara::npoints, ManyBodyOperator::par, TBDensRPara::rmax, and ManyBodyOperator::size.
Referenced by main().
{
  char* name = malloc(60);
  sprintf(name, "TwoBodyDensityR-%05.2f-%d",
          par->rmax, par->npoints);
  OpTwoBodyDensityR.name = name;
  OpTwoBodyDensityR.dim = 4*par->npoints;
  OpTwoBodyDensityR.size = 4*par->npoints;
  OpTwoBodyDensityR.par = par;
}
void initOpTwoBodyDensityRL (TBDensRLPara * par)
Definition at line 118 of file TwoBodyDensity.c.
References ManyBodyOperator::dim, TBDensRLPara::lambdamax, TBDensRLPara::lmax, ManyBodyOperator::name, TBDensRLPara::npoints, ManyBodyOperator::par, TBDensRLPara::rmax, and ManyBodyOperator::size.
Referenced by main().
{
  char* name = malloc(60);
  sprintf(name, "TwoBodyDensityRL-%d-%d-%05.2f-%d",
          par->lmax, par->lambdamax, par->rmax, par->npoints);
  OpTwoBodyDensityRL.name = name;
  OpTwoBodyDensityRL.dim = (2*par->lmax+6)*par->npoints;
  OpTwoBodyDensityRL.size = (2*par->lmax+6)*par->npoints;
  OpTwoBodyDensityRL.par = par;
}
double sqr (double x) [inline]
Definition at line 30 of file TwoBodyDensity.c.
Referenced by calcInterpol(), and initcg2().
{ return x*x; }
void writeprojectedPairs (FILE * fp, const Projection * P, const complex double(**) pairsexp[4], const Eigenstates * E)
Definition at line 685 of file TwoBodyDensity.c.
References hbc, Eigenstates::index, j, Projection::jmax, Eigenstates::ngood, Eigenstates::norm, Projection::odd, and Eigenstates::v.
Referenced by main().
{
  int odd=P->odd;
  int jmax=P->jmax;
  int p,j,i;
  char prefix[8];
  int* idx;
  int ngood;
  complex double *norm, *H;
  complex double (*pairs)[4];
  for (p=0; p<=1; p++)
    for (j=odd; j<jmax; j=j+2) {
      ngood = E->ngood[idxpij(jmax,p,j)];
      if (ngood) {
        if(odd) sprintf(prefix, "[%d/2%c]", j, p ? '-' : '+');
        else    sprintf(prefix, "[%d%c]", j/2, p ? '-' : '+');
        idx = E->index[idxpij(jmax,p,j)];
        norm = E->norm[idxpij(jmax,p,j)];
        H = E->v[idxpij(jmax,p,j)];
        pairs = pairsexp[idxpij(jmax,p,j)];
        fprintf(fp, "\n%s N           = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.5f", creal(norm[idx[i]]));
        fprintf(fp, "\n%s H           = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", hbc*creal(H[idx[i]]));
        fprintf(fp, "\n%s (S,T)=(0,0) = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", creal(pairs[idx[i]][0]/norm[idx[i]]));
        fprintf(fp, "\n%s (S,T)=(0,1) = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", creal(pairs[idx[i]][1]/norm[idx[i]]));
        fprintf(fp, "\n%s (S,T)=(1,0) = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", creal(pairs[idx[i]][2]/norm[idx[i]]));
        fprintf(fp, "\n%s (S,T)=(1,1) = ", prefix);
        for (i=0; i<ngood; i++)
          fprintf(fp, "   %8.3f", creal(pairs[idx[i]][3]/norm[idx[i]]));
        fprintf(fp, "\n");
      }
    }
}
void writeTBDensQ (FILE * fp, const Projection * P, const TBDensQPara * p, int j, int pi, int a, void * tbdensme, const Eigenstates * E)
Definition at line 798 of file TwoBodyDensity.c.
References Eigenstates::index, Projection::jmax, Eigenstates::norm, TBDensQPara::npoints, and TBDensQPara::qmax.
Referenced by main().
{
  int jmax = P->jmax;
  int ipj = idxpij(jmax,pi,j);
  int npoints = p->npoints;
  double qmax = p->qmax;
  int idx = E->index[ipj][a];
  complex double norm = E->norm[ipj][idx];
  complex double (**densme)[4*npoints] = tbdensme;
  complex double (*dens)[npoints] = densme[ipj][idx];
  int i;
  double q, d00, d01, d10, d11;
  for (i=0; i<npoints; i++) {
    q = qmax*i/(npoints-1);
    d00 = dens[0][i]/norm;
    d01 = dens[1][i]/norm;
    d10 = dens[2][i]/norm;
    d11 = dens[3][i]/norm;
    fprintf(fp, "%6.3f\t%13.8g\t%13.8g\t%13.8g\t%13.8g\n",
            q, d00, d01, d10, d11);
  }
}
void writeTBDensQL (FILE * fp, const Projection * P, const TBDensQLPara * p, int j, int pi, int a, void * tbdensme, const Eigenstates * E)
Definition at line 887 of file TwoBodyDensity.c.
References dim, Eigenstates::index, Projection::jmax, TBDensQLPara::lmax, Eigenstates::norm, TBDensQLPara::npoints, and TBDensQLPara::qmax.
Referenced by main().
{
  int jmax = P->jmax;
  int ipj = idxpij(jmax,pi,j);
  int npoints = p->npoints;
  int lmax = p->lmax;
  int dim = 2*lmax+6;
  double qmax = p->qmax;
  int idx = E->index[ipj][a];
  complex double norm = E->norm[ipj][idx];
  complex double (**densme)[dim*npoints] = tbdensme;
  complex double (*dens)[npoints] = densme[ipj][idx];
  int i, l, d;
  double q, dd;
  for (i=0; i<npoints; i++) {
    q = qmax*i/(npoints-1);
    fprintf(fp, "  %6.3f", q);
    for (d=0; d<dim; d++) {
      dd = dens[d][i]/norm;
      fprintf(fp, "\t%13.8g", dd);
    }
    fprintf(fp, "\n");
  }
}
void writeTBDensR (FILE * fp, const Projection * P, const TBDensRPara * p, int j, int pi, int a, void * tbdensme, const Eigenstates * E)
Definition at line 755 of file TwoBodyDensity.c.
References Eigenstates::index, Projection::jmax, Eigenstates::norm, TBDensRPara::npoints, and TBDensRPara::rmax.
Referenced by main().
{
  int jmax = P->jmax;
  int ipj = idxpij(jmax,pi,j);
  int npoints = p->npoints;
  double rmax = p->rmax;
  int idx = E->index[ipj][a];
  complex double norm = E->norm[ipj][idx];
  complex double (**densme)[4*npoints] = tbdensme;
  complex double (*dens)[npoints] = densme[ipj][idx];
  int i;
  double r, d00, d01, d10, d11;
  for (i=0; i<npoints; i++) {
    r = rmax*i/(npoints-1);
    d00 = dens[0][i]/norm;
    d01 = dens[1][i]/norm;
    d10 = dens[2][i]/norm;
    d11 = dens[3][i]/norm;
    fprintf(fp, "%6.3f\t%13.8g\t%13.8g\t%13.8g\t%13.8g\n",
            r, d00, d01, d10, d11);
  }
}
void writeTBDensRL (FILE * fp, const Projection * P, const TBDensRLPara * p, int j, int pi, int a, void * tbdensme, const Eigenstates * E)
Definition at line 842 of file TwoBodyDensity.c.
References dim, Eigenstates::index, Projection::jmax, TBDensRLPara::lmax, Eigenstates::norm, TBDensRLPara::npoints, and TBDensRLPara::rmax.
Referenced by main().
{
  int jmax = P->jmax;
  int ipj = idxpij(jmax,pi,j);
  int npoints = p->npoints;
  int lmax = p->lmax;
  int dim = 2*lmax+6;
  double rmax = p->rmax;
  int idx = E->index[ipj][a];
  complex double norm = E->norm[ipj][idx];
  complex double (**densme)[dim*npoints] = tbdensme;
  complex double (*dens)[npoints] = densme[ipj][idx];
  int i, l, d;
  double r, dd;
  for (i=0; i<npoints; i++) {
    r = rmax*i/(npoints-1);
    fprintf(fp, "  %6.3f", r);
    for (d=0; d<dim; d++) {
      dd = dens[d][i]/norm;
      fprintf(fp, "\t%13.8g", dd);
    }
    fprintf(fp, "\n");
  }
}
Variable Documentation
double* cg2tab = NULL
Definition at line 396 of file TwoBodyDensity.c.
ManyBodyOperator OpPairs
Initial value:
 {
 name : "Pairs",
 rank : 0,
 pi : 0,
 dim : 4,
 size : 4,
 par : NULL,
 me : calcPairsod
}
Definition at line 35 of file TwoBodyDensity.c.
Referenced by main().
ManyBodyOperator OpTwoBodyDensityQ
Initial value:
 {
  name : NULL,
  rank : 0,
  pi : 0,
  dim : 0,
  size : 0,
  par : NULL,
  me : calcTBDensQod
}
Definition at line 61 of file TwoBodyDensity.c.
Referenced by main().
ManyBodyOperator OpTwoBodyDensityQL
Initial value:
 {
  name : NULL,
  rank : 0,
  pi : 0,
  dim : 0,
  size : 0,
  par : NULL,
  me : calcTBDensQLod
}
Definition at line 84 of file TwoBodyDensity.c.
Referenced by main().
ManyBodyOperator OpTwoBodyDensityR
Initial value:
 {
  name : NULL,
  rank : 0,
  pi : 0,
  dim : 0,
  size : 0,
  par : NULL,
  me : calcTBDensRod
}
Definition at line 51 of file TwoBodyDensity.c.
Referenced by main().
ManyBodyOperator OpTwoBodyDensityRL
Initial value:
 {
  name : NULL,
  rank : 0,
  pi : 0,
  dim : 0,
  size : 0,
  par : NULL,
  me : calcTBDensRLod
}
Definition at line 74 of file TwoBodyDensity.c.
Referenced by main().