FMD: misc/utils.h File Reference
misc/utils.h File Reference
#include <stdio.h>
#include <zlib.h>
Functions
const char * svn_version (void)
get current SVN version
void createinfo (int argc, char *argv[])
save info about running process
void fprintinfo (FILE *fp)
print info about running process
void gzprintinfo (gzFile fp)
print info about running process
char * hostname (void)
returns string with hostname
char * curdate (void)
returns string with current time and date
int usertime (void)
returns process user time in seconds
char * stripstr (char *str, const char *strip)
strips strip from str
char * strjoin (const char *stra, const char *strb)
join two strings
int fileexists (const char *fname)
check if file exists and is readable (returns 0 for success)
void ensuredir (const char *dirname)
check for existence, create if not of directory
int backup (const char *fname)
renames fname to fname.bak
char * filepart (const char *fullname)
get the file component of fullname
char * pathpart (const char *fullname)
get the path component of fullname
char * md5hash (const char *fname)
create md5 hash for file fname
char * nucleusIDLformat (const char *name)
convert name e.g. "Si28" into IDL format
int readstringsfromfile (const char *fname, int *n, char *string[])
read list of strings from file
Function Documentation
int backup (const char * fname)
renames fname to fname.bak
Definition at line 136 of file utils.c.
References ensuredir().
Referenced by main().
{
  char backupname[1024];
  if (!access(fname, F_OK)) {
    ensuredir("BAK");
    sprintf(backupname, "BAK/%s-%d", fname, (int) time(NULL));
    return rename(fname, backupname);
  }
  return 0;
}
void createinfo (int argc, char * argv[])
save info about running process
Definition at line 32 of file utils.c.
References curdate(), cuserid(), git_version(), and hostname().
Referenced by main().
{
  int i;
  char *c = infostring;
  sprintf(c, "# FMD git: %s \n#\n", git_version());
  sprintf(c+strlen(infostring), "# %s @ %s, %s\n", cuserid(NULL), hostname(), curdate());
  sprintf(c+strlen(infostring), "# ");
  for (i=0; i<argc; i++)
    sprintf(c+strlen(infostring), "%s ", argv[i]);
  sprintf(c+strlen(infostring), "\n");
}
char* curdate (void)
returns string with current time and date
Definition at line 66 of file utils.c.
References stripstr().
Referenced by createinfo().
{
  time_t curtime;
  struct tm *curtimep;
  curtime = time(NULL);
  curtimep = localtime(&curtime);
  return (stripstr(asctime(curtimep),"\n"));
}
void ensuredir (const char * dirname)
check for existence, create if not of directory
Definition at line 118 of file utils.c.
Referenced by backup(), main(), writeprojectedMBMEtoFile(), and writeprojectedMultiMBMEtoFile().
{
  struct stat dirstat;
  if (!stat(dirname, &dirstat)) {
    if (!S_ISDIR(dirstat.st_mode)) {
      fprintf(stderr, "%s is not a directory\n", dirname);
      exit(-1);
    }
  } else {
    if (mkdir(dirname, 0755)) {
      fprintf(stderr, "couldn't create directory %s\n", dirname);
      exit(-1);
    }
  }
}
int fileexists (const char * fname)
check if file exists and is readable (returns 0 for success)
Definition at line 106 of file utils.c.
Referenced by readprojectedMBMEfromFile(), and readprojectedMultiMBMEfromFile().
{
  struct stat filestat;
  if (!stat(fname, &filestat))
    if (S_ISREG(filestat.st_mode))
      return 0;
  return -1;
}
char* filepart (const char * fullname)
get the file component of fullname
Definition at line 149 of file utils.c.
Referenced by main(), readprojectedMBMEfromFile(), readprojectedMultiMBMEfromFile(), writeprojectedMBMEtoFile(), and writeprojectedMultiMBMEtoFile().
{
  char *p;
  char *filep;
  if ((p = strrchr(fullname, '/'))) {
    filep = (char*) malloc(strlen(p)*sizeof(char));
    strcpy(filep, p+1);
  } else {
    filep = (char*) malloc((strlen(fullname)+1)*sizeof(char));
    strcpy(filep, fullname);
  }
  return filep;
}
void fprintinfo (FILE * fp)
print info about running process
Definition at line 46 of file utils.c.
Referenced by egradf(), main(), writeMulticonfigfile(), writeMultiEigenstatestoFile(), and writeMultiMulticonfigfile().
{
  fputs(infostring, fp);
}
void gzprintinfo (gzFile fp)
print info about running process
Definition at line 51 of file utils.c.
Referenced by writeprojectedMBMEtoFile(), and writeprojectedMultiMBMEtoFile().
{
  gzputs(fp, infostring);
}
char* hostname (void)
returns string with hostname
Definition at line 57 of file utils.c.
Referenced by createinfo(), and main().
{
  char* host = (char*) malloc(255*sizeof(char));
  gethostname(host, 255);
  return host;
}
char* md5hash (const char * fname)
create md5 hash for file fname
Definition at line 183 of file utils.c.
References BUFSIZE, md5_append(), md5_finish(), and md5_init().
Referenced by ClusterFMDread(), Clusterread(), ClustersFMDread(), CoreFMDread(), DiClusterMulticonfigRead(), DiClusterMultiProjSlaterDetRead(), DiClusterProjSlaterDetRead(), readMulticonfigfile(), readMultiMulticonfigfile(), readprojectedMBMEfromFile(), readprojectedMultiMBMEfromFile(), writeMulticonfigfile(), writeMultiEigenstatestoFile(), writeMultiMulticonfigfile(), writeprojectedMBMEtoFile(), and writeprojectedMultiMBMEtoFile().
{
  md5_state_t state;
  md5_byte_t digest[16];
  char* hex_output = malloc(33*sizeof(char));
  int di;
  FILE* fp;
  char buf[BUFSIZE];
  if (!(fp = fopen(fname, "r"))) {
    fprintf(stderr, "couldn't open %s for reading\n", fname);
    exit(-1);
  }
  md5_init(&state);
  while(1) {
    fgets(buf, BUFSIZE, fp);
    if (feof(fp)) break;
    md5_append(&state, (const md5_byte_t *) buf, strlen(buf));
  }
  md5_finish(&state, digest);
  fclose(fp);
  for (di=0; di<16; di++)
    sprintf(hex_output+di*2, "%02x", digest[di]);
  return hex_output;
}
char* nucleusIDLformat (const char * name)
convert name e.g. "Si28" into IDL format
Definition at line 213 of file utils.c.
Referenced by main().
{
  int i=0;
  char* idlstr;
  idlstr = (char*) malloc(9*sizeof(char));
  idlstr[i++] = '!'; idlstr[i++] = 'U';
  if (isdigit(name[1]))
    idlstr[i++] = name[1];
  if (isdigit(name[2]))
    idlstr[i++] = name[2];
  if (isdigit(name[3]))
    idlstr[i++] = name[3];
  idlstr[i++] = '!'; idlstr[i++] = 'N';
  if (isalpha(name[0]))
    idlstr[i++] = name[0];
  if (isalpha(name[1]))
    idlstr[i++] = name[1];
  idlstr[i] = '\0';
  return idlstr;
}
char* pathpart (const char * fullname)
get the path component of fullname
Definition at line 164 of file utils.c.
{
  char *p, *pp;
  char* pathp;
  const char *i;
  if ((p = strrchr(fullname, '/'))) {
    pathp = (char*) malloc((strlen(fullname)-strlen(p)+2)*sizeof(char));
    for (pp = pathp, i = fullname; i<=p; i++)
      *pp++ = *i;
    *pp = '\0';
  } else {
    pathp = (char*) malloc(sizeof(char));
    *pathp = '\0';
  }
  return pathp;
}
int readstringsfromfile (const char * fname, int * n, char * string[])
read list of strings from file
Definition at line 238 of file utils.c.
References STRLEN.
Referenced by main().
{
  FILE* fp;
  if (!(fp = fopen(fname, "r"))) {
    fprintf(stderr, "couldn't open %s for reading\n", fname);
    exit(-1);
  }
  int i=0;
  int res;
  do {
    string[i] = malloc(STRLEN*sizeof(char));
    res = fscanf(fp, " %s", string[i]);
    i++;
  } while (res != EOF);
  fclose(fp);
  *n = i-1;
  return 0;
}
char* stripstr (char * str, const char * strip)
strips strip from str
Definition at line 87 of file utils.c.
Referenced by AlphaAread(), AlphaCread(), Alpharead(), AMDAread(), AMDASread(), AMDdread(), AMDread(), AMDSread(), ClusterFMDread(), Clusterread(), ClustersFMDread(), CoreFMDread(), curdate(), FMDd3hread(), FMDread(), FMDrealread(), FMDrread(), FMDSread(), FMDvxzread(), main(), readInteractionfromFile(), readMultiSlaterDetfromFile(), readParafromFile(), readprojectedMBME(), and readSlaterDet().
{
  char* cp;
  if ((cp = strstr(str, strip)))
    *cp = '\0';
  return str;
}
char* strjoin (const char * stra, const char * strb)
join two strings
Definition at line 98 of file utils.c.
Referenced by main(), readprojectedMBMEfromFile(), and writeprojectedMBMEtoFile().
{
  char* c = malloc(strlen(stra)+strlen(strb));
  sprintf(c, "%s%s", stra, strb);
  return c;
}
const char* svn_version (void)
get current SVN version
int usertime (void)
returns process user time in seconds
Definition at line 78 of file utils.c.
Referenced by main().
{
  struct tms t;
  times(&t);
  return (t.tms_utime / sysconf(_SC_CLK_TCK));
}