FMD: numerics/zcw.h File Reference
numerics/zcw.h File Reference
Functions
int nangles2 (int i)
int nangles3 (int i)
void getangles2 (int idx, int i, double *alpha, double *beta)
void getangles3 (int idx, int i, double *alpha, double *beta, double *gamma)
Detailed Description
(c) 2003 Thomas Neff
Definition in file zcw.h.
Function Documentation
void getangles2 (int idx, int i, double * alpha, double * beta)
Definition at line 63 of file zcw.c.
References g2, and nzcw2.
{
  *alpha = 2*M_PI*((i*g2[idx][1]) % nzcw2[idx])/nzcw2[idx];
  *beta  = acos(-1.0 + 2.0*i*g2[idx][0]/nzcw2[idx]);
}
void getangles3 (int idx, int i, double * alpha, double * beta, double * gamma)
Definition at line 69 of file zcw.c.
References g3, and nzcw3.
Referenced by DiClusterMultiProjSlaterDetGet(), DiClusterMultiProjSlaterDetWeight(), DiClusterProjSlaterDetGet(), DiClusterProjSlaterDetWeight(), and getangintegrationpoint().
{
  *alpha = 2*M_PI*((i*g3[idx][1]) % nzcw3[idx])/nzcw3[idx];
  *beta  = acos(1.0 - 2.0*i*g3[idx][0]/nzcw3[idx]);
  *gamma = 2*M_PI*((i*g3[idx][2]) % nzcw3[idx])/nzcw3[idx];
}
int nangles2 (int i)
Definition at line 53 of file zcw.c.
References nzcw2.
{
  return nzcw2[idx];
}
int nangles3 (int i)
Definition at line 58 of file zcw.c.
References nzcw3.
Referenced by _initangintegration(), DiClusterMultiProjSlaterDetGet(), DiClusterMultiProjSlaterDetRead(), DiClusterMultiProjSlaterDetWeight(), DiClusterProjSlaterDetRead(), fprintProjectinfo(), and initAngintegration().
{
  return nzcw3[idx];
}