FMD: numerics/zcw.c File Reference
numerics/zcw.c File Reference
#include <math.h>
#include "zcw.h"
Defines
#define NZCWSETS2 9
#define NZCWSETS3 15
Functions
int nangles2 (int idx)
int nangles3 (int idx)
void getangles2 (int idx, int i, double *alpha, double *beta)
void getangles3 (int idx, int i, double *alpha, double *beta, double *gamma)
Variables
int nzcw2 [NZCWSETS2] = {21, 34, 55, 89, 144, 233, 377, 616, 987}
int nzcw3 [NZCWSETS3]
const int g2 [NZCWSETS2][2]
const int g3 [NZCWSETS3][3]
Detailed Description
ZCW angle sets
(c) 2003 Thomas Neff
Definition in file zcw.c.
Define Documentation
#define NZCWSETS2 9
Definition at line 16 of file zcw.c.
#define NZCWSETS3 15
Definition at line 18 of file zcw.c.
Function Documentation
void getangles2 (int idx, int i, double * alpha, double * beta)
Definition at line 63 of file zcw.c.
References g2, and nzcw2.
{
  *alpha = 2*M_PI*((i*g2[idx][1]) % nzcw2[idx])/nzcw2[idx];
  *beta  = acos(-1.0 + 2.0*i*g2[idx][0]/nzcw2[idx]);
}
void getangles3 (int idx, int i, double * alpha, double * beta, double * gamma)
Definition at line 69 of file zcw.c.
References g3, and nzcw3.
Referenced by DiClusterMultiProjSlaterDetGet(), DiClusterMultiProjSlaterDetWeight(), DiClusterProjSlaterDetGet(), DiClusterProjSlaterDetWeight(), and getangintegrationpoint().
{
  *alpha = 2*M_PI*((i*g3[idx][1]) % nzcw3[idx])/nzcw3[idx];
  *beta  = acos(1.0 - 2.0*i*g3[idx][0]/nzcw3[idx]);
  *gamma = 2*M_PI*((i*g3[idx][2]) % nzcw3[idx])/nzcw3[idx];
}
int nangles2 (int idx)
Definition at line 53 of file zcw.c.
References nzcw2.
{
  return nzcw2[idx];
}
int nangles3 (int idx)
Definition at line 58 of file zcw.c.
References nzcw3.
Referenced by _initangintegration(), DiClusterMultiProjSlaterDetGet(), DiClusterMultiProjSlaterDetRead(), DiClusterMultiProjSlaterDetWeight(), DiClusterProjSlaterDetRead(), fprintProjectinfo(), and initAngintegration().
{
  return nzcw3[idx];
}
Variable Documentation
const int g2[NZCWSETS2][2]
Initial value:
 {{1,8},
                              {1,13},
                              {1,21},
                              {1,34},
                              {1,55},
                              {1,89},
                              {1,144},
                              {1,233},
                              {1,377}}
Definition at line 26 of file zcw.c.
Referenced by getangles2().
const int g3[NZCWSETS3][3]
Initial value:
 {{1,1,1},
                              {1,2,4},
                              {1,3,8},
                              {1,11,16},
                              {1,14,20},
                              {1,16,44},
                              {1,14,37},
                              {1,64,94},
                              {1,36,92},
                              {1,77,130},
                              {1,284,446},
                              {1,602,917},
                              {1,439,1867},
                              {1,807,2846},
                              {1,1619,6011}}
Definition at line 36 of file zcw.c.
Referenced by getangles3().
int nzcw2[NZCWSETS2] = {21, 34, 55, 89, 144, 233, 377, 616, 987}
Definition at line 20 of file zcw.c.
Referenced by getangles2(), and nangles2().
int nzcw3[NZCWSETS3]
Initial value:
 {1, 10, 21, 35, 44, 98, 142, 200, 301, 504, 1086, 2022,
                        3993, 7991, 15990}
Definition at line 22 of file zcw.c.
Referenced by getangles3(), and nangles3().